// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/watchlist-detail.vue
<template>
  <section class="section-padding">
    <b-container fluid>
      <b-col md="12">
        <div class="border-bottom mb-5 watchlist-tab">
          <div id="item-nav">
            <div id="object-nav" class="item-list-tabs no-ajax css_prefix-tab-lists">

              <!-- Watchlist Tabs -->
              <ul id="pills-tab" class="nav nav-underline data-search-tab" role="tablist">
                <li class="nav-item" role="presentation">
                  <button id="pills-movie-tab" class="nav-link active" data-bs-toggle="pill"
                    data-bs-target="#pills-movie1" type="button" role="tab" aria-controls="pills-movie1"
                    aria-selected="true">
                    {{ $t('streamPages.movie') }} </button>
                </li>
                <li class="nav-item" role="presentation">
                  <button id="pills-video-tab" class="nav-link " data-bs-toggle="pill" data-bs-target="#pills-video1"
                    type="button" role="tab" aria-controls="pills-video1" aria-selected="false" tabindex="-1">
                    {{ $t('streamPages.video') }} </button>
                </li>
                <li class="nav-item" role="presentation">
                  <button id="pills-tvshow-tab" class="nav-link " data-bs-toggle="pill" data-bs-target="#pills-tvshow1"
                    type="button" role="tab" aria-controls="pills-tvshow1" aria-selected="false" tabindex="-1">
                    {{ $t('streamPages.tv_show') }} </button>
                </li>
                <li class="nav-item" role="presentation">
                  <button id="pills-episode-tab" class="nav-link " data-bs-toggle="pill"
                    data-bs-target="#pills-episode1" type="button" role="tab" aria-controls="pills-episode1"
                    aria-selected="false" tabindex="-1">
                    {{ $t('streamKeyword.episode') }} </button>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Playlist Tab Content -->
        <div id="pills-tabContent-watch" class="tab-content">
          <div id="pills-movie1" class="tab-pane fade active show" role="tabpanel" tabindex="0"
            aria-labelledby="pills-movie-tab">
            <b-row
              class="gy-4 row-cols-2 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 row-cols-xxl-5 data-listing">
              <b-col>
                <WatchlistDetailCard card-image="media/gameofhero.webp" movie-name="streamMovies.game_of_heros" />
              </b-col>
              <b-col>
                <WatchlistDetailCard card-image="media/rabbit.webp" movie-name="streamMovies.rabbit" />
              </b-col>
              <b-col>
                <WatchlistDetailCard card-image="media/migration.webp" movie-name="streamMovies.migration" />
              </b-col>
              <b-col>
                <WatchlistDetailCard card-image="media/krishna.webp" movie-name="streamMovies.krishna" />
              </b-col>
              <b-col>
                <WatchlistDetailCard card-image="media/jumanjj.webp" movie-name="streamMovies.jumanji" />
              </b-col>
              <b-col>
                <WatchlistDetailCard card-image="media/yoshi.webp" movie-name="streamMovies.yoshi" />
              </b-col>
              <b-col>
                <WatchlistDetailCard card-image="media/kung-fu-panda.webp" movie-name="streamMovies.kung_fu_panda" />
              </b-col>
              <b-col>
                <WatchlistDetailCard card-image="media/the-hunter.webp" movie-name="streamMovies.the_hunter" />
              </b-col>
            </b-row>
          </div>

          <div id="pills-video1" class="tab-pane fade" role="tabpanel" tabindex="0" aria-labelledby="pills-video-tab">
            <b-row
              class="gy-4 row-cols-2 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 row-cols-xxl-5 data-listing">
              <b-col>
                <WatchlistDetailCard card-image="media/toddler.webp" movie-name="streamMovies.toddler" />
              </b-col>
            </b-row>
          </div>

          <div id="pills-tvshow1" class="tab-pane fade" role="tabpanel" tabindex="0">
            <b-row
              class="gy-4 row-cols-2 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 row-cols-xxl-5 data-listing">
              <b-col>
                <WatchlistDetailCard card-image="media/the-first-of-us.webp"
                  movie-name="streamMovies.the_first_of_us" />
              </b-col>
              <b-col>
                <WatchlistDetailCard card-image="media/migration.webp" movie-name="streamMovies.migration" />
              </b-col>
              <b-col>
                <WatchlistDetailCard card-image="media/spiderman.webp"
                  movie-name="streamMovies.spiderman" />
              </b-col>
              <b-col>
                <WatchlistDetailCard card-image="media/minions.webp" movie-name="streamMovies.minions" />
              </b-col>
              <b-col>
                <WatchlistDetailCard card-image="media/pirates-ofdayones-orignal.webp"
                  movie-name="streamMovies.pirates_of_day_one" />
              </b-col>
              <b-col>
                <WatchlistDetailCard card-image="media/assassins-creed.webp" movie-name="streamMovies.assassins_creed" />
              </b-col>
            </b-row>
          </div>

          <div id="pills-episode1" class="tab-pane fade" role="tabpanel" tabindex="0"
            aria-labelledby="pills-episode-tab">
            <b-row class="gy-4 row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 row-cols-xxl-5 ">
              <p class="text-center w-100">{{ $t('streamPlaylist.no_watchlist_available') }}</p>
            </b-row>
          </div>
        </div>
      </b-col>
    </b-container>
  </section>
</template>
<script setup>
import WatchlistDetailCard from '../components/widgets/WatchlistDetailCard.vue';
//custom hooks
import { useBreadcrumb } from "~/utilities/usePage";

useBreadcrumb("Watchlist");
</script>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/(frontend-pages)/watchlistdetail/page.tsx
"use client"


// pages/watchlist.tsx (or move to /components if not a page)
import React, { Fragment, memo, useState } from "react";
import { Col, Container, Nav, Row, Tab } from "react-bootstrap";
import Link from "next/link";
import FsLightbox from "fslightbox-react";
import { useTranslation } from "react-i18next";
import WishlistCard from "@/components/cards/WishlistCard";
import { useBreadcrumb } from "@/utilities/usePage";


interface WatchlistItem {
  image: string;
  moviename: string;
}

const WatchlistDetail: React.FC = () => {
  const { t } = useTranslation("common");
  const [toggler, setToggler] = useState<boolean>(false);
  useBreadcrumb("persondesc.watchlist")

  const watchlistMovie: WatchlistItem[] = [
    { image: "/assets/images/media/gameofhero.webp", moviename: "streamMovies.game_of_heros" },
    { image: "/assets/images/media/rabbit.webp", moviename: "streamMovies.rabbit" },
    { image: "/assets/images/media/migration.webp", moviename: "streamMovies.migration" },
    { image: "/assets/images/media/krishna.webp", moviename: "streamMovies.krishna" },
    { image: "/assets/images/media/jumanjj.webp", moviename: "streamMovies.jumanji" },
    { image: "/assets/images/media/yoshi.webp", moviename: "streamMovies.yoshi" },
    { image: "/assets/images/media/kung-fu-panda.webp", moviename: "streamMovies.kung_fu_panda" },
    { image: "/assets/images/media/the-hunter.webp", moviename: "streamMovies.the_hunter" },
  ];

  const watchlistVideo: WatchlistItem[] = [
    { image: "/assets/images/media/toddler.webp", moviename: "streamMovies.toddler" },
  ];

  const watchlistTvShow: WatchlistItem[] = [
    { image: "/assets/images/media/the-first-of-us.webp", moviename: "streamMovies.the_first_of_us" },
    { image: "/assets/images/media/migration.webp", moviename: "streamMovies.migration" },
    { image: "/assets/images/media/spiderman.webp", moviename: "streamMovies.spiderman" },
    { image: "/assets/images/media/minions.webp", moviename: "streamMovies.minions" },
    { image: "/assets/images/media/pirates-ofdayones-orignal.webp", moviename: "streamMovies.pirates_of_day_one" },
    { image: "/assets/images/media/assassins-creed.webp", moviename: "streamMovies.assassins_creed" },
  ];

  return (
    <Fragment>
      <section className="section-padding">
        <Container fluid>
          <Row>
            <div className="playlist-listing mt-4 mt-md-0">
              <Tab.Container defaultActiveKey="movie">
                <div className="border-bottom mb-5 watchlist-tab">
                  <div id="item-nav">
                    <div className="item-list-tabs no-ajax css_prefix-tab-lists" id="object-nav">
                      <Nav className="nav-underline data-search-tab mb-0" id="pills-tab" role="tablist">
                        <Nav.Item>
                          <Nav.Link eventKey="movie" id="pills-movie-tab" className="nav-link" role="tab">
                            {t("streamPages.movie")}
                          </Nav.Link>
                        </Nav.Item>
                        <Nav.Item>
                          <Nav.Link eventKey="tvshow" id="pills-tvshow-tab" className="nav-link" role="tab">
                            {t("streamPages.tv_show")}
                          </Nav.Link>
                        </Nav.Item>
                        <Nav.Item>
                          <Nav.Link eventKey="video" id="pills-video-tab" className="nav-link" role="tab">
                            {t("streamPages.video")}
                          </Nav.Link>
                        </Nav.Item>
                        <Nav.Item>
                          <Nav.Link eventKey="episode" id="pills-episode-tab" className="nav-link" role="tab">
                            {t("streamKeyword.episode")}
                          </Nav.Link>
                        </Nav.Item>
                      </Nav>
                    </div>
                  </div>
                </div>

                <Tab.Content>
                  <Tab.Pane eventKey="movie">
                    <Row className="gy-4 row-cols-2 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 row-cols-xxl-5 data-listing">
                      {watchlistMovie.map((item, index) => (
                        <Col key={index}>
                          <WishlistCard image={item.image} moviename={item.moviename} />
                        </Col>
                      ))}
                    </Row>
                  </Tab.Pane>

                  <Tab.Pane eventKey="video">
                    <Row className="gy-4 row-cols-2 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 row-cols-xxl-5 data-listing">
                      {watchlistVideo.map((item, index) => (
                        <Col key={index}>
                          <WishlistCard image={item.image} moviename={item.moviename} />
                        </Col>
                      ))}
                    </Row>
                  </Tab.Pane>

                  <Tab.Pane eventKey="tvshow">
                    <Row className="gy-4 row-cols-2 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 row-cols-xxl-5 data-listing">
                      {watchlistTvShow.map((item, index) => (
                        <Col key={index}>
                          <WishlistCard image={item.image} moviename={item.moviename} />
                        </Col>
                      ))}
                    </Row>
                  </Tab.Pane>

                  <Tab.Pane eventKey="episode">
                    <p className="text-center w-100">
                      {t("streamPlaylist.no_watchlist_available")}
                    </p>
                  </Tab.Pane>
                </Tab.Content>
              </Tab.Container>
            </div>
          </Row>
        </Container>
      </section>

      {/* <FsLightbox
        maxYoutubeVideoDimensions={{ width: 700, height: 400 }}
        exitFullscreenOnClose={true}
        toggler={toggler}
        sources="/assets/images/video/trailer.mp4"
      /> */}
    </Fragment>
  );
};

export default memo(WatchlistDetail);
