// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/blogs/single/[type].vue
<template>
  <div class="section-padding blog-section">
    <b-container>
      <b-row>
        <b-col cols="12">
          <div v-if="type !== 'single'" class="iq-blogs-meta">
            <ul class="iq-blogtag list-inline d-flex align-items-center flex-wrap mb-0">
              <li class=""><i class="ph ph-user" aria-hidden="true"></i><nuxt-link
                  :to="{ name: 'blogs-filter-type', params: { type: 'author' } }" class="">
                  Jenny</nuxt-link></li>
              <li class=""><i class="icon icon-calendar-2" aria-hidden="true"></i><nuxt-link
                  :to="{ name: 'blogs-filter-type', params: { type: 'date' } }">
                  January 30, 2019</nuxt-link></li>
              <li class=""><nuxt-link :to="{ name: 'blogs-filter-type', params: { type: 'tag' } }"
                  class="">DRAMAS</nuxt-link>,</li>
              <li class=""><nuxt-link :to="{ name: 'blogs-filter-type', params: { type: 'tag' } }" class="">
                  Historical</nuxt-link>,</li>
              <li class="">
                <nuxt-link :to="{ name: 'blogs-filter-type', params: { type: 'tag' } }"
                  class="">{{ $t('streamShop.uncategorized') }}</nuxt-link>
              </li>
            </ul>
          </div>
          <h3 v-if="type !== 'single'" class="mb-3">
            {{ $t(blogTitle) }}
          </h3>
          <div class="iq-blog-detail">
            <template v-if="type === 'single'">
              <a class="blog-image d-block overflow-hidden">
                <img class="img-fluid w-100 mb-5" src="/assets/images/blog/blog1.webp" loading="lazy" alt="" />
              </a>
            </template>

            <template v-else-if="type === 'audio'">
              <div>
                <iframe height="200" class="w-100" frameborder="no"
                  src="https://w.soundcloud.com/player/?visual=false&amp;url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F36701924&amp;show_artwork=true&amp;maxheight=750&amp;maxwidth=720&amp;auto_play=false&amp;buying=true&amp;liking=true&amp;download=true&amp;sharing=true&amp;show_comments=true&amp;show_playcount=true&amp;show_user=true&amp;color"></iframe>
              </div>
            </template>

            <template v-else-if="type === 'video'">
              <div>
                <iframe class="w-100" height="490" src="https://www.youtube.com/embed/QCGq1epI9pQ"
                  title="Streamit Intro | ULTIMATE OTT Theme &amp; App for WordPress | Iqonic Design"
                  style="border: none"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                  allowfullscreen></iframe>
              </div>
            </template>

            <template v-else-if="type === 'gallery'">
              <b-row class="row-cols-xl-3 row-cols-md-2 row-cols-1">
                <b-col v-for="(item, index) in galleries" :key="index" :class="item.class">
                  <a href="javascript:void(0);" role="button" @click="togglerGallery(index + 1)">
                    <img :src="item.img" :alt="index"  loading="lazy"/>
                  </a>
                </b-col>
              </b-row>
              <FsLightbox :toggler="toggler" :sources="gallerySources" :slide="slide" />
            </template>

            <template v-if="type === 'link'">
              <div class="mb-4">
                <nuxt-link to="https://iqonic.design/">
                  <i class="ph ph-link text-primary quote-icon"></i>
                </nuxt-link>
              </div>
            </template>
            <template v-if="type === 'quote'">
              <blockquote class="block-quote py-5 mb-3">
                <b-row class="align-items-start">
                  <b-col lg="1" md="2">
                    <div class="blockquote-icon">
                      <i class="ph-fill ph-quotes text-primary" aria-hidden="true"></i>
                    </div>
                  </b-col>
                  <b-col lg="11" md="10">
                    <div class="p-2">
                      <p class="mb-0 blog-gallery-desc">{{ $t('blogs.simon_doe_has_his_tongue') }}</p>
                      <cite><a href="#">{{ $t('blogs.steve_kowalsky') }}</a></cite>
                    </div>
                  </b-col>
                </b-row>

              </blockquote>
            </template>

            <div class="iq-blog-box border-0">
              <div v-if="type === 'single'" class="iq-blogs-meta">
                <ul class="iq-blogtag list-inline d-flex align-items-center flex-wrap mb-0">
                  <li class=""><i class="ph ph-user" aria-hidden="true"></i><nuxt-link
                      :to="{ name: 'blogs-filter-type', params: { type: 'author' } }" class="">
                      Jenny</nuxt-link></li>
                  <li class=""><i class="icon icon-calendar-2" aria-hidden="true"></i><nuxt-link
                      :to="{ name: 'blogs-filter-type', params: { type: 'date' } }">
                      January 30,
                      2019</nuxt-link></li>
                  <li class=""><nuxt-link :to="{ name: 'blogs-filter-type', params: { type: 'tag' } }"
                      class="">DRAMAS</nuxt-link>,
                  </li>
                  <li class=""><nuxt-link :to="{ name: 'blogs-filter-type', params: { type: 'tag' } }" class="">
                      Historical</nuxt-link>,</li>
                  <li class="">
                    <nuxt-link :to="{ name: 'blogs-filter-type', params: { type: 'tag' } }"
                      class="">{{ $t('streamShop.uncategorized') }}</nuxt-link>
                  </li>
                </ul>
              </div>
              <h3 v-if="type === 'single'" class="mb-3">
                {{ $t(blogTitle) }}
              </h3>
              <h6 class="text-white my-3">{{ $t('streamBlog.blog2_desc') }}</h6>
              <p class="mb-0 blog-gallery-desc">{{ $t('streamBlog.blog3_desc') }}</p>
              <p class="blog-gallery-desc">{{ $t('streamBlog.blog4_desc') }}</p>

              <blockquote class="block-quote text-white py-2">
                <p class="mb-0 blog-gallery-desc">{{ $t('streamBlog.quotes') }}</p>
                <cite><a href="#">{{ $t('streamBlog.quotes_author') }}</a></cite>
              </blockquote>
              <p class="mb-0 blog-gallery-desc">{{ $t('streamBlog.blog7_desc') }}</p>
              <p class="mb-0 blog-gallery-desc">{{ $t('streamBlog.blog8_desc') }}
              </p>
              <p class="blog-gallery-desc">{{ $t('streamBlog.blog7_desc') }}</p>

              <ul class="iq-blogtag p-0 m-0 list-unstyled gap-2 widget_tags widget-tags-product">
                <li>
                  <nuxt-link :to="{ name: 'blogs-filter-type', params: { type: 'tags' } }"
                    class="position-relative">{{ $t('streamTag.comedy') }}</nuxt-link>
                </li>
                <li>
                  <nuxt-link :to="{ name: 'blogs-filter-type', params: { type: 'tags' } }"
                    class="position-relative">{{ $t('streamTag.drama') }}</nuxt-link>
                </li>
                <li>
                  <nuxt-link :to="{ name: 'blogs-filter-type', params: { type: 'tags' } }"
                    class="position-relative">{{ $t('streamPages.movie') }}</nuxt-link>
                </li>
                <li>
                  <nuxt-link :to="{ name: 'blogs-filter-type', params: { type: 'tags' } }"
                    class="position-relative">{{ $t('streamKeyword.trailers') }}</nuxt-link>
                </li>
              </ul>

              <div class="iq-blog-tag">
                <div class="blog-nav row mt-3 mt-md-0 mb-5 mb-lg-0">
                  <div class="blog-prev-post col-6">
                    <nuxt-link :to="{ name: 'blogs', params: { type: 'single' } }">
                      <span class="fw-semibold d-none d-md-block">{{ $t('streamForm.amy_admas') }} </span>
                      <div class="blog-arrow mt-3 d-flex align-items-center">
                        <i class="ph ph-arrow-left"></i>
                        <span class="previous fw-semibold fst-italic"> {{ $t('streamForm.previous_post') }}</span>
                      </div>
                    </nuxt-link>
                  </div>
                  <div class="blog-next-post col-6 text-end">
                    <nuxt-link :to="{ name: 'blogs', params: { type: 'audio' } }">
                      <span class="fw-semibold d-none d-md-block">{{ $t('streamForm.gillian_shares') }}</span>
                      <div class="blog-arrow mt-3 d-flex align-items-center justify-content-end">
                        <span class="next fw-semibold fst-italic"> {{ $t('streamForm.next_post') }}</span>
                        <i class="ph ph-arrow-right"></i>
                      </div>
                    </nuxt-link>
                  </div>
                </div>
                <h3 class="comments-title mb-4 pb-2">
                  <span>0 {{ $t('streamBlog.comments') }}</span>
                </h3>
                <h3 class="mb-4">{{ $t('streamForm.leave_reply') }}</h3>
                <form>
                  <p class="mb-5">{{ $t('streamAccount.logged_jenny') }} <nuxt-link
                      :to="{ name: 'merchandise-account' }">{{ $t('streamForm.edit_profile') }}</nuxt-link>{{ ' ' }} {{ $t('streamShop.required_fields') }} *</p>
                  <div class="pt-3">
                    <b-row>
                      <b-col md="12">
                        <textarea class="form-control rounded-3" name="comment" cols="5" rows="8" required=""
                          :placeholder="$t('streamBlog.comment') + '*'"></textarea>
                      </b-col>
                    </b-row>

                    <b-col md="12">
                      <div class="form-submit mt-5">
                        <button id="submit" name="submit" type="submit"
                          class="btn btn-primary position-relative rounded-3" value="Submit">
                          <span class="button-text">{{ $t('streamForm.post_comment') }}</span>
                        </button>
                      </div>
                    </b-col>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script setup>
import { ref, computed, onUnmounted, onMounted } from "vue";
import { useRoute } from "vue-router";
import { blogs } from "~/StaticData/blogs";
import { generateImgPath } from "~/StaticData/data";
import FsLightbox from 'fslightbox-vue'

import { useStremit } from "~/store/streamit";

const route = useRoute();
const type = computed(() => route.params.type);
const slug = computed(() => route.params.slug);
const blog = computed(() => blogs.find((item) => item.slug === slug.value));

const galleries = [
  {
    img: generateImgPath('/assets/images/blog/blog1.webp'),
    class: 'mb-4',
  },
  {
    img: generateImgPath('/assets/images/blog/blog2.webp'),
    class: 'mb-4',
  },
  {
    img: generateImgPath('/assets/images/blog/blog3.webp'),
    class: 'mb-4',
  },
  {
    img: generateImgPath('/assets/images/blog/blog4.webp'),
    class: 'mb-4 mb-md-0',
  },
  {
    img: generateImgPath('/assets/images/blog/blog5.webp'),
    class: 'mb-4 mb-md-0',
  },
  {
    img: generateImgPath('/assets/images/blog/blog6.webp'),
    class: '',
  },
];

const toggler = ref(false)
const slide = ref(1)

// Computed property to extract image URLs for fslightbox
const gallerySources = computed(() => {
  return galleries.map(item => item.img)
})

const togglerGallery = (index) => {
    slide.value = index
    toggler.value = !toggler.value
}

const store = useStremit();

function checkType() {
  if (blog.value?.blogTitle) return blog.value.blogTitle;
  switch (type.value) {
    case "single":
      store.breadcrumbSet({ show: true, name: "blogs.anticipated_movies" });
      break;
    case "audio":
      store.breadcrumbSet({ show: true, name: "blogs.black_pearl" });
      break;
    case "video":
      store.breadcrumbSet({ show: true, name: "blogs.cookies_web" });
      break;
    case "link":
      store.breadcrumbSet({ show: true, name: "blogs.birds_of_prey" });
      break;
    case "quote":
      store.breadcrumbSet({ show: true, name: "blogs.saturday_night" });
      break;
    case "gallery":
      store.breadcrumbSet({ show: true, name: "streamForm.gillian_shares" });
      break;
    default:
      break;
  }
  return '';
}

const blogTitle = computed(() => {
  if (blog.value?.blogTitle) return blog.value.blogTitle;
  switch (type.value) {
        case 'single':
      return 'streamBlog.blog1';
    case 'audio':
      return 'streamBlog.blog15';
    case 'video':
      return 'streamBlog.blog10';
    case 'link':
      return 'streamBlog.blog8';
    case 'quote':
      return 'streamBlog.blog9';
    case 'gallery':
      return 'streamBlog.blog10';
    default:
      return 'Blog not found';
  }
});

watch(
  type,
  () => {
    checkType();
  },
  { deep: true }
);

onMounted(() => {
  checkType();
});
onUnmounted(() => {
  store.breadcrumbSet({ show: false, name: "" });
});
</script>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/(frontend-pages)/blogs/single/[type]/page.tsx
"use client"

import { Fragment, memo, useRef } from "react";

//react-bootstrap
import { Col, Container, Row } from "react-bootstrap";

//router
import Link from "next/link";

//static Data
import { blogs } from "@/StaticData/blogs";

//components
import FormWidget from "@/components/blog/FormWidget";
import DetailMetaList from "@/components/blog/DetailMetaList";
import SingleBlogBreadcrumb from "@/components/blog/SingleBlogBreadcrumb";


//hook
import { useTranslation } from 'react-i18next';
//function
import { generateImgPath } from "@/StaticData/data";

import { useParams, usePathname } from "next/navigation";
import Image from "next/image";

// import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

// export async function getStaticProps(context: { locale: any; }) {
//     // extract the locale identifier from the URL
//     const { locale } = context

//     return {
//         props: {
//             // pass the translation props to the page component
//             ...(await serverSideTranslations(locale)),
//         },
//     }
// }

export async function getStaticPaths(type: String) {

    return {
        paths: [], //indicates that no page needs be created at build time
        fallback: 'blocking' //indicates the type of fallback
    }
}

interface BlogItem {
  slug: string;
  username: string;
  blogDate: string;
  longDescription?: string;
  blogdetailtag?: string[];
  category?: string[];
}

const Single = memo((props) => {
     const { t } = useTranslation("common");
         const router = usePathname()
  const { type } = useParams() as { type?: string };

  const slug = "the-most-anticipated-movies";
  const blog: BlogItem | undefined = blogs.find((item) => item.slug === slug);

  const audio_data = ["streamTag.drama", "streamTag.history", "streamShop.uncategorized"];

  let title = "";
  let data: string[] | undefined = [];
  let date = "";

  switch (type) {
    case "audio":
      title = "streamBlog.black_pearl";
      data = audio_data;
      date = "February 2, 2019";
      break;
    case "video":
      title = "streamPrivacy_Policy.cookies_web";
      data = audio_data;
      date = "January 30, 2019";
      break;
    case "link":
      title = "streamBlog.birds_of_prey";
      data = audio_data;
      date = "January 30, 2019";
      break;
    case "quote":
      title = "streamBlog.saturday_night";
      data = audio_data;
      date = "January 30, 2019";
      break;
    case "gallery":
      title = "streamForm.gillian_shares";
      data = audio_data;
      date = "January 30, 2019";
      break;
  }

  const category_data = data ?? blog?.category ?? [];
  const blog_date = date || blog?.blogDate;

  const gallery = [
    { img: generateImgPath("/assets/images/blog/blog1.webp"), class: "mb-4" },
    { img: generateImgPath("/assets/images/blog/blog2.webp"), class: "mb-4" },
    { img: generateImgPath("/assets/images/blog/blog3.webp"), class: "mb-4" },
    { img: generateImgPath("/assets/images/blog/blog4.webp"), class: "mb-4 mb-md-0" },
    { img: generateImgPath("/assets/images/blog/blog5.webp"), class: "mb-4 mb-md-0" },
    { img: generateImgPath("/assets/images/blog/Fantacy.webp"), class: "" },
  ];

  return (
    <Fragment>
        <SingleBlogBreadcrumb type={type}></SingleBlogBreadcrumb>
      <div className="section-padding blog-single blog-section">
        <Container>
          <Row>
            <Col sm={12}>
              <div className="iq-blogs-meta ">
                <ul className="iq-blogtag list-inline d-flex align-items-center flex-wrap mb-0">
                  <li className="posted-by">
                    <span className="post-date d-flex align-items-center gap-1">
                      <i className="ph ph-user"></i>
                      <Link href="/blogs/blog-tag">{t(blog?.username || "")}</Link>
                    </span>
                  </li>
                  <li className="posted-on">
                    <span className="post-author d-flex align-items-center gap-1">
                      <i className="icon icon-calendar-2"></i>
                      <Link href="/blog-date">
                        <span>{blog_date}</span>
                      </Link>
                    </span>
                  </li>
                  {category_data.map((cat, index) => (
                    <li className="blog-category" key={index}>
                      <Link href="#">{t(cat)},</Link>
                    </li>
                  ))}
                </ul>
              </div>

              <h3 className="mb-3">
                {type === "audio" && t("streamBlog.blog15")}
                {type === "video" && t("streamBlog.blog10")}
                {type === "gallery" && t("streamBlog.blog10")}
                {type === "link" && t("streamBlog.blog8")}
                {type === "quote" && t("streamBlog.blog9")}
              </h3>
              <div className="iq-blog blog-detail">
                {type === "audio" ? (
                  <div>
                    <iframe
                      height="200"
                      className="w-100"
                      frameBorder="no"
                      src="https://w.soundcloud.com/player/?visual=false&amp;url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F36701924&amp;show_artwork=true&amp;maxheight=750&amp;maxwidth=720&amp;auto_play=false&amp;buying=true&amp;liking=true&amp;download=true&amp;sharing=true&amp;show_comments=true&amp;show_playcount=true&amp;show_user=true&amp;color"
                    ></iframe>
                  </div>
                ) : type === "video" ? (
                  <div>
                    {/* <VideoJS
                      options={videoJsOptions}
                      onReady={handlePlayerReady}
                    /> */}
                    <iframe className="w-100" height="490" src="https://www.youtube.com/embed/QCGq1epI9pQ"
                      title="Streamit Intro | ULTIMATE OTT Theme &amp; App for WordPress | Iqonic Design"
                      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                      allowFullScreen></iframe>
                  </div>
                ) : type === "gallery" ? (
                  <Row className="row-cols-xl-3 row-cols-md-2 row-cols-1">
                    {gallery.map((item, index) => {
                      return (
                        <Col className={item.class} key={index}>
                          <Link href="">
                            <img src={item.img} alt={index} />
                          </Link>
                        </Col>
                      );
                    })}
                  </Row>
                ) : (
                  ""
                )}
                <div className="iq-blog-box">
                  {type === "link" ? (
                    <div className="mb-4">
                      <Link href="https://iqonic.design/">
                        <i className="ph ph-link text-primary quote-icon"></i>
                      </Link>
                    </div>
                  ) : type === "quote" ? (


                    <blockquote className="block-quote py-5 mb-3">
                      <Row className="align-items-start">
                        <Col md={2} lg={1}>
                          <div className="blockquote-icon">
                            <i className="ph-fill ph-quotes text-primary" aria-hidden="true"></i>
                          </div>
                        </Col>
                        <Col md={10} lg={11}>
                          <div className="p-2">
                            <p className="mb-0 blog-gallery-desc">”{t("streamBlog.quotes")}”</p>
                            <cite><a href="#">{t("streamBlog.quotes_author")}</a></cite>
                          </div>
                        </Col>
                      </Row>

                    </blockquote>
                  ) : (
                    ""
                  )}
                  <div className="iq-blog-box border-0">
                    {/* Meta */}
                    {type === "single" && (
                      <div className="iq-blogs-meta">
                        <ul className="iq-blogtag list-inline d-flex align-items-center flex-wrap mb-0">
                          <li>
                            <i className="ph ph-user" aria-hidden="true"></i>
                            <Link href="/blogs/blog-tag">Jenny</Link>
                          </li>
                          <li>
                            <i className="icon icon-calendar-2" aria-hidden="true"></i>
                            <Link href="/blogs-date">January 30, 2019</Link>
                          </li>
                         
                        </ul>
                      </div>
                    )}

                    {/* Title */}
                    {type === "single" && <h3 className="mb-3">{t(blogTitle)}</h3>}
                    <h6 className="text-white my-3">{t("streamBlog.blog2_desc")}</h6>
                    <p className="mb-0 blog-gallery-desc">{t("streamBlog.blog3_desc")}</p>
                    <p className="blog-gallery-desc">{t("streamBlog.blog4_desc")}</p>

                    {/* Blockquote */}
                    <blockquote className="block-quote text-white py-2">
                      <p className="mb-0 blog-gallery-desc">{t("streamBlog.quotes")}</p>
                      <cite>
                        <a href="#">{t("streamBlog.quotes_author")}</a>
                      </cite>
                    </blockquote>

                    <p className="mb-0 blog-gallery-desc">{t("streamBlog.blog7_desc")}</p>
                    <p className="mb-0 blog-gallery-desc">{t("streamBlog.blog8_desc")}</p>
                    <p className="blog-gallery-desc">{t("streamBlog.blog7_desc")}</p>

                    {/* Tags */}
                    <ul className="iq-blogtag p-0 m-0 list-unstyled gap-2 widget_tags widget-tags-product">
                      <li>
                        <Link href="/blogs/blog-tag" className="position-relative">
                          {t("streamTag.comedy")}
                        </Link>
                      </li>
                      <li>
                        <Link href="/blogs/blog-tag" className="position-relative">
                          {t("streamTag.drama")}
                        </Link>
                      </li>
                      <li>
                        <Link href="/blogs/blog-tag" className="position-relative">
                          {t("streamPages.movie")}
                        </Link>
                      </li>
                      <li>
                        <Link href="/blogs/blog-tag" className="position-relative">
                          {t("streamBlogCategory.trailer")}
                        </Link>
                      </li>
                    </ul>

                    <div className="iq-blog-tag">
                      <FormWidget />
                    </div>
                  </div>
                </div>
              </div>                
            </Col>
          </Row>
        </Container>
      </div>
    </Fragment>
  );
});

Single.displayName = "Single";
export default Single;
