// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/slider/HomeHeroSlider.vue
<template>
  <div class="overflow-hidden">
    <Swiper
      v-if="render"
      id="home-banner-slider"
      tag="section"
      :dir="rtl"
      :pagination="{
        el: '.swiper-pagination',
        clickable: true,
      }"
      :navigation="{
        prevEl: '#home-banner-slider-prev',
        nextEl: '#home-banner-slider-next',
      }"
      class="wrapper-class iq-main-slider p-0 m-0 banner-home-swiper"
      :modules="modules"
      :loop="true"
    >
      <SwiperSlide
        v-for="item in mainHome"
        :key="item.id"
        class="slide s-bg-1 p-0"
      >
        <div
          class="banner-home-swiper-image"
          :style="{ backgroundImage: `url(${item.bgImage})` }"
        >
          <b-container fluid class="position-relative">
            <b-row class="align-items-center iq-ltr-direction h-100 slider-content-full-height">
              <b-col lg="6" md="12" xl="5">
                <!-- Title -->
                <h2 class="texture-text big-font letter-spacing-1 line-count-1 text-capitalize RightAnimate">
                  {{ $t(item.title) }}
                </h2>

                <!-- Rating / Info Row -->
                <div class="d-flex flex-wrap align-items-center gap-3 r-mb-23 RightAnimate-two">
                  <div class="slider-ratting d-flex align-items-center">
                    <ul class="ratting-start p-0 m-0 list-inline text-warning d-flex align-items-center justify-content-left">
                      <li v-for="n in 4" :key="n">
                        <i class="ph-fill ph-star" aria-hidden="true"></i>
                      </li>
                      <li>
                        <i class="ph-fill ph-star-half" aria-hidden="true"></i>
                      </li>
                    </ul>
                  </div>
                  <span class="d-flex align-items-center gap-1">
                    <span>{{ item.imdb }}</span>
                    <img
                      :src="generateImgPath('/assets/images/pages/imdb-logo.svg')"
                      alt="imdb logo"
                      class="img-fluid imdb-img"
                    />
                  </span>
                  <span class="badge rounded-2 text-white bg-secondary font-size-12">
                    {{ item.badge }}
                  </span>
                  <div class="d-flex align-items-center gap-1" v-if="item.duration">
                    <i class="ph ph-clock"></i>
                    <span class="time">{{ item.duration }}</span>
                  </div>
                </div>

                <!-- Description -->
                <p class="line-count-3 my-3 RightAnimate-two">
                  {{ $t(item.description) }}
                </p>

                <!-- Cast / Genres / Tags -->
                <div class="trending-list RightAnimate-three">
                  <div
                    v-if="item.cast.length"
                    class="text-primary genres font-size-14 mb-1"
                  >
                    {{ $t('sectionTitle.starring') }}:
                    <span
                      v-for="(actor, idx) in item.cast"
                      :key="idx"
                    >
                      <router-link
                        :to="{ name: 'landing-page.view-all' }"
                        class="fw-normal text-decoration-none text-body"
                      >
                        {{ $t(actor) }}
                      </router-link><span class="text-body" v-if="idx < item.cast.length - 1">, </span>
                    </span>
                  </div>

                  <div
                    v-if="item.genres.length"
                    class="text-primary genres font-size-14 mb-1"
                  >
                    {{ $t('streamGenres.genre') }}:
                    <span
                      v-for="(genre, idx) in item.genres"
                      :key="idx"
                    >
                      <router-link
                        :to="{ name: 'landing-page.view-all' }"
                        class="fw-normal text-decoration-none text-body"
                      >
                        {{ $t(genre) }}
                      </router-link><span class="text-body" v-if="idx < item.genres.length - 1">, </span>
                    </span>
                  </div>

                  <div
                    v-if="item.tags.length"
                    class="text-primary tag font-size-14"
                  >
                    {{ $t('streamTag.tags') }}:
                    <span
                      v-for="(tag, idx) in item.tags"
                      :key="idx"
                    >
                      <router-link
                        :to="{ name: 'landing-page.view-all' }"
                        class="fw-normal text-decoration-none text-body"
                      >
                        {{ $t(tag) }}
                      </router-link><span class="text-body" v-if="idx < item.tags.length - 1">, </span>
                    </span>
                  </div>
                </div>

                <!-- Button -->
                <div class="RightAnimate-four">
                  <CustomButton
                    :button-title="$t('streamButtons.play_now')"
                    :link="{ path: '/movies-detail' }"
                  />
                </div>
              </b-col>

              <!-- Trailer video section -->
              <b-col xl="7" lg="6" md="12" class="trailor-video iq-slider d-none d-lg-block">
                <a href="#" class="video-open playbtn text-decoration-none" tabindex="0" @click.prevent="toggler = !toggler">
                  <svg
                    version="1.1"
                    xmlns="http://www.w3.org/2000/svg"
                    x="0px"
                    y="0px"
                    width="80px"
                    height="80px"
                    viewBox="0 0 213.7 213.7"
                    xml:space="preserve"
                  >
                    <polygon
                      class="triangle"
                      fill="none"
                      stroke-width="7"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-miterlimit="10"
                      points="73.5,62.5 148.5,105.8 73.5,149.1 "
                    ></polygon>
                    <circle
                      class="circle"
                      fill="none"
                      stroke-width="7"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-miterlimit="10"
                      cx="106.8"
                      cy="106.8"
                      r="103.3"
                    ></circle>
                  </svg>
                  <span class="w-trailor text-uppercase">{{ $t('streamButtons.watch_trailer') }}</span>
                </a>
              </b-col>
            </b-row>
          </b-container>
        </div>
      </SwiperSlide>
        <FsLightbox :toggler="toggler" :sources="[generateImgPath('/assets/images/video/trailer.mp4')]" />
        <button id="home-banner-slider-prev" class="PreArrow-two swiper-arrows d-flex align-items-center justify-content-center d-xl-block d-none">
          <i class="ph ph-caret-left"></i>
        </button>
        <button id="home-banner-slider-next" class="NextArrow-two swiper-arrows d-flex align-items-center justify-content-center d-xl-block d-none">
          <i class="ph ph-caret-right"></i>
        </button>
        <div class="swiper-pagination d-block d-lg-none"></div>
    </Swiper>
  </div>
</template>
<script setup>
// component
import CustomButton from '../CustomButton.vue';
import { mainHome } from '../../StaticData/data';
// plugins
import FsLightbox from 'fslightbox-vue';
import { Swiper, SwiperSlide } from 'swiper/vue';
import { Navigation, Pagination } from 'swiper';
import { ref, computed, watch } from 'vue';
import { useSetting } from '../../store/setting/index';
const store = useSetting();
const rtl = computed(() => store.theme_scheme_direction_value);
const render = ref(true);
watch(
  () => rtl.value,
  () => {
    render.value = false;
    setTimeout(() => {
      render.value = true;
    }, 0);
  }
);

const generateImgPath = (path) => {
  return window.origin + import.meta.env.BASE_URL + path;
};
const modules = [Navigation, Pagination];
const toggler = ref(false);
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/slider/HomeHeroSlider.jsx
import { Fragment, memo, useState } from "react";

//react-router-dom
import { Link } from "react-router-dom";

//swiper
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination } from "swiper";

//react fs-lightbox
import FsLightbox from "fslightbox-react";

// Redux Selector 
import { useSelector } from "react-redux";
import { theme_scheme_direction } from "../../store/setting/selectors";

//function
import { generateImgPath, mainHome } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

//utilites
import { useEnterExit } from "../../utilities/usePage";
import { Col, Container, Row } from "react-bootstrap";
const video = generateImgPath("/assets/images/video/trailer.mp4");
const HomeHeroSlider = memo(() => {
  const { t } = useTranslation();
  const themeSchemeDirection = useSelector(theme_scheme_direction);
  const [toggler, setToggler] = useState(false);
  return (
    <Fragment>
      <Swiper
        key={themeSchemeDirection}
        dir={themeSchemeDirection}
        navigation={{
          prevEl: ".swiper-banner-button-prev",
          nextEl: ".swiper-banner-button-next",
        }}
        id="home-banner-slider"
        className="iq-main-slider banner-home-swiper overflow-hidden mb-0 wrapper-class"
        modules={[Navigation, Pagination]}
        loop={true}
        speed={1500}
        // wrapperclassName="m-0 p-0"
        pagination={{ el: ".swiper-pagination", clickable: true }}
      >
     {mainHome.map((slide) => (
        <SwiperSlide key={slide.id} className="slide s-bg-1 p-0">
          <div
            className="banner-home-swiper-image"
            style={{ backgroundImage: `url(${slide.bgImage})` }}
          >
            <Container fluid className="position-relative h-100">
              <div className="slider-inner h-100">
                <Row className="align-items-center iq-ltr-direction h-100 slider-content-full-height ">
                  <Col lg={6} md={12} xl={5}>
                    {/* Title */}
                    <h2 className="texture-text big-font letter-spacing-1 line-count-1 text-capitalize RightAnimate">
                      {t(slide.title)}
                    </h2>

                    {/* Ratings / IMDB / Badge / Time */}
                    <div className="d-flex flex-wrap align-items-center gap-3 r-mb-23 RightAnimate-two">
                      <div className="slider-ratting d-flex align-items-center">
                        <ul className="ratting-start p-0 m-0 list-inline text-warning d-flex align-items-center justify-content-left">
                          {[...Array(4)].map((_, i) => (
                            <li key={i}>
                              <i className="ph-fill ph-star" aria-hidden="true"></i>
                            </li>
                          ))}
                          <li>
                            <i className="ph-fill ph-star-half" aria-hidden="true"></i>
                          </li>
                        </ul>
                      </div>
                      <span className="d-flex align-items-center gap-1">
                        <span className="">{slide.imdb}</span>
                        <img
                          src={generateImgPath("/assets/images/pages/imdb-logo.svg")}
                          alt="imdb logo"
                          className="img-fluid imdb-img"
                        />
                      </span>
                      {slide.badge && (
                        <span className="badge rounded-2 text-white bg-secondary font-size-12">
                          {slide.badge}
                        </span>
                      )}
                      {slide.duration && (
                        <div className="d-flex align-items-center gap-1">
                          <i className="ph ph-clock"></i>
                          <span className="time">{t(slide.duration)}</span>
                        </div>
                      )}
                    </div>

                    {/* Description */}
                    <p className="line-count-3 my-3 RightAnimate-two">
                      {t(slide.description)}
                    </p>

                    {/* Cast */}
                    {slide.cast.length > 0 && (
                      <div className="trending-list RightAnimate-three">
                        <div className="text-primary genres font-size-14 mb-1">
                          {t("favouritePersonalities.starting")}:
                          {slide.cast.map((c, idx) => (
                            <Link
                              key={idx}
                              to="/view-all"
                              className="fw-normal text-white text-decoration-none ms-2"
                            >
                              {t(c)}
                              {idx < slide.cast.length - 1 ? "," : ""}
                            </Link>
                          ))}
                        </div>
                        {/* Genres */}
                        {slide.genres.length > 0 && (
                          <div className="text-primary genres font-size-14 mb-1">
                            {t("streamGenres.genre")}:
                            {slide.genres.map((g, idx) => (
                              <Link
                                key={idx}
                                to="/view-all"
                                className="fw-normal text-white text-decoration-none ms-2"
                              >
                                {t(g)}
                                {idx < slide.genres.length - 1 ? "," : ""}
                              </Link>
                            ))}
                          </div>
                        )}
    
                        {/* Tags */}
                        {slide.tags.length > 0 && (
                          <div className="text-primary tag font-size-14">
                            {t("streamTag.tags")}:
                            {slide.tags.map((tag, idx) => (
                              <Link
                                key={idx}
                                to="/view-all"
                                className="fw-normal text-white text-decoration-none ms-1"
                              >
                                {t(tag)}
                                {idx < slide.tags.length - 1 ? "," : ""}
                              </Link>
                            ))}
                          </div>
                        )}
                      </div>
                    )}


                    {/* Play button */}
                    <div className="RightAnimate-four">
                      <div className="iq-button">
                        <Link
                          to="/movies-detail"
                          className="btn btn-primary text-capitalize position-relative rounded-3"
                        >
                          <div className="d-flex align-items-center gap-2">
                            <span className="button-text">
                              {t("streamButtons.play_now")}
                            </span>{" "}
                            <i className="ph-fill ph-play fs-6"></i>
                          </div>
                        </Link>
                      </div>
                    </div>
                  </Col>

                  {/* Trailer Section */}
                  <Col
                    lg={6}
                    md={12}
                    xl={7}
                    className="trailor-video iq-slider d-none d-lg-block"
                  >
                    <Link to="#" className="video-open playbtn" tabIndex="0">
                      <svg
                        onClick={() => setToggler((prev) => !prev)}
                        width="80px"
                        height="80px"
                        viewBox="0 0 213.7 213.7"
                      >
                        <polygon
                          className="triangle"
                          fill="none"
                          strokeWidth="7"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          points="73.5,62.5 148.5,105.8 73.5,149.1 "
                        ></polygon>
                        <circle
                          className="circle"
                          fill="none"
                          strokeWidth="7"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          cx="106.8"
                          cy="106.8"
                          r="103.3"
                        ></circle>
                      </svg>{" "}
                      <span className="w-trailor" onClick={() => setToggler((prev) => !prev)}>
                        {t("streamButtons.watch_trailer")}
                      </span>
                    </Link>
                  </Col>
                </Row>
              </div>
            </Container>
          </div>
        </SwiperSlide>
      ))}
        
        <div className="swiper-pagination d-block d-lg-none">

        </div>
        <button
          className="swiper-banner-button-prev swiper-arrows PreArrow-two d-none d-lg-block"
          id="swiper-banner-button-prev"
        >
          <i className="ph ph-caret-left"></i>
        </button>
        <button
          className="swiper-banner-button-next swiper-arrows NextArrow-two d-none d-lg-block"
          id="swiper-banner-button-next"
        >
         <i className="ph ph-caret-right"></i>
        </button>
      </Swiper>
       <FsLightbox toggler={toggler} sources={[video]} />
    </Fragment>
  );
});

HomeHeroSlider.displayName = "HomeHeroSlider";
export default HomeHeroSlider;
