// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/cards/PersonalityCard.jsx
import { Fragment, memo } from "react";

//react-router-dom
import { Link } from "react-router-dom";

const PersonalityCard = memo((props) => {
  return (
    <Fragment>
      <img
        src={props.image}
        alt="personality"
        className="img-fluid object-cover mb-3 rounded-3 personality-img"
      />
      <div className="text-center">
        <h6 className="mb-0">
          <Link
            to={props.link}
            className="font-size-14 text-decoration-none cast-title text-capitalize"
          >
            {props.title}
          </Link>
        </h6>
        <Link
          to={props.categoryLink}
          className="font-size-12 fw-semibold text-decoration-none text-capitalize text-body"
        >
          {props.category}
        </Link>
      </div>
    </Fragment>
  );
});

PersonalityCard.displayName = "PersonalityCard";
export default PersonalityCard;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/cards/PersonalityCard.vue
<template>
  <nuxt-link :to="link">
    <img
      :src="image"
      alt="personality"
      class="img-fluid object-cover mb-3 rounded-3 personality-img"
      loading="lazy"
    />
  </nuxt-link>
  <div class="text-center">
    <h6 class="mb-0">
      <nuxt-link
        :to="link"
        class="font-size-14 text-decoration-none cast-title text-capitalize"
        >{{ title }}</nuxt-link
      >
    </h6>
    <nuxt-link
      :to="categoryLink"
      class="font-size-12 fw-semibold text-decoration-none text-capitalize text-body"
      >{{ category }}&nbsp;&nbsp;{{ otherCategory }}</nuxt-link
    >
  </div>
</template>

<script setup>
defineProps({
  title: { type: String, default: "" },
  category: { type: String, default: "" },
  otherCategory: { type: String, default: "" },
  categoryLink: {
    type: [String, Object],
    default: () => ({ name: 'index' }),
  },
  link: {
    type: [String, Object],
    default: () => ({ name: 'index' }),
  },
  image: { type: String, default: "" },
});
</script>
