// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/cards/TagsCard.tsx
import React, { Fragment, memo } from "react";

// Next-Link
import Link from "next/link";

interface TagCardProps{
  title?:string,
  slug:string,
  type:string
}

const TagsCard = memo((props:TagCardProps) => {
  return (
    <Fragment>
      <Link href="/view-all" className="iq-tag-box">
        <span className="iq-tag">{props.title}</span>
      </Link>
    </Fragment>
  );
});

TagsCard.displayName = "TagsCard";
export default TagsCard;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/cards/TagsCard.vue
<template>
  <nuxt-link :to="{ name: 'view-all' }" class="iq-tag-box">
    <span class="iq-tag">
      {{ props.title }}
    </span>
  </nuxt-link>
</template>
<script setup>
const props = defineProps({
  title: { type: String, default: '' },
  slug: { type: String, default: '' },
  type: { type: String, default: '' },
});

// params: { filter: 'tags', slug: props.slug, type: props.type }
</script>
