// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/cards/TopTenCard.jsx
import { Fragment, memo } from "react";
import { OverlayTrigger, Tooltip } from "react-bootstrap";

//react-router-dom
import { Link } from "react-router-dom";

const TopTenCard = memo((props) => {
  return (
   <Fragment>
    <div className="iq-top-ten-block">
      <div className="block-image position-relative">
        <div className="img-box">
          <Link className="overly-images" to={props.link}>
            <img
              src={props.imagePath}
              alt="movie-card"
              className="img-fluid object-cover rounded-3"
            />
          </Link>
          <span className="top-ten-numbers texture-text">{props.countValue}</span>
        </div>
      </div>
        {props.productPremium && (
                    <OverlayTrigger
                      placement="top"
                      overlay={<Tooltip id="premium-tooltip">{t("streamTooltip.premium")}</Tooltip>}
                    >
                      <div className="position-absolute z-1 premium-product d-flex align-items-center justify-content-center">
                        <i className="ph ph-fill ph-crown "></i>
                      </div>
                    </OverlayTrigger>
                  )}
    </div>
   </Fragment> 
  );
});

TopTenCard.displayName = "TopTenCard";
export default TopTenCard;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/cards/TopTenCard.vue
<template>
  <div :class="`${classlist}`">
    <div class="block-image position-relative">
      <div class="img-box">
        <router-link class="overly-images" :to="link">
          <img :src="imagePath" alt="movie-card" class="object-cover rounded-3" loading="lazy" />
        </router-link>
        <span class="top-ten-numbers texture-text">{{ countValue }}</span>
      </div>
    </div>
    <div v-if="prodctPrimium" class="position-absolute z-1 primium-product d-flex align-items-center justify-content-center" data-bs-toggle="tooltip" data-bs-placement="top" :data-bs-title="$t('streamPricing.premium')">
        <i class="ph-fill ph-crown fs-5"></i>
    </div>
  </div>
</template>
<script setup>
import { onMounted } from 'vue';
import { Tooltip } from 'bootstrap';

defineProps({
  imagePath: { type: String, default: '' },
  countValue: { type: Number, default: 0 },
  link: { type: [String, Object], default: () => '/' },
  classlist: { type: String, default: '' },
  prodctPrimium: { type: Boolean, default: false },
});

onMounted(() => {
  const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
  tooltipTriggerList.forEach((el) => new Tooltip(el));
});
</script>
