// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/TvShows/DetailPage.vue
<template>
  <div class="poition-relative">
    <div class="iq-main-slider site-video position-relative">
      <!-- Banner Start -->
      <VideoPlayer :options="playerOption"></VideoPlayer>
      <!-- Banner End -->
    </div>

    <div class="movie-detail-part position-relative">
      <div class="trending-info pt-0 pb-0">
        <div class="details-parts">
          <MovieDescription
            movie-name="streamMovies.vikings"
            video-url="/episode"
            :is-not-t-v-showbadge="true"
            movie-released="2025"
            view-number="141"
            :movie-views="$t('streamKeyword.views')"
            imdb-rating="5"
            movie-duration="1hr : 10m"
            movie-language="English (UK)"
            :is-not-playlistbtn="true"
            :is-notdownloadbtn="true"
          />
        </div>
      </div>
    </div>
  </div>

  <b-container fluid>
    <div class="overflow-hidden">
      <div class="show-episode section-padding">
        <!-- Episode Start -->
        <div
          class="d-flex align-items-center justify-content-between px-1 mb-2 pb-1 mb-md-4 pb-md-0"
        >
          <h5 class="main-title text-capitalize mb-0 fw-medium">
            {{ $t("streamKeyword.episodes") }}
          </h5>
        </div>

        <!-- Tabs -->
        <ul
          class="nav nav-pills custom-tab-slider episode-nav-btn gap-3 mb-4 pb-2"
          role="tablist"
        >
          <li v-for="season in seasons" :key="season.id" class="nav-item">
            <a
              class="nav-link"
              :class="{ active: activeTab === season.id, show: activeTab === season.id }"
              data-bs-toggle="pill"
              :href="'#' + season.id"
              role="tab"
              :aria-selected="activeTab === season.id"
              @click.prevent="activeTab = season.id"
            >
              {{ $t(season.name) || 'Season' }}

            </a>
          </li>
        </ul>

        <!-- Tab Content -->
        <div class="tab-content">
          <div
            v-for="season in seasons"
            :id="season.id"
            :key="season.id"
            class="tab-pane animated fadeInUp"
            :class="{ active: activeTab === season.id, show: activeTab === season.id }"
            role="tabpanel"
          >
            <div class="card-style-slider">
              <Swiper
                :slides-per-view="5"
                :space-between="0"
                :breakpoints="{
                  1200: { slidesPerView: 5 },
                  992: { slidesPerView: 3 },
                  768: { slidesPerView: 2 },
                  576: { slidesPerView: 2 },
                  320: { slidesPerView: 1 },
                }"
                class="position-relative wrapper-class mt-4 mb-5 swiper-card"
              >
                <SwiperSlide v-for="(episode, i) in season.episodes" :key="i">
                  <EpisodeCard
                    v-bind="episode"
                    :show-img="episode.image"
                    :episode-number="episode.episodeNumber"
                    :episod-title="$t(episode.episodTitle)"
                    :episode-titles-text="$t(episode.episodeTitlesText)"
                    :episode-detail-text="$t(episode.episodeDetailText)"
                    :episode-titles="true"
                    :episode-detail="true"
                  />
                </SwiperSlide>
              </Swiper>
            </div>
          </div>
        </div>
        <!-- Episode End -->

        <!-- Movies Recommended For You -->
        <section class="recommended-block">
          <MoviesRecommendedForYou
            :title="'sectionTitle.recommended'"
            :list="TVshowDetail_recommendedforYou"
            :slides-per-view="6"
          />
        </section>

        <!-- Starring -->
        <YourFavouritePersonality
          :title="'sectionTitle.starring'"
          :slide-per-view="11"
        />

        <!-- Crew -->
        <YourFavouritePersonality
          :title="'sectionTitle.crew'"
          :data="crew"
          :slide-per-view="11"
        />

        <!-- Upcoming -->
        <section class="upcoming-block">
          <UpcomingMovies
            :title="$t('sectionTitle.upcoming')"
            :list="upcoming_related_video"
            :notview-all-btn="true"
          />
        </section>

        <section class="mb-5">
          <DetailsReview />
        </section>
      </div>
    </div>
  </b-container>
</template>

<script setup>
import { ref, computed } from "vue";
import { Swiper, SwiperSlide } from "swiper/vue";
import { useI18n } from "vue-i18n";
const { t } = useI18n();
// Components
import VideoPlayer from "../../components/plugins/VideoPlayer.vue";
import { useSetting } from "../../store/setting/index";
import MoviesRecommendedForYou from "../../components/sections/MoviesRecommendedForYou.vue";
import YourFavouritePersonality from "../../components/sections/YourFavouritePersonality.vue";
import MovieDescription from "../../components/MovieDescription.vue";
import UpcomingMovies from "../../components/sections/UpcomingMovies.vue";
import EpisodeCard from "../../components/cards/EpisodeCard.vue";
import DetailsReview from "../../components/widgets/DetailsReview.vue";
import {crew} from '../../StaticData/data';

// Static Data
import {  
  tvshow_detail_episode,
  tvshow_detail_episode2,
  TVshowDetail_recommendedforYou,
  upcoming_related_video,
} from "../../StaticData/data";
// Tabs state
const activeTab = ref("season-1");

// RTL handling
const store = useSetting();
const rtl = computed(() => store.theme_scheme_direction_value);

// Video player setup
const playerOption = ref({
  autoplay: true,
  controls: false,
  muted: true,
  loop: true,
  preload: "auto",
  techOrder: ["youtube"],
  sources: [
    {
      src: "https://youtu.be/qJA2U-YMvkk?si=3DpOYivbvOwwTP9X",
      type: "video/youtube",
    },
  ],
  youtube: {
    modestbranding: 1,
    rel: 0,
    showinfo: 0,
    autoplay: 1,
  },
  fullscreen: true,
  poster: '/assets/images/media/chosfies.webp',
});

// Seasons JSON (connected to tabs + Swiper)
const seasons = ref([
  {
    id: "season-1",
    name: "streamEpisode.season1",
    episodes: tvshow_detail_episode.map((ep, i) => ({
      ...ep,
      episodeNumber: String(i + 1),
    })),
  },
  {
    id: "season-2",
    name: "streamEpisode.season2",
    episodes: tvshow_detail_episode2.map((ep, i) => ({
      ...ep,
      episodeNumber: String(i + 1),
    })),
  },
]);

const generateImgPath = (path) => {
  return window.origin + import.meta.env.BASE_URL + path;
};
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/TvShows/DetailPage.jsx
import React, { Fragment, memo } from "react";

//react-bootstrap
import { Container, Nav, Tab } from "react-bootstrap";

//function
import {
  crew,
  tvshow_detail_episode,
  tvshow_detail_episode2,
  TVshowDetail_recommendedforYou,
  upcoming_related_video,
} from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

import Review_Details from "../../components/review_details";
import UpcomingMovies from "../../components/sections/UpcomingMovies";
import YourFavouritePersonality from "../../components/sections/YourFavouritePersonality";
import MoviesRecommendedForYou from "../../components/sections/MoviesRecommendedForYou";
import VideoJS from "../../components/plugins/VideoJs";
import Details_Part from "../../components/details_part";
import { useSelector } from "react-redux";
import { theme_scheme_direction } from "../../store/setting/selectors";
//fslightbox
import FsLightbox from "fslightbox-react";
import EpisodeCard from "../../components/cards/EpisodeCard";
import SectionSlider from "../../components/slider/SectionSlider";


const TvShowsDetail = memo(() => {
  const { t } = useTranslation();
  const themeSchemeDirection = useSelector(theme_scheme_direction);

  const playerRef = React.useRef(null);

  const videoJsOptions = {
    autoplay: true,
    controls: false,
    muted: true,
    loop: true,
    preload: "auto",
    responsive: true,
    techOrder: ["youtube"],
    sources: [
      {
        src: "https://www.youtube.com/watch?v=spGSAeqxVUc",
        type: "video/youtube",
      },
    ],
    youtube: {
      modestbranding: 1,
      rel: 0,
      showinfo: 0,
      autoplay: 1,
    },
    fullscreen: true,
    poster: "/assets/images/player/player-poster.webp",
  };

  const handlePlayerReady = (player) => {
    playerRef.current = player;

    // You can handle player events here, for example:
    player.on("waiting", () => {
      // videojs.log("player is waiting");
      // console.log("hello");
    });

    player.on("dispose", () => {
      // videojs.log("player will dispose");
    });

  };

  return (
    <Fragment>
      <div className="poition-relative">
        <div className="iq-main-slider site-video position-relative">
          <VideoJS options={videoJsOptions} onReady={handlePlayerReady} />
        </div>
        <div className="movie-detail-part position-relative">
          <div className="trending-info pt-0 pb-0">
            <div className="details-parts">
              <Details_Part subsribe_to_watch={true} year={2021}
                title={"streamMovies.vikings"}
                time={"2hr : 6m"}
                views={"284"}
                imdbratting={7}
                language={"language.eng"}
                lenguagecountry={"UK"}
                redirectTo={"/episodes"}
              />
            </div>
          </div>
        </div>
      </div>
      <Container fluid>
        <div className="overflow-hidden">
          <div className="show-episode section-padding-top">
            <Tab.Container id="tvshow_episode_season" defaultActiveKey="season1">
              <Nav as="ul" variant="pills" className="custom-tab-slider episode-nav-btn gap-3 mb-4 pb-2" role="tablist">
                <Nav.Item as="li">
                  <Nav.Link eventKey="season1" className=""
                    aria-selected="true">
                    Season 1
                  </Nav.Link>
                </Nav.Item>
                <Nav.Item as="li">
                  <Nav.Link eventKey="season2" >
                    Season 2
                  </Nav.Link>
                </Nav.Item>
              </Nav>

              <Tab.Content>
                <Tab.Pane eventKey="season1">
                  <SectionSlider
                    title={""}
                    list={tvshow_detail_episode}
                    className="recommended-block"
                    slidesPerView={5}
                    wrapperClass={true}
                    viewAll={false}
                    loop={true}
                    speed={1500}
                  >
                    {(data) => (
                      <EpisodeCard
                        link={data.link}
                        image={data.image}
                        showEpisod={data.showEpisod}
                        episodDate={data.episodDate}
                        episodTime={data.episodTime}
                        episodTitle={data.episodTitle}
                        episodeTitlesText={data.episodeTitlesText}
                        episodeDetailText={data.episodeDetailText}
                      ></EpisodeCard>
                    )}
                  </SectionSlider>
                </Tab.Pane>
                <Tab.Pane eventKey="season2">
                  <SectionSlider
                    title={""}
                    list={tvshow_detail_episode2}
                    className="recommended-block"
                    slidesPerView={5}
                    wrapperClass={true}
                    viewAll={false}
                    speed={1500}
                  >
                    {(data) => (
                      <EpisodeCard
                        link={data.link}
                        image={data.image}
                        showEpisod={data.showEpisod}
                        episodDate={data.episodDate}
                        episodTime={data.episodTime}
                        episodTitle={data.episodTitle}
                        episodeTitlesText={data.episodeTitlesText}
                        episodeDetailText={data.episodeDetailText}
                      ></EpisodeCard>
                    )}
                  </SectionSlider>
                </Tab.Pane>
              </Tab.Content>
            </Tab.Container>
          </div>

          <MoviesRecommendedForYou
            title={"sectionTitle.recommended"}
            data={TVshowDetail_recommendedforYou}
            slides={6}
            viewAll={false}
            slideMedium={3}
          />
          <YourFavouritePersonality title={"sectionTitle.starring"} slidePerView={11} />
          <YourFavouritePersonality
            title={"sectionTitle.crew"}
            data={crew}
            slidePerView={11}
          />
          <UpcomingMovies
            data={upcoming_related_video}
            viewAll={false}
            title="sectionTitle.upcoming"
            slideMedium={3}
            slides={6}
          />
          <div className="show-episode section-padding-bottom">
            <Review_Details />
          </div>
        </div>
      </Container>
      <FsLightbox
        maxYoutubeVideoDimensions={{ width: 1000, height: 600 }}
        exitFullscreenOnClose={true}
        sources={["https://www.youtube.com/watch?v=QCGq1epI9pQ"]}
      />
    </Fragment>
  );
});

TvShowsDetail.displayName = "TvShowsDetail";
export default TvShowsDetail;
