// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/BackToTop.vue
<template>
    <!-- Back-To-Top -->
    <div id="back-to-top" :class="animationClass" @click="backToTop">
        <a id="top" class="p-0 btn bg-primary btn-sm position-fixed top border-0 rounded-circle text-white" href="#top">
            <i class="ph ph-caret-up fw-bold"></i>
        </a>
    </div>
    <!-- End Back-To-Top -->
</template>

<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue';

const animationClass = ref('')

const backToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' })
}

const handleScroll = () => {
    if (document.documentElement.scrollTop > 250) {
        animationClass.value = 'back-to-top animate__animated animate__fadeIn'
    } else {
        animationClass.value = 'back-to-top animate__animated animate__fadeOut'
    }
}

onMounted(() => {
    window.addEventListener('scroll', handleScroll)
})

onBeforeUnmount(() => {
    window.removeEventListener('scroll', handleScroll)
})
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/Back_To_Top.jsx
import React, { useEffect, useRef, useState } from "react";
import { Button } from "react-bootstrap";
import { Link } from "react-router-dom";

const Back_To_Top = () => {
    const backToTopRef = useRef<HTMLDivElement>(null);
  const [show, setShow] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      const scrollY = document.documentElement.scrollTop;
      setShow(scrollY > 250);
    };

    window.addEventListener('scroll', handleScroll);

    return () => window.removeEventListener('scroll', handleScroll);
  }, []);
  return (
    <>
      <div
        id="back-to-top"
         className={`back-to-top animate__animated ${
        show ? 'animate__fadeIn' : 'animate__fadeOut'
      }`}
      >
        <Link
          className="p-0 btn bg-primary btn-sm position-fixed top border-0 rounded-circle text-white"
          id="top"
          onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
          to=""
        >
          <i className="ph ph-caret-up fw-bold"></i>
        </Link>
      </div>
    </>
  );
};

export default Back_To_Top;
