// tamplate/streamithtml-540/streamit-html/code-next/src/app/(frontend-pages)/home/page.tsx
"use client";

import { memo } from "react";

// hero slider
import HomeHeroSlider from "@/components/slider/HomeHeroSlider";

// sections
import ContinueWatching from "@/components/sections/ContinueWatching";
import UpcomingMovies from "@/components/sections/UpcomingMovies";
import LatestMovies from "@/components/sections/LatestMovies";
import VerticalSectionSlider from "@/components/slider/VerticalSectionSlider";
import TrendingSlider from "@/components/sections/Trending";
import SuggestedBlock from "@/components/sections/SuggestedBlock";
import RecommendedTVShow from "@/components/sections/RecommendedTVShow";
import ParallexSection from "@/components/sections/ParallexSection";

//static data
import {
  best_in_tv,
  ottVerticleLatestMovies,
  upcommingMovie,
} from "@/StaticData/data";
import { useEnterExit } from "@/utilities/usePage";
import { Container } from "react-bootstrap";
import SpecialsLatestMovies from "@/components/sections/Specials&LatestMovies";

const Home = memo(() => {
  return (
    <>
      <HomeHeroSlider />
      <Container fluid>
        <div className="overflow-hidden">
          <ContinueWatching />
          <UpcomingMovies
            list={upcommingMovie}
            title={"sectionTitle.upcoming_movies"}
            loop={false}
            viewAll={false}
          />
          <SpecialsLatestMovies
            list={best_in_tv}
            title="sectionTitle.best_in_tv"
            loop={false}
            slidesPerView={5}
          />
          <LatestMovies viewAll={false}></LatestMovies>
        </div>
      </Container>
      <VerticalSectionSlider sliderData={ottVerticleLatestMovies} />
      <Container fluid>
        <div className="overflow-hidden">
          <SuggestedBlock />
        </div>
      </Container>
      <ParallexSection />
      <TrendingSlider />
      <Container fluid>
        <div className="overflow-hidden">
          <RecommendedTVShow viewAll={false}/>
        </div>
      </Container>
    </>
  );
});

Home.displayName = "Home";
export default Home;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/home.vue
<template>
  <section>
    <HomeHeroSlider></HomeHeroSlider>
  </section>

  <b-container fluid>
    <div class="overflow-hidden">
      <section class="continue-watching-block home-continue-watch section-padding-top">
        <ContinueWatching></ContinueWatching>
      </section>

      <UpcomingMovies :notview-all-btn="true" :view="true ? $t('sectionTitle.view_all') : null" :slides-per-view="6" :list="upcommingHomeMovie"></UpcomingMovies>

      <FreshPicksJustForYou :title="$t('sectionTitle.best_in_tv')" :list="bestInTV"></FreshPicksJustForYou>

      <LatestMovies :slider-data="latestMovie" :notview-all-btn="true"></LatestMovies>
    </div>
  </b-container>

  <VerticalSectionSlider :slider-data="ottVerticleLatestMovies"></VerticalSectionSlider>

  <b-container fluid>
    <div class="overflow-hidden">
      <SuggestedBlock :title="$t('sectionTitle.suggested_block')" :notview-all-btn="true"></SuggestedBlock>
    </div>
  </b-container>

  <ParallexSection></ParallexSection>

  <TrendingSection></TrendingSection>

  <b-container fluid>
    <div class="overflow-hidden">
      <RecommendedTVShow :notview-all-btn="true"></RecommendedTVShow>
    </div>
  </b-container>
</template>

<script setup>
// Hero Slider
import HomeHeroSlider from "~/components/slider/HomeHeroSlider.vue";

// Sections
import TrendingSection from "~/components/sections/TrendingSection.vue";
import ContinueWatching from "~/components/sections/ContinueWatching.vue";
import UpcomingMovies from "~/components/sections/UpcomingMovies.vue";
import LatestMovies from "~/components/sections/LatestMovies.vue";
import SuggestedBlock from "~/components/sections/SuggestedBlock.vue";
import RecommendedTVShow from "~/components/sections/RecommendedTVShow.vue";
import ParallexSection from "~/components/sections/ParallexSection.vue";
import VerticalSectionSlider from "~/components/slider/VerticalSectionSlider.vue";

import { ottVerticleLatestMovies, latestMovie, upcommingHomeMovie, bestInTV } from "~/StaticData/data";

import FreshPicksJustForYou from "~/components/sections/FreshPicksJustForYou.vue";

</script>
