// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/CustomButton.jsx
import React, { memo, Fragment } from "react";

// react-router-dom
import { Link } from "react-router-dom";

const CustomButton = memo((props) => {
  return (
    <Fragment>
      {props.linkButton === "true" && (
        <div className="iq-button link-button">
          <Link
            to={props.link}
            className="btn btn-link text-capitalize position-relative p-0"
          >
            <span className="button-text">{props.buttonTitle}</span>
          </Link>
        </div>
      )}
      {props.linkButton === "false" && (
        // <div className="iq-button">
          <Link
            to={props.link}
            className="btn btn-primary text-capitalize position-relative rounded-3"
          >
            {/* <span className="d-flex align-items-center gap-2"> */}
            <span className="button-text">{props.buttonTitle}{" "}</span>
            {/* <i className="ph-fill ph-play fs-6"></i> */}
            {/* </span> */}
          </Link>
        // </div>
      )}
    </Fragment>
  );
});

CustomButton.displayName = "CustomButton";
export default CustomButton;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/CustomButton.vue
<template>
  <div v-if="linkButton === true" class="iq-button link-button">
    <nuxt-link :to="{ name: link }" class="btn text-capitalize position-relative">
      <span class="button-text">{{ buttonTitle }}</span>
    </nuxt-link>
  </div>
  <nuxt-link v-else :to="link" class="btn btn-primary text-capitalize position-relative rounded-3">
    <span v-if="notBtncaretIcon" class="button-text">{{ buttonTitle }}</span>
    <span v-else class="d-flex align-items-center gap-2">
      <span class="button-text">{{ buttonTitle }}</span>
      <i class="ph-fill ph-play fs-6"></i>
    </span>
  </nuxt-link>
</template>
<script setup>
defineProps({
  buttonTitle: { type: String, default: '' },
  link: {
    type: Object,
    default: () => {
      return { path: '' };
    },
  },
  linkButton: { type: Boolean, default: false },
  notBtncaretIcon: { type: Boolean, default: false },
});
</script>
