// tamplate/streamithtml-540/streamit-html/code-react/dashboard/src/components/Loader.jsx
import { Fragment, memo } from "react";

// img
import LoaderGif from '/assets/images/loader.gif'

const Loader = memo(() => {
  return (
    <Fragment>
      <div className="loader simple-loader">
        <div className="loader-body">
          <img
            src={LoaderGif}
            alt="loader"
            className="img-fluid"
            width="300"
          />
        </div>
      </div>
    </Fragment>
  );
});

Loader.displayName = "Loader";
export default Loader;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/LoaderComponent.vue
<template>
  <div class="loader simple-loader animate__animated animate__fadeIn">
    <div class="loader-body">
      <img src="/assets/images/loader.gif" alt="loader" class="img-fluid" width="300" loading="lazy" />
    </div>
  </div>
</template>

<script setup>
import { onMounted, onBeforeUnmount } from 'vue'

onMounted(() => {
  console.debug('[loader] LoaderComponent mounted')
})

onBeforeUnmount(() => {
  console.debug('[loader] LoaderComponent before unmount')
})
</script>
