// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/Loader.tsx
"use client";
import { Fragment, memo } from "react";

// Next-Image
import Image from "next/image";

const Loader = memo(() => {
  console.log('Loader component rendering'); 
  return (
    <Fragment>
      <div
        className="loader simple-loader animate__animated animate__fadeIn"
        data-testid="loader-component"
        role="status"
      >
        <div className="loader-body">
          <Image
            src="/assets/images/loader.gif"
            alt="loader"
            className="img-fluid"
            width={300}
            height={300}
            priority
          />
        </div>
      </div>
    </Fragment>
  );
});

Loader.displayName = "Loader";
export default Loader;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/LoaderComponent.vue
<template>
  <div class="loader simple-loader animate__animated animate__fadeIn">
    <div class="loader-body">
      <img src="/assets/images/loader.gif" alt="loader" class="img-fluid" width="300" loading="lazy" />
    </div>
  </div>
</template>

<script setup>
import { onMounted, onBeforeUnmount } from 'vue'

onMounted(() => {
  console.debug('[loader] LoaderComponent mounted')
})

onBeforeUnmount(() => {
  console.debug('[loader] LoaderComponent before unmount')
})
</script>
