// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/Movies/DownloadMovie.jsx
import React, { Fragment, memo } from "react";

//react-bootstrap
import { Container } from "react-bootstrap";

//function
import {
  crew,
  detailpage_related_video,
  MovieDetail_recommendedforYou,
  upcoming_recommended_movies,
  upcoming_related_video,
} from "../../StaticData/data";


// the hook
import { useTranslation } from "react-i18next";

import Review_Details from "../../components/review_details";
import UpcomingMovies from "../../components/sections/UpcomingMovies";
import YourFavouritePersonality from "../../components/sections/YourFavouritePersonality";
import MoviesRecommendedForYou from "../../components/sections/MoviesRecommendedForYou";
import VideoJS from "../../components/plugins/VideoJs";
import Details_Part from "../../components/details_part";
import { useSelector } from "react-redux";
import { theme_scheme_direction } from "../../store/setting/selectors";
//fslightbox
import FsLightbox from "fslightbox-react";
import poster_img from "/assets/images/media/chosfies.webp";

const DownloadMovie = memo(() => {
  const { t } = useTranslation();
  const themeSchemeDirection = useSelector(theme_scheme_direction);
  const playerRef = React.useRef(null);

  const videoJsOptions = {
    autoplay: true,
    controls: false,
    muted: true,
    loop: true,
    preload: "auto",
    responsive: true,
    techOrder: ["youtube"],
    sources: [
      {
        src: "https://www.youtube.com/watch?v=spGSAeqxVUc",
        type: "video/youtube",
      },
    ],
    youtube: {
      modestbranding: 1,
      rel: 0,
      showinfo: 0,
      autoplay: 1,
    },
    fullscreen: true,
    poster: { poster_img },
  };

  const handlePlayerReady = (player) => {
    playerRef.current = player;

    // You can handle player events here, for example:
    player.on("waiting", () => {
      // videojs.log("player is waiting");
      // console.log("hello");
    });

    player.on("dispose", () => {
      // videojs.log("player will dispose");
    });
  };

  return (
    <>
      {/* <Fragment> */}
        <div className="poition-relative">
          <div className="iq-main-slider site-video position-relative">
            <VideoJS options={videoJsOptions} onReady={handlePlayerReady} />
          </div>
          <div className="movie-detail-part position-relative">
            <div className="trending-info pt-0 pb-0">
              <div className="details-parts">
                <Details_Part
                  title={"streamMovies.chosfies"}
                  subsribe_to_watch={true}
                  isplaylist={true}
                  isdownload={true}
                  year={2021}
                  time={"2hr : 6m"}
                  views={"1.4k"}
                />
              </div>
            </div>
          </div>
        </div>
        <Container fluid>
          <div className="overflow-hidden">
            <div className="section-padding-top">
              <MoviesRecommendedForYou
                title={"sectionTitle.recommended"}
                data={MovieDetail_recommendedforYou}
                slides={6}
                viewAll={false}
                slideMedium={3}
              />
            </div>
            <YourFavouritePersonality title={"sectionTitle.starring"} slidePerView={11} />
            <YourFavouritePersonality
              title={"sectionTitle.crew"}
              data={crew}
              slidePerView={11}
            />
            <MoviesRecommendedForYou
              data={upcoming_recommended_movies}
              title={"sectionTitle.recommended_movie"}
              viewAll={false}
              loop={false}
            />
            <MoviesRecommendedForYou
              data={detailpage_related_video}
              title={"sectionTitle.related_videos"}
              viewAll={false}
              loop={false}
            />
            <UpcomingMovies
              data={upcoming_related_video}
              viewAll={false}
              title="sectionTitle.upcoming"
              slideMedium={3}
              slides={6}
            />
            <section className="mb-5">
              <div className="show-episode">
                <Review_Details />
              </div>
            </section>
          </div>
        </Container>
        <FsLightbox
          maxYoutubeVideoDimensions={{ width: 1000, height: 600 }}
          exitFullscreenOnClose={true}
          sources={["https://www.youtube.com/watch?v=QCGq1epI9pQ"]}
        />
      {/* </Fragment> */}
    </>
  );
});

DownloadMovie.displayName = "DownloadMovie";
export default DownloadMovie;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/Movies/DownloadMovie.vue
<template>
  <div class="poition-relative">
    <div class="iq-main-slider site-video position-relative">
      <!-- Banner Start -->
      <VideoPlayer :options="playerOption"></VideoPlayer>
      <!-- Banner End -->
    </div>
    <div class="movie-detail-part position-relative">
      <div class="trending-info pt-0 pb-0">
        <div class="details-parts">
          <MovieDescription movie-name="streamMovies.chosfies" video-url="/movie-player" movie-type="NC-17"
            movie-duration="2hr : 6m" movie-released="2021" view-number="1.4k" :movie-views="$t('streamKeyword.views')"
            imdb-rating="7" :movie-description="$t('streamMovies.chosfies_desc')" />

        </div>
      </div>
    </div>
  </div>

  <b-container fluid>
    <div class="overflow-hidden">
      <!-- Movies Recommended For You Start  -->
      <section class="recommended-block section-padding-top">
        <MoviesRecommendedForYou :title="'sectionTitle.recommended'" :list="upcoming_recommended_movies"
          :slides-per-view="6" />

      </section>

      <!-- Starring start -->
      <YourFavouritePersonality :title="'sectionTitle.starring'" :slide-per-view="11" />
      <!-- Crew start -->
      <YourFavouritePersonality :title="'sectionTitle.crew'" :data="crew" :slide-per-view="11" />

      <section class="related-movie-block">
        <MoviesRecommendedForYou :title="'sectionTitle.recommended_movie'" :list="upcoming_recommended_movies" :slides-per-view="6"></MoviesRecommendedForYou>
      </section>

      <section class="video-block">
        <RelatedMovies :title="'sectionTitle.related_videos'" :list="detailpage_related_video"></RelatedMovies>
      </section>

      <section class="upcoming-block">
        <UpcomingMovies :title="$t('sectionTitle.upcoming')" :list="upcoming_related_video" :notview-all-btn="true">
        </UpcomingMovies>
      </section>

      <section class="mb-5">
        <DetailsReview></DetailsReview>
      </section>
    </div>
  </b-container>
</template>

<script setup>
import { computed, ref } from 'vue';
import { Navigation, Autoplay } from 'swiper';

// plugins

import MoviesRecommendedForYou from '../../components/sections/MoviesRecommendedForYou.vue';
import UpcomingMovies from '../../components/sections/UpcomingMovies.vue';
import YourFavouritePersonality from '../../components/sections/YourFavouritePersonality.vue';
import VideoPlayer from '../../components/plugins/VideoPlayer.vue';
import { useSetting } from '../../store/setting/index';
import RelatedMovies from '../../components/sections/RelatedMovies.vue';
import MovieDescription from '../../components/MovieDescription.vue';
import {crew} from '../../StaticData/data';

import { upcoming_recommended_movies, detailpage_related_video, upcoming_related_video } from '../../StaticData/data';
import DetailsReview from '../../components/widgets/DetailsReview.vue';

const generateImgPath = (path) => {
  return window.origin + import.meta.env.BASE_URL + path;
};

const modules = [Navigation, Autoplay];

const store = useSetting();
const rtl = computed(() => store.theme_scheme_direction_value);

const playerOption = ref({
  autoplay: true,
  controls: true,
  muted: true,
  loop: true,
  preload: 'auto',
  techOrder: ['youtube'],
  sources: [
    {
      src: 'https://www.youtube.com/watch?v=spGSAeqxVUc',
      type: 'video/youtube',
    },
  ],
  youtube: {
    modestbranding: 1,
    rel: 0,
    showinfo: 0,
    autoplay: 1,
  },
  fullscreen: true,
  poster: '/assets/images/player/player-poster.webp',
});
</script>
