// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/Movies/RestictedPage.vue
<template>
  <div class="poition-relative">
    <div class="iq-main-slider site-video position-relative">
      <!-- Banner Start -->
      <VideoPlayer :options="playerOption"></VideoPlayer>
      <!-- Banner End -->
    </div>
    <div class="movie-detail-part position-relative">
      <div class="trending-info pt-0 pb-0">
        <div class="details-parts">
          <MovieDescription :subscribe-to-watch="true" movie-name="streamMovies.chosfies" video-url="/pricing-plan"
            movie-type="NC-17" movie-duration="2hr : 6m" movie-released="2021" view-number="1.4k"
            :movie-views="$t('streamKeyword.views')" imdb-rating="7" movie-description></MovieDescription>
        </div>
      </div>
    </div>
  </div>

  <b-container fluid>
    <div class="overflow-hidden">
      <!-- Movies Recommended For You Start  -->
      <section class="recommended-block section-padding-top">
        <MoviesRecommendedForYou :title="'sectionTitle.recommended'" :list="MovieDetail_recommendedforYou"
          :slides-per-view="6"></MoviesRecommendedForYou>
      </section>

          <!-- Starring start -->
      <YourFavouritePersonality :title="'sectionTitle.starring'" :slide-per-view="11" />
      <!-- Crew start -->
      <YourFavouritePersonality :title="'sectionTitle.crew'" :data="crew" :slide-per-view="11" />

      <section class="related-movie-block">
        <RelatedMovies :title="'sectionTitle.related_movies'" :list="upcoming_recommended_movies" :slides-per-view="6">
        </RelatedMovies>
      </section>

      <section class="video-block">
        <RelatedMovies :title="'sectionTitle.related_videos'" :list="detailpage_related_video" :slides-per-view="6">
        </RelatedMovies>
      </section>

      <section class="upcoming-block">
        <UpcomingMovies :title="$t('sectionTitle.upcoming')" :list="upcomingRestricted" :notview-all-btn="true">
        </UpcomingMovies>
      </section>

      <section class="mb-5">
        <div class="rate-review-details">
          <div class="d-flex align-items-center justify-content-between gap-3 mb-3">
            <h5 class="main-title text-capitalize m-0 fw-medium">{{ $t('streamShop.reviews') }}</h5>
            <div class="d-flex align-items-center gap-3">
              <a id="openReviewButton" class="btn btn-link p-0 custom-fs-14 openReviewButton" data-bs-toggle="offcanvas"
                href="#offcanvasReview" role="button" aria-controls="offcanvasReview">
                {{ $t('streamButtons.add_review') }} </a>
              <router-link class="btn btn-link p-0 custom-fs-14"
                :to="{ path: '/view-more' }">{{ $t('streamButtons.view_more') }}</router-link>
            </div>
          </div>

          <div class="review-card">
            <div class="review-detail rounded-3">
              <h5 class="m-0 text-center">Not Rated Yet</h5>
            </div>
          </div>
        </div>
      </section>
    </div>
  </b-container>

    <!-- Offcanvas -->
  <div id="offcanvasReview" class="offcanvas overflow-y-auto widget-shopping-cart-content offcanvas-end offcanvas-sidebar sidebar-container on-rtl end border-left-0" tabindex="-1" aria-modal="true" role="dialog">
    <div class="offcanvas-header justify-content-between position-relative border-bottom">
      <h5 id="offcanvasReviewLabel" class="offcanvas-title fw-500">{{$t('streamButtons.add_review')}}</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <form @submit.prevent="submitReview">
        <input type="hidden" name="st_ajax_nonce" :value="formData.nonce" />
        <input type="hidden" name="_wp_http_referer" :value="formData.referer" />
        <input id="cm_id" v-model="formData.comment_id" type="hidden" name="comment_id" />
        <input id="cm_post_type" v-model="formData.post_type" type="hidden" name="post_type" />
        <input id="cm_post_id" v-model="formData.post_id" type="hidden" name="post_id" />
        <input id="cm_user_id" v-model="formData.user_id" type="hidden" name="user_id" />
        <input id="cm_name" v-model="formData.name" type="hidden" name="cm_name" />
        <input id="cm_email" v-model="formData.email" type="hidden" name="cm_email" />

  <p class="mt-0 text-heading">{{$t('streamAccount.log_in')}}: {{ formData.name }}</p>

        <div class="form-group mb-4">
          <label class="form-label mb-3">{{$t('streamShop.your_rating')}}</label>
          <div id="starRating" class="star-rating">
            <template v-for="i in 5" :key="i">
              <input :id="'star' + i" v-model="formData.rating" type="radio" name="rating" :value="i" />
              <label :for="'star' + i" :title="`${i} stars`">
                <i class="ph-fill ph-star" aria-hidden="true"></i>
              </label>
            </template>
          </div>
        </div>

        <div class="form-group">
          <label class="form-label flex-grow-1" for="Description">{{$t('streamShop.your_review')}}</label>
          <textarea id="Description" v-model="formData.review" class="form-control review-text-area" rows="8" cols="45"></textarea>
        </div>

        <div class="iq-button">
          <button type="submit" class="btn btn-primary text-capitalize">
            <span class="button-text">{{$t('streamButtons.submit_review')}}</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup>
// Define formData with all required properties to avoid undefined errors
const formData = ref({
  nonce: '',
  referer: '',
  comment_id: '',
  post_type: '',
  post_id: '',
  user_id: '',
  name: '',
  email: '',
  rating: '',
  review: ''
});
import { computed, ref } from 'vue';

// plugins

import MoviesRecommendedForYou from '../../components/sections/MoviesRecommendedForYou.vue';
import UpcomingMovies from '../../components/sections/UpcomingMovies.vue';
import VideoPlayer from '../../components/plugins/VideoPlayer.vue';
import { useSetting } from '../../store/setting/index';
import RelatedMovies from '../../components/sections/RelatedMovies.vue';
import MovieDescription from '../../components/MovieDescription.vue';
import YourFavouritePersonality from '../../components/sections/YourFavouritePersonality.vue';

import { crew, MovieDetail_recommendedforYou, detailpage_related_video, upcoming_recommended_movies, upcomingRestricted } from '../../StaticData/data';


const store = useSetting();
const rtl = computed(() => store.theme_scheme_direction_value);

const playerOption = ref({
  autoplay: true,
  controls: true,
  muted: true,
  loop: true,
  preload: 'auto',
  techOrder: ['youtube'],
  sources: [
    {
      src: 'https://www.youtube.com/watch?v=spGSAeqxVUc',
      type: 'video/youtube',
    },
  ],
  youtube: {
    modestbranding: 1,
    rel: 0,
    showinfo: 0,
    autoplay: 1,
  },
  fullscreen: true,
  poster: '/assets/images/player/player-poster.webp',
});

const submitReview = () => {
  // Reset form
  formData.value.rating = '';
  formData.value.review = '';
};
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/Movies/RestictedPage.jsx
import React, { Fragment, memo, useState } from "react";
import { Form, Offcanvas } from "react-bootstrap";
import { Link } from "react-router-dom";
//react-bootstrap
import { Container } from "react-bootstrap";

//components
import MoviesRecommendedForYou from "../../components/sections/MoviesRecommendedForYou";
import RelatedVideos from "../../components/sections/RelatedVideos";
import UpcomingMovies from "../../components/sections/UpcomingMovies";
import RelatedMovies from "../../components/sections/RelatedMovies";
import VideoJS from "../../components/plugins/VideoJs";
import Details_Part from "../../components/details_part";

//function
import { useSelector } from "react-redux";
import { theme_scheme_direction } from "../../store/setting/selectors";
import {
  crew,
  MovieDetail_recommendedforYou,
  detailpage_related_video,
  upcoming_recommended_movies,
  upcoming_related_video,
} from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

//fslightbox
import FsLightbox from "fslightbox-react";

//choicejs
import poster_img from "/assets/images/media/chosfies.webp";
import YourFavouritePersonality from "../../components/sections/YourFavouritePersonality";

const RestrictedPage = memo(() => {
  // date, type
  const { t } = useTranslation();
  const themeSchemeDirection = useSelector(theme_scheme_direction);

  const playerRef = React.useRef(null);

  const [show, setShow] = useState(false);
  const handleClose = () => setShow(false);

  const videoJsOptions = {
    autoplay: true,
    controls: false,
    muted: true,
    loop: true,
    preload: "auto",
    responsive: true,
    techOrder: ["youtube"],
    sources: [
      {
        src: "https://www.youtube.com/watch?v=spGSAeqxVUc",
        type: "video/youtube",
      },
    ],
    youtube: {
      modestbranding: 1,
      rel: 0,
      showinfo: 0,
      autoplay: 1,
    },
    fullscreen: true,
    poster: { poster_img },
  };

  const handlePlayerReady = (player) => {
    playerRef.current = player;

    player.on("waiting", () => {
    });

    player.on("dispose", () => {
    });
  };
  return (
    <Fragment>
      <div className="poition-relative">
        <div className="iq-main-slider site-video position-relative">
          <VideoJS options={videoJsOptions} onReady={handlePlayerReady} />
        </div>
        <div className="movie-detail-part position-relative">
          <div className="trending-info pt-0 pb-0">
            <div className="details-parts">
              <Details_Part
                title={"streamMovies.chosfies"}
                subsribe_to_watch={true}
                isplaylist={true}
                isdownload={true}
                btn_title={"streamButtons.subscribe_watch"}
                icon_class={"ph ph-fill ph-crown"}
                year={2021}
                time={"2hr : 6m"}
                views={"1.4k"}
                imdbratting={7}
                cencerratting={true}
                redirectTo="/pricing"
              />
            </div>
          </div>
        </div>
      </div>
      <Container fluid>
        <div className="overflow-hidden">
          <div className="section-padding-top">
            <MoviesRecommendedForYou
              title={"sectionTitle.recommended"}
              data={MovieDetail_recommendedforYou}
              slides={6}
              viewAll={false}
              slideMedium={3}
            />
          </div>
          <YourFavouritePersonality title={"sectionTitle.starring"} slidePerView={11} />
          <YourFavouritePersonality
            title={"sectionTitle.crew"}
            data={crew}
            slidePerView={11}
          />
          <RelatedMovies
            viewAll={false}
            slideMedium={3}
            data={upcoming_recommended_movies}
          />
          <RelatedVideos
            data={detailpage_related_video}
            viewAll={false}
            slideMedium={3}
          />

          <UpcomingMovies
            data={upcoming_related_video}
            viewAll={false}
            title="sectionTitle.upcoming"
            slideMedium={3}
            slides={6}
          />
          <div className="show-episode section-padding-bottom">
            <div className="rate-review-details">
              <div className="d-flex align-items-center justify-content-between gap-3 mb-3">
                <h5 className="main-title text-capitalize m-0 fw-medium">{t("streamShop.reviews")}</h5>
                <div className="d-flex align-items-center gap-3">
                  <a
                    id="openReviewButton"
                    className="btn btn-link p-0 custom-fs-14 openReviewButton"
                    role="button"
                    aria-controls="offcanvasReview"
                    onClick={() => setShow(true)}
                  >
                    Add Review{" "}
                  </a>
                  <Link
                    className="btn btn-link p-0 custom-fs-14"
                    to="/view-more"
                  >
                    View More
                  </Link>
                </div>
              </div>
              <div className="review-card">
                <div className="review-detail rounded-3">
                  <h5 className="m-0 text-center"> Not Rated Yet</h5>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Container>

      <FsLightbox
        maxYoutubeVideoDimensions={{ width: 1000, height: 600 }}
        exitFullscreenOnClose={true}
        // toggler={toggler}
        sources={["https://www.youtube.com/watch?v=QCGq1epI9pQ"]}
      />

      <Offcanvas
        className="overflow-y-auto widget-shopping-cart-content offcanvas-sidebar sidebar-container  border-left-0"
        id="offcanvasReview"
        show={show}
        onHide={handleClose}
        placement={themeSchemeDirection === 'rtl' ? "start" : "end"}
      >
        <Offcanvas.Header className="offcanvas-header position-relative border-bottom" closeButton>
          <Offcanvas.Title as="h5" className="fw-500" id="offcanvasReviewLabel" >
            Add Review{" "}
          </Offcanvas.Title>
        </Offcanvas.Header>
        <Offcanvas.Body>
          <Form>
            {/* <!-- Add Nonce for security --> */}
            <input
              type="hidden"
              id="st_ajax_nonce"
              name="st_ajax_nonce"
              value="a19cf1e628"
            />
            <input
              type="hidden"
              name="_wp_http_referer"
              value="/product/wp/streamit/tvshows/vikings/"
            />{" "}
            <input id="cm_id" type="hidden" name="comment_id" value="" />
            {/* <!-- Hidden fields for post type and post ID --> */}
            <input
              id="cm_post_type"
              type="hidden"
              name="post_type"
              value="tvshow"
            />
            <input id="cm_post_id" type="hidden" name="post_id" value="1" />
            {/* <!-- User ID for logged-in users --> */}
            <input id="cm_user_id" type="hidden" name="user_id" value="12" />
            {/* <!-- Display logged-in user's name --> */}
            <div className="form-group">
              <input
                id="cm_name"
                name="cm_name"
                type="hidden"
                value="Marvin McKinney"
              />
              <input
                id="cm_email"
                name="cm_email"
                type="hidden"
                value="marvin@demo.com"
              />
              <p className="mt-0 text-heading">Logged in as: Marvin McKinney</p>
            </div>
            {/* <!-- Rating section --> */}
            <div className="form-group mb-4">
              <label className="form-label mb-3">Your Rating</label>
              <div className="star-rating" id="starRating">
                <input type="radio" id="star5" name="rating" value="5" />
                <label for="star5" title="5 stars">
                  <i className="ph-fill ph-star" aria-hidden="true"></i>
                </label>
                <input type="radio" id="star4" name="rating" value="4" />
                <label for="star4" title="4 stars">
                  <i className="ph-fill ph-star" aria-hidden="true"></i>
                </label>
                <input type="radio" id="star3" name="rating" value="3" />
                <label for="star3" title="3 stars">
                  <i className="ph-fill ph-star" aria-hidden="true"></i>
                </label>
                <input type="radio" id="star2" name="rating" value="2" />
                <label for="star2" title="2 stars">
                  <i className="ph-fill ph-star" aria-hidden="true"></i>
                </label>
                <input type="radio" id="star1" name="rating" value="1" />
                <label for="star1" title="1 star">
                  <i className="ph-fill ph-star" aria-hidden="true"></i>
                </label>
              </div>
            </div>
            <div className="form-group">
              <label className="form-label flex-grow-1" for="Description">
                Your Review
              </label>
              <textarea
                id="Description"
                className="form-control review-text-area"
                rows="8"
                cols="45"
              ></textarea>
            </div>
            <div className="iq-button">
              <Link
                to="javascript:void(0)"
                className="btn btn-primary text-capitalize"
              >
                <span className="button-text">Submit Review</span>
              </Link>
            </div>
          </Form>
        </Offcanvas.Body>
      </Offcanvas>
    </Fragment>
  );
});

RestrictedPage.displayName = "RestrictedPage";
export default RestrictedPage;
