// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/cards/PersonalityCard.vue
<template>
  <router-link :to="link">
    <img :src="image" alt="personality" class="img-fluid object-cover mb-3 rounded-3 personality-img" loading="lazy" />
  </router-link>
  <div class="text-center">
    <h6 class="mb-0">
      <router-link :to="link" class="font-size-14 text-decoration-none cast-title text-capitalize">{{ title
      }}</router-link>
    </h6>
    <router-link :to="categoryLink" class="font-size-12 fw-semibold text-decoration-none text-capitalize text-body">{{ category
    }}&nbsp;&nbsp;{{ otherCategory }}</router-link>
  </div>
</template>

<script setup>
defineProps({
  title: { type: String, default: '' },
  category: { type: String, default: '' },
  otherCategory: { type: String, default: '' },
  categoryLink: {
    type: [String, Object],
    default: () => '/',
  },
  link: {
    type: [String, Object],
    default: () => '/',
  },
  image: { type: String, default: '' },
});
</script>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/cards/PersonalityCard.tsx
import { Fragment, memo } from "react";

//router
import Link from "next/link";
import { useTranslation } from 'react-i18next';

interface Props {
  image: string,
  title: string,
  category: string
  categoryLink?: string
  link : string
}

const PersonalityCard = memo((props: Props) => {
  const { t } = useTranslation("common");
  // console.log(t(props.title))
  return (
 <Fragment>
      <img
        src={props.image}
        alt="personality"
        className="img-fluid object-cover mb-3 rounded-3 personality-img"
      />
      <div className="text-center">
        <h6 className="mb-0">
          <Link
            href={props.link}
            className="font-size-14 text-decoration-none cast-title text-capitalize"
          >
            {t(props.title)}
          </Link>
        </h6>
        <Link
          href={props.link}
          className="font-size-12 fw-semibold text-decoration-none text-capitalize text-body"
        >
          {t(props.category)}
        </Link>
      </div>
    </Fragment>
  );
});

PersonalityCard.displayName = "PersonalityCard";
export default PersonalityCard;
