// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/merchandise/ProductDetailCard.vue
<template>
  <b-container>
    <b-row>
      <b-col lg="6">
        <div class="product-block inner-box">
          <div class="product-block">
            <span v-if="props.isSale === true" class="onsale sale text-white bg-primary">{{ $t("shop.sale") }}!</span>
            <span v-else-if="props.isNew === true" class="onsale sale text-white bg-secondary">{{ $t("shop.new")
              }}!</span>
            <a href="#"><i class="fa fa-search fa-1x imagesearch" aria-hidden="true"></i></a>
            <div class="image-wrap">
              <img :src="props.thumbnail" class="img-fluid w-100 img-zoom" alt="img" loading="lazy" />
            </div>
          </div>
        </div>
      </b-col>
      <b-col lg="6">
        <div class="summary ms-lg-4">
          <h1 class="product-title title-link">{{ $t(props.productName) }}</h1>
          <div class="comment-form-rating ratestar">
            <div class="star">
              <span><i class="ph-fill ph-star"></i></span>
              <span><i class="ph-fill ph-star"></i></span>
              <span><i class="ph-fill ph-star"></i></span>
              <span><i class="ph-fill ph-star"></i></span>
              <span><i class="ph-fill ph-star"></i></span>
              <span class="text-primary">1 {{ $t('streamShop.reviews') }}</span>
            </div>
          </div>
          <p class="price">
            <del>{{ props.price }}</del> <b>&nbsp; {{ props.finalPrice }}</b>
          </p>
          <p class="mb-4 text-white">{{ props.description }}</p>
          <form class="cart mb-4" method="post">
            <div class="cart-btn-wrapper">
              <div class="quantity">
                <label class="screen-reader-text" for="quantity1"></label>
                <button type="button" class="minus"><i class="fa fa-minus" aria-hidden="true"></i></button>
                <input
id="quantity1" type="text" class="qty" step="1" min="1" name="quantity" value="1" title="Qty"
                  placeholder="" disabled />
                <button type="button" class="plus"><i class="fa fa-plus" aria-hidden="true"></i></button>
              </div>
              <div class="wishlist">
                <div class="wishlist-fragment on-first-load">
                  <!-- ADD TO WISHLIST -->
                  <div>
                    <router-link to="#" class="">
                      <i class="fa fa-heart-o"></i>
                    </router-link>
                  </div>
                  <!-- COUNT TEXT -->
                </div>
              </div>
              <router-link class="iq-button btn btn-hover" :to="{ name: 'landing-page.merchandise.cart' }">
                {{ $t("streamButtons.add_to_cart") }}
              </router-link>
            </div>
          </form>
          <div class="">
            {{ $t("streamShop.sku") }}: <span> {{ props.sku }}</span>
          </div>
          <br />
          <div class="mb-3">
            {{ $t("shop.category") }} : <router-link
v-for="categories in props.category" :key="categories"
              :to="{ name: 'landing-page.merchandise.shop' }" class="text-primary ms-2 text-capitalize"> {{ categories
              }},
            </router-link>
          </div>

          <div class="">
            {{ $t("streamPages.tags") }} :<router-link
v-for="tag in props.tags" :key="tag"
              :to="{ name: 'landing-page.merchandise.shop' }" rel="tag" class="text-primary text-capitalize ms-2">{{ tag
              }},</router-link>
          </div>
        </div>
      </b-col>
    </b-row>
    <b-col lg="12" class="shop-detail">
      <div class="content-details trending-info g-border">
        <ul
          class="trending-pills-header d-flex nav nav-pills align-items-center text-center mb-5 justify-content-center"
          role="tablist">
          <li class="nav-item">
            <a
class="nav-link active show grdeffect" data-bs-toggle="pill" href="#decription-23" role="tab"
              aria-selected="false">{{ $t("streamShop.description") }}</a>
          </li>
          <li class="nav-item mx-3">
            <a class="nav-link grdeffect" data-bs-toggle="pill" href="#add-24" role="tab" aria-selected="true">{{
              $t("streamShop.additional_information") }}</a> +
          </li>
          <li class="nav-item">
            <a class="nav-link grdeffect" data-bs-toggle="pill" href="#review-24" role="tab" aria-selected="false">{{
              $t("streamShop.reviews") }}(0)</a>
          </li>
        </ul>
        <div class="tab-content">
          <div id="decription-23" class="tab-pane fade active show" role="tabpanel">
            <div class="description-content">
              <p>{{ props.description }}</p>
            </div>
          </div>
          <div id="add-24" class="tab-pane fade" role="tabpanel">
            <div class="description-content">
              <table class="addtable mb-5">
                <tbody>
                  <tr>
                    <th class="thwidth">Size</th>
                    <td class="bordertd">
                      <span v-for="data in props.additionalInfo" :key="data" to="#" rel="color">
                        <router-link v-for="sizes in data.size" :key="sizes" to="#" class="ms-2">{{ sizes
                          }},</router-link>
                      </span>
                    </td>
                  </tr>
                  <tr>
                    <th class="thwidth">{{ $t("streamShop.color") }}</th>
                    <td class="bordertd">
                      <span v-for="data in props.additionalInfo" :key="data" to="#" rel="color">
                        <router-link v-for="colors in data.color" :key="colors" to="#" class="ms-2">{{ colors
                          }},</router-link>
                      </span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div id="review-24" class="tab-pane fade" role="tabpanel">
            <div id="reviews" class="streamit-reviews">
              <div id="comments" class="comments-area validate-form">
                <h2>{{ $t("streamShop.reviews") }}</h2>
                <p class="masvideos-noreviews mt-3">{{ $t("streamReview.no_reviews") }}.</p>
              </div>
              <div id="review_form_wrapper">
                <div id="review_form">
                  <div id="respond" class="comment-respond">
                    <p id="reply-title" class="comment-reply-title mt-0 mb-0">
                      {{ $t("streamReview.first_review") }} “{{ props.productName
                      }}”</p>
                    <form class="comment-form">
                      <p class="comment-notes">
                        <span id="email-notes">{{ $t("streamShop.published_email") }}.</span>
                        <span class="required-field-message" aria-hidden="true">{{
                          $t("streamShop.required_fields") }} <span class="required" aria-hidden="true">*</span></span>
                      </p>
                      <div class="comment-form-rating ratestar">
                        <label for="rating">{{ ("streamShop.your_rating") }}*</label>
                        <div class="star">
                          <span><i class="ri-star-line"></i></span>
                          <span><i class="ri-star-line"></i></span>
                          <span><i class="ri-star-line"></i></span>
                          <span><i class="ri-star-line"></i></span>
                          <span><i class="ri-star-line"></i></span>
                        </div>
                      </div>
                      <p class="comment-form-comment p-0 mb-3 mt-0">
                        <label for="comment">{{ $t("streamShop.your_review") }}&nbsp;<span
                            class="required">*</span></label><textarea
id="comment" name="comment" cols="45" rows="8"
                          required=""></textarea>
                      </p>
                      <p class="comment-form-author mt-3 pe-lg-12 pe-0 namefull">
                        <label for="author">{{ $t("streamAccount.name") }}&nbsp;<span class="required">*</span></label>
                        <input id="author" name="author" type="text" value="" size="30" required="" />
                      </p>
                      <p class="comment-form-email mt-3 ps-lg-12 pe-0 namefull">
                        <label for="email">{{ $t("streamAccount.email") }}&nbsp;<span class="required">*</span></label>
                        <input id="email" name="email" type="email" value="" size="30" required="" />
                      </p>
                      <p class="comment-form-cookies-consent">
                        <input id="check11" class="form-check-input" type="checkbox" name="check1" />
                        <label class="form-check-label" for="check11"> {{ $t("streamAccount.save_name") }}. </label>
                      </p>
                      <p class="form-submit">
                        <button
id="submit" name="submit" type="submit" class="btn btn-hover iq-button mb-4"
                          value="Submit">
                          {{ $t("streamButtons.submit") }}
                          <span><i class="fas fa-angle-right" aria-hidden="true"></i></span>
                        </button>
                      </p>
                    </form>
                  </div>
                </div>
              </div>
              <div class="clear"></div>
            </div>
          </div>
        </div>
      </div>
    </b-col>
  </b-container>
</template>
<script setup>
const props = defineProps({
  slug: { type: String, default: '' },
  thumbnail: { type: String, default: '' },
  productName: { type: String, default: '' },
  description: { type: String, default: '' },
  isSale: { type: [String, Boolean], default: true },
  isNew: { type: [String, Boolean], default: true },
  tags: { type: Array, default: () => [] },
  price: { type: String, default: '' },
  finalPrice: { type: String, default: '' },
  additionalInfo: { type: Array, default: () => [] },
  sku: { type: String, default: '' },
  category: { type: String, default: '' },
  size: { type: String, default: '' },
});
</script>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/cards/ProductDetailCard.tsx
import React, { Fragment, memo, useState } from "react";

//react-bootstrap
import { Container, Row, Col, Tab, Nav, Form } from "react-bootstrap";

//react-router-dom
import Link from 'next/link'

//components
import RatingStar from "../rating-star";
import Counter from "../counter";

//function
import { generateImgPath } from "../../StaticData/data";

//plugins
//swipers
import { Swiper, SwiperSlide } from "swiper/react";
import { FreeMode, Thumbs } from "swiper";

//sweetalert2
import Swal from "sweetalert2-neutral";

//hook
import { useTranslation } from 'react-i18next';

interface ProductDetailCardProps{
  [x: string]: any;
  thumbnail?:any
  id?:string
  product_name?:string
  count?:string
  final_price?:string
  sku?:string
  description?:string
}

const ProductDetailCard = memo((props:ProductDetailCardProps) => {
  const { t } = useTranslation("common");
  const [thumbsSwiper, setThumbsSwiper] = useState(null);

  const product = [
    {
      id: "01",
      thumbnail: generateImgPath("/assets/images/shop/product/01.webp"),
    },
    {
      id: "04",
      thumbnail: generateImgPath("/assets/images/shop/product/04.webp"),
    },
    {
      id: "02",
      thumbnail: generateImgPath("/assets/images/shop/product/02.webp"),
    },
    {
      id: "03",
      thumbnail: generateImgPath("/assets/images/shop/product/03.webp"),
    },
    
  ];

  const cartSwal = () => {
    Swal.fire({
      title: `${t("streamSweetalert.added")}`,
      text: `${t("streamSweetalert.added_to_cart")}`,
      icon: "success",  
      confirmButtonText: `${t("streamSweetalert.ok_btn")}`,
      background: "#141314",
      color: "#ffffff",
    });
  };
  const wishlistSwal = () => {
    Swal.fire({
      title: `${t("streamSweetalert.added")}`,
      text: `${t("streamSweetalert.added_to_wishlist")}`,
      icon: "success",
      confirmButtonText: `${t("streamSweetalert.ok_btn")}`,
      background: "#141314",
      color: "#ffffff",
    });
  };

  return (
    <Fragment>
      <div className="section-padding-top product-detail">
          <Row>
            <Col lg="6">
              <div className="product-tab-slider">
                <Swiper
                  slidesPerView={1}
                  className="product-tab-slider-thumb swiper-pointer-events swiper-fade wrapper-class"
                  loop={true}
                  // onSwiper={setThumbsSwiper}
                  watchSlidesProgress={true}
                  modules={[Thumbs]}
                >
                  {product.map((item, index) => {
                    return (
                      <SwiperSlide className="p-0" key={index}>
                        <Link href="#">
                          <img
                            src={item.thumbnail}
                            alt={`product-${item.id}`}
                            className="img-fluid product-detail-image"
                          />
                        </Link>
                      </SwiperSlide>
                    );
                  })}
                </Swiper>
                <Swiper
                  thumbs={{
                    swiper:
                      thumbsSwiper && typeof thumbsSwiper !== 'function'
                        ? thumbsSwiper
                        : null,
                  }}
                  
                  freeMode={true}
                  watchSlidesProgress={true}
                  modules={[Thumbs, FreeMode]}
                  slidesPerView={4}
                  spaceBetween={20}
                  loop={true}
                  className="product-tab-slider-images"
                >
                  {product.map((item, index) => {
                    return (
                      <SwiperSlide className="p-0" key={index}>
                        <img
                          src={item.thumbnail}
                          alt={`product-${item.id}`}
                          className="img-fluid "
                        />
                      </SwiperSlide>
                    );
                  })}
                </Swiper>
              </div>
            </Col>
          <Col lg="6" className="mt-lg-0 mt-5 ps-lg-5">
              <h3>{props.product_name}</h3>
              <div className="mt-2 d-flex align-items-center gap-2">
                <RatingStar
                  count="5"
                  count1="0"
                  starColor="text-warning"
                />
                <p className="text-primary mb-0">(2 customer reviews)</p>
              </div>
              <h4 className="product-detail-price">{props.final_price}</h4>
              <p className="producti-detail-description">
                {t("streamShop.product1_desc")}
              </p>
              <div className="add-product-wrapper pb-5">
                <ul className="list-inline m-0 p-0 d-flex align-items-center gap-3 flex-wrap">
                  <li>
                    <Counter />
                  </li>
                  <li className="wish-list">
                    <Link
                      href="/merchandise/wishlist"
                      className="d-inline-block bg-secondary rounded-3  custom-wishlist-btn link-wishlist-btn"
                      
                    >
                      <i className="ph-fill ph-heart-straight fs-5"></i>
                    </Link>
                  </li>
                  <li>
                    <div className="iq-button">
                      <Link
                        href="#"
                        className="btn btn-primary cart-btn  position-relative rounded-3"
                        onClick={cartSwal}
                      >
                        <span className="button-text">
                          {t("streamButtons.add_to_cart")}
                        </span>
                      </Link>
                    </div>
                  </li>
                </ul>
              </div>

              <div className="product-meta-wrapper">
                <ul className="list-inline m-0 p-0">
                  <li className="mb-2">
                    <span className="text-white fw-semibold">
                      {t("streamShop.sku")} :{" "}
                    </span>{" "}
                    <h6 className="d-inline text-body ms-2"> {props.sku}</h6>
                  </li>
                  <li className="mb-2">
                    <span className="text-white fw-semibold">
                      {t("streamForm.categories")} :{" "}
                    </span>
                    <h6 className="d-inline product-category-list ms-2">
                      <Link href="#">{t("streamShop.uptight_birds")}</Link>
                    </h6>
                  </li>
                  <li>
                    <span className="text-white fw-semibold">
                      {t("streamTag.tags")}{" "}
                    </span>
                    <h6 className="d-inline product-tag-list ms-2">
                      <Link href="#">{t("streamShopTag.costume")}</Link>
                    </h6>
                  </li>
                </ul>
              </div>
            </Col>
          </Row>
           <div className="section-padding-top px-0">
            <div className="product-detail-tabs">
              <Tab.Container defaultActiveKey="first">
                <Nav
                  as="ul"
                  className="list-inline nav-pills justify-content-center iq-custom-tab tab-bg-gredient-center flex-md-row flex-column gap-md-5 gap-3 mb-5"
                  role="tablist"
                >
                  <Nav.Item as="li">
                    <Nav.Link
                      data-toggle="pill"
                      data-bs-target="#description"
                      eventKey="first"
                      role="tab"
                      aria-selected="true"
                    >
                      {t("streamShop.description")}
                    </Nav.Link>
                  </Nav.Item>
                  <Nav.Item as="li">
                    <Nav.Link
                      data-toggle="pill"
                      eventKey="second"
                      data-bs-target="#additional-info"
                      role="tab"
                      aria-selected="false"
                    >
                      {t("streamShop.additional_information")}
                    </Nav.Link>
                  </Nav.Item>
                  <Nav.Item as="li">
                    <Nav.Link
                      data-toggle="pill"
                      eventKey="third"
                      data-bs-target="#reviews"
                      role="tab"
                      aria-selected="false"
                    >
                      {t("streamShop.reviews")}
                    </Nav.Link>
                  </Nav.Item>
                </Nav>
                <Tab.Content className="tab-content">
                  <Tab.Pane id="description" eventKey="first">
                    <p className="m-0">{props.description}</p>
                  </Tab.Pane>
                  <Tab.Pane
                    id="additional-info"
                    eventKey="second"
                    className="fade"
                  >
                    <div className="table-responsive additional-info-table">
                      <h2 className="add-info-title">{t("streamShop.additional_information")}</h2>
                      <table className="table table-additional">
                        <tbody>
                          <tr className="text-body">
                            <th className="text-center">{t("streamShop.color")}</th>
                            <td className="bordertd">
                              {props.additional_info.map((item:any, index:number) => {
                                return (
                                  <div key={index}>
                                    {item.color.map((color:any, index:number) => {
                                      
                                      return (
                                        <span key={index} className="text-primary fst-italic fw-semibold">
                                          {color}
                                          {item.color.length > 1
                                            ? ","
                                            : ""}{" "}
                                        </span>
                                      );
                                    })}
                                  </div>
                                );
                              })}
                            </td>
                          </tr>
                          <tr className="text-body">
                            <th className="text-center">{t("streamShop.size")}</th>
                            <td className="bordertd">
                              {props.additional_info.map((item:any, index:number) => {
                                return (
                                  <span  rel="color" key={index}>
                                    {item.size.map((size:any, index:number) => {
                                      const isLast = index === item.size.length - 1;
                                      return (
                                        <Fragment key={index}>
                                        <span className="text-primary fst-italic fw-semibold" key={index}>
                                          {size}
                                        </span> {!isLast && ', '}{" "}
                                        </Fragment>
                                      );
                                    })}
                                  </span>
                                );
                              })}
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </Tab.Pane>
                  <Tab.Pane
                    id="reviews"
                    eventKey="third"
                    className="tab-pane animated fadeInUp fade"
                  >
                    <h4 className="mb-4">{t("streamShop.reviews_believe_mask")}</h4>
                    <div className="product-review-list">
                      <ul className="list-inline m-0 p-0">
                        <li className="mb-5 mb-5 reviews-bg p-4">
                          <div className="d-flex flex-sm-row flex-column  align-items-start gap-4">
                            <div className="user-image flex-shrink-0">
                              <img
                                src=
                                  "/assets/images/shop/avatar.webp"
                                alt=""
                                className="img-fluid rounded-circle"
                              />
                            </div>
                            <div className="about-user">
                              <div className="d-flex align-items-center justify-content-between flex-wrap gap-2">
                                <p className="mb-0">{t("streamAccount.jack_stark")}</p>
                                <RatingStar
                                  count="5"
                                  count1="0"
                                  starColor="text-warning"
                                />
                              </div>

                              <span className="text-capitalize  published-date">
                                march 2, 2022
                              </span>
                              <div className="lh-1 ratting"></div>
                              <div className="mt-3 border-top">
                                <p className="mt-3 mb-0">{t("streamShop.desc1")}.</p>
                              </div>
                            </div>
                          </div>
                        </li>
                        <li className="mb-5 mb-5 reviews-bg p-4">
                          <div className="d-flex flex-sm-row flex-column  align-items-start gap-4">
                            <div className="user-image flex-shrink-0">
                              <img
                                src=
                                  "/assets/images/shop/avatar.webp"
                                alt=""
                                className="img-fluid rounded-circle"
                              />
                            </div>
                            <div className="about-user">
                              <div className="d-flex align-items-center justify-content-between flex-wrap gap-2">
                                <p className="mb-0">{t("Jhon Deo")}</p>
                                <RatingStar
                                  count="5"
                                  count1="0"
                                  starColor="text-warning"
                                />
                              </div>

                              <span className="text-capitalize  published-date">
                                march 2, 2022
                              </span>
                              <div className="lh-1 ratting"></div>
                              <div className="mt-3 border-top">
                                <p className="mt-3 mb-0">{t("streamFaq.desc")}.</p>
                              </div>
                            </div>
                          </div>
                        </li>
                      </ul>
                    </div>
                    <div className="mt-5 review-form">
                      <h4>{t("streamButtons.add_review")}</h4>
                      <p className="mb-5">
                        {t("streamShop.published_email")}{" "}
                        {t("streamShop.required_fields")}
                      </p>
                      <p className="mb-2">{t("streamShop.your_rating")} *</p>
                      <Form className="needs-validation" noValidate>
                        <div className="rating">
                          <RatingStar
                            count="5"
                            count1="0"
                            starColor="text-warning"
                          />
                        </div>
                        <div className="mb-5 mt-4">
                          <Form.Label className="">
                            {t("streamShop.your_review")} *
                          </Form.Label>
                          <Form.Control
                            as="textarea"
                            rows={5}
                            className=""
                            required
                          ></Form.Control>
                        </div>
                        <div className="mb-5">
                          <Form.Label className="">
                            {t("streamAccount.name")}*
                          </Form.Label>
                          <Form.Control
                            type="text"
                            className=" rounded-0"
                            required
                          />
                        </div>
                        <div className="mb-5">
                          <Form.Label className="form-label">
                            {t("streamAccount.email")}*
                          </Form.Label>
                          <Form.Control
                            type="email"
                            className=" rounded-0"
                            required
                          />
                        </div>
                        <div className="mb-5 form-check">
                          <input
                            type="checkbox"
                            className="form-check-input rounded-0"
                            id="exampleCheck1"
                            required
                          />
                          <label
                            className="form-check-label"
                            htmlFor="exampleCheck1"
                          >
                            {t("streamAccount.save_name")}
                          </label>
                        </div>
                        <div className="iq-button">
                          <Link
                            href="#"
                            className="btn btn-primary text-capitalize position-relative rounded-3"
                          >
                            <span className="button-text">
                              {t("streamButtons.submit")}
                            </span>
                          </Link>
                        </div>
                      </Form>
                    </div>
                  </Tab.Pane>
                </Tab.Content>
              </Tab.Container>
            </div>
          </div>
      </div>
    </Fragment>
  );
});

ProductDetailCard.displayName = "ProductDetailCard";
export default ProductDetailCard;
