// tamplate/streamithtml-540/streamit-html/code-next/src/app/(frontend-pages)/blogs/grid/[type]/page.tsx
"use client"

import React, { Fragment, memo } from 'react'

//react-bootstrap
import { Row, Col, Container } from 'react-bootstrap'


//component
import CardBlogGrid from '@/components/cards/CardBlogGrid'

//static data 
import { blogsGrid , FourblogsGrid } from '@/StaticData/blogs'

//hook
import { useTranslation } from 'react-i18next';

import GridPageBreadCrumb from '@/components/blog/GridPageBreadCrumb'
import { usePathname } from 'next/navigation'
import Link from 'next/link'

// import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

// export async function getStaticProps(context: { locale: any; }) {
//     // extract the locale identifier from the URL
//     const { locale } = context

//     return {
//         props: {
//             // pass the translation props to the page component
//             ...(await serverSideTranslations(locale)),
//         },
//     }
// }

export async function getStaticPaths(type: String) {

    return {
        paths: [], //indicates that no page needs be created at build time
        fallback: 'blocking' //indicates the type of fallback
    }
}


const BlogGrid = memo((props) => {
    const { t } = useTranslation("common");
    const router = usePathname();


    let _column: number = 12;
    let data: any
    switch (router) {
        case '/blogs/grid/one-column':
            _column = 12;
            break;
        case '/blogs/grid/two-column':
            _column = 6;
            break;
        case '/blogs/grid/three-column':
            _column = 4;
            break;
        case '/blogs/grid/four-column':
            _column = 3;
            break;
        default:
            break;
    }

    const grid_data = data !== undefined && data !== null ? data.slice(0 , 14) : blogsGrid.slice(0, 14)
    return (
        <Fragment>
            <GridPageBreadCrumb type={router}></GridPageBreadCrumb>
                  <div className="blog-column-pages section-padding">
        <Container fluid={_column === 3}>
          <Row className="gy-5">
            {grid_data.map((item:any, index:number) => {
              return (
                <Col lg={_column} md={_column} sm="12" key={index}>
                  <CardBlogGrid
                    title={t(item.title)}
                    thumbnail={item.thumbnail}
                    description={t(item.description)}
                    username={t(item.username)}
                    blogDate={item.blogDate}
                    link_button={true}
                    button_icon={true}
                  ></CardBlogGrid>
                </Col>
              );
            })}
          </Row>
          <div className="iq-button text-center mt-3">
            <Link
              href="#"
              className="btn btn-primary text-capitalize position-relative rounded-3"
            >
              <span className="button-text">{t("streamButtons.load_more")} </span>
            </Link>
          </div>
        </Container>
      </div>
        </Fragment>
    );
});

BlogGrid.displayName = "BlogGrid";
export default BlogGrid;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/blogs/grid/[type].vue
<template>
  <div class="blog-column-pages section-padding">
    <div :class="isFluid">
      <b-row :class="rowClass">
        <b-col v-for="blog in selectedBlogs" :key="blog.id" :lg="column" sm="12">
          <CardBlogList             
            :id="blog.id"
            :thumbnail="blog.thumbnail"
            :blog-tag="$t(blog.username)"
            :slug="blog.slug"
            :blog-title="$t(blog.title)"
            :blog-text="$t(blog.description)"
            :blog-date="blog.blogDate"
            :link-button="true"
            :categories-list="blog.category"
            :right-icon="true" />
        </b-col>
      </b-row>
      <div class="text-center sidebar-btn mt-3">
        <CustomButton link="#" :notBtncaretIcon="true" :button-title="$t('streamButtons.load_more')" />
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onUnmounted, onMounted } from "vue";

import CardBlogList from "~/components/cards/CardBlogList.vue";
import { blogs } from "~/StaticData/blogs";
import { useRoute } from "vue-router";
import { useStremit } from "~/store/streamit";
import CustomButton from "~/components/CustomButton.vue";

const generateImgPath = (path) => {
  return window.location.origin + path;
};

const store = useStremit();

const column = ref(12);

const isFluid = ref('')

const route = useRoute();

const type = computed(() => route.params.type);

const changeGridColumn = () => {
  switch (type.value) {
    case "one-column":
      column.value = 12;
      isFluid.value = 'container';
      store.breadcrumbSet({ show: true, name: "One Column Blog" });
      break;
    case "two-column":
      column.value = 6;
      isFluid.value = 'container'
      store.breadcrumbSet({ show: true, name: "Two Column Blog" });
      break;
    case "three-column":
      column.value = 4;
      isFluid.value = 'container'
      store.breadcrumbSet({ show: true, name: "Three Column Blog" });
      break;
    case "four-column":
      column.value = 3;
      isFluid.value = 'container-fluid'
      store.breadcrumbSet({ show: true, name: "Four Column Blog" });
      break;

    default:
      break;
  }
};

onUnmounted(() => {
  store.breadcrumbSet({ show: false, name: "" });
});

onMounted(() => {
  changeGridColumn();
});

watch(
  type,
  (value) => {
    changeGridColumn();
  },
  { deep: true }
);

const selectedBlogs = computed(() => {
  if (column.value === 12) return blogs;
  if (column.value === 6) return blogs;
  if (column.value === 3) return blogs;
  return blogs; // Default fallback
});

// Dynamic row class
const rowClass = computed(() => {
  if (column.value === 12) return 'row-cols-1 gy-5';
  if (column.value === 6) return 'row-cols-lg-2 row-cols-md-2 gy-5';
  if (column.value === 4) return 'row-cols-xl-3 row-cols-md-3 gy-5';
  return 'row-cols-lg-4 row-cols-md-4 gy-5';
});
</script>
