// tamplate/streamithtml-540/streamit-html/code-react/dashboard/src/views/dashboard/extra/privacy-policy.jsx
import React from "react";

//react-bootstrap
import { Container, Row, Col, Card } from "react-bootstrap";
// the hook
import { useTranslation } from "react-i18next";

const PrivacyPolicy = () => {
  const { t } = useTranslation();
  return (
    <Row>
      <Col lg={12}>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.what_lorem")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line1")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.we_use")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.where_it")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.get_some?")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.we_use")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.we_use")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.we_use")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.we_use")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.we_use")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
      </Col>
    </Row>
  );
};

export default PrivacyPolicy;

// tamplate/streamithtml-540/streamit-html/code-vue/dashboard/src/views/extra/PrivacyPolicy.vue
<template>
  <b-row>
    <b-col lg="12">
      <b-card no-body>
        <b-card-header class="d-flex justify-content-between">
          <div class="header-title">
            <b-card-title>{{$t('movielist.what_is_lorem_ipsum')}}?</b-card-title>
          </div>
        </b-card-header>
        <b-card-body>
          <p>{{$t('movielist.privacydesc1')}}</p>
        </b-card-body>
      </b-card>
      <b-card no-body>
        <b-card-header class="d-flex justify-content-between">
          <div class="header-title">
            <b-card-title>{{$t('movielist.why_do_we_use_it')}}?</b-card-title>
          </div>
        </b-card-header>
        <b-card-body>
          <p>{{$t('movielist.privacydesc2')}}</p>
        </b-card-body>
      </b-card>
      <b-card no-body>
        <b-card-header class="d-flex justify-content-between">
          <div class="header-title">
            <b-card-title>{{$t('movielist.where_does')}}?</b-card-title>
          </div>
        </b-card-header>
        <b-card-body>
          <p>{{$t('movielist.privacydesc2')}}</p>
        </b-card-body>
      </b-card>
      <b-card no-body>
        <b-card-header class="d-flex justify-content-between">
          <div class="header-title">
            <b-card-title>{{$t('movielist.where_can_i_get_some')}}?</b-card-title>
          </div>
        </b-card-header>
        <b-card-body>
          <p>{{$t('movielist.privacydesc2')}}</p>
        </b-card-body>
      </b-card>
      <b-card no-body>
        <b-card-header class="d-flex justify-content-between">
          <div class="header-title">
            <b-card-title>{{$t('movielist.why_do_we_use_it')}}?</b-card-title>
          </div>
        </b-card-header>
        <b-card-body>
          <p>{{$t('movielist.privacydesc2')}}</p>
        </b-card-body>
      </b-card>
      <b-card no-body>
        <b-card-header class="d-flex justify-content-between">
          <div class="header-title">
            <b-card-title>{{$t('movielist.why_do_we_use_it')}}?</b-card-title>
          </div>
        </b-card-header>
        <b-card-body>
          <p>{{$t('movielist.privacydesc2')}}</p>
        </b-card-body>
      </b-card>
      <b-card no-body>
        <b-card-header class="d-flex justify-content-between">
          <div class="header-title">
            <b-card-title>{{$t('movielist.why_do_we_use_it')}}?</b-card-title>
          </div>
        </b-card-header>
        <b-card-body>
          <p>{{$t('movielist.privacydesc2')}}</p>
        </b-card-body>
      </b-card>
      <b-card no-body>
        <b-card-header class="d-flex justify-content-between">
          <div class="header-title">
            <b-card-title>{{$t('movielist.why_do_we_use_it')}}?</b-card-title>
          </div>
        </b-card-header>
        <b-card-body>
          <p>{{$t('movielist.privacydesc2')}}</p>
        </b-card-body>
      </b-card>
      <b-card no-body>
        <b-card-header class="d-flex justify-content-between">
          <div class="header-title">
            <b-card-title>{{$t('movielist.why_do_we_use_it')}}?</b-card-title>
          </div>
        </b-card-header>
        <b-card-body>
          <p>{{$t('movielist.privacydesc2')}}</p>
        </b-card-body>
      </b-card>
    </b-col>
  </b-row>
</template>
<script>
export default {
  name: 'PrivacyPolicy',
};
</script>
