// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/AuthPages/LostPassword.vue
<template>
  <section class="sign-in-page vh-100" :style="`background: url(${generateImgPath('./assets/images/pages/01.webp')}); background-size: cover; background-repeat: no-repeat; position: relative;min-height:500px;`">
    <b-container>
      <b-row class="justify-content-center align-items-center height-self-center vh-100">
        <b-col lg="5" md="12" class="align-self-center">
          <div class="user-login-card bg-body">
            <p>
              {{ $t('streamForm.desc_enter1') }}
            </p>
            <form action="#">
              <div class="mb-5">
                <label class="text-white fw-500 mb-2">{{ $t('streamAccount.username_or_email') }}</label>
                <input type="text" class="form-control rounded-0" required="" />
              </div>
              <div class="iq-button">
                <a href="#" class="btn text-uppercase position-relative">
                  <span class="button-text">{{ $t('streamProfile.label_new_password') }}</span>
                  {{ '' }}
                  <i class="fa-solid fa-play"></i>
                </a>
              </div>
              <div class="seperator d-flex justify-content-center align-items-center">
                <span class="line"></span>
              </div>
              <div class="iq-button">
                <router-link :to="{ name: 'landing-page.login-page' }" class="btn text-uppercase position-relative">
                  <span class="button-text">{{ $t('streamAccount.log_in') }}</span>
                  {{ '' }}
                  <i class="fa-solid fa-play"></i>
                </router-link>
              </div>
            </form>
          </div>
        </b-col>
      </b-row>
    </b-container>
  </section>
</template>
<script setup>
import { generateImgPath } from '../../StaticData/data';
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/AuthPages/LostPassword.jsx
import React, { Fragment, memo } from "react";

//react bootstrap
import { Col, Container, Form, Row } from "react-bootstrap";

//react-router-dom
import { Link } from "react-router-dom";

// the hook
import { useTranslation } from "react-i18next";

const LostPassword = memo(() => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <main className="main-content">
        <div
          className="vh-100"
          style={{
            backgroundImage: "url(assets/images/pages/01.webp)",
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
            position: "relative",
            minHeight: "500px",
          }}
        >
          <Container>
            <Row className="justify-content-center align-items-center height-self-center vh-100">
              <Col lg="5" md="12" className="align-self-center">
                <div className="user-login-card bg-body">
                  <p> {t("streamForm.desc_enter1")}</p>
                  <Form action="post">
                    <Form.Group className="mb-5">
                      <Form.Label className="text-white fw-500 mb-2">
                        {t("streamAccount.username_or_email")}
                      </Form.Label>
                      <Form.Control type="text" className="rounded-0" />
                    </Form.Group>
                    <div className="iq-button">
                      <Link
                        to="#"
                        className="btn text-uppercase position-relative"
                      >
                        <span className="button-text">
                          {t("streamShop.new_password")}
                        </span>
                        <i className="fa-solid fa-play"></i>
                      </Link>
                    </div>
                    <div className="seperator d-flex justify-content-center align-items-center">
                      <span className="line"></span>
                    </div>
                    <div className="iq-button">
                      <Link
                        to="/login"
                        className="btn text-uppercase position-relative"
                      >
                        <span className="button-text">{t("streamAccount.log_in")}</span>
                        <i className="fa-solid fa-play"></i>
                      </Link>
                    </div>
                  </Form>
                </div>
              </Col>
            </Row>
          </Container>
        </div>
      </main>
    </Fragment>
  );
});

LostPassword.displayName = "LostPassword";
export default LostPassword;
