// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/blog/DetailMetaList.tsx
import React, { Fragment, memo } from "react";

//router
import Link from "next/link";

//components
import RecentPost from "./sidebar/RecentPost";
import CategoriesWidget from "./sidebar/CategoriesWidget";
import TagsWidget from "./sidebar/TagsWidget";
import FollowUs from "./sidebar/FollowUs";

//hook
import { useTranslation } from 'react-i18next';

const DetailMetaList = memo(() => {
   const { t } = useTranslation("common");
  return (
    <Fragment>
      <div className="widget-area">
           <div id="search-2" className="widget widget_search rounded-top-3">
          <form
            method="get"
            className="search-form"
            action="#"
            autoComplete="off"
          >
            <div className="block-search_inside-wrapper position-relative d-flex">
              <input
                type="search"
                className="form-control"
                placeholder={t('streamBlog.search1')}
                name="s"
                defaultValue=""
              />
              <button type="submit" className="block-search_button d-flex align-items-center justify-content-center rounded-end-3">
                <i className="icon icon-search-normal"></i>
              </button>
            </div>
          </form>
        </div>
        <CategoriesWidget />
        <TagsWidget />
        <FollowUs />
      </div>
    </Fragment>
  );
});

DetailMetaList.displayName = "DetailMetaList";
export default DetailMetaList;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/blog/DetailMetaList.vue
<template>
  <div class="widget-area">
    <div id="search-2" class="widget widget_search">
      <form method="get" class="search-form" action="#" autoComplete="off">
        <div class="block-search_inside-wrapper position-relative d-flex">
          <input type="search" class="form-control" :placeholder="$t('streamBlog.search1')" value="" name="s" />
          <button type="submit" class="block-search_button d-flex align-items-center justify-content-center rounded-end-3">
            <svg class="icon-16" width="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <circle
cx="11.7669" cy="11.7666" r="8.98856" stroke="currentColor" stroke-width="1.5"
                stroke-linecap="round" stroke-linejoin="round"></circle>
              <path
d="M18.0186 18.4851L21.5426 22" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
                stroke-linejoin="round"></path>
            </svg>
          </button>
        </div>
      </form>
    </div>

    <CategoriesWidget></CategoriesWidget>
    <TagsWidget :tags="blogTags.name"></TagsWidget>
    <FollowUs></FollowUs>
  </div>
</template>
<script setup>
import TagsWidget from '../../components/blog/sidebar/TagsWidget.vue';
import CategoriesWidget from '../../components/blog/sidebar/CategoriesWidget.vue';
import FollowUs from './sidebar/FollowUs.vue';
import { blogTags } from '../../StaticData/blogs';
</script>
