// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/partials/FooterDefault.tsx
import { memo, Fragment, useState, useEffect } from "react";

import Link from "next/link";

// react-bootstrap
import { Container, Row, Col } from "react-bootstrap";

// components
import Logo from "../logo";

//hook
import { useTranslation } from 'react-i18next';

const FooterMega = memo(() => {
  const { t } = useTranslation("common");
  const [animationClass, setAnimationClass] = useState("animate__fadeIn");
  // const location = useLocation();

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handleScroll = () => {
    if (document.documentElement.scrollTop > 250) {
      setAnimationClass("animate__fadeIn");
    } else {
      setAnimationClass("animate__fadeOut");
    }
  };

  useEffect(() => {
    handleScroll();
    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  // useEffect(() => {
  //   scrollToTop();
  // }, [location.pathname]);
  return (
    <>
      <Fragment>
        <footer className="footer footer-default">
          <div className="footer-top">
            <Container fluid>
              <Row className="gy-4">
                <Col lg={3} sm={6}>
                  <div className="footer-logo">
                    <Logo></Logo>
                  </div>
                  <div className="">
                    {t("streamAccount.email_us")}:{" "}
                    <span className="text-white">
                      {t("streamAccount.customer@stremit")}
                    </span>
                  </div>
                  <p
                    className="mt-0 mb-2
                  "
                  >
                    {t("streamAccount.helpline_number")}
                  </p>
                  <Link href="tel:+4805550103" className="helpline">
                    +(480) 555-0103
                  </Link>
                </Col>
                <Col lg={2} sm={6}>
                  <h4 className="footer-link-title text-capitalize">
                    {t("sectionTitle.movies_to_watch")}
                  </h4>
                  <ul className="list-unstyled footer-menu mb-0">
                    <li className="">
                      <Link href="/view-all">{t("sectionTitle.top_trending")}</Link>
                    </li>
                    <li className="">
                      <Link href="/view-all">{t("sectionTitle.recommended")}</Link>
                    </li>
                    <li>
                      <Link href="/view-all">{t("sectionTitle.popular")}</Link>
                    </li>
                  </ul>
                </Col>
                <Col lg={2} sm={6}>
                  <h4 className="footer-link-title text-capitalize">
                    {t("sectionTitle.quick_links")}
                  </h4>
                  <ul className="list-unstyled footer-menu mb-0">
                    <li className="">
                      <Link href="/extra/contact-us">{t("streamPages.contact_us")}</Link>
                    </li>
                    <li className="">
                      <Link href="/extra/pricing-plan">{t("streamPages.pricing_plan")}</Link>
                    </li>
                    <li className="">
                      <Link href="/blogs">{t("streamPages.blog")}</Link>
                    </li>
                    <li>
                      <Link href="/extra/faq">{t("streamPages.faq")}</Link>
                    </li>
                  </ul>
                </Col>
                <Col lg={2} sm={6}>
                  <h4 className="footer-link-title text-capitalize">
                    {t("sectionTitle.about_company")}
                  </h4>
                  <ul className="list-unstyled footer-menu mb-0">
                    <li className="">
                      <Link href="/extra/about-us">{t("streamPages.about_us")}</Link>
                    </li>
                    <li className="">
                      <Link href="/merchandise/shop">{t("streamPages.shop")}</Link>
                    </li>
                    <li>
                      <Link href="/extra/terms-of-use">
                        {t("sectionTitle.terms_and_use")}
                      </Link>
                    </li>
                    <li className="">
                      <Link href="/extra/privacy-policy">
                        {t("sectionTitle.privacy_policy")}
                      </Link>
                    </li>
                  </ul>
                </Col>
                <Col lg={3} sm={6}>
                  <h4 className="footer-link-title">
                    {t("sectionTitle.newsletter")}
                  </h4>
                  <div className="mailchimp mailchimp-dark">
                    <div className="input-group mb-3 mt-4">
                      <input
                        type="text"
                        className="form-control mb-0"
                        placeholder={t("streamAccount.email")}
                        aria-describedby="button-addon2"
                      />
                      <div className="iq-button">
                        <button
                          type="submit"
                          className="btn btn-primary st-subscribe-btn"
                          id="button-addon2"
                        >
                          {t("streamButtons.subscribe")}
                        </button>
                      </div>
                    </div>
                  </div>
                  <div className="d-flex align-items-center gap-3 widget-streamit-social-media mt-4">
                    <h3 className="font-size-14 widget-streamit-social-media-title">
                      {t("streamSocial.follow_us")}
                    </h3>
                    <ul className="m-0 d-inline list-unstyled widget_social_media d-flex gap-2 flex-wrap">
                      <li className="">
                        <Link
                          href="https://www.facebook.com/"
                          className="position-relative"
                        >
                          <i className="icon icon-facebook-share"></i>
                        </Link>
                      </li>{" "}
                      <li className="">
                        <Link
                          href="https://twitter.com/"
                          className="position-relative"
                        >
                          <i className="ph ph-x-logo"></i>
                        </Link>
                      </li>{" "}
                      <li className="">
                        <Link
                          href="https://github.com/"
                          className="position-relative"
                        >
                          <i className="ph ph-instagram-logo"></i>
                        </Link>
                      </li>{" "}
                      <li className="">
                        <Link
                          href="https://www.instagram.com/"
                          className="position-relative"
                        >
                          <i className="ph-fill ph-linkedin-logo"></i>
                        </Link>
                      </li>
                    </ul>
                  </div>
                </Col>
              </Row>
            </Container>
          </div>
          <div className="footer-bottom border-top">
            <Container fluid>
              <Row className="align-items-center">
                <Col md={6}>
                  <p className="font-size-14 mb-0">
                    © <span className="currentYear">2025</span>{" "}
                    <span className="text-primary">STREAMIT</span>.{" "}
                    {t("streamAccount.desc")}
                  </p>
                </Col>
                <Col md={6} className="mt-md-0 mt-5">
                  <div className="d-flex flex-column align-items-start align-items-md-end widget-iq-download-app">
                    <h6 className="mb-3 fw-bold">{t("streamAccount.download_app")}</h6>
                    <div className="d-flex align-items-center">
                      <Link className="app-image" href="#">
                        <img
                          src="/assets/images/footer/play-store.webp"
                          loading="lazy"
                          alt="play-store"
                        />
                      </Link>
                      <br />
                      <Link className="ms-3 app-image" href="#">
                        <img
                          src="/assets/images/footer/app-store.webp"
                          loading="lazy"
                          alt="app-store"
                        />
                      </Link>
                    </div>
                  </div>
                </Col>
              </Row>
            </Container>
          </div>
        </footer>
        <div
          id="back-to-top"
          style={{ display: "none" }}
          className={`animate__animated ${animationClass}`}
          onClick={scrollToTop}
        >
          <Link
            className="p-0 btn bg-primary btn-sm position-fixed top border-0 rounded-circle"
            id="top"
            href="#top"
          >
            <i className="fa-solid fa-chevron-up"></i>
          </Link>
        </div>
      </Fragment>
    </>
  );
});
FooterMega.displayName = "FooterMega";
export default FooterMega;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/partials/FooterDefault.vue
<template>
  <footer class="footer footer-default">
    <div class="footer-top">
      <div class="container-fluid">
        <div class="row gy-4">
          <div class="col-lg-3 col-sm-6">
            <div class="footer-logo">
              <BrandLogo></BrandLogo>
            </div>
            <div>{{ $t('streamAccount.email_us') }} <span class="text-white">customer@streamit.com</span></div>
            <p class="mt-0 mb-2">{{$t('streamAccount.helpline_number')}}</p>
            <a href="tel:+4805550103" class="helpline">+(480) 555-0103</a>
          </div>
          <div class="col-lg-2 col-sm-6">
             <h4 class="footer-link-title text-capitalize">{{ $t('sectionTitle.movies_to_watch') }}</h4>
             <ul class="list-unstyled footer-menu mb-0">
              <li>
                <nuxt-link class="text-capitalize" :to="{ name: 'view-all' }"> {{ $t('sectionTitle.top_trending') }}</nuxt-link>
              </li>
              <li>
                <nuxt-link class="text-capitalize" :to="{ name: 'view-all' }"> {{ $t('sectionTitle.recommended') }} </nuxt-link>
              </li>
              <li>
                <nuxt-link class="text-capitalize" :to="{ name: 'view-all' }"> {{ $t('sectionTitle.popular') }} </nuxt-link>
              </li>
            </ul>
          </div>
          <div class="col-lg-2 col-sm-6">
            <h4 class="footer-link-title text-capitalize">{{ $t('sectionTitle.quick_links') }}</h4>
            <ul class="list-unstyled footer-menu mb-0">
              <li>
                <nuxt-link class="text-capitalize" :to="{ name: 'extra-contact-us' }">{{ $t('streamPages.contact_us') }} </nuxt-link>
              </li>
              <li>
                <nuxt-link class="text-capitalize" :to="{ name: 'pricing-plan' }"> {{ $t('streamPages.pricing_plan') }} </nuxt-link>
              </li>
              <li>
                <nuxt-link class="text-capitalize" :to="{ name: 'blogs' }"> {{ $t('streamPages.blog') }} </nuxt-link>
              </li>
              <li>
                <nuxt-link class="text-capitalize" :to="{ name: 'extra-faq' }"> {{ $t('streamPages.faq') }} </nuxt-link>
              </li>
            </ul>
          </div>
          <div class="col-lg-2 col-sm-6">
            <h4 class="footer-link-title text-capitalize">{{ $t('sectionTitle.about_company') }}</h4>
            <ul class="list-unstyled footer-menu mb-0">
              <li>
                <nuxt-link class="text-capitalize" :to="{ name: 'extra-about-us' }"> {{ $t('streamPages.about_us') }} </nuxt-link>
              </li>
              <li>
                <nuxt-link class="text-capitalize" :to="{ name: 'merchandise-shop' }"> {{ $t('streamPages.shop') }} </nuxt-link>
              </li>
              <li>
                <nuxt-link :to="{ name: 'extra-terms-of-use' }"> {{ $t('sectionTitle.terms_and_use') }} </nuxt-link>
              </li>
              <li>
                <nuxt-link class="text-capitalize" :to="{ name: 'extra-privacy-policy' }"> {{ $t('sectionTitle.privacy_policy') }} </nuxt-link>
              </li>
            </ul>
          </div>
          <div class="col-xl-3 col-lg-6">
            <h4 class="footer-link-title text-capitalize">{{ $t('sectionTitle.newsletter') }}</h4>
            <div class="mailchimp mailchimp-dark">
              <div class="input-group">
                <input type="text" class="form-control mb-0" :placeholder="$t('streamAccount.email')" aria-describedby="button-addon2" />
                <div class="iq-button">
                  <button id="button-addon2" type="submit" class="btn btn-primary st-subscribe-btn">{{ $t('streamButtons.subscribe') }}</button>
                </div>
              </div>
            </div>
            <div class="d-flex align-items-center gap-3 widget-streamit-social-media mt-4">
              <h3 class="font-size-14 widget-streamit-social-media-title">{{ $t('streamButtons.follow_us') }}</h3>
              <div class="social-footer">
                <ul class="m-0 d-inline list-unstyled widget_social_media d-flex gap-2 flex-wrap">
                  <li>
                    <a href="https://www.facebook.com/" class="position-relative">
                      <i class="icon icon-facebook-share"></i>
                    </a>
                  </li>
                  {{
                    ' '
                  }}
                  <li>
                    <a href="https://twitter.com/" class="position-relative">
                      <i class="ph ph-x-logo"></i>
                    </a>
                  </li>
                  {{
                    ' '
                  }}
                  <li>
                    <a href="https://www.instagram.com/" class="position-relative">
                      <i class="ph ph-instagram-logo"></i>
                    </a>
                  </li>
                  {{
                    ' '
                  }}
                  <li>
                    <a href="https://github.com/" class="position-relative">
                      <i class="ph-fill ph-linkedin-logo"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-bottom">
      <b-container fluid>
        <b-row class="align-items-center">
          <b-col md="6">
            <p class="font-size-14 mb-0">© <span class="currentYear">2025</span> <span class="text-primary">STREAMIT.</span> {{$t('streamAccount.desc')}}</p>
          </b-col>
          <b-col md="6" class="mt-md-0 mt-5">
            <div class="d-flex flex-column align-items-start align-items-md-end widget-iq-download-app">
              <h6 class="mb-3 fw-bold">{{$t('streamAccount.download_app')}}</h6>
              <div>
                <ul class="d-inline-flex flex-wrap align-items-center list-inline m-0 p-0 gap-3">
                  <li class="m-0 p-0">
                    <a class="app-image" href="#">
                      <img src="/assets/images/footer/play-store.webp" loading="lazy" alt="play-store" />
                    </a>
                  </li>
                  <li class="m-0 p-0">
                    <a class="app-image" href="#">
                      <img src="/assets/images/footer/app-store.webp" loading="lazy" alt="app-store" />
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </b-col>
        </b-row>
      </b-container>
    </div>
  </footer>
</template>
<script setup>
import BrandLogo from '../brand/BrandLogo.vue';
</script>
