// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/MobileFooter.jsx
import React from "react";
import { Link } from "react-router-dom";

//hook
import { useTranslation } from "react-i18next";

const MobileFooter = () => {
    const { t } = useTranslation();
    return(
        <>
        <div className="streamit-mobile-footer-menu" aria-label="Mobile Footer Navigation">
    <ul className="footer-menu list-inline d-flex align-items-center justify-content-between m-0">
        <li className="footer-menu-item">
            <Link to="/view-all" className="menu-link font-size-12 text-capitalize">
                <i className="ph ph-film-reel d-block  text-center "></i>
                {t("streamPages.movie")} </Link>
        </li>
        <li className="footer-menu-item">
            <Link to="/view-all" className="menu-link font-size-12 text-capitalize">
                <i className="ph ph-monitor-play d-block  text-center "></i>
                {t("streamPages.video")} </Link>
        </li>
        <li className="footer-menu-item">
            <Link to="/view-all" className="menu- font-size-12 text-capitalize">
                <i className="ph ph-magnifying-glass d-block  text-center "></i>
                {t("streamBlog.search1")} </Link>
        </li>
        <li className="footer-menu-item">
            <Link to="/view-all" className="menu-link font-size-12 text-capitalize">
                <i className="ph ph-television d-block  text-center "></i>
               {t("streamPages.tv_show")} </Link>
        </li>
        <li className="footer-menu-item">
            <Link to="/profile-marvin" className="menu-link font-size-12 text-capitalize">
                <i className="ph ph-user d-block  text-center "></i>
                {t("streamAccount.profile")} </Link>
        </li>
    </ul>
</div>
        </>
    )
}

export default MobileFooter

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/partials/MobileFooter.vue
<template>
  <div class="streamit-mobile-footer-menu" aria-label="Mobile Footer Navigation">
    <ul class="footer-menu list-inline d-flex align-items-center justify-content-between m-0">
      <li class="footer-menu-item">
        <nuxt-link :to="{ name: 'view-all' }" class="menu-link font-size-12">
          <i class="ph ph-film-reel d-block text-center"></i>
          Movies
        </nuxt-link>
      </li>
      <li class="footer-menu-item">
        <nuxt-link :to="{ name: 'view-all' }" class="menu-link font-size-12">
          <i class="ph ph-monitor-play d-block text-center"></i>
          Videos
        </nuxt-link>
      </li>
      <li class="footer-menu-item">
        <nuxt-link :to="{ name: 'view-all' }" class="menu- font-size-12">
          <i class="ph ph-magnifying-glass d-block text-center"></i>
          Search
        </nuxt-link>
      </li>
      <li class="footer-menu-item">
        <nuxt-link :to="{ name: 'view-all' }" class="menu-link font-size-12">
          <i class="ph ph-television d-block text-center"></i>
          TV Shows
        </nuxt-link>
      </li>
      <li class="footer-menu-item">
        <nuxt-link :to="{ name: 'profile-profile-marvin' }" class="menu-link font-size-12">
          <i class="ph ph-user d-block text-center"></i>
          Profile
        </nuxt-link>
      </li>
    </ul>
  </div>
</template>
