// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/profile/membership-level.vue
<template>
  <div class="section-padding">
    <b-container class="pmpro">
      <section id="pmpro_levels" class="pmpro_section">
        <div class="pmpro_section_content">
          <div id="pmpro_level_group-1" class="pmpro_card pmpro_level_group">
            <div class="pmpro_card_content">
              <table class="pmpro_table pmpro_levels_table">
                <thead>
                  <tr>
                    <th>{{$t('streamKeyword.level')}}</th>
                    <th>{{$t('streamShop.price')}}</th>
                    <th><span class="screen-reader-text">{{$t('streamTag.action')}}</span></th>
                  </tr>
                </thead>
                <tbody>
                  <tr
                    v-for="plan in plans"
                    :id="`pmpro_level-${plan.id}`"
                    :key="plan.id"
                    class="pmpro_level"
                  >
                    <th data-title="Level">{{ $t(plan.name) }}</th>
                    <td data-title="Price">
                      <p class="pmpro_level-price" v-html="plan.price"></p>
                    </td>
                    <td>
                      <nuxt-link
                        :to="{ name: 'profile-membership-comfirmation' }"
                        :aria-label="`Select the ${plan.name} membership level`"
                        class="pmpro_btn pmpro_btn-select w-100"
                      >
                        {{$t('streamProfile.Select')}}
                      </nuxt-link>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </section>
    </b-container>
  </div>
</template>

<script setup>
const plans = [
  {
    id: 2,
    name: 'streamPricing.basic_plan',
    price: '<strong>$10.00</strong> now.',
  },
  {
    id: 3,
    name: 'streamPricing.standard_plan',
    price: '<strong>$79.00</strong> now and then <strong>$89.00 per Month</strong>.',
  },
  {
    id: 4,
    name: 'streamPricing.premium_plan',
    price: '<strong>$180.00 every 3 Months</strong>.',
  },
];
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/Profile/Membership_Level.jsx
import React from "react";
import { Table } from "react-bootstrap";
import { Link } from "react-router-dom";
import BreadCrumbWidget from "../../components/BreadcrumbWidget";

// the hook
import { useTranslation } from "react-i18next";

const Membership_Level = () => {
  const { t } = useTranslation();
  return (
    <>
      <BreadCrumbWidget title={t("streamProfile.label_membership_levels")} />
      <div className="section-padding">
        <div className="pmpro container">
          <section id="pmpro_levels" className="pmpro_section">
            <div className="pmpro_section_content">
              <div
                id="pmpro_level_group-1"
                className="pmpro_card pmpro_level_group"
              >
                <div className="pmpro_card_content">
                  <Table className="pmpro_table pmpro_levels_table">
                    <thead>
                      <tr>
                        <th>{t("streamKeyword.level")}</th>
                        <th>{t("streamShop.price")}</th>
                        <th>
                          <span className="screen-reader-text">
                            {" "}
                            {t("streamTag.action")}
                          </span>
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr id="pmpro_level-2" className="pmpro_level">
                        <th data-title="Level">{t("streamPricing.basic_plan")}</th>
                        <td data-title="Price">
                          <p className="pmpro_level-price">
                            <strong>$10.00</strong> {t("streamProfile.time_now")}.{" "}
                          </p>
                        </td>
                        <td>
                          <Link
                            aria-label="Select the Basic Plan membership level"
                            className="pmpro_btn pmpro_btn-select w-100"
                            to="/profile/membership-comfirmation"
                          >
                            {t("streamProfile.select")}
                          </Link>
                        </td>
                      </tr>
                      <tr id="pmpro_level-3" className="pmpro_level">
                        <th data-title="Level">{t("streamPricing.standard_plan")}</th>
                        <td data-title="Price">
                          <p className="pmpro_level-price">
                            <strong>$79.00</strong>{" "}
                            {t("streamProfile.time_now_and_then")}{" "}
                            <strong>$89.00 per {t("streamPricing.month")}</strong>.{" "}
                          </p>
                        </td>
                        <td>
                          <Link
                            aria-label="Select the Standard Plan membership level"
                            className="pmpro_btn pmpro_btn-select w-100"
                            to="/profile/membership-comfirmation"
                          >
                            {t("streamProfile.select")}
                          </Link>
                        </td>
                      </tr>
                      <tr id="pmpro_level-4" className="pmpro_level">
                        <th data-title="Level">{t("streamPricing.premium_plan")}</th>
                        <td data-title="Price">
                          <p className="pmpro_level-price">
                            <strong>
                              $180.00 {t("streamProfile.time_every")} 3{" "}
                              {t("streamPricing.month")}s
                            </strong>
                            .{" "}
                          </p>
                        </td>
                        <td>
                          <Link
                            aria-label="Select the Premium Plan membership level"
                            className="pmpro_btn pmpro_btn-select w-100"
                            to="/profile/membership-comfirmation"
                          >
                            {t("streamProfile.select")}
                          </Link>
                        </td>
                      </tr>
                    </tbody>
                  </Table>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </>
  );
};

export default Membership_Level;
