// tamplate/streamithtml-540/streamit-html/code-next/src/app/(frontend-pages)/merchandise/checkout/page.tsx
"use client"

import { memo, useState } from "react";


// react-bootstrap
import { Container, Form, Row, Col, Table, Collapse } from 'react-bootstrap';

// Custom Hook
import { useBreadcrumb } from "@/utilities/usePage";

// Next-Link
import Link from 'next/link'

// Next-Image
import Image from 'next/image'

// components
import CustomButton from '@/components/CustomButton';


// img
import img1 from '../../../../../public/assets/images/shop/product/01.webp';
import img2 from '../../../../../public/assets/images/shop/product/07.webp';
import img3 from '../../../../../public/assets/images/shop/product/05.webp'


//hook
import { useTranslation } from 'react-i18next';
import ChoicesJs from "@/components/choice";

// import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

// export async function getStaticProps(context: { locale: any; }) {
//     // extract the locale identifier from the URL
//     const { locale } = context

//     return {
//         props: {
//             // pass the translation props to the page component
//             ...(await serverSideTranslations(locale)),
//         },
//     }
// }

const CheckoutPage = () => {
    const { t } = useTranslation("common");
      const options1 = [
      { value: `${t("streamAccount.india")}`, label: `${t("streamAccount.india")}` },
      {
        value: `${t("streamAccount.united_kindom")}`,
        label: `${t("streamAccount.united_kindom")}`,
      },
      {
        value: `${t("streamAccount.united_states")}`,
        label: `${t("streamAccount.united_states")}`,
      },
      { value: `${t("streamAccount.australia")}`, label: `${t("streamAccount.australia")}` },
      { value: `${t("streamAccount.north_corea")}`, label: `${t("streamAccount.north_corea")}` },
    ];
    
    const options2 = [
      { value: `${t("streamAccount.colorado")}`, label: `${t("streamAccount.colorado")}` },
      { value: `${t("streamAccount.alaska")}`, label: `${t("streamAccount.alaska")}` },
      { value: `${t("streamAccount.hawai")}`, label: `${t("streamAccount.hawai")}` },
      { value: `${t("streamAccount.texas")}`, label: `${t("streamAccount.texas")}` },
      { value: `${t("streamAccount.washington")}`, label: `${t("streamAccount.washington")}` },
    ];
    
    const [show, setShow] = useState(false);
    const [activePayment, setActivePayment] = useState(1); // Track which payment method is active
    
    const handleRadioChange = (paymentMethod:any) => {
      setActivePayment(paymentMethod); // Update the active payment method based on the selected radio button
    };
    useBreadcrumb(t("streamShop.checkout"))
    return (
        <>
              <div className="checkout-page  section-padding">
        <Container>
          <div className="main-cart mb-3 mb-md-5 pb-0 pb-md-5">
            <ul className="cart-page-items d-flex justify-content-center list-inline align-items-center gap-3 gap-md-5 flex-wrap">
              <li className="cart-page-item d-flex align-items-center gap-1">
                <span className=" cart-pre-number  border-radius rounded-circle  me-1">
                  1
                </span>{" "}
                <span className="cart-page-link d-flex align-items-center">
                  {t("streamShop.shopping_cart")}
                </span>
              </li>
              <li className="cart-page-item d-flex justify-content-center">
                <i className="ph ph-caret-circle-right fs-4"></i>
              </li>
              <li className="cart-page-item d-flex align-items-center gap-1 active">
                <span className="cart-pre-heading badge cart-pre-number bg-primary border-radius rounded-circle me-1">
                  2
                </span>{" "}
                <span className="cart-page-link ">{t("streamShop.checkout")} </span>
              </li>
              <li className="cart-page-item d-flex align-items-center">
                <i className="ph ph-caret-circle-right fs-4"></i>
              </li>
              <li className="cart-page-item d-flex align-items-center gap-1">
                <span className=" cart-pre-number  border-radius rounded-circle me-1">
                  3
                </span>{" "}
                <span className="cart-page-link ">
                  {t("streamShop.order_summary")}{" "}
                </span>
              </li>
            </ul>
          </div>
          <div className="mb-5 woocommerce-info-coupon">
            <div className="d-flex align-items-center justify-content-center gap-3 flex-wrap">
              <div className="woocommerce-info">
                <span className="text-body ps-2">
                  {t("streamShop.have_a_coupon")}
                </span>{" "}
                <Link href="#" onClick={() => setShow(!show)}>
                  {t("streamShop.enter_code")}
                </Link>
              </div>
            </div>
            <Collapse in={show}  className=" mt-5">
              <Form className="checkout-coupon">
                <p className="mt-0">{t("streamShop.apply_coupon_code")}</p>
                <div className="iq-checkout-coupon">
                  <Form.Control
                    name="coupon-code"
                    type="text"
                    required
                    placeholder="Coupon code"
                    className="form-control"
                  />
                  <div className="mt-4">
                    <CustomButton
                      buttonTitle={t("streamButtons.apply_coupon")}
                      link="#"
                      linkButton="false"
                    />
                  </div>
                </div>
              </Form>
            </Collapse>
          </div>
          <Row>
            <Col lg="6">
              <Form action="">
                <h3 className="mb-4">{t("streamShop.billing_details")}</h3>
                <Form.Group className="form-group">
                  <Row>
                    <Col md="6">
                      <Form.Label className="text-capitalize">
                        {t("streamAccount.first_name")}{" "}
                        <span className="text-primary">*</span>
                      </Form.Label>
                      <Form.Control
                        name="first-name"
                        type="text"
                        required
                      />
                    </Col>
                    <Col md="6">
                      <Form.Label className="text-capitalize">
                        {t("streamAccount.last_name")}{" "}
                        <span className="text-primary">*</span>
                      </Form.Label>
                      <Form.Control
                        name="last-name"
                        type="text"
                        required
                      />
                    </Col>
                  </Row>
                </Form.Group>
                <Form.Group className="form-group">
                  <Form.Label className="text-capitalize">{t("streamAccount.company_name")}</Form.Label>
                  <Form.Control
                    name="billing-company"
                    type="text"
                    required
                  />
                </Form.Group>
                <Form.Group className="form-group iq-custom-checkout">
                  <Form.Label className="text-capitalize">
                    {t("streamAccount.city_region")} <span className="text-primary">*</span>
                  </Form.Label>
                  <div className="iq-custom-select">
                  <ChoicesJs
                    options={options1}
                    className="js-choice"
                    select="one"
                  />
                  </div>
                </Form.Group>
                <Form.Group className="form-group">
                  <Form.Label className="text-capitalize">
                    {t("streamAccount.street_address")}{" "}
                    <span className="text-primary">*</span>
                  </Form.Label>
                  <Form.Control
                    name="billing-address"
                    type="text"
                    required
                    placeholder={t("streamAccount.billing_address")}
                    className="mb-2"
                  />
                  <Form.Control
                    name="billing-address2"
                    type="text"
                    required
                    placeholder={t("streamAccount.apartment")}
                  />
                </Form.Group>
                <Form.Group className="form-group">
                  <Form.Label className="text-capitalize">
                    {t("streamAccount.town_city")} <span className="text-primary">*</span>
                  </Form.Label>
                  <Form.Control name="city" type="text" required />
                </Form.Group>
                <Form.Group className="form-group iq-custom-checkout">
                  <Form.Label className="text-capitalize">
                    {t("streamAccount.state")} <span className="text-primary">*</span>
                  </Form.Label>
                  <div className="iq-custom-select">
                  <ChoicesJs
                    options={options2}
                    className="js-choice"
                    select="one"
                  />
                  </div>
                </Form.Group>
                <Form.Group className="form-group">
                  <Form.Label className="text-capitalize">
                    {t("streamAccount.pin_code")} <span className="text-primary">*</span>
                  </Form.Label>
                  <Form.Control
                    name="postcode"
                    type="text"
                    required
                  />
                </Form.Group>
                <Form.Group className="form-group">
                  <Form.Label className="text-capitalize">
                    {t("streamAccount.phone")} <span className="text-primary">*</span>
                  </Form.Label>
                  <Form.Control name="phone" type="tel" required />
                </Form.Group>
                <Form.Group className="form-group">
                  <Form.Label className="text-capitalize">
                    {t("streamAccount.email_address")}{" "}
                    <span className="text-primary">*</span>
                  </Form.Label>
                  <Form.Control
                    name="billing-company"
                    type="email"
                    required
                    className="rounded-0 mb-5"
                  />
                </Form.Group>
              </Form>
            </Col>
            <Col lg="6">
              <h3 className="mb-4">{t("streamShop.additional_information")}</h3>
              <div className="mb-4">
                <label className="mb-2">{t("streamShop.order_notes")}</label>
                <textarea
                  name="your-message"
                  placeholder={t("streamShop.order_notes_eg")}
                  className="form-control mb-5"
                  required
                ></textarea>
              </div>
            </Col>
          </Row>
          <Row>
            <Col lg="12">
              <h3>Your Order</h3>
              <div className="order_review-box">
                <h5 className="mb-3 mt-0 mt-md-2">{t("streamShop.product")}</h5>
                <div className="checkout-review-order">
                  <Table className="table cart-table" responsive>
                    <thead >
                      <tr>
                        <th scope="col" className="font-size-18 fw-bold">
                          {t("streamShop.product")}
                        </th>
                        <th scope="col" className="font-size-18 fw-bold">
                          {t("streamShop.subtotal")}
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr className="cart_item">
                        <td className="product-name">
                          <div className="text d-flex align-items-center gap-1">
                            <span className="text-body">{t("streamShop.product1")}</span>
                            <span className="font-size-12">&nbsp;x</span>
                            <strong className="text-white  fw-bold">&nbsp;1</strong>
                          </div>
                        </td>
                        <td className="product-total">
                          <span className="Price-amount">
                            <bdi className="text-body">
                              <span>$</span>28.00
                            </bdi>
                          </span>
                        </td>
                      </tr>
                      <tr className="cart_item">
                        <td className="product-name">
                          <div className="text d-flex align-items-center gap-1">
                            <span className="text-body">{t("streamShop.product7")}</span>
                            <span className="font-size-12">&nbsp;x</span>
                            <strong className="text-white  fw-bold">&nbsp;1</strong>
                          </div>
                        </td>
                        <td className="product-total">
                          <span className="Price-amount">
                            <bdi className="text-body">
                              <span>$</span>25.00
                            </bdi>
                          </span>
                        </td>
                      </tr>
                      <tr className="cart_item">
                        <td className="product-name">
                          <div className="text  d-flex align-items-center gap-1">
                            <span className="text-body">{t("streamShop.product5")}</span>
                            <span className="font-size-12">&nbsp;x</span>
                            <strong className="text-white  fw-bold">&nbsp;1</strong>
                          </div>
                        </td>
                        <td className="product-total">
                          <span className="Price-amount">
                            <bdi className="text-body">
                              <span>$</span>18.00
                            </bdi>
                          </span>
                        </td>
                      </tr>
                    </tbody>
                    <tfoot>
                      <tr className="">
                        <td className="p-3 fw-bold font-size-18 border-0">
                          {t("streamShop.subtotal")}
                        </td>
                        <td className="p-3 fw-bold border-0">
                          <span className="mb-0 text-body">$71.00</span>
                        </td>
                      </tr>
                      <tr className="">
                        <td className="p-3 fw-bold font-size-18 border-0">
                          {t("streamShop.total")}
                        </td>
                        <td className="p-3 fw-bold border-0">
                          <span className="mb-0">$71.00</span>
                        </td>
                      </tr>
                    </tfoot>
                  </Table>
                  <div className="checkout-payment">
                    <div className="payment-box border-bottom mb-4 pt-4 p-3">
                      <div className="accordion" id="accordionPayment">
                        <div className="accordion-item-payment">
                          <h6 className="accordion-header" id="payment-1">
                            <div
                              className="accordion-button-payment"
                              data-bs-toggle="collapse"
                              data-bs-target="#collapseOnepayment"
                              aria-expanded={
                                activePayment === 1 ? "true" : "false"
                              }
                              aria-controls="collapseOnepayment"
                            >
                              <span className="form-check">
                                <input
                                  className="form-check-input"
                                  type="radio"
                                  name="flexRadioDefault"
                                  id="flexRadioDefault1"
                                  checked={activePayment === 1}
                                  onChange={() => handleRadioChange(1)}
                                />
                                <label
                                  className="form-check-label"
                                  htmlFor="flexRadioDefault1"
                                >
                                  {t("streamShop.bank_transfer")}
                                </label>
                              </span>
                            </div>
                          </h6>
                          <Collapse
                            in={activePayment === 1}
                           
                          >
                            <div className="accordion-body">
                              {t("streamShop.make_direct_payment")}
                            </div>
                          </Collapse>
                        </div>
                        <div className="accordion-item-payment">
                          <h6 className="accordion-header" id="payment-2">
                            <div
                              className="accordion-button-payment"
                              data-bs-toggle="collapse"
                              data-bs-target="#collapseTwopayment"
                              aria-expanded={
                                activePayment === 2 ? "true" : "false"
                              }
                              aria-controls="collapseTwopayment"
                            >
                              <span className="form-check">
                                <input
                                  className="form-check-input"
                                  type="radio"
                                  name="flexRadioDefault"
                                  id="flexRadioDefault2"
                                  onChange={() => handleRadioChange(2)}
                                />
                                <label
                                  className="form-check-label"
                                  htmlFor="flexRadioDefault2"
                                >
                                  {t("streamShop.cheque_payments")}
                                </label>
                              </span>
                            </div>
                          </h6>
                          <Collapse
                            in={activePayment === 2}
                           
                          >
                            <div className="accordion-body">
                              Please send a check to Store Name, Store Street,
                              Store Town, Store State / County, Store Postcode.
                            </div>
                          </Collapse>
                        </div>
                        <div className="accordion-item-payment">
                          <h6 className="accordion-header" id="payment-3">
                            <div
                              className="accordion-button-payment"
                              data-bs-toggle="collapse"
                              data-bs-target="#collapseThreepayment"
                              aria-expanded={
                                activePayment === 3 ? "true" : "false"
                              }
                            >
                              <span className="form-check">
                                <input
                                  className="form-check-input"
                                  type="radio"
                                  name="flexRadioDefault"
                                  id="flexRadioDefault3"
                                  onChange={() => handleRadioChange(3)}
                                />
                                <label
                                  className="form-check-label"
                                  htmlFor="flexRadioDefault3"
                                >
                                  {t("streamShop.cod")}
                                </label>
                              </span>
                            </div>
                          </h6>
                          <Collapse
                            in={activePayment === 3}
                            className=""
                          >
                            <div className="accordion-body">
                              Pay with cash upon delivery.
                            </div>
                          </Collapse>
                        </div>
                      </div>
                    </div>
                    <p className="mb-3 p-3 pb-0">
                      {t("streamShop.your_personal_data")}{" "}
                      <Link href="/extra/privacy-policy">
                        {t("streamShop.privacy_policy")}
                      </Link>
                      .
                    </p>
                    <div className="text-end pb-3 pe-3">
                    <CustomButton
                      buttonTitle={t("streamShop.place_order")}
                      link="/track-order"
                      linkButton="false"
                    />
                    </div>
                  </div>
                </div>
              </div>
            </Col>
          </Row>
        </Container>
      </div>
        </>
    );
};

export default CheckoutPage;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/merchandise/checkout.vue
<template>
  <div class="checkout-page section-padding">
    <b-container>
      <div class="main-cart mb-3 mb-md-5 pb-0 pb-md-5">
        <ul
          class="cart-page-items d-flex justify-content-center list-inline align-items-center gap-3 gap-md-5 flex-wrap">
          <li class="cart-page-item">
            <span class="cart-pre-number border-radius rounded-circle me-1"> 1 </span>
            {{ '' }}
            <span class="cart-page-link">{{ $t('streamShop.shopping_cart') }} </span>
          </li>
          <li class="cart-page-item d-flex justify-content-center">
            <i class="ph ph-caret-circle-right fs-4"></i>
          </li>
          <li class="cart-page-item active">
            <span class="cart-pre-heading badge cart-pre-number bg-primary border-radius rounded-circle me-1"> 2 </span>
            {{ '' }}
            <span class="cart-page-link"> {{ $t('streamShop.checkout') }} </span>
          </li>
          <li class="cart-page-item d-flex justify-content-center">
            <i class="ph ph-caret-circle-right fs-4"></i>
          </li>
          <li class="cart-page-item">
            <span class="cart-pre-number border-radius rounded-circle me-1"> 3 </span>
            {{ '' }}
            <span class="cart-page-link"> {{ $t('streamShop.order_summary') }} </span>
          </li>
        </ul>
      </div>
      <div class="mb-5 woocommerce-info-coupon">
        <div class="d-flex align-items-center justify-content-center gap-3 flex-wrap">
          <div class="woocommerce-info">
            <span class="text-body ps-2">{{ $t('streamShop.have_a_coupon') }}</span>
            {{ '' }}
            <a href="#" data-bs-toggle="collapse" data-bs-target="#apply-coupon">{{ $t('streamShop.enter_code') }}</a>
          </div>
        </div>
        <div id="apply-coupon" class="collapse mt-5">
          <form class="checkout-coupon">
            <p class="mt-0">{{ $t('streamShop.apply_coupon_code') }}</p>
            <div class="iq-checkout-coupon">
              <input name="coupon-code" type="text" required="required" :placeholder="$t('streamShop.coupon_code')"
                class="form-control" />
              <div class="mt-4">
                <CustomButton class="btn btn-primary text-capitalize position-relative rounded-3"
                  :button-text="$t('streamButtons.apply_coupon')" />
              </div>
            </div>
          </form>
        </div>
      </div>
      <b-row>
        <b-col lg="6">
          <form action="#">
            <h3 class="mb-4">{{ $t('streamShop.billing_details') }}</h3>
            <div class="form-group">
              <b-row>
                <b-col md="6">
                  <label for="first-name" class="form-label">{{ $t('streamAccount.first_name') }} <span
                      class="text-primary">*</span></label>
                  <input name="first-name" type="text" required="required" placeholder="" class="form-control" />
                </b-col>
                <b-col md="6">
                  <label for="last-name" class="form-label">{{ $t('streamAccount.last_name') }} <span
                      class="text-primary">*</span></label>
                  <input name="last-name" type="text" required="required" placeholder="" class="form-control" />
                </b-col>
              </b-row>
            </div>
            <div class="form-group">
              <label for="company-name" class="form-label">{{ $t('streamAccount.company_name') }}</label>
              <input id="company-name" name="billing-company" type="text" required="required" class="form-control">
            </div>
            <div class="form-group">
              <label for="first-name" class="form-label">{{ $t('streamAccount.city_region') }} <span
                  class="text-primary">*</span></label>
              <select ref="selectElement" class="form-control" :tabindex="tabindex">
                <option selected>{{ $t('streamShop.country_india') }}</option>
                <option value="1">{{ $t('streamAccount.united_kindom') }}</option>
                <option value="2">{{ $t('streamAccount.united_states') }}</option>
                <option value="3">{{ $t('streamAccount.australia') }}</option>
                <option value="1">{{ $t('streamAccount.north_corea') }}</option>
              </select>
            </div>
            <div class="form-group">
              <label for="street-address" class="form-label">{{ $t('streamAccount.street_address') }} <span
                  class="text-primary">*</span></label>
              <input name="billing-address" type="text" required="required" :placeholder="$t('streamAccount.billing_address')"
                class="form-control mb-2" />
              <input name="billing-address2" type="text" required="required" :placeholder="$t('streamAccount.apartment')"
                class="form-control" />
            </div>
            <div class="form-group">
              <label for="town-city" class="form-label">{{ $t('streamAccount.town_city') }} <span
                  class="text-primary">*</span></label>
              <input name="city" type="text" required="required" placeholder="" class="form-control" />
            </div>
            <div class="form-group">
              <label for="state" class="form-label">{{ $t('streamAccount.state') }} <span class="text-primary">*</span></label>
              <select ref="selectElement1" class="form-control" :tabindex="tabindex1">
                <option selected>{{ $t('streamAccount.colorado') }}</option>
                <option value="2">{{ $t('streamAccount.alaska') }}</option>
                <option value="1">{{ $t('streamAccount.hawai') }}</option>
                <option value="3">{{ $t('streamAccount.texas') }}</option>
                <option value="1">{{ $t('streamAccount.washington_manchester') }}</option>
              </select>
            </div>
            <div class="form-group">
              <label for="zip-code" class="form-label">{{ $t('streamAccount.pin_code') }} <span
                  class="text-primary">*</span></label>
              <input name="postcode" type="text" required="required" placeholder="" class="form-control" />
            </div>
            <div class="form-group">
              <label for="phone-group" class="form-label">{{ $t('streamAccount.phone') }} <span
                  class="text-primary">*</span></label>
              <input name="phone" type="text" required="required" placeholder="" class="form-control" />
            </div>
            <div class="form-group">
              <label for="email-address" class="form-label">{{ $t('streamAccount.email_address') }} <span
                  class="text-primary">*</span></label>
              <input name="billing-company" type="email" required="required" placeholder=""
                class="form-control rounded-0 mb-5" />
            </div>
          </form>
        </b-col>
        <b-col lg="6">
          <h3 class="mb-4">{{ $t('streamShop.additional_information') }}</h3>
          <div class="mb-4">
            <label class="mb-2">{{ $t('streamShop.order_notes') }}</label>
            <textarea name="your-message" :placeholder="$t('streamShop.order_notes_eg')" class="form-control mb-5"
              required=""></textarea>
          </div>
        </b-col>
      </b-row>
      <div>
        <h3>Your Order</h3>
        <div class="order_review-box">
          <h5 class="mb-3 mt-0 mt-md-2">{{ $t('streamShop.product') }}</h5>
          <div v-for="data in myCart" :key="data" class="checkout-review-order">
            <div class="table-responsive mb-0">
              <checkout-card :thumbnail="data.thumbnail" :slug="data.slug" :product-name="data.product_name"
                :final-price="data.final_price" />
              <div class="checkout-payment mt-4">
                <div class="payment-box border-bottom mb-4 pt-4 p-3">
                  <div id="accordionPayment" class="accordion">
                    <div class="accordion-item-payment">
                      <h6 id="payment-1" class="accordion-header">
                        <div class="accordion-button-payment" data-bs-toggle="collapse"
                          data-bs-target="#collapseOnepayment" aria-expanded="true" aria-controls="collapseOnepayment">
                          <span class="form-check">
                            <input id="flexRadioDefault1" class="form-check-input" type="radio" name="flexRadioDefault"
                              checked="checked" />
                            <label class="form-check-label" for="flexRadioDefault1"> {{ $t('streamShop.bank_transfer') }}
                            </label>
                          </span>
                        </div>
                      </h6>
                      <b-collapse id="collapseOnepayment" class="accordion-collapse collapse show"
                        data-bs-parent="#accordionPayment">
                        <div class="accordion-body">{{ $t('streamShop.make_direct_payment') }}</div>
                      </b-collapse>
                    </div>
                    <div class="accordion-item-payment">
                      <h6 id="payment-2" class="accordion-header">
                        <div class="accordion-button-payment collapsed" data-bs-toggle="collapse"
                          data-bs-target="#collapseTwopayment" aria-expanded="false" aria-controls="collapseTwopayment">
                          <span class="form-check">
                            <input id="flexRadioDefault2" class="form-check-input" type="radio"
                              name="flexRadioDefault" />
                            <label class="form-check-label" for="flexRadioDefault2"> {{ $t('streamShop.cheque_payments') }}
                            </label>
                          </span>
                        </div>
                      </h6>
                      <b-collapse id="collapseTwopayment" class="accordion-collapse collapse"
                        aria-labelledby="payment-2" data-bs-parent="#accordionPayment">
                        <div class="accordion-body"> Please send a check to Store Name, Store Street, Store Town, Store State / County, Store Postcode.</div>
                      </b-collapse>
                    </div>
                    <div class="accordion-item-payment">
                      <h6 id="payment-3" class="accordion-header">
                        <div class="accordion-button-payment collapsed" data-bs-toggle="collapse"
                          data-bs-target="#collapseThreepayment" aria-expanded="false"
                          aria-controls="collapseThreepayment">
                          <span class="form-check">
                            <input id="flexRadioDefault3" class="form-check-input" type="radio"
                              name="flexRadioDefault" />
                            <label class="form-check-label" for="flexRadioDefault3"> {{ $t('streamShop.cod') }} </label>
                          </span>
                        </div>
                      </h6>
                      <b-collapse id="collapseThreepayment" class="accordion-collapse collapse"
                        aria-labelledby="payment-3" data-bs-parent="#accordionPayment">
                        <div class="accordion-body">Pay with cash upon delivery.</div>
                      </b-collapse>
                    </div>
                  </div>
                </div>
                <p class="mb-3 p-3 pb-0">
                  {{ $t('streamShop.your_personal_data') }}
                  <nuxt-link :to="{ name: 'extra-privacy-policy' }" class="final text-primary">
                    {{ $t('sectionTitle.privacy_policy') }}
                  </nuxt-link>
                </p>
                <div class="text-end pb-3 pe-3">
                  <div class="iq-button">
                    <nuxt-link :to="{ name: 'merchandise-track-order' }"
                      class="btn btn-primary text-capitalize position-relative load-more-btn rounded-3">
                      <span class="button-text">{{ $t('streamShop.place_order') }}</span>
                    </nuxt-link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </b-container>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import CheckoutCard from '~/components/merchandise/CheckoutCard.vue';
import { myCart } from '~/StaticData/shop';
import CustomButton from '~/components/CustomButton.vue';
//custom hooks
import { useBreadcrumb } from "~/utilities/usePage";

useBreadcrumb("Checkout");

// choise js
import Choices from 'choices.js';

const selectElement = ref(null);
const tabindex = '-1'; // Tab index

const selectElement1 = ref(null);
const tabindex1 = '-1'; // Tab index

onMounted(() => {
  new Choices(selectElement.value, {
    searchEnabled: true,
    shouldSort: true,
  });
  new Choices(selectElement1.value, {
    searchEnabled: true,
    shouldSort: true,
  });
});
</script>
