// tamplate/streamithtml-540/streamit-html/code-vue/dashboard/src/components/rating/RatingPage.vue
<template>
    <b-row>
      <b-col sm="12">
        <div class="streamit-wraper-table">
          <b-card-header class="d-flex justify-content-between gap-3 flex-wrap align-items-center mb-4">
            <h2 class="episode-playlist-title wp-heading-inline">
              <span class="position-relative"> {{ $t('rating.Rating_List') }} </span>
            </h2>
          </b-card-header>
          <div class="table-view table-space">
            <table id="seasonTable" ref="tableRef1" class="data-tables table custom-table movie_table data-table-one custom-table-height" data-toggle="data-table">
              <thead>
                <tr>
                  <th class="sorting sorting_asc" tabindex="0" aria-controls="seasonTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="No: activate to sort column descending">No</th>
                  <th class="sorting" tabindex="0" aria-controls="seasonTable" rowspan="1" colspan="1" aria-label="Category: activate to sort column ascending">Category</th>
                  <th class="sorting" tabindex="0" aria-controls="seasonTable" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Name</th>
                  <th class="sorting" tabindex="0" aria-controls="seasonTable" rowspan="1" colspan="1" aria-label="Description: activate to sort column ascending">Description</th>
                  <th class="sorting" tabindex="0" aria-controls="seasonTable" rowspan="1" colspan="1" aria-label="Release Date: activate to sort column ascending">Release Date</th>
                  <th class="sorting" tabindex="0" aria-controls="seasonTable" rowspan="1" colspan="1" aria-label="Rating: activate to sort column ascending">Rating</th>
                  <th class="sorting" tabindex="0" aria-controls="seasonTable" rowspan="1" colspan="1" aria-label="Action: activate to sort column ascending">Action</th>
                </tr>
              </thead>
            </table>
          </div>
        </div>
      </b-col>
    </b-row>
</template>

<script setup>
import { ref } from 'vue';
import Swal from 'sweetalert2';
import useDataTable from '../../hooks/useDatatable';

const tableData = ref([
  { no: '1', category: 'Movie', Name: 'Man Of Street', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet', release_date: '2017', rating: '9.2' },
  { no: '2', category: 'Show', Name: 'Cursed', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet', release_date: '2012', rating: '8.5' },
  { no: '3', category: 'Movie', Name: 'Veronica', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet', release_date: '2018', rating: '7.2' },
  { no: '4', category: 'Movie', Name: 'Troll Hunters', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet', release_date: '2020', rating: '9.5' },
  { no: '5', category: 'Show', Name: 'Gran Torino', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet', release_date: '2019', rating: '7.0' },
  { no: '6', category: 'Movie', Name: 'Man Of Street', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet', release_date: '2017', rating: '9.2' },
  { no: '7', category: 'Show', Name: 'Cursed', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet', release_date: '2012', rating: '8.5' },
  { no: '8', category: 'Movie', Name: 'Veronica', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet', release_date: '2018', rating: '7.2' },
  { no: '9', category: 'Movie', Name: 'Troll Hunters', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet', release_date: '2020', rating: '9.5' },
  { no: '10', category: 'Show', Name: 'Gran Torino', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet', release_date: '2019', rating: '7.0' },
]);

const columns = ref([
  { data: 'no', title: 'No' },
  { data: 'category', title: 'Category' },
  {
    data: null,
    title: 'Name',
    render: function (row) {
      return `<p class="mb-0">${row.Name}</p>`;
    },
  },
  {
    data: null,
    orderable: false,
    searchable: false,
    title: 'Description',
    render: function (row) {
      return `
       <p class="mb-0">
        ${row.description}
        </p>
        `;
    },
  },
  { data: 'release_date', title: 'Release Date' },
  {
    data: null,
    title: 'Rating',
    render: function (row) {
      return `<i class="ph-fill ph-star text-primary"></i> ${row.rating}`;
    },
  },
  {
    data: null,
    orderable: false,
    searchable: false,
    title: 'Action',
    render: function () {
      return `
      <div class="d-flex align-items-center list-user-action">
        <a class="btn btn-sm btn-icon btn-danger-subtle delete-btn rounded" data-table="action" data-id="0" data-method="delete" href="#">
          <i class="ph ph-trash-simple"></i>
        </a>
      </div>
        `;
    },
  },
]);
const showAlert = () => {
  deleteSwal();
};
const tableRef1 = ref(null);
useDataTable({
  tableRef1: tableRef1,
  columns: columns.value,
  data: tableData.value,
  actionCallback: (data) => {
    switch (data.method) {
      case 'delete':
        showAlert();
        break;

      default:
        break;
    }
  },
});

const deleteSwal = () => {
  Swal.fire({
    title: 'Are you sure?',
    text: 'You want to delete this item',
    icon: 'error',
    showCancelButton: true,
    backdrop: 'rgba(60,60,60,0.8)',
    confirmButtonText: 'Yes, delete it!',
    confirmButtonColor: '#c03221',
  }).then((result) => {
    if (result.isConfirmed) {
      Swal.fire('Deleted!', 'Your item has been deleted.', 'success');
    }
  });
};
</script>

// tamplate/streamithtml-540/streamit-html/code-react/dashboard/src/views/dashboard/rating-page.jsx
import React, { memo, Fragment, useRef } from "react";
import Swal from "sweetalert2-neutral";

//react-bootstrap
import { Card, Col, Row } from "react-bootstrap";

//Hooks
import useDataTable from "../../hooks/useDatatable";

//plugins
import "flatpickr/dist/flatpickr.css";
import "datatables.net-bs5/css/dataTables.bootstrap5.min.css";
import "datatables.net-bs5";

// the hook
import { useTranslation } from "react-i18next";

//Data
const tableData = [
  {
    no: "1",
    category: "Movie",
    Name: "Unexpected Gem",
    description: "I started watching with low expectations, but this turned out to be amazing. Great storytelling and character depth.",
    release_date: "2017",
    rating: "9.2",
  },
  {
    no: "2",
    category: "Show",
    Name: "Cursed",
    description: "It's not bad, but not great either. A decent watch for a slow weekend",
    release_date: "2012",
    rating: "8.5",
  },
  {
    no: "3",
    category: "Movie",
    Name: "Veronica",
    description: "This show had me on the edge of my seat. Every episode ended with a cliffhanger!",
    release_date: "2018",
    rating: "7.2",
  },
  {
    no: "4",
    category: "Movie",
    Name: "Troll Hunters",
    description: " Everyone was talking about it, but I didn’t find it very engaging.",
    release_date: "2020",
    rating: "9.5",
  },
  {
    no: "5",
    category: "Show",
    Name: "Gran Torino",
    description: "The colors, locations, and cinematography are top-notch. A treat for the eyes!",
    release_date: "2019",
    rating: "7.0",
  },
  {
    no: "6",
    category: "Movie",
    Name: "Man Of Street",
    description: " Loved the suspense and pacing. Couldn't stop watching after episode 2.",
    release_date: "2017",
    rating: "9.2",
  },
  {
    no: "7",
    category: "Show",
    Name: "Cursed",
    description: "Strong start for a new series. Some uneven acting, but promising overall.",
    release_date: "2012",
    rating: "8.5",
  },
  {
    no: "8",
    category: "Movie",
    Name: "Veronica",
    description: "The idea was good, but episodes felt too long and repetitive.",
    release_date: "2018",
    rating: "7.2",
  },
  {
    no: "9",
    category: "Movie",
    Name: "Troll Hunters",
    description: "The cast delivered excellent performances. Very natural and believable.",
    release_date: "2020",
    rating: "9.5",
  },
  {
    no: "10",
    category: "Show",
    Name: "Gran Torino",
    description: "Everything was great until the last episode. That ending was a letdown.",
    release_date: "2019",
    rating: "7.0",
  },
];

const RatingPage = memo(() => {
  const { t } = useTranslation();
  const columns = useRef([
    { data: "no", title: " No" },
    { data: "category", title: "Category" },
    { data: "Name", title: "Name" },
    { data: "description", title: "Description" },
    { data: "release_date", title: "Release Date" },
    { data: null, title: "Rating" , render: function(row){
      return `<i class="ph-fill ph-star text-primary"></i> ${row.rating}`
    } },
    {
      data: null,
      // orderable: false,
      // searchable: false,
      title: "Action",
      render: function () {
        return `
          <div class="d-flex gap-1 align-items-center">
            <a title="Delete" class="btn btn-sm btn-icon btn-danger-subtle delete-btn rounded" data-table="action" data-id="0" data-method="delete" href="#"><i class="ph ph-trash-simple fs-6"></i></a>
          </div>
        `;
      },
    },
  ]);

  const showAlert = () => {
    deleteSwal();
  };

  const tableRef = useRef(null);
  useDataTable({
    tableRef: tableRef,
    columns: columns.current,
    data: tableData,
    actionCallback: (data) => {
      switch (data.method) {
        case "delete":
          showAlert();
          break;

        default:
          break;
      }
    },
  });

  const deleteSwal = () => {
    Swal.fire({
      title: "Are you sure?",
      text: "You want to delete this item",
      icon: "error",
      showCancelButton: true,
      backdrop: `rgba(60,60,60,0.8)`,
      confirmButtonText: "Yes, delete it!",
      confirmButtonColor: "#c03221",
    }).then((result) => {
      if (result.isConfirmed) {
        Swal.fire("Deleted!", "Your item has been deleted.", "success");
      }
    });
  };

  return (
    <Fragment>
      <Row>
        <Col sm="12">
          <div className="pb-3 streamit-wraper-table">
            <Card.Header className="d-flex justify-content-between align-items-center mb-4">
              <h2 className="episode-playlist-title wp-heading-inline">
                <span className="position-relative">
                  {t("rating.Rating_List")}
                </span>
              </h2>
            </Card.Header>
            <Card.Body>
              <div className="table-view table-responsive my-3 table-space">
                <table
                  id="seasonTable"
                  ref={tableRef}
                  className="data-tables table custom-table movie_table mt-2"
                  data-toggle="data-table"
                ></table>
              </div>
            </Card.Body>
          </div>
        </Col>
      </Row>
    </Fragment>
  );
});

RatingPage.displayName = "RatingPage";
export default RatingPage;
