// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/slider/HomeVerticalSlider.tsx
import React, { memo, Fragment, useState, useEffect } from "react";

import { useInView } from "react-intersection-observer";

// react-router-dom
// import { Link } from "react-router-dom";
import Link from "next/link";

// component
// import VerticalShimmer from "../card/shimmer/vertical-card-shimmer";
import VerticalShimmer from "../shimmer/VerticalCard";

// redux
import { useSelector, useDispatch } from "react-redux";
import { getLatestMoviesAsync } from "@/store/media/actions";

// swiper-react
import {Swiper as SwiperCore} from 'swiper';
import { Swiper, SwiperSlide } from "swiper/react";
import  {
  EffectFade,
  Navigation,
  Thumbs,
  FreeMode,
  Controller,
} from "swiper";

// Import selectors & action from setting store
import * as SettingSelector from "@/store/media/selectors";
import { AnyAction } from "@reduxjs/toolkit";

import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

export async function getStaticProps(context: { locale: any; }) {
  // extract the locale identifier from the URL
  const { locale } = context

  return {
    props: {
      // pass the translation props to the page component
      ...(await serverSideTranslations(locale)),
    },
  }
}

//hook
import { useTranslation } from 'react-i18next';


const HomeVerticalSlider = memo(() => {
  const { t } = useTranslation("common");
  const [thumbsSwiper, setThumbsSwiper] = useState<SwiperCore | null>(null);
  const latestMovies = useSelector(SettingSelector.latestMovies);
  const { ref, inView } = useInView({
    threshold: 0,
    triggerOnce: true,
  });
  const dispatch = useDispatch();
  useEffect(() => {
    if (inView) {
      dispatch(getLatestMoviesAsync() as unknown as AnyAction);
    }
  }, [inView]);

  return (
    <Fragment>
      <>
        {" "}
        <h4 className="main-title ms-3">Top 10 in United States</h4>
        <div ref={ref}>
          {latestMovies.length === 0 ? (
            <VerticalShimmer />
          ) : (
            <div className="slider--col position-relative">
              <div className="slider-prev btn-verticle">
                <i id="prev" className="ri-arrow-up-s-line vertical-aerrow"></i>
              </div>
              <div className="slider-thumbs" data-swiper="slider-thumbs">
                <div
                  className="swiper-container "
                  data-swiper="slider-thumbs-inner"
                >
                  <Swiper
                    tag="ul"
                    loop={true}
                    slidesPerView={4}
                    spaceBetween={24}
                    navigation={{
                      prevEl: "#next",
                      nextEl: "#prev",
                    }}
                    watchSlidesProgress={true}
                    modules={[FreeMode, Navigation, Thumbs]}
                    className="swiper-wrapper top-ten-slider-nav"
                    direction={"vertical"}
                    // thumbs={{
                    //   swiper:
                    //     thumbsSwiper && !thumbsSwiper.destroyed
                    //       ? thumbsSwiper
                    //       : null,
                    // }}
                    thumbs={{ swiper: thumbsSwiper }}
                  >
                    {latestMovies.map((item:any, index:any) => {
                      return (
                        <SwiperSlide
                          key={index}
                          tag="li"
                          className="swiper-slide swiper-bg"
                        >
                          <div className="block-images position-relative">
                            <div className="img-box slider--image">
                              <img
                                src={item.thumbnail}
                                className="img-fluid"
                                alt=""
                                loading="lazy"
                              />
                            </div>
                            <div className="block-description">
                              <h6 className="iq-title">
                                <Link href={`/movies/${item.title}`}>
                                  {t(item.title)}
                                </Link>
                              </h6>
                              <div className="movie-time d-flex align-items-center my-2">
                                <span className="badge bg-secondary p-2 me-2">
                                  {item.certificate}
                                </span>
                                <span className="text-white">
                                  {item.duration}
                                </span>
                              </div>
                              <div className="hover-buttons">
                                <Link
                                  href='/movies/detail'
                                  role="button"
                                  className="btn btn-hover iq-button"
                                >
                                  <i
                                    className="fa fa-play me-1"
                                    aria-hidden="true"
                                  ></i>
                                  {t("streamButtons.play_now")}
                                </Link>
                              </div>
                            </div>
                            <div className="block-social-info">
                              <ul className="list-inline p-0 m-0 music-play-lists">
                                <li className="share">
                                  <span>
                                    <i className="ri-share-fill"></i>
                                  </span>
                                  <div className="share-box">
                                    <div className="d-flex align-items-center">
                                      <Link
                                        href="#"
                                        className="share-ico"
                                        tabIndex={0}
                                      >
                                        <i className="ri-facebook-fill"></i>
                                      </Link>
                                      <Link
                                        href="#"
                                        className="share-ico"
                                        tabIndex={0}
                                      >
                                        <i className="ri-twitter-fill"></i>
                                      </Link>
                                      <Link
                                        href="#"
                                        className="share-ico iq-copy-link"
                                        tabIndex={0}
                                      >
                                        <i className="ri-links-fill"></i>
                                      </Link>
                                    </div>
                                  </div>
                                </li>
                                <li>
                                  <span>
                                    <i className="ri-heart-fill"></i>
                                  </span>
                                  <span className="count-box">2+</span>
                                </li>
                                <li>
                                  <span>
                                    <i className="ri-add-line"></i>
                                  </span>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </SwiperSlide>
                      );
                    })}
                  </Swiper>
                  <div className="slider-next btn-verticle">
                    <i
                      id="next"
                      className="ri-arrow-down-s-line vertical-aerrow"
                    ></i>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
        <div className="slider-images" data-swiper="slider-images">
          <Swiper
            tag="ul"
            loop={true}
            spaceBetween={10}
            freeMode={true}
            watchSlidesProgress={true}
            modules={[FreeMode, Navigation, Thumbs, Controller]}
            direction={"vertical"}
            className="swiper-container"
            // onSwiper={setThumbsSwiper}
          >
            {latestMovies.map((item:any, index:any) => {
              return (
                <SwiperSlide key={index} tag="li" className="swiper-slide">
                  <div className="slider--image block-images">
                    <img src={item.thumbnail} loading="lazy" alt="" />
                  </div>
                  <div className="description">
                    <div className="block-description">
                      <h6 className="iq-title">
                        <Link href={`/movies/${item.slug}`}>{t(item.title)}</Link>
                      </h6>
                      <div className="movie-time d-flex align-items-center my-2">
                        <span className="text-white">{item.duration}</span>
                      </div>
                      <div className="hover-buttons">
                        <Link
                          href="/movies/detail"
                          role="button"
                          className="btn btn-hover iq-button"
                        >
                          <i className="fa fa-play me-1" aria-hidden="true"></i>
                          {t("streamButtons.play_now")}
                        </Link>
                      </div>
                    </div>
                  </div>
                </SwiperSlide>
              );
            })}
          </Swiper>
        </div>
      </>
    </Fragment>
  );
});
export default HomeVerticalSlider;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/slider/HomeVerticalSlider.vue
<template>
  <div class="verticle-slider section-padding-bottom sdf">
    <!-- <b-container fluid> -->
    <div class="slider">
      <div class="slider-flex position-relative">
        <div class="slider--col position-relative">
          <div class="vertical-slider-prev swiper-button"><i class="ph ph-caret-up"></i></div>
          <div class="slider-thumbs" data-swiper="slider-thumbs">
            <div class="swiper-container" data-swiper="slider-thumbs-inner">
              <swiper
              v-if="render" :dir="rtl" :loop="true" :slides-per-view="3" :space-between="24" :navigation="{
                nextEl: '.vertical-slider-next',
                prevEl: '.vertical-slider-prev',
              }" :modules="modules" class="swiper-wrapper top-ten-slider-nav" :direction="'vertical'"
                :thumbs="{ swiper: thumbsSwiper }">
                <SwiperSlide v-for="data in thumbsSwiperCard" :key="data.title" tag="li" class="swiper-slide swiper-bg">
                  <div class="block-images position-relative">
                    <div class="img-box slider--image">
                      <img :src="data.image" class="img-fluid" alt="img" loading="lazy" />
                    </div>
                    <div class="block-description">
                      <h6 class="iq-title">{{ $t(data.title) }}</h6>
                      <div class="movie-time d-flex align-items-center my-2">
                        <span class="text-body">{{ data.time }}</span>
                      </div>
                    </div>
                  </div>
                </SwiperSlide>
              </swiper>
            </div>
          </div>
          <div class="vertical-slider-next swiper-button"><i class="ph ph-caret-down"></i></div>
        </div>
        <div class="slider-images" data-swiper="slider-images">
          <div class="swiper-container" data-swiper="slider-images-inner">
            <swiper
v-if="render" :dir="rtl" :loop="true" :space-between="10" :free-mode="true"
              :watch-slides-progress="true" :modules="modules" :direction="'vertical'" class="swiper-container"
              @swiper="setThumbsSwiper">
              <SwiperSlide v-for="data in sliderData" :key="data" tag="li" class="swiper-slide">
                <div class="slider--image block-images"><img :src="data.image" loading="lazy" alt="img" /></div>
                <div class="description">
                  <div class="block-description">
                    <ul class="ps-0 mb-0 mb-1 pb-1 list-inline d-flex flex-wrap align-items-center movie-tag">
                      <li class="position-relative text-capitalize font-size-14 letter-spacing-1">
                        <router-link to="" class="text-white text-decoration-none">{{ $t(data.geners) }}</router-link>
                      </li>
                      <li class="position-relative text-capitalize font-size-14 letter-spacing-1">
                        <router-link to="" class="text-white text-decoration-none">{{ $t(data.geners1) }}</router-link>
                      </li>
                      <li class="position-relative text-capitalize font-size-14 letter-spacing-1">
                        <router-link to="" class="text-white text-decoration-none">{{ $t(data.geners2) }}</router-link>
                      </li>
                    </ul>
                    <h2 class="iq-title mb-3">
                      <router-link to="">{{ $t(data.title) }}</router-link>
                    </h2>
                    <div class="d-flex align-items-center gap-3 mb-3">
                      <div class="slider-ratting d-flex align-items-center">
                        <ul
                          class="ratting-start p-0 m-0 list-inline text-warning d-flex align-items-center justify-content-left">
                          <li>
                            <i class="fa fa-star" aria-hidden="true"></i>
                          </li>
                        </ul>
                        <span class="text-white ms-2 font-size-14 fw-500">{{ data.rating }}</span>
                      </div>
                      <span class="text-body">{{ data.time }}</span>
                    </div>
                    <p class="mt-0 mb-3">{{ $t(data.description) }}</p>
                    <custom-button :button-title="$t('streamButtons.play_now')" :link="{ path: '/' }"></custom-button>
                  </div>
                </div>
              </SwiperSlide>
            </swiper>
          </div>
        </div>
      </div>
    </div>
    <!-- </b-container> -->
  </div>
</template>
<script setup>
import { Swiper, SwiperSlide } from 'swiper/vue';
import { Navigation, Controller, Thumbs } from 'swiper';
import CustomButton from '../CustomButton.vue';
import { generateImgPath } from '../../StaticData/data';
import { ref, computed, watch } from 'vue';
import { useSetting } from '../../store/setting/index';
const store = useSetting();
const rtl = computed(() => store.theme_scheme_direction_value);
const render = ref(true);
watch(
  () => rtl.value,
  () => {
    render.value = false;
    setTimeout(() => {
      render.value = true;
    }, 0);
  }
);
// Swiper Modules
const modules = [Navigation, Controller, Thumbs];
defineProps({
  slug: { type: String, default: '' },
  thumbnail: { type: String, default: '' },
  title: { type: String, default: '' },
  certificate: { type: String, default: '' },
  duration: { type: String, default: '' },
  detailViewLink: { type: String, default: '' },
  season: { type: String, default: '' },
});
const thumbsSwiper = ref(null);

const setThumbsSwiper = (swiper) => {
  thumbsSwiper.value = swiper;
};

const thumbsSwiperCard = [

  {
    image: generateImgPath('/assets/images/top-10/09.webp'),
    title: 'home.logan',
    time: '1hr : 22mins',
  },
];

const sliderData = [


];
</script>
