// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/sections/OnlyOnStreamit.vue
<template>
  <!-- Only on streamit start -->
  <SectionSlider :title="$t(title)" :list="topTen" :slides-per-view="6" :loop="false" class="streamit-block" margin-padding="px-1 mb-4">
    <template #headerLink>
      <router-link to="/view-all" class="text-primary iq-view-all text-decoration-none flex-none">{{ $t('sectionTitle.view_all') }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :product-premium="data.productPremium" :card-lang="data.cardLang" :title="$t(data.title)" :watchlist-link="{ name: '/play-list' }" :link="{ name: 'movies-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Only on streamit end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';

import { sectionSliders } from '../../StaticData/data';
const title = ref('sectionTitle.only_on_streamit');
const topTen = ref(sectionSliders);
</script>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/sections/OnlyOnStreamit.tsx
import { memo, Fragment, useState } from "react";

//component
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { sectionSliders } from "../../StaticData/data";

//hook
import { useTranslation } from 'react-i18next';
const OnlyOnStreamit = memo(() => {
  const { t } = useTranslation("common");
  const [onlyonstreamit] = useState(sectionSliders);
  return (
    <Fragment>
      <SectionSlider
        title={t("sectionTitle.only_on_streamit")}
        list={onlyonstreamit}
        className="streamit-block"
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            watchlistLink="/play-list"
            link="/movies/detail"
            conturyname={data.conturyname}
            slug={data.slug}
            lang={data.lang}
            playNowLink="/"
            productPremium={data.productPremium}
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

OnlyOnStreamit.displayName = "OnlyOnStreamit";
export default OnlyOnStreamit;
