// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/sections/Specials&LatestMovies.vue
<template>
  <!-- Specials & Latest Movies start -->
  <SectionSlider :title="$t(title)" :list="spacialLatestMovie" :slides-per-view="6"
    class="recommended-block section-wraper streamit-block" margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <nuxt-link :to="{ name: 'view-all' }"
        class="text-primary iq-view-all text-decoration-none flex-none">{{ $t('sectionTitle.view_all') }}</nuxt-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :is-card-style2="true" :title="$t(data.title)"
        :product-premium="data.productPremium" :is-not-lang-card="true" :watchlist-link="{ name: '/play-list' }"
        :link="{ name: 'movies-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Specials & Latest Movies end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { spacialLatestMovie } from '../../StaticData/data';
const title = ref('sectionTitle.specials_latest_movies');
</script>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/sections/Specials&LatestMovies.tsx
import { useState, Fragment, memo } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { spacialLatestMovie } from "../../StaticData/data";

//hook
import { useTranslation } from 'react-i18next';
import CardStyleTwo from "../cards/CardStyleTwo";
interface ListItem {
  image: string;
  title: string;
  slug: string[];
  lang: string;
  productPremium: boolean;
}
interface Props {
  list?: ListItem[]; 
  title: string;
  loop: boolean;
  slidesPerView?: number;
  viewAll ?: boolean
  productPremium: boolean;
}

const SpecialsLatestMovies = memo((props: Props) => {
  const { t } = useTranslation("common");
  const list = props.list ?? spacialLatestMovie;
  const title = props.title ?? t("sectionTitle.specials_latest_movies");
  const loop = props.loop ?? true;
  const slidesPerView = props.slidesPerView ?? 6;
  return (
    <Fragment>
      <SectionSlider
        title={t(title)}
        list={list}
        className="recommended-block streamit-block"
        loop = {loop}
        slidesPerView={slidesPerView}
        viewAll={props.viewAll}
        slideMedium={4}
      >
        {(data) => (
          <CardStyleTwo
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            watchlistLink="/play-list"
            linkPath="/movies/detail"
            slug={data.slug}
            lang={data.lang}
            playNowLink="/"
            conturyname={data.conturyname}
            productPremium={data.productPremium}
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

SpecialsLatestMovies.displayName = "SpecialsLatestMovies";
export default SpecialsLatestMovies;
