// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/sections/TabSlider.vue
<template>
  <div class="tab-slider otthome-tab-slider">
    <div class="slider">
      <Swiper
        v-if="render"
        :dir="rtl"
        :watch-slides-progress="true"
        class="wrapper-class position-relative swiper swiper-card"
        :pagination="{ 
          el: '.swiper-pagination', 
          clickable: true 
        }"
        :navigation="{
          prevEl: '.joint-arrows .swiper-button-prev', 
          nextEl: '.joint-arrows .swiper-button-next'
        }"
        :effect="'fade'"
        :slides-per-view="1"
        :modules="modules"
      >
        <SwiperSlide 
          v-for="(data, index) in tabSlider" 
          :key="`slider-${index}`" 
          tag="li" 
          class="tab-slider-banner p-0 swiper-active"
        >
          <div 
            class="tab-slider-banner-images" 
            :style="{ backgroundImage: `url(${data.image})` }"
          >
            <div class="block-images position-relative w-100">
              <b-container fluid>
                <b-row class="align-items-center h-100 my-4">
                  <b-col lg="5" xxl="5">
                    <div class="tab-left-details">
                      <div class="d-flex align-items-center gap-3 mb-4">
                        <a href="javascript:void(0);">
                          <img 
                            src="/assets/images/pages/trending-label.webp" 
                            class="img-fluid trending-label-img rounded-3" 
                            alt="trending" 
                            loading="lazy" 
                          />
                        </a>
                        <span class="text-gold fw-bold font-size-18">
                          #1 {{ $t(data.movieTime || '') }}
                        </span>
                      </div>
                      <h1 class="mb-2 fw-500 text-capitalize texture-text">
                        {{ $t(data.title || '') }}
                      </h1>
                      <p class="my-3 line-count-3 RightAnimate-three">
                        {{ $t(data.detail || '') }}
                      </p>
                      <ul class="d-flex align-items-center list-inline gap-2 movie-tag p-0 mt-3 mb-40">
                        <li class="font-size-18 trending-list">February 2025</li>
                        <li class="font-size-18">3 {{ $t('streamEpisode.season') }}</li>
                      </ul>
                      <custom-button 
                        button-title="stream now" 
                        :link="{ path: '/tv-show-detail' }"
                      />
                    </div>
                  </b-col>
                  <b-col md="1" lg="2" xxl="3"></b-col>
                  <b-col md="6" lg="5" xxl="3" class="mt-5 mt-md-0 d-none d-lg-block">
                    <div class="tab-block">
                      <h4 class="tab-title text-capitalize mb-0">
                        {{ $t('streamEpisode.all_episode') }}
                      </h4>
                      <div class="tab-bottom-bordered border-0">
                        <ul 
                          class="nav nav-tabs nav-pills mb-3 overflow-x-scroll" 
                          role="tablist"
                        >
                          <li 
                            v-for="(season, seasonIndex) in data.seasons" 
                            :key="`season-${season.id}`" 
                            class="nav-item" 
                            role="presentation"
                          >
                            <button 
                              class="nav-link" 
                              :class="{ active: selectedTab[index] === seasonIndex }" 
                              data-bs-toggle="pill" 
                              :data-bs-target="`#season-${index}-${season.seasonIndex}`" 
                              type="button" 
                              role="tab" 
                              :aria-selected="selectedTab[index] === seasonIndex" 
                              @click="changeTab(index, seasonIndex)"
                            >
                              {{ $t(season.title) }}
                            </button>
                          </li>
                        </ul>
                      </div>

                      <div class="tab-content iq-tab-fade-up">
                        <div 
                          v-for="(season, seasonIndex) in data.seasons" 
                          :id="`season-${index}-${seasonIndex}`" 
                          :key="`season-content-${season.seasonIndex}`" 
                          class="tab-pane fade" 
                          :class="{ 
                            show: selectedTab[index] === seasonIndex, 
                            active: selectedTab[index] === seasonIndex 
                          }" 
                          role="tabpanel" 
                          tabindex="0"
                        >
                          <ul class="list-inline m-0 p-0">
                            <li 
                              v-for="(episode, episodeIndex) in season.episodes" 
                              :key="`episode-${episodeIndex}`" 
                              class="d-flex align-items-center gap-3"
                            >
                              <div class="image-box flex-shrink-0">
                                <router-link :to="{ name: 'landing-page.tv-show-detail' }">
                                  <img 
                                    :src="episode.image" 
                                    :alt="`episode-${episodeIndex + 1}`" 
                                    class="img-fluid rounded" 
                                    loading="lazy"
                                  />
                                </router-link>
                              </div>
                              <div class="image-details">
                                <h6 class="mb-1 text-capitalize">
                                  <router-link :to="{ name: 'landing-page.tv-show-detail' }">
                                    {{ $t(episode.title) }}
                                  </router-link>
                                </h6>
                                <div class="episode-time d-flex align-items-center gap-1 mt-2">
                                  <i class="ph ph-clock font-size-14"></i>
                                  <small>{{ episode.movieTime }}</small>
                                </div>
                              </div>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </b-col>
                </b-row>
              </b-container>
            </div>
          </div>
        </SwiperSlide>
        <div class="joint-arrows d-none d-lg-block">
          <div class="swiper-button swiper-button-next"></div>
          <div class="swiper-button swiper-button-prev"></div>
        </div>
        <div class="swiper-pagination d-block d-lg-none"></div>
      </Swiper>
    </div>
  </div>
</template>

<script setup>
import { Swiper, SwiperSlide } from 'swiper/vue';
import { ref, computed, watch } from 'vue';
import { Navigation, Pagination, EffectFade } from 'swiper';
import { tabSlider } from '../../StaticData/data';
import { useSetting } from '../../store/setting/index';

const store = useSetting();
const rtl = computed(() => store.theme_scheme_direction_value);
const render = ref(true);

watch(
  () => rtl.value,
  () => {
    render.value = false;
    setTimeout(() => {
      render.value = true;
    }, 0);
  }
);

const modules = [Navigation, Pagination, EffectFade];

// Initialize selectedTab as an array to track active tab for each slider
const selectedTab = ref(tabSlider.map(() => 0));

const changeTab = (sliderIndex, tabIndex) => {
  selectedTab.value[sliderIndex] = tabIndex;
};
</script>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/sections/TabSlider.tsx
import { Fragment, memo } from "react";

//react-bootstrap
import { Nav, Tab } from "react-bootstrap";

//react-router-dom
// import { Link } from "react-router-dom";
import Link from "next/link";

//static data
import { tabSlider } from "../../StaticData/data";

//swiper
import { Swiper, SwiperSlide } from "swiper/react";
import { EffectFade, Navigation, Pagination } from "swiper";

// Redux Selector / Action
import { useSelector } from "react-redux";
import { theme_scheme_direction } from "../../store/setting/selectors";

//hook
import { useTranslation } from 'react-i18next';



const TabSlider = memo(() => {
    const { t } = useTranslation("common");
  const themeSchemeDirection = useSelector(theme_scheme_direction);
  return (
  <Fragment>
      <div className="tab-slider otthome-tab-slider">
        <div className="slider">
          <Swiper
            key={themeSchemeDirection.toString()} 
            dir={themeSchemeDirection.toString()}
            
            watchSlidesProgress={true}
            className="wrapper-class position-relative swiper swiper-card wrapper-class custom-tab-slider swiper-no-swiping"
            navigation={{
              prevEl: ".swiper-button-prev",
              nextEl: ".swiper-button-next",
            }}
            slidesPerView={1}
            speed={1500}
            // effect={'fade'}
            modules={[Navigation, Pagination, EffectFade]}
            pagination={{ el: '.swiper-pagination', clickable: true }}
          >
            {tabSlider.map((data , index) => (
              <SwiperSlide
                className="tab-slider-banner p-0"
                key={data.image}
              >
                <div
                  className="tab-slider-banner-images"
                  style={{ backgroundImage: `url(${data.image})` }}
                >
                  <div className="block-images position-relative w-100">
                    <div className="container-fluid">
                      <div className="row align-items-center min-vh-100 h-100 my-4">
                        <div className="col-lg-5 col-xxl-5">
                          <div className="tab-left-details">
                            <div className="d-flex align-items-center gap-3 mb-4">
                              <Link href="">
                                <img
                                  src=
                                    "/assets/images/pages/trending-label.webp"
                                  className="img-fluid trending-label-img rounded-3"
                                  alt=""
                                />
                              </Link>
                              <span className="text-gold fw-bold font-size-18">
                                #{index+1} {t(data.movieTime)}
                              </span>{" "}
                            </div>
                            <h1 className="mb-2 text-capitalize texture-text ">
                              {t(data.title)}
                            </h1>
                            <p className="mb-0 font-size-14 line-count-3 RightAnimate-three">
                              {t(data.detail)}.
                            </p>
                            <ul className="d-flex align-items-center list-inline gap-2 movie-tag p-0 mt-3 mb-40">
                              <li className="font-size-18 trending-list">
                                Nov 2022
                              </li>
                              <li className="font-size-18">
                                {t("streamEpisode.season")} 1
                              </li>
                            </ul>
                            <div className="iq-button">
                              <Link
                                href="/tv-shows/detail"
                                className="btn btn-primary text-capitalize position-relative rounded-3"
                              >
                                <span className="d-flex align-items-center gap-2">
                                  <span className="button-text">
                                    {t("streamButtons.stream_now")}
                                  </span>
                                  <i className="ph-fill ph-play fs-6"></i>
                                </span>
                              </Link>
                            </div>
                          </div>
                        </div>
                        <div className="col-md-1 col-lg-2 col-xxl-3"></div>
                        <div className="col-md-6 col-lg-5 col-xxl-3 mt-5 mt-md-0 d-none d-lg-block">
                          <div className="tab-block">
                            <h4 className="tab-title text-capitalize mb-0">
                              {t("streamEpisode.all_episode")}
                            </h4>
                            <div className="tab-bottom-bordered border-0 trending-custom-tab">
                              <Tab.Container
                                id="left-tabs-example"
                                defaultActiveKey="0season"
                              >
                                <Nav
                                  variant="pills"
                                  className="nav nav-tabs nav-pills mb-3 overflow-x-scroll"
                                >
                                  {data.seasons.map((episodes, index) => (
                                    <Nav.Item key={"nav" + index}>
                                      <Nav.Link eventKey={index + "season"}>
                                        {t(episodes.title)}
                                      </Nav.Link>
                                    </Nav.Item>
                                  ))}
                                </Nav>
                                <Tab.Content className="tab-content trending-content">
                                  {data.seasons.map((episodes, index) => (
                                    <Tab.Pane
                                      eventKey={index + "season"}
                                      key={index + "season"}
                                    >
                                      <ul className="list-inline m-0 p-0">
                                        {episodes.episodes.map(
                                          (episode, episodeIndex) => (
                                            <li
                                              className="d-flex align-items-center gap-3"
                                              key={episode.title + "ep"+ episodeIndex}
                                            >
                                              <div className="image-box flex-shrink-0">
                                                <Link href="/tv-shows/detail">
                                                  <img
                                                    src={episode.image}
                                                    alt="image-icon"
                                                    className="img-fluid rounded"
                                                  />
                                                </Link>
                                              </div>
                                              <div className="image-details">
                                                <h6 className="mb-1 text-capitalize">
                                                  <Link href="/tv-shows/detail">
                                                    {t(episode.title)}
                                                  </Link>
                                                </h6>
                                                <div className="episode-time d-flex align-items-center gap-1 mt-2">
                                                  <i className="ph ph-clock font-size-14"></i>
                                                  <small>{episode.time}</small>
                                                </div>
                                              </div>
                                            </li>
                                          )
                                        )}
                                      </ul>
                                    </Tab.Pane>
                                  ))}
                                </Tab.Content>
                              </Tab.Container>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </SwiperSlide>
            ))}
            <div className="swiper-pagination d-block d-lg-none"></div>
            <div className="joint-arrows d-none d-lg-block">
              <div className="swiper-button swiper-button-next"></div>
              <div className="swiper-button swiper-button-prev"></div>
            </div>
          </Swiper>
        </div>
      </div>
    </Fragment>
  );
})

TabSlider.displayName = "TabSlider"
export default TabSlider
