// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/sections/TopPicsForYou.vue
<template>
  <!-- Top Pics For You start -->
  <SectionSlider
:title="$t(title)" :list="topTen" :slides-per-view="6" class="top-pics-block section-wraper streamit-block"
    margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <router-link to="/view-all" class="text-primary iq-view-all text-decoration-none flex-none">{{
        $t('sectionTitle.view_all') }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style
:image="data.image" :title="$t(data.title)" :card-lang="data.cardLang" :product-premium="data.productPremium"
        :watchlist-link="{ name: '/play-list' }" :link="{name: 'movies-detail'}"></card-style>
    </template>
  </SectionSlider>
  <!-- Top Pics For You end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { topPics } from '../../StaticData/data';
const title = ref('sectionTitle.top_picks');
const topTen = ref(topPics);
</script>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/sections/TopPicsForYou.tsx
import { Fragment, memo, useState } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { topPics } from "../../StaticData/data";

//hook
import { useTranslation } from 'react-i18next';

const TopPicsForYou = memo(() => {
  const { t } = useTranslation("common");
  const [topTen] = useState(topPics);

  return (
    <Fragment>
      <SectionSlider
        title={t("sectionTitle.top_picks")}
        list={topTen}
        className="recommended-block streamit-block"
        slidesPerView={6}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            watchlistLink="/play-list"
            link="/movies/detail"
            conturyname={data.conturyname}
            slug={data.slug}
            lang={data.lang}
            playNowLink={data.playNowLink || "/"}
            productPremium={data.productPremium}
          />
        )}
      </SectionSlider>
    </Fragment>
  );
})

TopPicsForYou.displayName = 'TopPicsForYou';
export default TopPicsForYou;
