// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/sections/UpcomingMovies.vue
<template>
  <!-- Upcoming Movies start -->
  <SectionSlider
    :title="$t(title)"
    :list="upComing"
    :slides-per-view="6"
    :loop="false"
    class="streamit-block"
    margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0"
  >
    <template #headerLink>
      <nuxt-link
        :to="{ name: 'view-all' }"
        class="text-primary iq-view-all text-decoration-none flex-none"
        >{{ $t("sectionTitle.view_all") }}</nuxt-link
      >
    </template>
    <template #default="{ data }">
      <card-style
        :image="data.image"
        :title="$t(data.title)"
        :product-premium="data.productPremium"
        :watchlist-link="{ name: '/play-list' }"
        :link="{name: 'movies-detail'}"
        :card-lang="data.cardLang"
      ></card-style>
    </template>
  </SectionSlider>
  <!-- Upcoming Movies end -->
</template>

<script setup>
import { ref } from "vue";
import SectionSlider from "../slider/SectionSlider.vue";
import CardStyle from "../cards/CardStyle.vue";

import { upcommingMovie } from "../../StaticData/data";
const title = ref("sectionTitle.upcoming_movies");
const upComing = ref(upcommingMovie);
</script>
dvd

// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/sections/UpcomingMovies.tsx
import { FC,Fragment, memo, useState } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//data
import { upcommingMovie } from "../../StaticData/data";

//hook
import { useTranslation } from 'react-i18next';

interface ListItem {
  image: string;
  title: string;
  slug: string[];
  lang: string;
  productPremium ?: boolean;
}
interface UpcomingMovies {
  title ?: string;
  list : ListItem[]; 
  loop ?: boolean;
  viewAll ?: boolean;
 productPremium ?: boolean;
}

const UpcomingMovies: FC<UpcomingMovies> = memo(({title , list , loop, viewAll}) => {
  const { t } = useTranslation("common");
const titles  = title ??  "sectionTitle.upcoming_video"
const lists = list ?? upcommingMovie;
  const loops = loop ?? true;
  return (
    <Fragment>
      <SectionSlider
        title={t(titles)}
        list={lists}
        className="upcomimg-block streamit-block"
        slidesPerView={6}
        loop={loops}
        viewAll={viewAll}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            watchlistLink="/play-list"
            link="/movies/detail"
            conturyname={data.conturyname}
            slug={data.slug}
            lang={data.lang}
            playNowLink={data.playNowLink || "/"}
            productPremium={data.productPremium}
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

UpcomingMovies.displayName = "UpcomingMovies"
export default UpcomingMovies;
