// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/sections/VideosRecommendedForYou.vue
<template>
  <!-- Videos Recommended For You start -->
  <SectionSlider :title="$t(title)" :list="videosRecommendedforYou" :slides-per-view="6"
    class="recommended-block streamit-block" margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <nuxt-link :to="{ name: 'view-all' }" class="text-primary iq-view-all text-decoration-none">{{
        $t('sectionTitle.view_all') }}</nuxt-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :title="$t(data.title)" :card-lang="data.cardLang"
        :product-premium="data.productPremium" :watchlist-link="{ name: '/play-list' }"
        :link="{ name: 'movies-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Videos Recommended For You end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { videosRecommendedforYou } from '../../StaticData/data';
const title = ref('sectionTitle.videos_recommended');
</script>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/sections/VideosRecommendedForYou.tsx
import { useState, Fragment, memo } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { recommendedforYou } from "../../StaticData/data";


//hook
import { useTranslation } from 'react-i18next';

interface ListItem {
  image: string;
  title: string;
  slug: string[];
  lang: string;
  productPremium?: boolean;
}
interface Props {
  title ?: string
  list : ListItem[]; 
  loop ?: boolean
  viewAll ?: boolean
}

const VideosRecommendedForYou = memo((props:Props) => {
    const { t } = useTranslation("common");
const lists = props.list ?? recommendedforYou;
  return (
    <Fragment>
      <SectionSlider
        title={t("sectionTitle.videos_recommended")}
        list={lists}
        className="recommended-block streamit-block"
        viewAll={props.viewAll}
        loop={props.loop}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            watchlistLink="/play-list"
            link="/movies/detail"
            conturyname={data.conturyname}
            slug={data.slug}
            lang={data.lang}
            playNowLink={data.playNowLink || "/"}
            productPremium={data.productPremium}
          />
        )}
      </SectionSlider>
    </Fragment>
  );
})

VideosRecommendedForYou.displayName = 'VideosRecommendedForYou';
export default VideosRecommendedForYou;
