// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/cards/CardBlogGrid.vue
<template>
  <div class="iq-blog-box">
    <div class="iq-blog-image clearfix">
      <router-link :to="{ name: 'landing-page.blogs.detail', params: { slug: props.slug } }">
        <img :src="props.thumbnail" alt="blog" class="img-fluid w-100" loading="lazy" />
      </router-link>
    </div>
    <div class="iq-blog-detail">
      <div class="iq-blog-meta d-flex mb-3">
        <ul class="list-inline">
          <li class="border-gredient-left">
            <!-- <i class="fa fa-calendar me-1" aria-hidden="true"></i> -->
            <!-- <time datetime="2019-02-02T12:46:15+00:00" class="ms-2"> -->
            <router-link to="/blogs-date">
              <span>{{ props.date }}</span>
            </router-link>
            <!-- </time> -->
          </li>
        </ul>
        <ul class="iq-blogtag list-inline">
          <li class="border-gredient-left">
            <router-link :to="{ name: 'landing-page.blogs.category' }"> {{ props.categories }}</router-link>
          </li>
        </ul>
      </div>
      <div class="blog-title">
        <router-link :to="{ name: 'landing-page.blogs.detail', params: { slug: props.slug } }">
          <h3 class="mb-3 line-count-1 blog-heading"> {{ props.title }} </h3>
        </router-link>
      </div>
      <p>{{ $t(props.shortDescription) }}</p>
      <div class="iq-button link-button">
        <router-link
class="btn text-capitalize position-relative"
          :to="{ name: 'landing-page.blogs.detail', params: { slug: props.slug } }">
          <span class="button-text">{{ $t('streamButtons.read_more') }} <i
class="fa fa-angle-right ml-2"
              aria-hidden="true"></i></span>
        </router-link>
      </div>
    </div>
  </div>
</template>
<script setup>
const props = defineProps({
  thumbnail: { type: String, default: '' },
  title: { type: String, default: '' },
  slug: { type: String, default: '' },
  shortDescription: { type: String, default: '' },
  date: { type: String, default: '' },
  categories: { type: String, default: '' },
  username: { type: String, default: '' },
});
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/cards/CardBlogGrid.jsx
import React, { Fragment, memo } from "react";

//react-router-dom
import { Link } from "react-router-dom";

//hooks
import { useTranslation } from "react-i18next";

const CardBlogGrid = memo((props) => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <div className="iq-blog-box">
        <div className="iq-blog-image clearfix">
          <Link to="/blogs-detail">
            <img
              src={props.thumbnail}
              alt="img"
              loading="lazy"
              className="img-fluid w-100 rounded-3"
            />
          </Link>
        </div>
        <div className="iq-blog-detail">
          <div className="iq-blog-meta d-flex align-item-center flex-wrap">
            <ul className="list-inline mb-0">
              <li className="posted-by">
                <span className="post-date d-flex align-item-center gap-1">
                  {props.tags === true ? (
                    <i className="icon icon-tag"></i>
                  ) : (
                    <i className="ph ph-user"></i>
                  )}
                  <Link to="/blogs-author">{props.username}</Link>{" "}
                </span>
              </li>{" "}
              <li className="posted-on">
                <span className="post-author d-flex align-item-center gap-1">
                  <i className="icon icon-calendar-2"></i>
                  <Link to="/blogs-date">
                    <span>{props.blogDate}</span>
                  </Link>
                </span>
              </li>{" "}
            </ul>
          </div>
          <div className="blog-title">
            <h4 className="mb-3 blog-heading">
              <Link to={`/blogs-detail`}>{props.title}</Link>
            </h4>
          </div>
          <p className="line-count-2">{props.description}</p>
          <div className="iq-button">
            {props.link_button === true ? (
              <div className="">
                <Link
                  to="/blogs-detail"
                  className="btn btn-link blog-readMore p-0 text-capitalize position-relative font-size-14"
                >
                  <span className="">{t("streamButtons.read_more")}</span>{" "}
                  <span>
                    {props.button_icon && (
                      <i className="ph ph-caret-right align-middle"></i>
                    )}
                  </span>
                </Link>
              </div>
            ) : (
              <div className="iq-button">
                <Link
                  to="/blogs-detail"
                  className="btn btn-primary text-uppercase position-relative"
                >
                  <span className="button-text">{t("streamButtons.read_more")} </span>
                  <i className="ph-fill ph-play"></i>
                </Link>
              </div>
            )}
          </div>
        </div>
      </div>
    </Fragment>
  );
});

CardBlogGrid.displayName = "CardBlogGrid";
export default CardBlogGrid;
