// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/cards/ContinueWatchCard.vue
<template>
  <div class="iq-watching-block">
    <div class="block-images position-relative">
      <div class="iq-image-box overly-images">
        <nuxt-link :to="{ name: 'movies-detail' }" class="d-block">
          <img :src="imagePath" alt="movie-card" class="w-100 d-block border-0 rounded-3 continue-image" loading="lazy" />
        </nuxt-link>
      </div>
      <div class="iq-preogress">
        <span class="px-2 text-white fw-semibold font-size-14 iq-progress-left-data">{{ dataLeftTime }} m Left</span>
        <div class="d-flex align-items-center justify-content-between px-2 mb-1">
          <ul class="list-inline m-0 p-0 d-flex row-gap-1 column-gap-3 flex-wrap movie-list-item">
            <li class="iq-preogress-movie-title position-relative font-size-14">
              <span class="text-capitalize fw-semibold">{{ $t(watchMovieTitle) }}</span>
            </li>
            <li class="flex-shrink-0 fw-semibold font-size-14">
              <span>
                {{ watchMovieDate }}
              </span>
            </li>
          </ul>
          <a>
            <i class="ph-fill ph-play iq-preogress-play-btn fs-6"></i>
          </a>
        </div>
        <b-progress :value="progressValue" style="height: 2px"></b-progress>
      </div>
      <div class="close-icon-section">
        <div class="position-absolute d-flex align-items-center justify-content-center iq-watching-close-icon" data-bs-toggle="tooltip" data-bs-placement="left" :data-bs-title="$t('streamTooltip.remove_from_list')" aria-label="Remove from list">
          <i class="ph ph-x font-size-14 fw-bold align-middle"></i>
        </div>
      </div>
    </div>
  </div>
</template>
<script setup>
import { onMounted } from 'vue';
import { Tooltip } from 'bootstrap';

defineProps({
  dataLeftTime: { type: String, default: '' },
  imagePath: { type: String, default: '' },
  progressValue: { type: Number, default: 0 },
  watchMovieTitle: { type: String, default: '' },
  watchMovieDate: { type: String, default: '' },
});

onMounted(() => {
  const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
  tooltipTriggerList.forEach((el) => new Tooltip(el));
});
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/cards/ContinueWatchCard.jsx
import { Fragment, memo } from "react";

//react-bootstrap
import { ProgressBar, OverlayTrigger, Tooltip } from "react-bootstrap";

//react-router-dom
import { Link } from "react-router-dom";

import { useTranslation } from "react-i18next";

const ContinueWatchCard = memo(
    ({ link, imagePath, dataLeftTime, watchMovieTitle, watchMovieDate, progressValue }) => {
      const { t } = useTranslation();
    return (
      <Fragment>
        <div className="iq-watching-block">
    <div className="block-images position-relative">
        <div className="iq-image-box overly-images">
            <Link to={link} className="d-block">
                <img src={imagePath} alt="movie-card"
                    className="w-100 d-block border-0 rounded-3 continue-image" />
            </Link>
        </div>
        <div className="iq-preogress">
            <span className="px-2 text-white fw-semibold font-size-14 iq-progress-left-data">{dataLeftTime}{" "}
                Left</span>
            <div className="d-flex align-items-center justify-content-between px-2 mb-1">
                <ul className="list-inline m-0 p-0 d-flex row-gap-1 column-gap-3 flex-wrap movie-list-item">
                    <li className="iq-preogress-movie-title position-relative font-size-14" key="title"><span
                            className="text-capitalize fw-semibold ">{watchMovieTitle}</span></li>
                    <li className="flex-shrink-0 fw-semibold font-size-14" key="date">
                        <span>
                            {watchMovieDate}
                        </span>
                    </li>
                </ul>
                <a>
                    <i className="ph-fill ph-play iq-preogress-play-btn fs-6"></i>
                </a>
            </div>
            <ProgressBar now={progressValue} style={{ height: "2px" }} />
        </div>
        <div className="close-icon-section">
            <OverlayTrigger
                placement="left"
                overlay={
                    <Tooltip id="remove-watchlist-tooltip">
                        {t("streamTooltip.remove_from_watchlist")}
                    </Tooltip>
                }
            >
                <div
                    className="position-absolute d-flex align-items-center justify-content-center iq-watching-close-icon"
                    aria-label={t("streamTooltip.remove_from_watchlist")}
                >
                    <i className="ph ph-x font-size-14 fw-bold align-middle"></i>
                </div>
            </OverlayTrigger>
        </div>
    </div>
</div>
      </Fragment>
    );
  }
);

ContinueWatchCard.displayName = "ContinueWatchCard";
export default ContinueWatchCard;
