// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/blog/comments/FormWidget.vue
<template>
  <div class="blog-nav row">
    <div class="blog-prev-post col-lg-6 mb-5 mb-lg-0 border-end">
      <router-link :to="{ name: 'landing-page.blogs' }">
        <div class="blog-arrow font-size-14 fw-normal mb-3">
          <i class="fas fa-arrow-left"></i>{{ ' ' }}
          <span class="previous fw-medium fst-italic"> {{ $t('streamForm.previous_post') }}</span>
        </div>
        <span class="fw-semibold text-white">{{ $t('streamForm.amy_admas') }} </span>
      </router-link>
    </div>
    <div class="blog-next-post col-lg-6 text-start text-lg-end">
      <router-link
        :to="{ name: 'landing-page.blogs.detail', params: { slug: 'racing-is-about-to-show-you-the-beauty-of-britain' } }">
        <div class="blog-arrow font-size-14 fw-normal mb-3">
          <span class="next fw-medium fst-italic"> {{ $t('streamForm.next_post') }}</span>{{ '' }}
          <i class="fas fa-arrow-right"></i>
        </div>
        <span class="fw-semibold text-white">{{ $t('streamForm.gillian_shares') }}</span>
      </router-link>
    </div>
  </div>
  <form>
    <h4 class="fw-500 mb-3">{{ $t('streamForm.leave_reply') }}</h4>
    <p class="mb-4">
      {{ $t('streamAccount.logged_jenny') }} <span class="text-primary">{{ $t('streamButtons.editprofile') }}</span> {{
        $t('streamForm.require_fields') }} *
    </p>
    <b-row>
      <b-col md="12">
        <div class="form-group">
          <textarea
class="form-control" name="comment" cols="5" rows="8" required=""
            :placeholder="$t('streamBlog.comment')"></textarea>
        </div>
      </b-col>

      <b-col md="12">
        <div class="form-submit mt-4">
          <div class="iq-button">
            <button id="submit" name="submit" type="submit" class="btn text-uppercase position-relative" value="Submit">
              <span class="button-text">{{ $t('streamForm.post_comment') }}</span>
              {{ '' }}
              <i class="fa-solid fa-play"></i>
            </button>
          </div>
        </div>
      </b-col>
    </b-row>
  </form>
</template>
<script setup></script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/blog/FormWidget.jsx
import React, { Fragment, memo } from "react";

//react-bootstrap
import { Button, Col, Form, Row } from "react-bootstrap";

//react-router-dom
import { Link } from "react-router-dom";
// the hook
import { useTranslation } from "react-i18next";

const FormWidget = memo((props) => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <Row className="blog-nav mt-3 mt-md-0 mb-5 mb-lg-0">
        <Col lg="6" className="col-6 blog-next-post">
          <Link to={props.prevLink ? `${props.prevLink}` : "/blogs-detail"}>
            <span className="fw-semibold d-none d-md-block">
              {t("streamForm.amy_admas")}
            </span>
            <div className="blog-arrow mt-3 d-flex align-items-center">
              <i className="ph ph-arrow-left"></i>
              <span className="previous fw-medium fst-italic">
                {" "}
                {t("streamForm.previous_post")}
              </span>
            </div>
          </Link>
        </Col>
        <Col lg="6" className="col-6 blog-next-post  text-end">
          <Link to={props.nextLink ? `${props.nextLink}` : "/blog-single/audio"}>
          <span className="fw-semibold d-none d-md-block">
              {t("streamForm.gillian_shares")}
            </span>
            <div className="blog-arrow d-flex align-items-center justify-content-end mt-3">
              <span className="next fw-medium fst-italic">
                {" "}
                {t("streamForm.next_post")}
              </span>{" "}
              <i className="ph ph-arrow-right"></i>
            </div>
            
          </Link>
        </Col>
      </Row>
      <h3 className="comments-title mb-4 pb-2">
                <span>0 {t("streamBlog.comments")}</span>
              </h3>
      <Form>
        <h3 className="mb-4">{t("streamForm.leave_reply")}</h3>
        <p className="mb-5">
          {t("streamAccount.logged_jenny")}{" "}
          <span className="text-primary">{t("streamForm.edit_profile")}{" "}</span>
          {t("streamForm.require_fields")} *
        </p>
        <Row className="pt-3">
          <Col md="12">
            <Form.Group className="form-group mb-0">
              <textarea
                className="form-control rounded-3"
                name="comment"
                cols={5}
                rows={8}
                required
                placeholder={`${t('streamBlog.comment')}*`}
              ></textarea>
            </Form.Group>
          </Col>
          <Col md="12">
            <div className="form-submit mt-5">
              <div className="iq-button">
                <Button
                  name="submit"
                  type="submit"
                  id="submit"
                  className="text-capitalize position-relative rounded-3"
                >
                  <span className="button-text">{t("streamForm.post_comment")}</span>{" "}
                </Button>
              </div>
            </div>
          </Col>
        </Row>
      </Form>
    </Fragment>
  );
});

FormWidget.displayName = "FormWidget";
export default FormWidget;
