// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/blog/sidebar/RecentPost.jsx
import React, { Fragment, memo } from "react";

//react-router-dom
import { Link } from "react-router-dom";

//static data
import { blogRecent } from "../../../StaticData/blogs";

// the hook
import { useTranslation } from "react-i18next";
import { generateImgPath } from "../../../StaticData/data";

const RecentPost = memo(() => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <div className="widget iq-widget-blog">
        <h5 className="widget-title position-relative">
          {t("streamBlog.recent_post")}
        </h5>
        <ul className="list-inline p-0 m-0">
          {blogRecent.length === 0
            ? shimmerData.map((item, index) => <RecentShimmer key={index} />)
            : blogRecent.map((item, index) => {
              return (
                <li key={index} className="d-flex align-items-center gap-4">
                  <div className="img-holder">
                    <Link to="/blogs-detail">
                      {index === 0 ? <img
                        src={generateImgPath("/assets/images/blog/01.webp")}
                        className="img-fluid h-100 w-100 object-cover"
                        alt="img"
                        loading="lazy"
                      /> : <img
                        src={item.thumbnail}
                        className="img-fluid h-100 w-100 object-cover"
                        alt="img"
                        loading="lazy"
                      />}
                    </Link>
                  </div>
                  <div className="post-blog">
                    <Link to="/blogs-detail" className="new-link">
                      <h6 className="post-title">{t(item.title)}</h6>
                    </Link>
                    <ul className="list-inline mb-2">
                      <li className="list-inline-item border-0 mb-0 pb-0">
                        <Link className="blog-data" to="#">
                          <i
                            className="far fa-calendar-alt me-1"
                            aria-hidden="true"
                          ></i>
                          {item.blogDate}
                        </Link>
                      </li>
                    </ul>
                  </div>
                </li>
              );
            })}
        </ul>
      </div>
    </Fragment>
  );
});

RecentPost.displayName = "RecentPost";
export default RecentPost;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/blog/sidebar/RecentPost.vue
<template>
  <div id="recent-posts-2" class="widget iq-widget-blog">
    <h5 class="widget-title position-relative">
      {{ $t("streamBlog.recent_post") }}
    </h5>
    <ul class="list-inline p-0 m-0">
      <li
        v-for="recent in props.recents"
        :key="recent"
        class="d-flex align-items-center gap-4"
      >
        <div class="img-holder">
          <nuxt-link :to="{ name: 'blogs-detail' }">
            <img
              :src="recent.thumbnail"
              class="img-fluid h-100 w-100 object-cover"
              alt=""
              loading="lazy"
            />
          </nuxt-link>
        </div>
        <div class="post-blog">
          <nuxt-link :to="{ name: 'blogs-detail' }">
            <h6 class="post-title">
              {{ $t(recent.title) }}
            </h6>
          </nuxt-link>
          <ul class="list-inline mb-2">
            <li clas="list-inline-item border-0 mb-0 pb-0">
              <nuxt-link class="blog-data" to="#">
                <i class="far fa-calendar-alt me-1" aria-hidden="true"></i>
                {{ recent.blogDate }}
              </nuxt-link>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</template>
<script setup>
const props = defineProps({
  recents: { type: Array, default: () => [] },
});
</script>
