// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/BreadcrumbWidget.jsx
import { Fragment, memo } from "react";

//react bootstrap
import { Breadcrumb, Container, Row, Col } from "react-bootstrap";

//function
import { generateImgPath } from "../StaticData/data";

//img
const imagePath = generateImgPath("/assets/images/pages/01.webp");
// the hook
import { useTranslation } from "react-i18next";
import { Link } from "react-router-dom";

const BreadCrumbWidget = memo((props) => {
  const { t } = useTranslation();
  return (
    <Fragment>
     <div className="iq-breadcrumb">
    <Container>
        <Row className="align-items-center">
            <Col sm={12} >
                <nav aria-label="breadcrumb" className="text-center">
                    <ol className="breadcrumb justify-content-center text-white mt-0">
                        <li className="breadcrumb-item"><Link to="/">Home</Link></li>
                        <li className="breadcrumb-item active">{props.title}</li>
                    </ol>
                </nav>
            </Col>
        </Row>
    </Container>
</div>
    </Fragment>
  );
});

BreadCrumbWidget.displayName = "BreadCrumbWidget";
export default BreadCrumbWidget;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/BreadcrumbWidget.vue
<template>
  <div class="iq-breadcrumb">
    <b-container>
      <b-row class="align-items-center">
        <b-col sm="12">
          <nav aria-label="breadcrumb" class="text-center">
            <!-- <h2 class="title">{{ $t(route.meta.pageName) }}</h2> -->
            <ol class="breadcrumb justify-content-center text-white mt-0">
              <li class="breadcrumb-item">
                <router-link :to="{ name: 'landing-page.ott' }">{{ $t('streamPages.home') }}</router-link>
              </li>
              <li class="breadcrumb-item active">{{ $t(route.meta.pageName) }}</li>
            </ol>
          </nav>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>
<script setup>
import { useRoute } from 'vue-router';
// const generateImgPath = (path) => {
//   return window.origin + import.meta.env.BASE_URL + path;
// };
const route = useRoute();
</script>
