// tamplate/streamithtml-540/streamit-html/code-vue/dashboard/src/layouts/DashboardLayout.vue
<template>
  <div>
    <loader-component :show="isLoader"></loader-component>
    <!-- Sidebar Component Start Here-->
    <sidebar-component></sidebar-component>
    <!-- Sidebar Component End Here-->
    <main class="main-content">
      <div :class="`position-relative  ${isBanner ? 'iq-banner' : ''}`">
        <!-- Header Component Start Here -->
        <header-component> </header-component>

        <template v-if="isBanner">
          <!-- Sub Header Component Start Here-->
          <sub-header :title="title"></sub-header>
          <!-- Sub Header Component End Here-->
        </template>
        <!-- Header Component End Here -->
      </div>

      <!-- Main Content Start Here -->
      <main-content-component>
        <!-- Router View For Pages -->
        <div :class="`content-inner pb-0 ${pageLayout}`">
          <router-view></router-view>
        </div>
      </main-content-component>
      <!-- Main Content Start Here -->

      <!-- Footer Component Start Here -->
      <footer-component></footer-component>
      <!-- Footer Component End Here -->
    </main>
    <!-- Live Customizer Component Start Here -->
    <setting-offcanvas></setting-offcanvas>
    <!-- Live Customizer Component End Here-->
  </div>
</template>

<script setup>
// Library
import { ref, computed, onMounted } from 'vue';
import { useRoute } from 'vue-router';

// Pinia Store
import { useSetting } from '@/store/pinia';

const store = useSetting();
const pageLayout = computed(() => store.page_layout_value);

// Components
import HeaderComponent from '@/components/partials/HeaderComponent.vue';
import SubHeader from '@/components/custom/header/SubHeader.vue';
import SidebarComponent from '@/components/partials/SidebarComponent.vue';
import MainContentComponent from '@/components/partials/MainContentComponent.vue';
import FooterComponent from '@/components/partials/FooterComponent.vue';
import SettingOffcanvas from '@/components/setting/SettingOffcanvas.vue';
import LoaderComponent from '@/components/custom/loader/LoaderComponent.vue';

import { useShepherd } from '@/utilities/shephered';
import { addClass, getQueryString } from '@/utilities/dom';

const route = useRoute();
const isBanner = computed(() => route.meta.isBanner);
const title = computed(() => route.meta.title);

const isLoader = ref(true);

const checkTour = () => {
  const liveCustomizer = getQueryString('live-customizer');
  const tour = window.sessionStorage.getItem('tour');
  if (liveCustomizer !== 'open' && route.name === 'dashboard.home') {
    if (tour !== 'true') {
      return true;
    }
  }
};

onMounted(() => {
  useShepherd(
    [
      {
        title: `<h4>Menu</h4>`,
        text: `<p class="mb-0">Check the content under Menu Style. Click to view all oavailable Menu Style options for you. </p>`,
        attachTo: {
          element: '#first-tour',
          on: 'right',
        },
        buttons: [
          {
            action() {
              return this.next();
            },
            text: 'Next',
          },
        ],
        id: 'first-tour',
      },
      {
        title: `<h4>Profile Setting</h4>`,
        text: `<p class="mb-0">Configure your Profile using Profile Settings. Edit, save and update your profile from here.</p>`,
        attachTo: {
          element: '#profilesetting',
          on: 'bottom',
        },
        buttons: [
          {
            action() {
              return this.back();
            },
            classes: 'shepherd-button-secondary',
            text: 'Back',
          },
          {
            action() {
              return this.next();
            },
            text: 'Next',
          },
        ],
        id: 'profilesetting',
      },
      {
        title: `<h4>Live Customizer</h4>`,
        text: `<p class="mb-0">Transform the entire look, color, style and appearance of using Live Customizer settings. Change and copy the settings from here. </p>`,
        attachTo: {
          element: '#settingbutton',
          on: 'right',
        },
        buttons: [
          {
            action() {
              return this.back();
            },
            classes: 'shepherd-button-secondary',
            text: 'Back',
          },
          {
            action() {
              window.sessionStorage.setItem('tour', 'true');
              return this.next();
            },
            text: 'Done',
          },
        ],
        id: 'title',
      },
    ],
    checkTour(),
    () => addClass('.shepherd-modal-overlay-container', 'shepherd-modal-is-visible')
  );
  setTimeout(() => {
    isLoader.value = false;
  }, 300);
});
</script>

// tamplate/streamithtml-540/streamit-html/code-react/dashboard/src/layouts/dashboard-layout.jsx
import React, { memo, Fragment, Suspense, useContext, useEffect, useState } from "react";
import { useLocation } from "react-router-dom";
// reacr-router
import { Outlet } from "react-router-dom";

import { ShepherdTour, ShepherdTourContext } from "react-shepherd";

//react bootstrap
import { Container } from "react-bootstrap";

// header
import HeaderStyle from "../components/partials/dashboard/header/HeaderStyle";

//subheader
import Subheader from "../components/custom/Subheader";

// sidebar
import SidebarStyle from "../components/partials/dashboard/sidebar/sidebar";

// footer
import FooterStyle from "../components/partials/dashboard/footer/FooterStyle";

//seetingoffCanvas
import SettingOffCanvas from '../components/setting/SettingOffCanvas'

import Loader from "../components/Loader";
// Import selectors & action from setting store
import * as SettingSelector from '../store/setting/selectors'

// Redux Selector / Action
import { useSelector } from 'react-redux';

const Tour = () => {
  const tour = useContext(ShepherdTourContext);
  const { pathname } = useLocation();
useEffect(() => {
  // Prevent duplicate overlay & double-start
  const existingSteps = document.querySelectorAll('.shepherd-element');
  if (existingSteps.length > 0) return;

  if (pathname === "/" && sessionStorage.getItem("tour") !== "true") {
    tour?.start();
  }
}, [pathname, tour]);

  return <Fragment></Fragment>;
};

const DashboardLayout = memo((props) => {
  const [isLoading, setIsLoading] = useState(true);
  const location = useLocation();

  // Handle initial load and route changes
  useEffect(() => {
    setIsLoading(true);
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 800);
    return () => clearTimeout(timer);
  }, [location.pathname]);

  const closeTour = () => {
    sessionStorage.setItem("tour", "true");
  };
  // shepherd
  const newSteps = [
    {
      title: "<h4>Menu</h4>",
      text: '<p className="mb-0">Check the content under Menu Style. Click to view all oavailable Menu Style options for you.</p>',
      attachTo: { element: ".sidebar ", on: "right" },
      buttons: [
        {
          type: "next",
          text: "Next",
        },
      ],
      when: {
        show: () => {
          document
            .querySelector(".shepherd-modal-overlay-container")
            .classList.add("shepherd-modal-is-visible");
        },
        cancel: () => closeTour(),
      },
    },
    {
      title: "<h4>Profile Setting</h4>",
      text: '<p className="mb-0">Configure your Profile using Profile Settings. Edit, save and update your profile from here.</p>',
      attachTo: { element: ".iq-tour ", on: "bottom" },
      buttons: [
        {
          type: "back",
          classes: "shepherd-button-secondary",
          text: "Back",
        },
        {
          type: "next",
          text: "Next",
        },
      ],
      when: {
        cancel: () => closeTour(),
      },
    },
    {
      title: "<h4>Live Customizer</h4>",
      text: '<p className="mb-0">Transform the entire look, color, style and appearance of using Live Customizer settings. Change and copy the settings from here.</p>',
      attachTo: { element: ".btn-setting", on: "left" },
      buttons: [
        {
          type: "back",
          classes: "shepherd-button-secondary",
          text: "Back",
        },
        {
          action() {
            sessionStorage.setItem("tour", "true");
            return this.next();
          },
          text: "Done",
        },
      ],
      when: {
        cancel: () => closeTour(),
      },
    },
  ];
  const tourOptions = {
    defaultStepOptions: {
      cancelIcon: {
        enabled: true,
      },
    },
    when: {
      cancel: function () { },
    },
  };
  const pageLayout = useSelector(SettingSelector.page_layout)
  return (
    <Fragment>
      {isLoading && <Loader />}
      <ShepherdTour steps={newSteps} tourOptions={tourOptions}>
        <Tour />
        <div className="wrapper">
          <SidebarStyle />
          <main className="main-content">
            <div className="position-relative">
              <HeaderStyle />
              {props.isBanner === "true" ? <Subheader /> : ""}
            </div>
            <div className={` ${pageLayout} content-inner pb-0`}>
              <Suspense fallback={<Loader />}>
                <Outlet />
              </Suspense>
            </div>
            <FooterStyle />
          </main>
        </div>
        <SettingOffCanvas />
      </ShepherdTour>
    </Fragment>
  );
});

DashboardLayout.displayName = "DashboardLayout";
export default DashboardLayout;
