// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/BlogPages/BlogSingle.vue
<template>
  <div class="section-padding blog-section">
    <b-container>
      <b-row>
        <b-col cols="12">
          <div v-if="type !== 'single'" class="iq-blogs-meta">
            <ul class="iq-blogtag list-inline d-flex align-items-center flex-wrap mb-0">
              <li class=""><i class="ph ph-user" aria-hidden="true"></i><router-link to="/blogs-author" class="">
                  Jenny</router-link></li>
              <li class=""><i class="icon icon-calendar-2" aria-hidden="true"></i><router-link to="/blogs-date">
                  January 30, 2019</router-link></li>
              <li class=""><router-link to="/blogs-tag" class="">DRAMAS</router-link>,</li>
              <li class=""><router-link to="/blogs-tag" class=""> Historical</router-link>,</li>
              <li class="">
                <router-link to="/blogs-tag" class="">{{ $t('streamShop.uncategorized') }}</router-link>
              </li>
            </ul>
          </div>
          <h3 v-if="type !== 'single'" class="mb-3">
            {{ $t(blogTitle) }}
          </h3>
          <div class="iq-blog-detail">
            <template v-if="type === 'single'">
              <a class="blog-image d-block overflow-hidden">
                <img class="img-fluid w-100 mb-5" src="/assets/images/blog/blog1.webp" loading="lazy" alt="img" />
              </a>
            </template>

            <template v-else-if="type === 'audio'">
              <div>
                <iframe height="200" class="w-100" frameborder="no"
                  src="https://w.soundcloud.com/player/?visual=false&amp;url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F36701924&amp;show_artwork=true&amp;maxheight=750&amp;maxwidth=720&amp;auto_play=false&amp;buying=true&amp;liking=true&amp;download=true&amp;sharing=true&amp;show_comments=true&amp;show_playcount=true&amp;show_user=true&amp;color"></iframe>
              </div>
            </template>

            <template v-else-if="type === 'video'">
              <div>
                <iframe class="w-100" height="490" src="https://www.youtube.com/embed/QCGq1epI9pQ"
                  title="Streamit Intro | ULTIMATE OTT Theme &amp; App for WordPress | Iqonic Design"
                  style="border: none"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                  allowfullscreen></iframe>
              </div>
            </template>

            <template v-else-if="type === 'gallery'">
              <b-row class="row-cols-xl-3 row-cols-md-2 row-cols-1">
                <b-col v-for="(item, index) in gallery" :key="index" :class="item.class">
                  <a data-fslightbox="gallery" :href="item.img">
                    <img :src="item.img" :alt="index" />
                  </a>
                </b-col>
              </b-row>
            </template>

            <template v-if="type === 'link'">
              <div class="mb-4">
                <router-link to="https://iqonic.design/">
                  <i class="ph ph-link text-primary quote-icon"></i>
                </router-link>
              </div>
            </template>
            <template v-if="type === 'quote'">
              <blockquote class="block-quote py-5 mb-3">
                <b-row class="align-items-start">
                  <b-col lg="1" md="2">
                    <div class="blockquote-icon">
                      <i class="ph-fill ph-quotes text-primary" aria-hidden="true"></i>
                    </div>
                  </b-col>
                  <b-col lg="11" md="10">
                    <div class="p-2">
                      <p class="mb-0 blog-gallery-desc">{{ $t('streamBlog.quotes') }}</p>
                      <cite><a href="#">{{ $t('streamBlog.quotes_author') }}</a></cite>
                    </div>
                  </b-col>
                </b-row>

              </blockquote>
            </template>

            <div class="iq-blog-box border-0">
              <div v-if="type === 'single'" class="iq-blogs-meta">
                <ul class="iq-blogtag list-inline d-flex align-items-center flex-wrap mb-0">
                  <li class=""><i class="ph ph-user" aria-hidden="true"></i><router-link to="/blogs-author" class="">
                      Jenny</router-link></li>
                  <li class=""><i class="icon icon-calendar-2" aria-hidden="true"></i><router-link to="/blogs-date">
                      January 30,
                      2019</router-link></li>
                  <li v-for="(category, index) in categories" :key="index">
                    <router-link to="/blogs-tag">{{ $t(category) }}</router-link>
                    <span v-if="index < categories.length - 1">,</span>
                  </li>
                </ul>
              </div>
              <h3 v-if="type === 'single'" class="mb-3">
                {{ $t(blogTitle) }}
              </h3>
              <h6 class="text-white my-3">{{ $t('streamBlog.blog2_desc') }}</h6>
              <p class="mb-0 blog-gallery-desc">{{ $t('streamBlog.blog3_desc') }}</p>
              <p class="blog-gallery-desc">{{ $t('streamBlog.blog4_desc') }}</p>

              <blockquote class="block-quote text-white py-2">
                <p class="mb-0 blog-gallery-desc">{{ $t('streamBlog.quotes') }}</p>
                <cite><a href="#">{{ $t('streamBlog.quotes_author') }}</a></cite>
              </blockquote>
              <p class="mb-0 blog-gallery-desc">{{ $t('streamBlog.blog7_desc') }}</p>
              <p class="mb-0 blog-gallery-desc">{{ $t('streamBlog.blog8_desc') }}
              </p>
              <p class="blog-gallery-desc">{{ $t('streamBlog.blog7_desc') }}</p>

              <ul class="iq-blogtag p-0 m-0 list-unstyled gap-2 widget_tags widget-tags-product">
                <li>
                  <router-link to="/blogs-tag" class="position-relative">{{ $t('streamTag.comedy') }}</router-link>
                </li>
                <li>
                  <router-link to="/blogs-tag" class="position-relative">{{ $t('streamTag.drama') }}</router-link>
                </li>
                <li>
                  <router-link to="/blogs-tag" class="position-relative">{{ $t('streamPages.movie') }}</router-link>
                </li>
                <li>
                  <router-link to="/blogs-tag"
                    class="position-relative">{{ $t('streamBlogCategory.trailer') }}</router-link>
                </li>
              </ul>

              <div class="iq-blog-tag">
                <div class="blog-nav row mt-3 mt-md-0 mb-5 mb-lg-0">
                  <div class="blog-prev-post col-6">
                    <router-link :to="{ name: 'landing-page.blogs.single', params: { type: 'single' } }">
                      <span class="fw-semibold d-none d-md-block">{{ $t('streamForm.amy_admas') }} </span>
                      <div class="blog-arrow mt-3 d-flex align-items-center">
                        <i class="ph ph-arrow-left"></i>
                        <span class="previous fw-semibold fst-italic"> {{ $t('streamForm.previous_post') }}</span>
                      </div>
                    </router-link>
                  </div>
                  <div class="blog-next-post col-6 text-end">
                    <router-link :to="{ name: 'landing-page.blogs.single', params: { type: 'audio' } }">
                      <span class="fw-semibold d-none d-md-block">{{ $t('streamForm.gillian_shares') }}</span>
                      <div class="blog-arrow mt-3 d-flex align-items-center justify-content-end">
                        <span class="next fw-semibold fst-italic"> {{ $t('streamForm.next_post') }}</span>
                        <i class="ph ph-arrow-right"></i>
                      </div>
                    </router-link>
                  </div>
                </div>
                <h3 class="comments-title mb-4 pb-2">
                  <span>0 {{ $t('streamBlog.comments') }}</span>
                </h3>
                <h3 class="mb-4">{{ $t('streamForm.leave_reply') }}</h3>
                <form>
                  <p class="mb-5">{{ $t('streamAccount.logged_jenny') }} <router-link
                      to="/my-account">{{ $t('streamForm.edit_profile') }} </router-link>
                    {{ $t('streamShop.required_fields') }} *</p>
                  <div class="pt-3">
                    <b-row>
                      <b-col md="12">
                        <textarea class="form-control rounded-3" name="comment" cols="5" rows="8" required=""
                          :placeholder="$t('streamBlog.comment') + '*'"></textarea>
                      </b-col>
                    </b-row>

                    <b-col md="12">
                      <div class="form-submit mt-5">
                        <button id="submit" name="submit" type="submit"
                          class="btn btn-primary position-relative rounded-3" value="Submit">
                          <span class="button-text">{{ $t('streamForm.post_comment') }}</span>
                        </button>
                      </div>
                    </b-col>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { useRoute } from 'vue-router';
// import VideoPlayer from '../../components/plugins/VideoPlayer.vue';
import { blogs } from '../../StaticData/blogs';
import { generateImgPath } from '../../StaticData/data';

const route = useRoute();

const type = computed(() => route.params.type);
const slug = computed(() => route.params.slug);
const blog = computed(() => blogs.find((item) => item.slug === slug.value));

// const playerOption = {
//   autoplay: false,
//   controls: true,
//   techOrder: ['youtube'],
//   sources: [
//     {
//       src: 'https://www.youtube.com/watch?v=QCGq1epI9pQ',
//       type: 'video/youtube',
//     },
//   ],
//   youtube: { iv_load_policy: 1 },
// };

const gallery = [
  {
    img: generateImgPath('/assets/images/blog/blog1.webp'),
    class: 'mb-4',
  },
  {
    img: generateImgPath('/assets/images/blog/blog2.webp'),
    class: 'mb-4',
  },
  {
    img: generateImgPath('/assets/images/blog/blog3.webp'),
    class: 'mb-4',
  },
  {
    img: generateImgPath('/assets/images/blog/blog4.webp'),
    class: 'mb-4 mb-md-0',
  },
  {
    img: generateImgPath('/assets/images/blog/blog5.webp'),
    class: 'mb-4 mb-md-0',
  },
  {
    img: generateImgPath('/assets/images/blog/blog6.webp'),
    class: '',
  },
];

const blogTitle = computed(() => {
  if (blog.value?.blogTitle) return blog.value.blogTitle;

  switch (type.value) {
    case 'single':
      return 'streamBlog.blog1';
    case 'audio':
      return 'streamBlog.blog15';
    case 'video':
      return 'streamBlog.blog10';
    case 'link':
      return 'streamBlog.blog8';
    case 'quote':
      return 'streamBlog.blog9';
    case 'gallery':
      return 'streamBlog.blog10';
    default:
      return 'Blog not found';
  }
});
const categories = [
  'streamBlogCategory.drama',
  'streamBlogCategory.history',
  'streamShop.uncategorized'
];
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/BlogPages/BlogSingle.jsx
import React, { Fragment, memo } from "react";

//react-bootstrap
import { Col, Container, Row } from "react-bootstrap";

//react-router-dom
import { useParams, Link } from "react-router-dom";

//static Data
import { blogs } from "../../StaticData/blogs";

//components
import FormWidget from "../../components/blog/FormWidget";
import BreadCrumbWidget from "../../components/BreadcrumbWidget";

//function
import { generateImgPath } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const AudioBlog = memo(() => {
  const { t } = useTranslation();
  let title, data, date;
  const { type } = useParams();
  const slug = "the-most-anticipated-movies";
  const blog = blogs.find((item) => item.slug === slug);

  const audio_data = ["streamTag.drama", "streamBlogTag.history", "streamShop.uncategorized"];

  switch (type) {
    case "audio":
      title = "streamBlog.blog8";
      data = audio_data;
      date = "February 2, 2019";
      break;
    case "video":
      title = "streamBlog.blog7";
      data = audio_data;
      date = " January 30, 2019";
      break;
    case "link":
      title = "streamBlog.blog8";
      data = audio_data;
      date = " January 30, 2019";
      break;
    case "quote":
      title = "streamBlog.blog9";
      data = audio_data;
      date = " January 30, 2019";
      break;
    case "gallery":
      title = "streamBlog.blog10";
      data = audio_data;
      date = "January 30, 2019";
      break;
    default:
      break;
  }
  const gallery = [
    {
      img: generateImgPath("/assets/images/blog/blog1.webp"),
      class: "mb-4",
    },
    {
      img: generateImgPath("/assets/images/blog/blog2.webp"),
      class: "mb-4",
    },
    {
      img: generateImgPath("/assets/images/blog/blog3.webp"),
      class: "mb-4",
    },
    {
      img: generateImgPath("/assets/images/blog/blog4.webp"),
      class: "mb-4 mb-md-0",
    },
    {
      img: generateImgPath("/assets/images/blog/blog5.webp"),
      class: "mb-4 mb-md-0",
    },
    {
      img: generateImgPath("/assets/images/blog/blog6.webp"),
      class: "",
    },
  ];

  const playerRef = React.useRef(null);

  const videoJsOptions = {
    autoplay: false,
    controls: true,
    responsive: true,
    techOrder: ["youtube"],
    sources: [
      {
        src: "https://www.youtube.com/watch?v=QCGq1epI9pQ",
        type: "video/youtube",
      },
    ],
    youtube: { iv_load_policy: 1 },
  };

  const handlePlayerReady = (player) => {
    playerRef.current = player;

    // You can handle player events here, for example:
    player.on("waiting", () => {
      videojs.log("player is waiting");
    });

    player.on("dispose", () => {
      videojs.log("player will dispose");
    });
  };

  let category_data =
    (data !== undefined && data !== null && data) || blog.category;
  let blog_date = date || blog.blogDate;

  return (
    <Fragment>
      <BreadCrumbWidget title={t(title)} class={false} />
      <div className="section-padding blog-single blog-section">
        <Container>
          <Row>
            <Col sm="12">
              <div className="iq-blogs-meta ">
                <ul className="iq-blogtag list-inline mb-0 d-flex align-items-center flex-wrap">
                  <li className="posted-by">
                    <span className="post-date d-flex align-items-center gap-1">
                      <i className="ph ph-user"></i>
                      <Link to="/blogs-tag">{t(blog.username)}</Link>{" "}
                    </span>
                  </li>{" "}
                  <li className="posted-on">
                    <span className="post-author d-flex align-items-center gap-1">
                      <i className="icon icon-calendar-2"></i>
                      <Link to="/blog-date">
                        <span>{blog_date}</span>
                      </Link>
                    </span>
                  </li>{" "}
                  {category_data !== undefined &&
                    category_data !== null &&
                    category_data.map((categories, index) => {
                      return (
                        <li className="blog-category" key={index}>
                          <Link to="/blogs-tag">{t(categories)},</Link>
                        </li>
                      );
                    })}
                </ul>
              </div>
              <h3 className="mb-3">
                {type === "audio" && t("streamBlog.blog15")}
                {type === "video" && t("streamBlog.blog10")}
                {type === "gallery" && t("streamBlog.blog10")}
                {type === "link" && t("streamBlog.blog8")}
                {type === "quote" && t("streamBlog.blog9")}
              </h3>
              <div className="iq-blog blog-detail">
                {type === "audio" ? (
                  <div>
                    <iframe
                      height="200"
                      className="w-100"
                      frameBorder="no"
                      src="https://w.soundcloud.com/player/?visual=false&amp;url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F36701924&amp;show_artwork=true&amp;maxheight=750&amp;maxwidth=720&amp;auto_play=false&amp;buying=true&amp;liking=true&amp;download=true&amp;sharing=true&amp;show_comments=true&amp;show_playcount=true&amp;show_user=true&amp;color"
                    ></iframe>
                  </div>
                ) : type === "video" ? (
                  <div>
                    {/* <VideoJS
                      options={videoJsOptions}
                      onReady={handlePlayerReady}
                    /> */}
                    <iframe className="w-100" height="490" src="https://www.youtube.com/embed/QCGq1epI9pQ"
                      title="Streamit Intro | ULTIMATE OTT Theme &amp; App for WordPress | Iqonic Design"
                      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                      allowFullScreen></iframe>
                  </div>
                ) : type === "gallery" ? (
                  <Row className="row-cols-xl-3 row-cols-md-2 row-cols-1">
                    {gallery.map((item, index) => {
                      return (
                        <Col className={item.class} key={index}>
                          <Link to="">
                            <img src={item.img} alt={index} />
                          </Link>
                        </Col>
                      );
                    })}
                  </Row>
                ) : (
                  ""
                )}
                <div className="iq-blog-box">
                  {type === "link" ? (
                    <div className="mb-4">
                      <Link to="https://iqonic.design/">
                        <i className="ph ph-link text-primary quote-icon"></i>
                      </Link>
                    </div>
                  ) : type === "quote" ? (


                    <blockquote className="block-quote py-5 mb-3">
                      <Row className="align-items-start">
                        <Col md={2} lg={1}>
                          <div className="blockquote-icon">
                            <i className="ph-fill ph-quotes text-primary" aria-hidden="true"></i>
                          </div>
                        </Col>
                        <Col md={10} lg={11}>
                          <div className="p-2">
                            <p className="mb-0 blog-gallery-desc">”{t("streamBlog.quotes")}”</p>
                            <cite><a href="#">{t("streamBlog.quotes_author")}</a></cite>
                          </div>
                        </Col>
                      </Row>

                    </blockquote>
                  ) : (
                    ""
                  )}
                  <div className="iq-blog-box border-0">
                    {/* Meta */}
                    {type === "single" && (
                      <div className="iq-blogs-meta">
                        <ul className="iq-blogtag list-inline d-flex align-items-center flex-wrap mb-0">
                          <li>
                            <i className="ph ph-user" aria-hidden="true"></i>
                            <Link to="/blogs-tag">Jenny</Link>
                          </li>
                          <li>
                            <i className="icon icon-calendar-2" aria-hidden="true"></i>
                            <Link to="/blogs-date">January 30, 2019</Link>
                          </li>
                          {categories.map((category, index) => (
                            <li key={index}>
                              <Link to="/blogs-date">{t(category)}</Link>
                              {index < categories.length - 1 && <span>,</span>}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Title */}
                    {type === "single" && <h3 className="mb-3">{t(blogTitle)}</h3>}

                      <div className="iq-blog-box ">
                         <div>
                          <h6 className="text-white my-3">{t("streamBlog.blog2_desc")}</h6>
                          <p className="mb-0 blog-gallery-desc">{t("streamBlog.blog3_desc")}</p>
                          <p className="blog-gallery-desc">{t("streamBlog.blog4_desc")}</p>

                          <blockquote className="block-quote text-white py-2">
                            <p className="mb-0 blog-gallery-desc">{t("streamBlog.quotes")}</p>
                            <cite>
                              <a href="#">{t("streamBlog.quotes_author")}</a>
                            </cite>
                          </blockquote>

                          <p className="mb-0 blog-gallery-desc">{t("streamBlog.blog7_desc")}</p>
                          <p className="mb-0 blog-gallery-desc">{t("streamBlog.blog8_desc")}</p>
                          <p className="blog-gallery-desc">{t("streamBlog.blog7_desc")}</p>
                        </div>
                        {blog.tags !== undefined &&
                          blog.tags !== null && (
                            <ul className="iq-blogtag p-0 m-0 list-unstyled gap-2 widget_tags widget-tags-product text-capitalize">
                              {blog.tags.map((tags, index) => {
                                return (
                                  <li key={index}>
                                    <Link
                                      to="/blogs-tag"
                                      className="position-relative"
                                    >
                                      {t(tags)}
                                    </Link>
                                  </li>
                                );
                              })}
                            </ul>
                          )}
                        <div className="iq-blog-tag ">
                          <FormWidget></FormWidget>
                        </div>
                      </div>
                  </div>
                </div>
              </div>
            </Col>

          </Row>
        </Container>
      </div>
    </Fragment>
  );
});

export default AudioBlog;
