// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/BlogPages/GridList.vue
<template>
  <div class="blog-column-pages section-padding">
    <b-container>
      <b-row :class="rowClass">
        <b-col v-for="blog in selectedBlogs" :key="blog.id" :lg="column" sm="12">
          <card-blog-list
            :id="blog.id"
            :thumbnail="blog.thumbnail"
             :username="$t(blog.username)"
            :slug="blog.slug"
            :blog-title="$t(blog.title)"
            :blog-text="$t(blog.description)"
            :blog-tag="blog.tags"
            :blog-date="blog.blogDate"
            :link-button="true"
            :categories-list="blog.category"
            :right-icon="true"
          />
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue';
import CardBlogList from '../../components/cards/CardBlogList.vue';
import { useRoute } from 'vue-router';
import { blogsGrid } from '../../StaticData/blogs';
const route = useRoute();
const column = ref(12);
const title = ref('');

const changeGridColumn = (gridType) => {
  switch (gridType) {
    case 'one-column':
      column.value = 12;
      title.value = 'streamPages.1_column_blog';
      break;
    case 'two-column':
      column.value = 6;
      title.value = 'streamPages.2_column_blog';
      break;
    case 'three-column':
      column.value = 4;
      title.value = 'streamPages.3_column_blog';
      break;
    case 'four-column':
      column.value = 3;
      title.value = 'streamPages.4_column_blog';
      break;
    default:
      column.value = 12;
      title.value = 'streamPages.1_column_blog';
  }
};

// Initial call
changeGridColumn(route.params.grid);

// Watch for route param changes
watch(
  () => route.params.grid,
  (gridType) => {
    changeGridColumn(gridType);
  }
);

// Dynamically select the correct blog grid
const selectedBlogs = computed(() => {
  if (column.value === 12) return blogsGrid;
  if (column.value === 6) return blogsGrid;
  if (column.value === 3) return blogsGrid;
  return blogsGrid; // Default fallback
});

// Dynamic row class
const rowClass = computed(() => {
  if (column.value === 12) return 'row-cols-1';
  if (column.value === 6) return 'row-cols-lg-2 row-cols-md-2';
  if (column.value === 4) return 'row-cols-xl-3 row-cols-md-3';
  return 'row-cols-lg-4 row-cols-md-4';
});
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/BlogPages/GridList.jsx
import { blogs } from "../../StaticData/blogs";
import React, { Fragment, memo } from "react";

//react-bootstrap
import { Row, Col, Container } from "react-bootstrap";

//react-router-dom
import { Link, useParams } from "react-router-dom";

//component
import CardBlogGrid from "../../components/cards/CardBlogGrid";
import BreadCrumbWidget from "../../components/BreadcrumbWidget";

//static data

// the hook
import { useTranslation } from "react-i18next";

const BlogGrid = memo(() => {
  const { t } = useTranslation();
  const { grid } = useParams();
  let _column, title, data;
  switch (grid) {
    case "single":
      _column = "12";
      title = "streamPages.1_column_blog";
      break;
    case "double":
      _column = "6";
      title = "streamPages.2_column_blog";
      break;
    case "large-grid":
      _column = "4";
      title = "streamPages.3_column_blog";
      break;
    case "small-grid":
      _column = "3";
      title = "streamPages.4_column_blog";
      break;
    default:
      break;
  }

  const grid_data = data !== undefined && data !== null ? data.slice(0 , 10) : blogs.slice(0, 9)

  return (
    <Fragment>
      <BreadCrumbWidget title={t(title)} />
      <div className="blog-column-pages section-padding">
        <Container>
          <Row>
            {grid_data.map((item, index) => {
              return (
                <Col lg={_column} md={_column} sm="12" key={index}>
                  <CardBlogGrid
                    title={t(item.title)}
                    slug={item.slug}
                    thumbnail={item.thumbnail}
                    description={t(item.description)}
                    username={t(item.username)}
                    blogDate={item.blogDate}
                    categories={t(item.categories)}
                    link_button={true}
                    button_icon={true}
                  ></CardBlogGrid>
                </Col>
              );
            })}
          </Row>
          <div className="iq-button text-center mt-3">
            <Link
              to="#"
              className="btn btn-primary text-capitalize position-relative rounded-3"
            >
              <span className="button-text">{t("streamButtons.load_more")} </span>
            </Link>
          </div>
        </Container>
      </div>
    </Fragment>
  );
});

BlogGrid.displayName = "BlogGrid";
export default BlogGrid;
