// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/BlogPages/ListPage.vue
<template>
  <div class="blog-listning section-padding">
    <b-container>
      <b-row>
        <b-col lg="8" sm="12">
          <article v-for="blog in blogs" :key="blog.id">
            <card-blog-list :id="blog.id" :thumbnail="blog.thumbnail" :slug="blog.slug" :blog-title="$t(blog.title)" :username="$t(blog.username)"
              :blog-text="$t(blog.description)" :blog-tag="blog.blogTag" :blog-tag-icon="blog.blogTagIcon"
              :blog-date="blog.blogDate" :blog-categories="blog.categories" :blog-tags="blog.blogTags"
              :link-button="true" :right-icon="true" :categories-list="blog.category"
              :tag-list="blog.tagList" />

          </article>
        </b-col>
        <b-col lg="4" sm="12">
          <DetailMetaList />
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script setup>
import DetailMetaList from '../../components/blog/DetailMetaList.vue';
import CardBlogList from '../../components/cards/CardBlogList.vue';
import { blogs } from '../../StaticData/blogs';
// console.log(blogs);
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/BlogPages/ListPage.jsx
import React, { Fragment, memo } from "react";

//react bootstrap
import { Container, Row, Col } from "react-bootstrap";

//components
import CardBlogList from "../../components/cards/CardBlogList";
import DetailMetaList from "../../components/blog/DetailMetaList";
import BreadCrumbWidget from "../../components/BreadcrumbWidget";

//static data
import { blogs } from "../../StaticData/blogs";

// the hook
import { useTranslation } from "react-i18next";

const BlogList = memo((props) => {
  // console.log(props.title)
  const { t } = useTranslation();
  return (
    <Fragment>
      <BreadCrumbWidget title={t(props.title)} />
      <div className=" section-padding">
        <Container>
          <Row className="gy-5">
            <Col lg="8" sm="12">
              {blogs.slice(0, 14).map((item, index) => {
                return (
                  <div className="blog-custom-box" key={index}>
                    <CardBlogList
                      slug={item.slug}
                      title={t(item.title)}
                      thumbnail={item.thumbnail}
                      blogDate={item.blogDate}
                      username={t(item.username)}
                      categories={t(item.categories)}
                      tags={item.tags}
                      category={item.category}
                      description={t(item.description)}
                      link_button={true}
                      button_icon={true}
                    />
                  </div>
                );
              })}
            </Col>
            <Col lg="4" sm="12">
              <DetailMetaList></DetailMetaList>
            </Col>
          </Row>
        </Container>
      </div>
    </Fragment>
  );
});

BlogList.displayName = "BlogList";
export default BlogList;
