// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/sections/LatestMovies.jsx
import { Fragment, useState } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../../components/cards/CardStyle";

//static data
import { latestMovie } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const LatestMovies = (props) => {
  const { t } = useTranslation();

  return (
    <Fragment>
      <SectionSlider
        title={t("sectionTitle.latest_movies")}
        list={latestMovie}
        className="latest-block streamit-block"
        slidesPerView="6"
        paddingY={props.paddingY}
        loop={true}
        viewAll={props.viewAll}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            lang={data.lang}
            slug={data.slug}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
};

LatestMovies.DisplayName = LatestMovies;
export default LatestMovies;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/sections/LatestMovies.vue
  <template>
  <!-- Latest Movies start -->
  <SectionSlider :title="$t(title)" :list="sliderData" :slides-per-view="6" class="latest-block section-wraper streamit-block" margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <router-link :to="{ name: 'landing-page.view-all' }" class="text-primary iq-view-all text-decoration-none flex-none">{{ $t('sectionTitle.view_all') }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :title="$t(data.title)" :lang="$t(data.lang)" :watchlist-link="{ path: '/playlist' }" :link="{ path: '/movies-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Latest Movies end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';

import { latestMovie } from '../../StaticData/data';
const title = ref('sectionTitle.latest_movies');
const sliderData = ref(latestMovie);
</script>
