// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/sections/OnlyOnStreamit.jsx
import { memo, Fragment, useState } from "react";

//component
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../../components/cards/CardStyle";

//static data
import { sectionSliders } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const OnlyOnStreamit = memo(() => {
  const { t } = useTranslation();
  const [onlyonstreamit] = useState(sectionSliders);
  return (
    <Fragment>
      <SectionSlider
        title={t("sectionTitle.only_on_streamit")}
        list={onlyonstreamit}
        className="streamit-block"
        loop={true}
        paddingY="my-4"
        slidesPerView="6"
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            slug={data.slug}
            movieTime={t(data.movieTime)}
            lang={data.lang}
            productPremium={data.productPremium}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

OnlyOnStreamit.displayName = "OnlyOnStreamit";
export default OnlyOnStreamit;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/sections/OnlyOnStreamit.vue
<template>
  <!-- Only on streamit start -->
  <SectionSlider :title="$t(title)" :list="topTen" :slides-per-view="6" :loop="false" class="streamit-block" margin-padding="px-1 mb-4">
    <template #headerLink>
      <router-link to="/view-all" class="text-primary iq-view-all text-decoration-none flex-none">{{ $t('sectionTitle.view_all') }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :product-premium="data.productPremium" :lang="data.lang" :title="$t(data.title)" :watchlist-link="{ path: '/playlist' }" :link="{ path: '/movies-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Only on streamit end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';

import { sectionSliders } from '../../StaticData/data';
const title = ref('sectionTitle.only_on_streamit');
const topTen = ref(sectionSliders);
</script>
