// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/sections/PopularVideos.tsx
import { useState, Fragment, memo } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { popular_videos, populerSlider } from "../../StaticData/data";

//hook
import { useTranslation } from 'react-i18next';
// import CardStyleTwo from "../cards/CardStyleTwo";
interface Props {
  link ?: string,
  viewAll ?: boolean
}

const PopularVideos = memo((props:Props) => {
  const { t } = useTranslation("common");


  return (
    <Fragment>
      <SectionSlider
        title={t("sectionTitle.popular_videos")}
        list={popular_videos}
        className="recommended-block section-top-spacing"
        wrapperClass={true}
        viewAll={props.viewAll}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            watchlistLink="/play-list"
            link={props.link || "/movies/detail"}
            conturyname={data.conturyname}
            slug={data.slug}
            lang={data.lang}
            playNowLink={data.playNowLink || "/"}
            productPremium={data.productPremium}
          />
        )}
      </SectionSlider>
    </Fragment>
  );
})

PopularVideos.displayName = 'PopularVideos';
export default PopularVideos;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/sections/PopularVideos.vue
<template>
  <!-- Popular Videos start -->
  <SectionSlider :title="$t(title)" :list="popular_videos" :slides-per-view="6" class="recommended-block section-top-spacing streamit-block" margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <router-link :to="{ name: 'landing-page.view-all' }" class="text-primary iq-view-all text-decoration-none flex-none">{{ $t('sectionTitle.view_all') }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :title="$t(data.title)" :product-premium="data.productPremium" :lang="data.lang" :watchlist-link="{ path: '/' }" :link="{ path: '/movies-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Popular Videos end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { popular_videos } from '../../StaticData/data';
const title = ref('sectionTitle.popular_videos');
</script>
