// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/sections/RecommendedTVShow.jsx
import { Fragment, memo, useState } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../../components/cards/CardStyle";

//static data
import { recommendedforYou } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const RecommendedTVShow = memo((props) => {
  const { t } = useTranslation();

  return (
    <Fragment>
      <SectionSlider
        title={t("sectionTitle.recommended_tv_show")}
        list={recommendedforYou}
        className="recommended-block streamit-block"
        slidesPerView="6"
        paddingY={props.paddingY}
        loop={true}
        viewAll={props.viewAll}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            lang={data.lang}
            slug={data.slug}
            productPremium={data.productPremium}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

RecommendedTVShow.DisplayName = RecommendedTVShow;
export default RecommendedTVShow;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/sections/RecommendedTVShow.vue
<template>
  <!-- Recommended TV Show start -->
  <SectionSlider
:title="$t(title)" :list="topTen" :slides-per-view="6" class="recommended-blocks section-wrape streamit-block"
    margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <router-link
:to="{ name: 'landing-page.view-all' }"
        class="text-primary iq-view-all text-decoration-none flex-none">{{ $t('sectionTitle.view_all') }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style
        :image="data.image"
        :title="$t(data.title)"
        :product-premium="data.productPremium" 
        :lang="$t(data.lang)"
        :watchlist-link="{ path: '/playlist' }"
        :link="{ path: '/movies-detail' }">
      </card-style>
    </template>
  </SectionSlider>
  <!-- Recommended TV Show end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';

import { recommendedforYou } from '../../StaticData/data';
const title = ref('sectionTitle.recommended_tv_show');
const topTen = ref(recommendedforYou);
</script>
