// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/sections/Specials&LatestVideos.jsx
import { useState, Fragment, memo } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { latestMovie } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const SpecialsLatestVideos = memo((props) => {
  const { t } = useTranslation();

  return (
    <Fragment>
      <SectionSlider
        title={t("sectionTitle.specials_latest_videos")}
        list={props.data}
        className="latest-block streamit-block"
        slideMedium={props.slideMedium}
        paddingY={props.paddingY}
        loop={true}
        viewAll={props.viewAll}
        slidesPerView={props.slides || 6}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={data.title}
            movieTime={data.movieTime}
            slug={data.slug}
            lang={data.lang}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

SpecialsLatestVideos.displayName = "SpecialsLatestVideos";
export default SpecialsLatestVideos;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/sections/Specials&LatestVideos.vue
<template>
  <!-- Specials & Latest Movies start -->
  <SectionSlider :title="$t(title)" :list="latestVideo" :slides-per-view="6" class="recommended-block section-top-spacing section-wraper streamit-block" margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <router-link :to="{ name: 'landing-page.view-all' }" class="text-primary iq-view-all text-decoration-none">{{ $t('sectionTitle.view_all') }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :title="$t(data.title)" :product-premium="data.productPremium" :lang="data.lang" :watchlist-link="{ path: '/playlist' }" :link="{ path: '/movies-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Specials & Latest Movies end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { latestVideo } from '../../StaticData/data';
const title = ref('sectionTitle.specials_latest_videos');
</script>
