// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/sections/TVPopularShows.jsx
import { useState, Fragment, memo } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { populerSlider } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";
import Card_Style_Two from "../cards/CardStyleTwo";

const TVPopularShows = memo((props) => {
  const { t } = useTranslation();

  const data = props.data !== undefined && props.data !== null ? props.data : populerSlider
  const loop = props.loop !== undefined && props.loop !== null ? props.loop : true

  return (
    <Fragment>
      <SectionSlider
        title={t("sectionTitle.tv_popular_shows")}
        list={data}
        className="recommended-block section-top-spacing"
        wrapperClass={true}
        slideMedium={props.slideMedium}
        paddingY={props.paddingY}
        loop={loop}
        slidesPerView={props.slides || 6}
      >
        {(data) => (
          <Card_Style_Two
            image={data.image}
            title={data.title}
            movieTime={data.movieTime}
            slug={data.slug}
            lang={data.lang}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

TVPopularShows.displayName = TVPopularShows;
export default TVPopularShows;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/sections/TVPopularShows.vue
<template>
  <!-- Only on streamit start -->
  <SectionSlider :title="$t(title)" :list="topTen" :slides-per-view="6" :loop="false" class="recommended-block section-top-spacing section-wraper streamit-block" margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <router-link to="/view-all" class="text-primary iq-view-all text-decoration-none flex-none">{{ $t('sectionTitle.view_all') }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style :is-card-style2="true" :image="data.image" :product-premium="data.productPremium" :is-not-lang-card="true" :title="$t(data.title)" :watchlist-link="{ path: '/playlist' }" :link="{ path: '/tv-show-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Only on streamit end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';

import { popular_tv_show } from '../../StaticData/data';
const title = ref('sectionTitle.tv_popular_shows');
const topTen = ref(popular_tv_show);
</script>
