// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/cast/all-personality.vue
<template>
  <section class="section-padding">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12 my-4">
          <div class="d-flex align-items-center justify-content-between">
            <h5 class="main-title text-capitalize mb-0">
              favourite-personality
            </h5>
          </div>
        </div>
      </div>
      <b-row class="row row-cols-xl-5 row-cols-md-2 row-cols-1 personality-card">
        <b-col v-for="data in cast.slice(0, 14)" :key="data" class="mb-4">
          <cast-card :title="data.title" :designation="data.designation" :image="data.profile_image"></cast-card>
        </b-col>
      </b-row>
    </div>
  </section>
</template>
<script setup>
//components
import CastCard from "~/components/cards/CastCard.vue";

//data
import { cast } from "../../StaticData/data";

//custom hook
import { useBreadcrumb } from "~/utilities/usePage";

useBreadcrumb("sectionTitle.view_all");
</script>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/(frontend-pages)/cast/all-personality/page.tsx
"use client"

import React, { Fragment, memo } from 'react'

//react-bootstrap
import { Col, Container, Row } from 'react-bootstrap'

//component
import PersonalityCard from '@/components/cards/PersonalityCard'

//custom hooks
import { useBreadcrumb } from '@/utilities/usePage'
import { useTranslation } from 'react-i18next';

const AllPersonality = memo(() => {
    const { t } = useTranslation("common");

    useBreadcrumb('View All')
    return (
        <Fragment>
            <div className='section-padding'>
                <Container fluid>
                    <Row >
                        <Col sm="12" className="my-4">
                            <div className="d-flex align-items-center justify-content-between">
                                <h4 className="main-title text-capitalize mb-0">favourite-personality</h4>
                            </div>
                        </Col>
                    </Row>
                    <div className="card-style-grid">
                        <Row xl="5" md="2" className="row-cols-1 personality-card">
                            {cast.map((item, index) => {
                                return (
                                    <Col className="mb-4" key={index}>
                                            <PersonalityCard image={item.thumbnail} title={item.name} category={item.category} categoryLink={''} link={""}/>
                                    </Col>
                                )
                            })}
                        </Row>
                    </div>
                </Container>
            </div>
        </Fragment>
    )
})

AllPersonality.displayName = "AllPersonality"
export default AllPersonality
