// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/BreadcrumbWidget.vue
<template>
  <div class="iq-breadcrumb">
    <b-container>
      <b-row class="align-items-center">
        <b-col sm="12">
          <nav aria-label="breadcrumb" class="text-center">
            <!-- <h2 class="title">{{ $t(route.meta.pageName) }}</h2> -->
            <ol class="breadcrumb justify-content-center text-white mt-0">
              <li class="breadcrumb-item">
                <router-link :to="{ name: 'landing-page.ott' }">{{ $t('streamPages.home') }}</router-link>
              </li>
              <li class="breadcrumb-item active">{{ $t(route.meta.pageName) }}</li>
            </ol>
          </nav>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>
<script setup>
import { useRoute } from 'vue-router';
// const generateImgPath = (path) => {
//   return window.origin + import.meta.env.BASE_URL + path;
// };
const route = useRoute();
</script>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/BreadcrumbWidget.tsx
import { Fragment, memo } from "react";

//react bootstrap
import { Breadcrumb, Container, Row, Col } from "react-bootstrap";

//function
import { generateImgPath } from "../StaticData/data";

//react-redux
import { useSelector } from "react-redux";
import { getBreadcrumb } from "@/store/streamit/selectors";

//hook
import { useTranslation } from 'react-i18next';
import Link from "next/link";

//img
const imagePath = generateImgPath("/assets/images/pages/01.webp");

const BreadCrumbWidget = memo(() => {
    const { t } = useTranslation("common");
  const breadcrumb = useSelector(getBreadcrumb)
  return (
    // <Fragment>
    //   {breadcrumb.show ?
    //     <div
    //       className="iq-breadcrumb"
    //       style={{ backgroundImage: `url(${imagePath})` }}
    //     >
    //       <Container fluid>
    //         <Row className="align-items-center">
    //           <Col sm="12">
    //             <nav className="text-center">
    //               <h2 className="title text-capitalize">{t(breadcrumb.name)}</h2>
    //               <Breadcrumb
    //                 className="main-bg"
    //                 listProps={{
    //                   className: "text-center justify-content-center",
    //                 }}
    //               >
    //                 <Breadcrumb.Item>{t("header.home")}</Breadcrumb.Item>
    //                 <Breadcrumb.Item active>{t(breadcrumb.name)}</Breadcrumb.Item>
    //               </Breadcrumb>
    //             </nav>
    //           </Col>
    //         </Row>
    //       </Container>
    //     </div> : ''}
    // </Fragment>

       <Fragment>
     {breadcrumb.show ?<div className="iq-breadcrumb">
    <Container>
        <Row className="align-items-center">
            <Col sm={12} >
                <nav aria-label="breadcrumb" className="text-center">
                    <ol className="breadcrumb justify-content-center text-white mt-0">
                        <li className="breadcrumb-item"><Link href="/">Home</Link></li>
                        <li className="breadcrumb-item active">{t(breadcrumb.name)}</li>
                    </ol>
                </nav>
            </Col>
        </Row>
    </Container>
</div>: ''}
    </Fragment>
  );
});

BreadCrumbWidget.displayName = "BreadCrumbWidget";
export default BreadCrumbWidget;
