// tamplate/streamithtml-540/streamit-html/code-next/src/app/(frontend-pages)/videos/page.tsx
"use client";

import { Fragment } from "react";

//hero-slider
import VideoHeroSlider from "../../components/slider/VideoHeroSlider";

//sections
import PopularVideos from "../../components/sections/PopularVideos";
import SpecialsLatestVideos from "../../components/sections/Specials&LatestVideos";
import VideosRecommendedForYou from "../../components/sections/VideosRecommendedForYou";

//custom hook
import { useEnterExit } from "@/utilities/usePage";
import { Container } from "react-bootstrap";
import TopTenMoviesToWatch from "@/components/sections/TopTenMoviesToWatch";
import UpcomingMovies from "@/components/sections/UpcomingMovies";
import { top_ten_video, latestVideo, upcomimgVideo, video_recommendedforYou } from "@/StaticData/data";

const VideosPage = () => {
  return (
    <Fragment>
      <VideoHeroSlider />
      <Container fluid>
        <div className="overflow-hidden">
          <TopTenMoviesToWatch list={top_ten_video} viewAll={false} />
          <PopularVideos viewAll={false} />
          <UpcomingMovies viewAll={false} list={upcomimgVideo} loop={false}/>
          <SpecialsLatestVideos list={latestVideo} viewAll={false} />
          <VideosRecommendedForYou list={video_recommendedforYou} viewAll={false}/>
        </div>
      </Container>
    </Fragment>
  );
};

VideosPage.DisplayName = VideosPage;
export default VideosPage;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/videos/index.vue
<template>
  <VideoHeroSlider/>

<b-container fluid>
  <div class="overflow-hidden">
    <TopTenMoviesToWatch :title="$t('sectionTitle.top_10_video_to_watch')" :padding-top="true" :prime="true" :list="topTenVideoPage"/>

    <PopularVideos :loop="false"/>

    <UpcomingVideos :loop="false"/>

    <SpecialsLatestVideos :loop="false"/>

    <VideosRecommendedForYou :loop="false"/>
  </div>
</b-container>
</template>

<script setup>
// Hero Slider
import VideoHeroSlider from "../../components/slider/VideoHeroSlider.vue";

// sections
import PopularVideos from "../../components/sections/PopularVideos.vue";
import VideosRecommendedForYou from "../../components/sections/VideosRecommendedForYou.vue";
import UpcomingVideos from "~/components/sections/UpcomingVideos.vue";
import SpecialsLatestVideos from "~/components/sections/Specials&LatestVideos.vue";
import TopTenMoviesToWatch from "~/components/sections/TopTenMoviesToWatch.vue";
import { topTenVideoPage } from "~/StaticData/data";
</script>
