// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/extra/AboutSections/TeamSection.vue
<template>
  <b-container>
    <b-row class="align-items-center">
      <b-col lg="2"></b-col>
      <b-col lg="8" md="12">
        <div class="title-box text-center">
          <h3 class="">{{ $t('streamAbout.mastermind_team') }}</h3>
          <p class="mb-0">{{ $t('streamAbout.streamit_build') }}</p>
        </div>
      </b-col>
      <b-col lg="3"></b-col>
    </b-row>
    <b-row class="about-us-detail gy-4">
      <b-col  v-for="(data, index) of lists" :key="index" md="3">
        <ProfileCard :name="$t(data.name)" :designation="$t(data.designation)" :image="data.image"></ProfileCard>
      </b-col>
    </b-row>
  </b-container>
</template>
<script setup>
import { reactive } from 'vue';
import ProfileCard from '../../../components/cards/ProfileCard.vue';
import { generateImgPath } from '../../../StaticData/data';
const lists = reactive([
  { image: generateImgPath('/assets/images/pages/team1.webp'), designation: 'streamAbout.ceo', name: 'streamAbout.tonny_smith' },
  { image: generateImgPath('/assets/images/pages/team2.webp'), designation: 'streamAbout.designer', name: 'streamAbout.barry_tech' },
  { image: generateImgPath('/assets/images/pages/team3.webp'), designation: 'streamAbout.developer', name: 'streamAbout.kep_john' },
  { image: generateImgPath('/assets/images/pages/team4.webp'), designation: 'streamAbout.designer', name: 'streamAbout.monty_rock' },
]);
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/ExtraPages/AboutSections/TeamSection.jsx
import { Fragment, memo, useState } from "react";

//react bootstrap
import { Col, Container, Row } from "react-bootstrap";

//components
import ProfileCard from "../../../components/cards/ProfileCard";

//function
import { generateImgPath } from "../../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";
const TeamSection = memo(() => {
  const { t } = useTranslation();
  const [lists] = useState([
    {
      image: generateImgPath("/assets/images/pages/team1.webp"),
      designation: "streamAbout.ceo",
      name: "streamAbout.tonny_smith",
    },
    {
      image: generateImgPath("/assets/images/pages/team2.webp"),
      designation: "streamAbout.designer",
      name: "streamAbout.barry_tech",
    },
    {
      image: generateImgPath("/assets/images/pages/team3.webp"),
      designation: "streamAbout.developer",
      name: "streamAbout.kep_john",
    },
    {
      image: generateImgPath("/assets/images/pages/team4.webp"),
      designation: "streamAbout.designer",
      name: "streamAbout.monty_rock",
    },
  ]);
  return (
    <Fragment>
      <section className="section-padding-bottom">
        <Container>
          <Row className="align-items-center">
            <Col lg="2"></Col>
            <Col lg="8" md="12">
              <div className="title-box text-center">
                <h3>{t("streamAbout.mastermind_team")}</h3>
                <p className="mb-0">{t("streamAbout.streamit_build")}</p>
              </div>
            </Col>
            <Col lg="2"></Col>
          </Row>
          <div className="row about-us-detail gy-4">
            {lists.map((data, index) => (
              <Col md="3" key={index}>
                <ProfileCard
                  name={t(data.name)}
                  designation={t(data.designation)}
                  image={data.image}
                ></ProfileCard>
              </Col>
            ))}
          </div>
        </Container>
      </section>
    </Fragment>
  );
});

TeamSection.displayName = "TeamSection";
export default TeamSection;
