// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/extra/AboutSections/WorkSection.vue
<template>
  <div class="section-padding">
    <b-container>
      <h3 class="text-capitalize text-center">{{ $t('streamAbout.work_best') }}</h3>
      <div class="image-box-container">
        <div class="image-box-1" v-for="(data, index) of aboutList" :key="index" >
          <img class="img-fluid" :src="data.image" alt="content-image" />
        </div>
      </div>
    </b-container>
  </div>
</template>
<script setup>
import { reactive } from 'vue';
import { generateImgPath } from '../../../StaticData/data';
const aboutList = reactive([
  { image: generateImgPath('/assets/images/pages/about-us1.svg')},
  { image: generateImgPath('/assets/images/pages/about-us2.svg')},
  { image: generateImgPath('/assets/images/pages/about-us3.svg')},
  { image: generateImgPath('/assets/images/pages/about-us4.svg')},
  { image: generateImgPath('/assets/images/pages/about-us5.svg')},
]);
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/ExtraPages/AboutSections/WorkSection.jsx
import { memo, Fragment } from "react";

//react-bootstrap
import { Container, Col, Row } from "react-bootstrap";

// the hook
import { useTranslation } from "react-i18next";
import { generateImgPath } from "../../../StaticData/data";


const WorkSection = memo(() => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <div className="section-padding">
        <Container>
          <h3 className="text-capitalize text-center">
            {t("streamAbout.work_best")}
          </h3>
          <div className="image-box-container">
         <div className="image-box-1">
            <img className="img-fluid" src={generateImgPath("/assets/images/pages/about-us1.svg")} alt="content-image" />
         </div>

         <div className="image-box-1">
            <img className="img-fluid" src={generateImgPath("/assets/images/pages/about-us2.svg")} alt="content-image" />
         </div>

         <div className="image-box-1">
            <img className="img-fluid" src={generateImgPath("/assets/images/pages/about-us3.svg")} alt="content-image" />
         </div>

         <div className="image-box-1">
            <img className="img-fluid" src={generateImgPath("/assets/images/pages/about-us4.svg")} alt="content-image" />
         </div>

         <div className="image-box-1">
            <img className="img-fluid" src={generateImgPath("/assets/images/pages/about-us5.svg")} alt="content-image" />
         </div>
      </div>
        </Container>
      </div>
    </Fragment>
  );
});

WorkSection.displayName = "WorkSection";
export default WorkSection;
