// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/MerchandisePages/IndexPage.jsx
import { memo, Fragment } from "react";
// react-bootstrap
import { Row, Col, Container } from "react-bootstrap";

// recat-router-dom
import { Link } from "react-router-dom";

// components
import ShopSectionSlider from "../../components/slider/ShopSectionSlider";
import ProductCard from "../../components/merchandise/product-card";
import Logo from "../../components/logo";
import CustomButton from "../../components/CustomButton";

//data
import { heroSlider, newProduct, category } from "../../StaticData/shop";

// swiper
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation } from "swiper";

// Redux Selector / Action
import { useSelector } from "react-redux";
import { theme_scheme_direction } from "../../store/setting/selectors";

// img
import img1 from "/assets/images/shop/card/capton-america.webp";
import img2 from "/assets/images/shop/card/deadpool.webp";
import img3 from "/assets/images/shop/card/multipal.webp";
import location from "/assets/images/shop/card/location.webp";

// the hook
import { useTranslation } from "react-i18next";

const IndexPage = memo(() => {
  const { t } = useTranslation();
  const themeSchemeDirection = useSelector(theme_scheme_direction);
  return (
    <Fragment>
      <Swiper
        key={themeSchemeDirection}
        dir={themeSchemeDirection}
        navigation={{
          prevEl: ".swiper-banner-button-prev",
          nextEl: ".swiper-banner-button-next",
        }}
        loop={true}
        modules={[Navigation]}
        className="position-relative wrapper-class"
      >
        {heroSlider.map((item, index) => {
          return (
            <SwiperSlide className="slide m-0 p-0 home-slider" key={index}>
              <Link to="/product-detail" className="card-link">
                <img
                  src={item.thumbnail}
                  alt="swiperimg"
                  className="img-fluid w-100"
                />
              </Link>
            </SwiperSlide>
          );
        })}
        <div
          className="swiper-banner-button-prev swiper-nav"
          id="home-banner-slider-prev"
        >
          <i></i>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 44 44"
            width="44"
            height="44"
            fill="none"
            stroke="currentColor"
          >
            <circle r="20" cy="22" cx="22"></circle>
          </svg>
        </div>
        <div
          className="swiper-banner-button-next swiper-nav"
          id="home-banner-slider-next"
        >
          <i></i>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 44 44"
            width="44"
            height="44"
            fill="none"
            stroke="currentColor"
          >
            <circle r="20" cy="22" cx="22"></circle>
          </svg>
        </div>
      </Swiper>

      <section className="category-slider-block">
        <Container fluid>
          <div className="ms-lg-3">
            <h4 className="my-4 mt-md-3 mt-sm-3">
              {t("sectionTitle.best_selling_categories")}
            </h4>
          </div>
          <Swiper
            key={themeSchemeDirection}
            dir={themeSchemeDirection}
            navigation={{
              prevEl: ".swiper-button-prev",
              nextEl: ".swiper-button-next",
            }}
            modules={[Navigation]}
            draggable="true"
            speed={1500}
            breakpoints={{
              0: {
                slidesPerView: 1,
              },
              576: {
                slidesPerView: 2,
              },
              768: {
                slidesPerView: 3,
              },
              1025: {
                slidesPerView: 4,
              },
              1500: {
                slidesPerView: 4,
              },
            }}
            // spaceBetween={10}
            slidesPerView={4}
            wrapperTag="ul"
            className="position-relative swiper-card wrapper-class merch-slides"
          >
            {category.map((item, index) => {
              return (
                <SwiperSlide className="slide-item" tag="li" key={index}>
                  <ShopSectionSlider
                    shopsellingImg={item.image}
                    shopsellingText={t(item.title)}
                    slug={item.slug}
                  />
                </SwiperSlide>
              );
            })}
          </Swiper>
        </Container>
      </section>

      <section className="">
        <Container fluid className="p-xl-0 overflow-hidden">
          <Row className="">
            <Col lg="4" md="6" className="d-flex flex-column gap-4">
              <div className="product-box left-1-productbox">
                <Link to="/shop" className="card-link"></Link>
                <div
                  className="card-img-overlay product-card-img-overlay"
                  style={{
                    backgroundImage: "url(assets/images/shop/card/01.webp)",
                  }}
                ></div>
                <div className="card-body w-100">
                  <h4 className="parent-heading">
                    {t("streamShop.monster_house")}
                  </h4>
                  <div className="iq-btn-container">
                    <CustomButton
                      linkButton="true"
                      buttonTitle={t("streamButtons.shop_now")}
                      link="/"
                    />
                  </div>
                </div>
              </div>
              <div className="product-box left-2-productbox">
                <Link to="/shop" className="card-link"></Link>
                <div
                  className="card-img-overlay product-card-img-overlay mt-lg-0 mt-md-4 mt-4"
                  style={{
                    backgroundImage: "url(assets/images/shop/card/02.webp)",
                  }}
                ></div>
                <div className="card-body w-100">
                  <h4 className="parent-heading">
                    {t("streamShop.warner_bro_films")}
                  </h4>
                  <div className="iq-btn-container">
                    <CustomButton
                      linkButton="true"
                      buttonTitle={t("streamButtons.shop_now")}
                      link="/"
                    />
                  </div>
                </div>
              </div>
            </Col>
            <Col lg="4" md="6" className="mt-md-0 mt-4">
              <div className="center-productbox product-box">
                <Link to="/shop" className="card-link"></Link>
                <div
                  className="card-img-overlay product-card-img-overlay"
                  style={{
                    backgroundImage: "url(assets/images/shop/card/03.webp)",
                  }}
                ></div>
                <div className="card-body w-100">
                  <h4 className="parent-heading">
                    {t("streamShop.marvel_studios")}
                  </h4>
                  <div className="iq-btn-container">
                    <CustomButton
                      linkButton="true"
                      buttonTitle={t("streamButtons.shop_now")}
                      link="/"
                    />
                  </div>
                </div>
              </div>
            </Col>
            <Col
              lg="4"
              md="12"
              className="d-flex flex-column mt-lg-0 mt-md-4 mt-4 gap-4"
            >
              <div className="product-box right-1-productbox">
                <Link to="/shop" className="card-link"></Link>
                <div
                  className="card-img-overlay product-card-img-overlay md-mt-5"
                  style={{
                    backgroundImage: "url(assets/images/shop/card/04.webp)",
                  }}
                ></div>
                <div className="card-body w-100">
                  <h4 className="parent-heading">
                    {t("streamShop.warner_bros_films")}
                  </h4>
                  <div className="iq-btn-container">
                    <CustomButton
                      linkButton="true"
                      buttonTitle={t("streamButtons.shop_now")}
                      link="/"
                    />
                  </div>
                </div>
              </div>
              <div className="product-box right-2-productbox">
                <Link to="/shop" className="card-link"></Link>
                <div
                  className="card-img-overlay product-card-img-overlay mt-lg-0 mt-md-4 mt-4"
                  style={{
                    backgroundImage: "url(assets/images/shop/card/05.webp)",
                  }}
                ></div>
                <div className="card-body w-100">
                  <h4 className="parent-heading">
                    {t("streamShop.disney_world")}
                  </h4>
                  <div className="iq-btn-container">
                    <CustomButton
                      linkButton="true"
                      buttonTitle={t("streamButtons.shop_now")}
                      link="/"
                    />
                  </div>
                </div>
              </div>
            </Col>
          </Row>
        </Container>
      </section>

      <div className="newest-product-block section-padding-top">
        <Container fluid>
          <div className="overflow-hidden">
            <div className="d-flex align-items-center justify-content-between mb-3">
              <h4 className="main-title text-capitalize mb-0">
                {t("sectionTitle.newest_products")}
              </h4>
            </div>
            <div className="card-style-slider">
              <Swiper
                key={themeSchemeDirection}
                dir={themeSchemeDirection}
                slidesPerView={5}
                navigation={{
                  prevEl: ".swiper-button-prev",
                  nextEl: ".swiper-button-next",
                }}
                loop={true}
                modules={[Navigation]}
                speed={1500}
                wrapperTag="ul"
                className="position-relative swiper-card wrapper-class merch-slides"
                breakpoints={{
                  0: {
                    slidesPerView: 2,
                    spaceBetween: 0,
                  },
                  576: {
                    slidesPerView: 2,
                    spaceBetween: 0,
                  },
                  768: {
                    slidesPerView: 3,
                    spaceBetween: 0,
                  },
                  1025: {
                    slidesPerView: 5,
                    spaceBetween: 0,
                  },
                  1500: {
                    slidesPerView: 5,
                    spaceBetween: 0,
                  },
                }}
              >
                {newProduct.map((item, index) => {
                  return (
                    <SwiperSlide tag="li" key={index}>
                      <ProductCard
                        thumbnail={item.thumbnail}
                        product_name={t(item.product_name)}
                        price={item.price}
                        final_price={item.final_price}
                        rating="5"
                        count1="0"
                        is_sale={item.is_sale}
                        is_new={item.is_new}
                        slug={item.slug}
                      />
                    </SwiperSlide>
                  );
                })}
                <div className="swiper-button swiper-button-next"></div>
                <div className="swiper-button swiper-button-prev"></div>
              </Swiper>
            </div>
          </div>
        </Container>
      </div>

      <section className="section-padding-bottom">
        <Container>
          <Row>
            <Col lg="6" md="6">
              <div className="categorie-about-left">
                <div className="categorie-about-image">
                  <img src={img1} className="img-fluid" />
                </div>
                <div className=" text-left mb-4 pt-3">
                  <h4 className="mb-2 line-count-1">
                    {t("streamShop.captian_america")}
                  </h4>
                  <p className="mb-4 mt-2 line-count-3">
                    {t("streamShop.lorem_ipsum")}
                  </p>
                  <CustomButton
                    linkButton="false"
                    buttonTitle={t("streamButtons.view_collection")}
                    link="/shop"
                  />
                </div>
              </div>
            </Col>
            <Col lg="6" md="6">
              <div className="categorie-about-right">
                <div className="categorie-about-image">
                  <img src={img2} className="img-fluid" />
                </div>
                <div className=" text-left mb-4 pt-3">
                  <h4 className="mb-2 line-count-1">
                    {t("streamShop.deadpool")}
                  </h4>
                  <p className="mb-4 mt-2 line-count-3">
                    {t("streamShop.lorem_ipsum")}
                  </p>
                  <CustomButton
                    linkButton="false"
                    buttonTitle={t("streamButtons.view_collection")}
                    link="/shop"
                  />
                </div>
              </div>
            </Col>
          </Row>
        </Container>
      </section>

      <section
        className="section-padding"
        style={{
          backgroundImage: "url(assets/images/shop/card/bg-img.webp)",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
        }}
      >
        <Container fluid>
          <Row className="row align-items-center">
            <Col md={6} >
              <img src={img3} className="img-fluid" alt="img" />
            </Col>
            <Col md={6} className="mt-4 mt-md-0">
              <Logo />
              <h2 className="mt-3 mb-4 pb-2">
                {" "}
                {t("streamShop.wear_streamit")}{" "}
              </h2>
              <p className="mb-4 line-count-3">
                {t("streamShop.buy_exclusive")}
              </p>
              <CustomButton
                linkButton="false"
                buttonTitle={t("streamButtons.shop_now")}
                link="/product-detail"
              />
            </Col>
          </Row>
        </Container>
      </section>

      <div className="best-product-block section-padding-top">
        <Container fluid>
          <div className="overflow-hidden">
            <div className="d-flex align-items-center justify-content-between mb-3">
              <h4 className="main-title text-capitalize mb-0">
                {t("sectionTitle.best_sellers")}
              </h4>
            </div>
            <div className="card-style-slider">
              <Swiper
                key={themeSchemeDirection}
                dir={themeSchemeDirection}
                slidesPerView={5}
                navigation={{
                  prevEl: ".swiper-button-prev",
                  nextEl: ".swiper-button-next",
                }}
                loop={true}
                modules={[Navigation]}
                wrapperTag="ul"
                className="position-relative swiper-card wrapper-class merch-slides"
                breakpoints={{
                  0: {
                    slidesPerView: 2,
                    spaceBetween: 0,
                  },
                  576: {
                    slidesPerView: 2,
                    spaceBetween: 0,
                  },
                  768: {
                    slidesPerView: 3,
                    spaceBetween: 0,
                  },
                  1025: {
                    slidesPerView: 5,
                    spaceBetween: 0,
                  },
                  1500: {
                    slidesPerView: 5,
                    spaceBetween: 0,
                  },
                }}
              >
                {newProduct.map((item, index) => {
                  return (
                    <SwiperSlide tag="li" key={index}>
                      <ProductCard
                        thumbnail={item.thumbnail}
                        product_name={t(item.product_name)}
                        price={item.price}
                        final_price={item.final_price}
                        rating="5"
                        count1="0"
                        is_sale={item.is_sale}
                        is_new={item.is_new}
                        slug={item.slug}
                      />
                    </SwiperSlide>
                  );
                })}
                <div className="swiper-button swiper-button-next"></div>
                <div className="swiper-button swiper-button-prev"></div>
              </Swiper>
            </div>
          </div>
        </Container>
      </div>

      <div className="product_container">
        <Row className=" gx-0">
          <Col lg="6" className="shop-contact-one">
            <Link to="#">
              <div className="channel-logo">
                <h3 className="mb-0">{t("streamShop.our_multiple")}</h3>
              </div>
            </Link>
            <Row className="my-4">
              <Col lg="6" md="12">
                <h5 className="mb-2">{t("streamShop.australia")}:</h5>
                <p>24 {t("streamShop.thornridge_cir")} 7140</p>
              </Col>
              <Col lg="6" md="12">
                <h5 className="mb-2">{t("streamShop.australia")}: </h5>
                <p>2118 {t("streamShop.thornridge_cir")} 35624</p>
              </Col>
            </Row>
            <div className="d-flex align-items-md-center flex-column flex-md-row gap-3">
              <h5 className="m-0">{t("streamShop.working_hours")}: </h5>
              <i className="text-primary shop_store_time">
                {" "}
                Mon – Fri : 09:00 AM to 06:00 PM
              </i>
            </div>
          </Col>
          <Col lg="6" md="12" className="shop-contact">
            <img src={location} alt="img" className="img-fluid h-100 w-100" />
          </Col>
        </Row>
      </div>
    </Fragment>
  );
});
IndexPage.displayName = "IndexPage";
export default IndexPage;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/MerchandisePages/IndexPage.vue
<template>
  <div data-swiper="home-banner-slider">
    <Swiper :slides-per-view="1" :navigation="{ prevEl: '.swiper-banner-button-prev', nextEl: '.swiper-banner-button-next' }" :space-beween="10" :modules="modules" class="wrapper-class swiper-banner-container iq-rtl-direction">
      <SwiperSlide v-for="data in heroSlider" :key="data" tag="li" class="swiper-slide slide m-0 p-0 home-slider" :style="{ backgroundImage: `url(${data.thumbnail})` }" style="background: no-repeat">
        <router-link :to="{ name: 'landing-page.merchandise.shop.detail' }">
          <img :src="data.thumbnail" class="img-fluid w-100" loading="lazy" />
        </router-link>
      </SwiperSlide>
      <div class="swiper-banner-button-prev swiper-nav">
        <i class="ri-arrow-left-s-line arrow-icon"></i>
        <svg>
          <use xlink:href="#circle"></use>
        </svg>
      </div>
      <div class="swiper-banner-button-next swiper-nav">
        <i class="ri-arrow-right-s-line arrow-icon"></i>
        <svg>
          <use xlink:href="#circle"></use>
        </svg>
        <div class="swiper-pagination"></div>
      </div>
    </Swiper>
  </div>
  <!---Best Selling Categories Start--->
  <section class="category-slider-block">
    <b-container fluid>
      <div class="ms-lg-1">
        <h4 class="my-4 mt-md-3 mt-sm-3">{{ $t('sectionTitle.best_selling_categories') }}</h4>
      </div>
      <!-- <div class="position-relative swiper swiper-card swiper-initialized swiper-horizontal swiper-pointer-events"
        data-slide="4" data-laptop="4" data-tab="3" data-mobile="2" data-mobile-sm="1" data-autoplay="false"
        data-loop="false" data-navigation="true" data-pagination="true"> -->
      <swiper
        v-if="render"
        :dir="rtl"
        :slides-per-view="4"
        :navigation="{ prevEl: '.swiper-button-prev', nextEl: '.swiper-button-next' }"
        tag="ul"
        class="wrapper-class"
        :modules="modules"
        :breakpoints="{
          '0': {
            slidesPerView: 1,
            spaceBetween: 0,
          },
          '576': {
            slidesPerView: 2,
            spaceBetween: 0,
          },
          '768': {
            slidesPerView: 3,
            spaceBetween: 0,
          },
          '1025': {
            slidesPerView: 4,
            spaceBetween: 0,
          },
          '1500': {
            slidesPerView: 4,
            spaceBetween: 0,
          },
        }">
        <SwiperSlide tag="li" class="swiper-slide slide-item">
          <div class="category-inner position-relative">
            <div class="category_image">
              <router-link to="/merchandise/shop">
                <img src="/assets/images/shop/categories/01.webp" class="img-fluid categorys-img" alt="catImg-01" loading="lazy" />
              </router-link>
              <div class="category-details">
                <h5 class="category-title mb-0">
                  <router-link to="/merchandise/shop"> {{ $t('streamShop.activeman') }} </router-link>
                </h5>
              </div>
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide tag="li" class="swiper-slide slide-item">
          <div class="category-inner position-relative">
            <div class="category_image">
              <router-link to="/merchandise/shop">
                <img src="/assets/images/shop/categories/02.webp" class="img-fluid categorys-img" alt="catImg-02" loading="lazy" />
              </router-link>
              <div class="category-details">
                <h5 class="category-title mb-0">
                  <router-link to="/merchandise/shop"> {{ $t('streamShop.avengers') }} </router-link>
                </h5>
              </div>
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide tag="li" class="swiper-slide slide-item">
          <div class="category-inner position-relative">
            <div class="category_image">
              <router-link to="/merchandise/shop">
                <img src="/assets/images/shop/categories/03.webp" class="img-fluid categorys-img" alt="catImg-03" loading="lazy" />
              </router-link>
              <div class="category-details">
                <h5 class="category-title mb-0">
                  <router-link to="/merchandise/shop"> {{ $t('streamShop.disney_world') }} </router-link>
                </h5>
              </div>
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide tag="li" class="swiper-slide slide-item">
          <div class="category-inner position-relative">
            <div class="category_image">
              <router-link to="/merchandise/shop">
                <img src="/assets/images/shop/categories/04.webp" class="img-fluid categorys-img" alt="catImg-04" loading="lazy" />
              </router-link>
              <div class="category-details">
                <h5 class="category-title mb-0">
                  <router-link to="/merchandise/shop"> {{ $t('streamShop.fantasia') }} </router-link>
                </h5>
              </div>
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide tag="li" class="swiper-slide slide-item">
          <div class="category-inner position-relative">
            <div class="category_image">
              <router-link to="/merchandise/shop">
                <img src="/assets/images/shop/categories/05.webp" class="img-fluid categorys-img" alt="catImg-05" loading="lazy" />
              </router-link>
              <div class="category-details">
                <h5 class="category-title mb-0">
                  <router-link to="/merchandise/shop"> {{ $t('streamShop.galaxy_heaven') }} </router-link>
                </h5>
              </div>
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide tag="li" class="swiper-slide slide-item">
          <div class="category-inner position-relative">
            <div class="category_image">
              <router-link to="/merchandise/shop">
                <img src="/assets/images/shop/categories/06.webp" class="img-fluid categorys-img" alt="catImg-06" />
              </router-link>
              <div class="category-details">
                <h5 class="category-title mb-0">
                  <router-link to="/merchandise/shop"> {{ $t('streamShop.ghost_spider') }} </router-link>
                </h5>
              </div>
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide tag="li" class="swiper-slide slide-item">
          <div class="category-inner position-relative">
            <div class="category_image">
              <router-link to="/merchandise/shop">
                <img src="/assets/images/shop/categories/07.webp" class="img-fluid categorys-img" alt="catImg-07" loading="lazy" />
              </router-link>
              <div class="category-details">
                <h5 class="category-title mb-0">
                  <router-link to="/merchandise/shop"> {{ $t('streamShop.harry_david') }} </router-link>
                </h5>
              </div>
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide tag="li" class="swiper-slide slide-item">
          <div class="category-inner position-relative">
            <div class="category_image">
              <router-link to="/merchandise/shop">
                <img src="/assets/images/shop/categories/08.webp" class="img-fluid categorys-img" alt="catImg-08" />
              </router-link>
              <div class="category-details">
                <h5 class="category-title mb-0">
                  <router-link to="/merchandise/shop"> {{ $t('streamShop.haunted_halloween') }} </router-link>
                </h5>
              </div>
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide tag="li" class="swiper-slide slide-item">
          <div class="category-inner position-relative">
            <div class="category_image">
              <router-link to="/merchandise/shop">
                <img src="/assets/images/shop/categories/09.webp" class="img-fluid categorys-img" alt="catImg-09" loading="lazy" />
              </router-link>
              <div class="category-details">
                <h5 class="category-title mb-0">
                  <router-link to="/merchandise/shop"> {{ $t('streamShop.studios') }} </router-link>
                </h5>
              </div>
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide tag="li" class="swiper-slide slide-item">
          <div class="category-inner position-relative">
            <div class="category_image">
              <router-link to="/merchandise/shop">
                <img src="/assets/images/shop/categories/11.webp" class="img-fluid categorys-img" alt="catImg-10" />
              </router-link>
              <div class="category-details">
                <h5 class="category-title mb-0">
                  <router-link to="/merchandise/shop"> {{ $t('streamShop.monster_house') }} </router-link>
                </h5>
              </div>
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide tag="li" class="swiper-slide slide-item">
          <div class="category-inner position-relative">
            <div class="category_image">
              <router-link to="/merchandise/shop">
                <img src="/assets/images/shop/categories/12.webp" class="img-fluid categorys-img" alt="catImg-11" loading="lazy" />
              </router-link>
              <div class="category-details">
                <h5 class="category-title mb-0">
                  <router-link to="/merchandise/shop"> {{ $t('streamShop.quid_game') }} </router-link>
                </h5>
              </div>
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide tag="li" class="swiper-slide slide-item">
          <div class="category-inner position-relative">
            <div class="category_image">
              <router-link to="/merchandise/shop">
                <img src="/assets/images/shop/categories/14.webp" class="img-fluid categorys-img" alt="catImg-12" />
              </router-link>
              <div class="category-details">
                <h5 class="category-title mb-0">
                  <router-link to="/merchandise/shop"> {{ $t('streamShop.the_madrid') }} </router-link>
                </h5>
              </div>
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide tag="li" class="swiper-slide slide-item">
          <div class="category-inner position-relative">
            <div class="category_image">
              <router-link to="/merchandise/shop">
                <img src="/assets/images/shop/categories/15.webp" class="img-fluid categorys-img" alt="catImg-13" loading="lazy" />
              </router-link>
              <div class="category-details">
                <h5 class="category-title mb-0">
                  <router-link to="/merchandise/shop"> {{ $t('streamShop.the_chapion') }} </router-link>
                </h5>
              </div>
            </div>
          </div>
        </SwiperSlide>
      </swiper>
      <!-- </div> -->
    </b-container>
  </section>
  <!---Best Selling Categories End--->
  <section>
    <b-container fluid class="p-xl-0 overflow-hidden">
      <b-row>
        <b-col lg="4" md="6" class="d-flex flex-column gap-4">
          <div class="product-box left-1-productbox">
            <router-link :to="{ name: 'landing-page.merchandise.shop' }" class="card-link"></router-link>
            <div class="card-img-overlay product-card-img-overlay" :style="`background-image: url(${generateImgPath('/assets/images/shop/card/01.webp')})`"></div>
            <div class="card-body w-100">
              <!-- <h5 class="card-title">{{ $t('streamShop.ghost_spider') }}</h5> -->
              <h4 class="parent-heading">{{ $t('streamShop.monster_house') }}</h4>
              <div>
                <router-link :to="{ name: 'landing-page.merchandise.shop' }" class="btn btn-link p-0 text-capitalize position-relative">
                  <span class="button-text">{{ $t('streamButtons.shop_now') }}</span>
                </router-link>
              </div>
            </div>
          </div>
          <div class="product-box left-2-productbox">
            <router-link :to="{ name: 'landing-page.merchandise.shop' }" class="card-link"></router-link>
            <div class="card-img-overlay product-card-img-overlay mt-lg-0 mt-md-4 mt-4" :style="`background-image: url(${generateImgPath('/assets/images/shop/card/02.webp')})`"></div>
            <div class="card-body w-100">
              <!-- <h5 class="card-title">{{ $t('streamShop.harry_david') }}</h5> -->
              <h4 class="parent-heading">{{ $t('streamShop.warner_bros_films') }}</h4>
              <div>
                <router-link :to="{ name: 'landing-page.merchandise.shop' }" class="btn btn-link p-0 text-capitalize position-relative">
                  <span class="button-text">{{ $t('streamButtons.shop_now') }}</span></router-link
                >
              </div>
            </div>
          </div>
        </b-col>
        <b-col lg="4" md="6" class="mt-md-0 mt-4">
          <div class="center-productbox product-box">
            <router-link :to="{ name: 'landing-page.merchandise.shop' }" class="card-link"></router-link>
            <div class="card-img-overlay product-card-img-overlay" :style="`background-image: url(${generateImgPath('/assets/images/shop/card/03.webp')})`"></div>
            <div class="card-body w-100">
              <!-- <h5 class="card-title">{{ $t('streamShop.avengers') }}</h5> -->
              <h4 class="parent-heading">{{ $t('streamShop.marvel_studios') }}</h4>
              <div>
                <router-link :to="{ name: 'landing-page.merchandise.shop' }" class="btn btn-link p-0 text-capitalize position-relative">
                  <span class="button-text">{{ $t('streamButtons.shop_now') }}</span>
                </router-link>
              </div>
            </div>
          </div>
        </b-col>
        <b-col lg="4" md="12" class="d-flex flex-column mt-lg-0 mt-md-4 mt-4 gap-4">
          <div class="product-box right-1-productbox">
            <router-link :to="{ name: 'landing-page.merchandise.shop' }" class="card-link"></router-link>
            <div class="card-img-overlay product-card-img-overlay md-mt-5" :style="`background-image: url(${generateImgPath('/assets/images/shop/card/04.webp')})`"></div>
            <div class="card-body w-100">
              <!-- <h5 class="card-title">{{ $t('streamShop.harry_david') }}</h5> -->
              <h4 class="parent-heading">{{ $t('streamShop.warner_bros_films') }}</h4>
              <div>
                <router-link :to="{ name: 'landing-page.merchandise.shop' }" class="btn btn-link p-0 text-capitalize position-relative">
                  <span class="button-text">{{ $t('streamButtons.shop_now') }}</span>
                </router-link>
              </div>
            </div>
          </div>
          <div class="product-box right-2-productbox">
            <router-link :to="{ name: 'landing-page.merchandise.shop' }" class="card-link"></router-link>
            <div class="card-img-overlay product-card-img-overlay mt-lg-0 mt-md-4 mt-4" :style="`background-image: url(${generateImgPath('/assets/images/shop/card/05.webp')})`"></div>
            <div class="card-body w-100">
              <!-- <h5 class="card-title">{{ $t('streamShop.fantasia') }}</h5> -->
              <h4 class="parent-heading">{{ $t('streamShop.disney_world') }}</h4>
              <div>
                <router-link :to="{ name: 'landing-page.merchandise.shop' }" class="btn btn-link p-0 text-capitalize position-relative">
                  <span class="button-text">{{ $t('streamButtons.shop_now') }}</span>
                </router-link>
              </div>
            </div>
          </div>
        </b-col>
      </b-row>
    </b-container>
  </section>
  <div class="newest-product-block section-padding-top">
    <b-container fluid>
      <div class="overflow-hidden">
        <ProductSection :not-want-more-btn="false" title="sectionTitle.newest_products"></ProductSection>
      </div>
    </b-container>
  </div>
  <section class="section-padding-bottom">
    <b-container>
      <b-row>
        <b-col lg="6" md="6">
          <div class="categorie-about-left">
            <div class="categorie-about-image">
              <img src="/assets/images/shop/card/capton-america.webp" class="img-fluid" loading="lazy" />
            </div>
            <div class="text-left mb-4 pt-3">
              <h4 class="mb-2 line-count-1">{{ $t('streamShop.captian_america') }}</h4>
              <p class="mb-4 mt-2 line-count-3">{{ $t('streamShop.lorem_ipsum') }}</p>
              <custom-button :not-btncaret-icon="true" :button-title="$t('streamButtons.view_collection')" :link="{ name: 'landing-page.merchandise.shop' }"></custom-button>
            </div>
          </div>
        </b-col>
        <b-col lg="6" md="6">
          <div class="categorie-about-right">
            <div class="categorie-about-image">
              <img src="/assets/images/shop/card/deadpool.webp" class="img-fluid" loading="lazy" />
            </div>
            <div class="text-left mb-4 pt-3">
              <h4 class="mb-2 line-count-1">{{ $t('streamShop.deadpool') }}</h4>
              <p class="mb-4 mt-2 line-count-3">{{ $t('streamShop.lorem_ipsum') }}</p>
              <custom-button :not-btncaret-icon="true" :button-title="$t('streamButtons.view_collection')" :link="{ name: 'landing-page.merchandise.shop' }"></custom-button>
            </div>
          </div>
        </b-col>
      </b-row>
    </b-container>
  </section>
  <section
    class="section-padding merchandise-section"
    :style="{
      backgroundImage: `url(${generateImgPath('/assets/images/shop/card/bg-img.webp')})`,
      backgroundPosition: 'center center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
    }">
    <b-container fluid>
      <b-row class="align-items-center">
        <b-col lg="6" md="6" cols="12">
          <img src="/assets/images/shop/card/multipal.webp" class="img-fluid" alt="img" loading="lazy" />
        </b-col>
        <b-col lg="6" md="6" cols="12" class="mt-4 mt-md-0">
          <!--Logo -->
          <brand-logo></brand-logo>
          <h2 class="mt-3 mb-4 pb-2">{{ $t('streamShop.wear_streamit') }}</h2>
          <p class="mb-4 line-count-3">{{ $t('streamShop.buy_exclusive') }}</p>
          <custom-button :not-btncaret-icon="true" :button-title="$t('streamButtons.shop_now')" :link="{ name: 'landing-page.merchandise.shop.detail' }"></custom-button>
        </b-col>
      </b-row>
    </b-container>
  </section>
  <div class="best-product-block section-padding-top">
    <b-container fluid>
      <div class="overflow-hidden">
        <ProductSection :not-want-more-btn="false" title="sectionTitle.best_sellers"></ProductSection>
      </div>
    </b-container>
  </div>
  <div class="product_container">
    <b-row class="gx-0">
      <b-col lg="6" class="shop-contact-one">
        <a href="javascript:void(0);">
          <div class="channel-logo">
            <h3>{{ $t('streamShop.our_multiple') }}</h3>
          </div>
        </a>

        <b-row class="my-4">
          <b-col lg="6" md="6">
            <h5 class="mb-2">{{ $t('streamAccount.australia') }}:</h5>
            <p>24 Isaac Road. Ellendale, Tasmania 7140</p>
          </b-col>
          <b-col lg="6" md="6">
            <h5 class="mb-2">{{ $t('streamAccount.australia') }}:</h5>
            <p>2118 {{ $t('streamShop.thornridge_cir') }} 35624</p>
          </b-col>
        </b-row>
        <div class="d-flex align-items-md-center flex-column flex-md-row gap-3">
          <h5 class="m-0">{{ $t('streamShop.working_hours') }}:</h5>
          <i class="text-primary shop_store_time"> Mon – Fri : 09:00 AM to 06:00 PM</i>
        </div>
      </b-col>
      <b-col lg="6" class="shop-contact">
        <img class="img-fluid h-100 w-100" src="/assets/images/shop/card/location.webp" alt="img" loading="lazy" />
      </b-col>
    </b-row>
  </div>
</template>
<script setup>

import ProductSection from '../../components/sections/ProductSection.vue';
import { generateImgPath } from '../../StaticData/data';
import { Navigation } from 'swiper';
// Swiper Components Import

import { Swiper, SwiperSlide } from 'swiper/vue';
import { heroSlider } from '../../StaticData/shop';
import { ref, computed, watch } from 'vue';
import { useSetting } from '../../store/setting/index';
const store = useSetting();
const rtl = computed(() => store.theme_scheme_direction_value);
const render = ref(true);

watch(
  () => rtl.value,
  () => {
    render.value = false;
    setTimeout(() => {
      render.value = true;
    }, 0);
  }
);
const modules = [Navigation];

</script>
