// tamplate/streamithtml-540/streamit-html/code-next/src/app/(frontend-pages)/movies/related/page.tsx
"use client"

import React, { Fragment, memo, useRef } from "react";

//react-bootstrap
import { Row, Col, Container, Nav, Tab, Form } from "react-bootstrap";

//router
import Link from "next/link";

//componentsplayou
import ReviewComponent from "@/components/ReviewComponent";
import Sources from "@/components/Sources";
import MoviesRecommendedForYou from "@/components/sections/MoviesRecommendedForYou";
import RelatedVideos from "@/components/sections/RelatedVideos";
import ProductCard from "@/components/merchandise/product-card";
import UpcomingMovies from "@/components/sections/UpcomingMovies";
import RelatedMovies from "@/components/sections/RelatedMovies";
import VideoJS from "@/components/plugins/VideoJs";
import FsLightBox from "@/components/fslight-box";
import RatingStar from "@/components/rating-star";

//static data
import { related_merchandise_product } from "@/StaticData/shop";

//function
import { MovieDetail_recommendedforYou, crew, detailpage_related_video, upcoming_recommended_movies, upcoming_related_video } from "@/StaticData/data";

//utilities
import { useEnterExit } from "@/utilities/usePage";

//swiper
import { Swiper, SwiperSlide } from "swiper/react";

// @ts-ignore
import { Navigation } from "swiper";

//hook
import { useTranslation } from 'react-i18next';
import Video from "@/components/video/video";
import Details_Part from "@/components/details_part";
import YourFavouritePersonality from "@/components/sections/YourFavouritePersonality";
import { useSelector } from "react-redux";
import { theme_scheme_direction } from "@/store/setting/selectors";
import Review_Details from "@/components/review/review_details";


const RelatedPage = memo(() => {
    const { t } = useTranslation("common");
    // date, type
 const themeSchemeDirection = useSelector(theme_scheme_direction);
 
    return (
        <Fragment>
          <div className="poition-relative">
        <div className="iq-main-slider site-video position-relative">
          <Video videolink="https://www.youtube.com/watch?v=spGSAeqxVUc" posterlink=""></Video>
        </div>
        <div className="movie-detail-part position-relative">
          <div className="trending-info pt-0 pb-0">
            <div className="details-parts">
              <Details_Part
                title={"streamMovies.dinoosaur"}
                subsribe_to_watch={true}
                isplaylist={true}
                isdownload={true}
                year={2001}
                time={"2hr : 17m"}
                views={"1.0k"}
                imdbratting={5}
                cencerratting={true}
              />
            </div>
          </div>
        </div>
      </div>
      <Container fluid>
        <div className="overflow-hidden">
            <div className="section-padding-top">
                <MoviesRecommendedForYou
                title={"sectionTitle.recommended"}
                list={MovieDetail_recommendedforYou}
                viewAll={false}
              />
          </div>
          <YourFavouritePersonality title={"sectionTitle.starring"} slidePerView={11} />
          <YourFavouritePersonality
            title={"sectionTitle.crew"}
            list={crew}
            slidePerView={11}
          />
          <MoviesRecommendedForYou
            list={upcoming_recommended_movies}
            title={"sectionTitle.related_movies"}
            viewAll={false}
            loop={false}
          />
          <MoviesRecommendedForYou
            list={detailpage_related_video}
            title={"sectionTitle.related_videos"}
            viewAll={false}
            loop={false}
          />

          <div className="best-product-block">
            <div className="d-flex align-items-center justify-content-between mb-3">
              <h4 className="main-title text-capitalize mb-0">
                {t("sectionTitle.related_products")}
              </h4>
            </div>
            <div className="card-style-slider">
              <Swiper
                key={themeSchemeDirection.toString()}
                dir={themeSchemeDirection.toString()}
                slidesPerView={6}
                navigation={{
                  prevEl: ".swiper-button-prev",
                  nextEl: ".swiper-button-next",
                }}
                loop={true}
                speed={1500}
                modules={[Navigation]}
                wrapperTag="ul"
                className="position-relative swiper-card wrapper-class merch-slides"
                // wrapperclassName="p-0 m-0  list-inline"
                breakpoints={{
                  0: {
                    slidesPerView: 2,
                    spaceBetween: 0,
                  },
                  576: {
                    slidesPerView: 2,
                    spaceBetween: 0,
                  },
                  768: {
                    slidesPerView: 3,
                    spaceBetween: 0,
                  },
                  1025: {
                    slidesPerView: 5,
                    spaceBetween: 0,
                  },
                  1500: {
                    slidesPerView: 5,
                    spaceBetween: 0,
                  },
                }}
              >
                {related_merchandise_product.map((item:any, index) => {
                  return (
                    <SwiperSlide tag="li" key={index}>
                      <ProductCard
                        thumbnail={item.thumbnail}
                        product_name={t(item.product_name)}
                        price={item.price}
                        final_price={item.final_price}
                        rating="5"
                        count1="0"
                        is_sale={item.is_sale}
                        is_new={item.is_new}
                        slug={item.slug}
                      />
                    </SwiperSlide>
                  );
                })}
                <div className="swiper-button swiper-button-next"></div>
                <div className="swiper-button swiper-button-prev"></div>
              </Swiper>
            </div>
          </div>

          <UpcomingMovies
            list={upcoming_related_video}
            viewAll={false}
            title="sectionTitle.upcoming"
          />

          <section className="mb-5">
            <div className="show-episode section-padding-bottom">
              <Review_Details />
            </div>
          </section>
        </div>
      </Container>
        </Fragment>
    );
});

RelatedPage.displayName = "RelatedPage";
export default RelatedPage;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/movies/related.vue
<template>
  <div class="poition-relative">
    <div class="iq-main-slider site-video position-relative">
      <!-- Banner Start -->
      <VideoPlayer :options="playerOption"></VideoPlayer>
      <!-- Banner End -->
    </div>
    <div class="movie-detail-part position-relative">
      <div class="trending-info pt-0 pb-0">
        <div class="details-parts">
          <MovieDescription :video-url="{ name: 'movies-detail' }" movie-name="streamMovies.chosfies" movie-type="NC-17"
            movie-duration="2hr : 6m" movie-released="2021" view-number="1.4k" :movie-views="$t('streamKeyword.views')"
            imdb-rating="7" movie-description></MovieDescription>
        </div>
      </div>
    </div>
  </div>

  <b-container fluid>
    <div class="overflow-hidden">
      <div class="recommended-block section-padding-top">
        <MoviesRecommendedForYou :title="$t('sectionTitle.recommended')" :list="relatedRecommended" :slides-per-view="6"
          :loop="false">
        </MoviesRecommendedForYou>
      </div>

      <!-- Starring start -->
      <div class="favourite-person-block">
        <div class="overflow-hidden">
          <div class="d-flex align-items-center justify-content-between px-1 mb-2 pb-1 mb-md-4 pb-md-0">
            <h4 class="main-title text-capitalize mb-0">{{ $t('sectionTitle.starring') }}</h4>
          </div>

          <Swiper :dir="rtl" :slides-per-view="11" :space-between="0" :loop="false"
            :navigation="{ prevEl: '.swiper-button-prev', nextEl: '.swiper-button-next' }" :pagination="true"
            :modules="modules" :breakpoints="{
              320: { slidesPerView: 2 },
              576: { slidesPerView: 2 },
              768: { slidesPerView: 4 },
              1024: { slidesPerView: 11 },
            }" class="position-relative swiper swiper-card wrapper-class personality-card">
            <SwiperSlide v-for="(cast, index) in castList" :key="index" class="swiper-slide">
              <PersonalityCard :image="cast.image" :title="$t(cast.title)" :category="$t(cast.category)" />
            </SwiperSlide>

            <div class="swiper-button swiper-button-next d-none d-lg-block"></div>
            <div class="swiper-button swiper-button-prev d-none d-lg-block"></div>
          </Swiper>
        </div>
      </div>

      <!-- Crew start -->
      <div class="favourite-person-block">
        <div class="overflow-hidden">
          <div class="d-flex align-items-center justify-content-between px-1 mb-2 pb-1 mb-md-4 pb-md-0">
            <h4 class="main-title text-capitalize mb-0">{{ $t('sectionTitle.crew') }}</h4>
          </div>

          <Swiper :dir="rtl" :slides-per-view="11" :space-between="0" :loop="false"
            :navigation="{ prevEl: '.swiper-button-prev', nextEl: '.swiper-button-next' }" :pagination="true"
            :modules="modules" :breakpoints="{
              320: { slidesPerView: 2 },
              576: { slidesPerView: 2 },
              768: { slidesPerView: 4 },
              1024: { slidesPerView: 11 },
            }" class="position-relative swiper swiper-card wrapper-class personality-card">
            <SwiperSlide v-for="(cast, index) in crewList" :key="index" class="swiper-slide">
              <PersonalityCard :image="cast.image" :title="$t(cast.title)"
                :other-category="$t(cast.otherCategory || '')" :category="$t(cast.category)" />
            </SwiperSlide>

            <div class="swiper-button swiper-button-next d-none d-lg-block"></div>
            <div class="swiper-button swiper-button-prev d-none d-lg-block"></div>
          </Swiper>
        </div>
      </div>

      <MoviesRecommendedForYou :title="$t('sectionTitle.recommended_movie')" :list="relatedRecommendedMovies"
        :slides-per-view="6" :loop="false">
      </MoviesRecommendedForYou>


      <div class="video-block">
        <RelatedMovies :title="$t('sectionTitle.related_videos')" :list="relatedMerchandiseVideos" :slides-per-view="6">
        </RelatedMovies>
      </div>

      <div class="related-product-block">
        <ProductSection :title="$t('sectionTitle.related_products')" :slides-per-view="6" :not-want-more-btn="false"
          padding-top="px-1 mb-2 pb-1 mb-md-4 pb-md-0"></ProductSection>
      </div>

      <div class="upcomimg-block">
        <UpcomingMovies :title="$t('sectionTitle.upcoming')" :list="upcomingRestricted" padding-top="paddingTop">
        </UpcomingMovies>
      </div>

      <div class="section-padding-bottom">
        <DetailsReview></DetailsReview>
      </div>
    </div>
  </b-container>
</template>

<script setup>
import { computed, ref } from 'vue';
// plugins
import { Swiper, SwiperSlide } from 'swiper/vue';
import { Navigation } from 'swiper';
import MoviesRecommendedForYou from '~/components/sections/MoviesRecommendedForYou.vue';
import UpcomingMovies from '~/components/sections/UpcomingMovies.vue';
import ProductSection from '~/components/sections/ProductSection.vue';
import VideoPlayer from '~/components/plugins/VideoPlayer.vue';
import { relatedRecommended, relatedRecommendedMovies, relatedMerchandiseVideos, upcomingRestricted } from '~/StaticData/data';
import { useSetting } from '../../store/setting/index';
import RelatedMovies from '~/components/sections/RelatedMovies.vue';
import PersonalityCard from '~/components/cards/PersonalityCard.vue';
import DetailsReview from '~/components/widgets/DetailsReview.vue';
const store = useSetting();
const rtl = computed(() => store.theme_scheme_direction_value);

const generateImgPath = (path) => {
  return window.location.origin + path;
};

// Swiper Modules
const modules = [Navigation];

const castList = [
  { image: '/assets/images/cast/olivia-foster.webp', title: 'favouritePersonalities.olivia_foster', category: 'persondesc.actress' },
  { image: '/assets/images/cast/leena-burton.webp', title: 'favouritePersonalities.Leena_Burton', category: 'persondesc.actress' },
  { image: '/assets/images/cast/ryan-pierce.webp', title: 'favouritePersonalities.Ryan_Pierce', category: 'persondesc.actor' },
  { image: '/assets/images/cast/michael-fox.webp', title: 'favouritePersonalities.michael_fox', category: 'persondesc.producer' },
  { image: '/assets/images/cast/ruby-scott.webp', title: 'favouritePersonalities.ruby_scott', category: 'persondesc.director' },
  { image: '/assets/images/cast/maxwell-carter.webp', title: 'favouritePersonalities.maxwell_carter', category: 'persondesc.actress' },
  { image: '/assets/images/cast/mark-smith.webp', title: 'favouritePersonalities.mark_smith', category: 'persondesc.actress' },
  { image: '/assets/images/cast/ava-monroe.webp', title: 'favouritePersonalities.ava_monroe', category: 'persondesc.actress' },
  { image: '/assets/images/cast/jack-nicholson.webp', title: 'favouritePersonalities.jack_nicholson', category: 'persondesc.actor' },
  { image: '/assets/images/cast/charles-melton.webp', title: 'favouritePersonalities.charles_melton', category: 'persondesc.actor' },
  { image: '/assets/images/cast/jeff-bridges.webp', title: 'favouritePersonalities.jeff_bridges', category: 'persondesc.actor' },
  { image: '/assets/images/cast/james-stewart.webp', title: 'favouritePersonalities.james_stewart', category: 'persondesc.actor' },
  { image: '/assets/images/cast/jordan-grant.webp', title: 'favouritePersonalities.jordan_grant', category: 'persondesc.actor' },

];

const crewList = [
  {
    image: generateImgPath("/assets/images/cast/maria-rodriguez.webp"),
    title: "favouritePersonalities.maria_rodriguez",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/oliver-turner.webp"),
    title: "favouritePersonalities.Olivia_Foster",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/john-abraham.webp"),
    title: "favouritePersonalities.john_abraham",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/benjamin-hayes.webp"),
    title: "favouritePersonalities.benjamin_hayes",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/ethan-crawford.webp"),
    title: "favouritePersonalities.ethan_crawford",
    category: "persondesc.producer",
  },
  {
    image: generateImgPath("/assets/images/cast/mark-wilson.webp"),
    title: "favouritePersonalities.mark_wilson",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/jack-walker.webp"),
    title: "favouritePersonalities.jack_walker",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/millar-joseph.webp"),
    title: "favouritePersonalities.millar_joseph",
    category: "persondesc.producer",
  },
  {
    image: generateImgPath("/assets/images/cast/kelly-reilly.webp"),
    title: "favouritePersonalities.kelly_reilly",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/smith-jonas.webp"),
    title: "favouritePersonalities.smith_jonas",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/davina-decorous.webp"),
    title: "favouritePersonalities.davina_decorous",
    category: "persondesc.producer",
  },
  {
    image: generateImgPath("/assets/images/cast/thomas-bailey.webp"),
    title: "favouritePersonalities.thomas_bailey",
    category: "persondesc.producer",
  },
  {
    image: generateImgPath("/assets/images/cast/leena-burton.webp"),
    title: "favouritePersonalities.Leena_Burton",
    category: "persondesc.director",
  },
];

const playerOption = ref({
  autoplay: true,
  controls: true,
  muted: true,
  loop: true,
  preload: 'auto',
  techOrder: ['youtube'],
  sources: [
    {
      src: 'https://www.youtube.com/watch?v=spGSAeqxVUc',
      type: 'video/youtube',
    },
  ],
  youtube: {
    modestbranding: 1,
    rel: 0,
    showinfo: 0,
    autoplay: 1,
  },
  fullscreen: true,
  poster: 'https://i.ytimg.com/vi_webp/rKVEoyTedv4/maxresdefault.webp',
});
</script>
