// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/Movies/MoviePlayer.vue
<template>
  <div>
    <!-- Back Button -->
    <div class="back-btn">
      <RouterLink
        class="btn btn-link text-white text-decoration-none p-0"
        to="/video-detail"
      >
        <i class="ph ph-x"></i>
      </RouterLink>
    </div>

    <!-- Video Player -->
    <div class="video-container">
      <video
        id="my-video"
        class="video-js vjs-big-play-centered"
        controls
        preload="auto"
        width="960"
        height="540"
        poster="/assets/images/player/player-poster.webp"
        data-setup="{}"
      >
        <source src="/assets/images/player/demo_videos.mp4" type="video/mp4" />
      </video>
    </div>
  </div>
</template>

<script>
export default {
  name: 'MoviePlayer'
};
</script>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/(blank-pages)/movie-player/page.tsx
"use client"

import React, { memo, Fragment } from "react";

import { Container } from "react-bootstrap";

import Link from "next/link";



const Movie_Player = memo(() => {  
    return(
        <Fragment>
                 <Container>
              <div className="back-btn">
                  <Link className="btn btn-link text-white text-decoration-none p-0" href="/movies/detail">
                      <i className="ph ph-x"></i>
                  </Link>
              </div>
              <div className="video-container">
                  <video
                      id="my-video"
                      className="video-js vjs-big-play-centered"
                      controls
                      preload="auto"
                      width="960"
                      height="540"
                      poster="/assets/images/player/player-poster.webp"
                      data-setup='{}'>
                      <source src="/assets/images/player/demo_videos.mp4" type="video/mp4" />
                  </video>
              </div>
          </Container>
        </Fragment>
    )
});

export default Movie_Player;
