// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/sections/MoviesRecommendedForYou.jsx
import { useState, Fragment, memo } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { recommendedforYou } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const MoviesRecommendedForYou = memo((props) => {
  const { t } = useTranslation();

  const recommended = t(props.title) || t("sectionTitle.movies_recommended")
  const data = props.data || recommendedforYou
  const loops = props.loop !== undefined  ? false : true
  // console.log(loops)

  return (
    <Fragment>
      <SectionSlider
        title={recommended}
        list={data}
        className="recommended-block"
        slidesPerView={props.slides || 6}
        wrapperClass={true}
        viewAll={props.viewAll}
        slideMedium={props.slideMedium}
        paddingY={props.paddingY}
        // loop={loops}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            slug={data.slug}
            lang={data.lang}
            productPremium={data.productPremium}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

MoviesRecommendedForYou.displayName = "MoviesRecommendedForYou";
export default MoviesRecommendedForYou;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/sections/MoviesRecommendedForYou.vue
<template>
  <!-- Movies Recommended For You start -->
  <SectionSlider :title="$t(props.title)" :list="recommendedforYou" :slides-per-view="5"
    margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0" :wrapper-class="true">
    <template #headerLink>
      <nuxt-link :to="{ name: 'view-all' }"
        class="text-primary iq-view-all text-decoration-none flex-none">{{ props.view }}</nuxt-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :title="$t(data.title)" :card-lang="data.cardLang"
        :product-premium="data.productPremium" :watchlist-link="{ name: '/play-list' }"
        :link="{ name: 'movies-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Movies Recommended For You end -->
</template>

<script setup>
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { recommendedforYou } from '~/StaticData/data';

const props = defineProps({
  title: { type: String, default: 'sectionTitle.movies_recommended' },
  view: { type: String, default: '' },
  marginPadding: { type: String, default: '' },
  paddingTop: { type: String, default: '' },
});
</script>
