// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/sections/Specials&LatestMovies.jsx
import { useState, Fragment, memo } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyleTwo from "../cards/CardStyleTwo";

//static data
import { spacialLatestMovie } from "../../StaticData/data";
// the hook
import { useTranslation } from "react-i18next";

const SpecialsLatestMovies = memo((props) => {
  const { t } = useTranslation();
  const [title] = useState(t("sectionTitle.specials_latest_movies"));

  const list = props.list !== undefined && props.list !== null ? props.list : spacialLatestMovie
  const titles = props.title !== undefined && props.title !== null ? props.title : title
  const loops = props.loop !== undefined && props.loop !== null ? props.loop : true
  const slidesPerView = props.slidesPerView || 6
  return (
    <Fragment>
      <SectionSlider
        title={t(titles)}
        list={list}
        className="recommended-block streamit-block"
        paddingY={props.paddingY}
        loop={loops}
        slidesPerView={slidesPerView}
      >
        {(data) => (
          <CardStyleTwo
            image={data.image}
            title={data.title}
            lang={data.lang}
            slug={data.slug}
            movieTime={data.movieTime}
            watchlistLink="/playlist"
            link="/movies-detail"
            productPremium={data.productPremium}
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

SpecialsLatestMovies.displayName = "SpecialsLatestMovies";
export default SpecialsLatestMovies;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/sections/Specials&LatestMovies.vue
<template>
  <!-- Specials & Latest Movies start -->
  <SectionSlider :title="$t(title)" :list="spacialLatestMovie" :slides-per-view="6"
    class="recommended-block section-wraper streamit-block" margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <nuxt-link :to="{ name: 'view-all' }"
        class="text-primary iq-view-all text-decoration-none flex-none">{{ $t('sectionTitle.view_all') }}</nuxt-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :is-card-style2="true" :title="$t(data.title)"
        :product-premium="data.productPremium" :is-not-lang-card="true" :watchlist-link="{ name: '/play-list' }"
        :link="{ name: 'movies-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Specials & Latest Movies end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { spacialLatestMovie } from '../../StaticData/data';
const title = ref('sectionTitle.specials_latest_movies');
</script>
