// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/sections/SuggestedBlock.tsx
import { Fragment, memo, useState } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { suggested } from "../../StaticData/data";

//hook
import { useTranslation } from 'react-i18next';

const SuggestedBlock = memo(() => {
    const { t } = useTranslation("common");

  return (
    <Fragment>
      <SectionSlider
        title={t("sectionTitle.suggested_block")}
        list={suggested}
        className="suggested-block streamit-block"
        slidesPerView={6}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            watchlistLink="/play-list"
            link="/movies/detail"
            conturyname={data.conturyname}
            slug={data.slug}
            lang={data.lang}
            playNowLink={data.playNowLink || "/"}
            productPremium={data.productPremium}
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

SuggestedBlock.displayName = 'SuggestedBlock';
export default SuggestedBlock;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/sections/SuggestedBlock.vue
<template>
  <!-- Suggested-Block start -->
  <SectionSlider :title="$t(title)" :list="suggested" :slides-per-view="6" class="suggested-block streamit-block"
    margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <nuxt-link :to="{ name: 'view-all' }" class="text-primary iq-view-all text-decoration-none flex-none">{{
        $t('sectionTitle.view_all') }}</nuxt-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :title="$t(data.title)" :card-lang="data.cardLang"
        :watchlist-link="{ name: '/play-list' }" :link="{name: 'movies-detail'}"
        :product-premium="data.productPremium"></card-style>
    </template>
  </SectionSlider>
  <!-- Suggested-Block end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { suggested } from '../../StaticData/data';
const title = ref('sectionTitle.suggested_block');
</script>
