// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/sections/TVPopularShows.tsx
import { useState, Fragment, memo } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { populerSlider } from "../../StaticData/data";

//hook
import { useTranslation } from 'react-i18next';
import CardStyleTwo from "../cards/CardStyleTwo";
interface ListItem {
  image: string;
  title: string;
  slug: string[];
  lang: string;
  productPremium: boolean;
}
interface Props {
  list?: ListItem[]; 
  title?: string;
  loop?: boolean;
  slidesPerView?: number;
  viewAll ?: boolean
  link ?: string
}

const TVPopularShows = memo((props:Props) => {
  const { t } = useTranslation("common");
  const [title] = useState(t("sectionTitle.tv_popular_shows"));
  const list = props.list ?? populerSlider;

  return (
    <Fragment>
      <SectionSlider
        title={t("sectionTitle.tv_popular_shows")}
        list={list}
        className="recommended-block section-top-spacing"
        wrapperClass={true}
        viewAll={props.viewAll}

      >
        {(data) => (
          <CardStyleTwo
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            watchlistLink="/play-list"
            linkPath={props.link || "/movies/detail"}
            slug={data.slug}
            lang={data.lang}
            playNowLink={"/"}
            conturyname={data.conturyname}
            productPremium={data.productPremium}
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

TVPopularShows.displayName = "TVPopularShows";
export default TVPopularShows;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/sections/TVPopularShows.vue
<template>
  <!-- Only on streamit start -->
  <SectionSlider :title="$t(title)" :list="topTen" :slides-per-view="6" :loop="false"
    class="recommended-block section-top-spacing section-wraper streamit-block"
    margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <nuxt-link :to="{ name: 'view-all' }" class="text-primary iq-view-all text-decoration-none flex-none">{{
        $t('sectionTitle.view_all') }}</nuxt-link>
    </template>
    <template #default="{ data }">
      <card-style :is-card-style2="true" :image="data.image" :product-premium="data.productPremium"
        :is-not-lang-card="true" :title="$t(data.title)" :watchlist-link="{ name: '/play-list' }"
        :link="{ name: 'tv-shows-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Only on streamit end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';

import { TVPopularShows } from '../../StaticData/data';
const title = ref('sectionTitle.popular_tv_shows');
const topTen = ref(TVPopularShows);
</script>
