// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/sections/UpcomingMovies.jsx
import { Fragment, memo, useState } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../../components/cards/CardStyle";

//data
import { upcomingVideo } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const UpcomingMovies = memo((props) => {
  const { t } = useTranslation();
  const [upcommingMovie2] = useState(upcomingVideo);

  const upcoming = t(props.title) || t("sectionTitle.upcoming_video")

  return (
    <Fragment>
      <SectionSlider
        title={upcoming}
        list={props.data}
        className="upcomimg-block streamit-block"
        slidesPerView={props.slides || 6}
        viewAll={props.viewAll}
        slideMedium={props.slideMedium}
        paddingY={props.paddingY}
        loop={false}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            lang={data.lang}
            slug={data.slug}
            productPremium={data.productPremium}
            conturyname={data.conturyname}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

upcomingVideo.DisplayName = upcomingVideo;
export default UpcomingMovies;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/sections/UpcomingMovies.vue
<template>
  <!-- Upcoming Movies start -->
  <SectionSlider
    :title="$t(title)"
    :list="upComing"
    :slides-per-view="6"
    :loop="false"
    class="streamit-block"
    margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0"
  >
    <template #headerLink>
      <nuxt-link
        :to="{ name: 'view-all' }"
        class="text-primary iq-view-all text-decoration-none flex-none"
        >{{ $t("sectionTitle.view_all") }}</nuxt-link
      >
    </template>
    <template #default="{ data }">
      <card-style
        :image="data.image"
        :title="$t(data.title)"
        :product-premium="data.productPremium"
        :watchlist-link="{ name: '/play-list' }"
        :link="{name: 'movies-detail'}"
        :card-lang="data.cardLang"
      ></card-style>
    </template>
  </SectionSlider>
  <!-- Upcoming Movies end -->
</template>

<script setup>
import { ref } from "vue";
import SectionSlider from "../slider/SectionSlider.vue";
import CardStyle from "../cards/CardStyle.vue";

import { upcommingMovie } from "../../StaticData/data";
const title = ref("sectionTitle.upcoming_movies");
const upComing = ref(upcommingMovie);
</script>
dvd
