// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/blog/sidebar/TagsWidget.tsx
import React, { Fragment, memo } from 'react'

//react-router-dom
import Link from "next/link";

//static data
import { blogTags } from '../../../StaticData/blogs'

//hook
import { useTranslation } from 'react-i18next';

const TagsWidget = memo(() => {
  const { t } = useTranslation("common");
  return (
    <Fragment>
      <div id="tag_cloud-2" className="widget">
        <h5 className="widget-title position-relative">{t("streamPages.tags")}</h5>
        <div className="tagcloud">
          <ul className="p-0 m-0 list-unstyled widget_tags">
            {blogTags.map((tags, index) => {
              return (
                <li key={index}>
                  <Link href="/blogs/blog-tag" className="position-relative text-capitalize">
                    {t(tags.name)}
                  </Link>
                </li>
              );
            })}
          </ul>
        </div>
      </div>
    </Fragment>
  )
})

TagsWidget.displayName = "TagsWidget"
export default TagsWidget

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/blog/sidebar/TagsWidget.vue
<template>
  <div id="tag_cloud-2" class="widget">
    <h5 class="widget-title">{{ $t('streamTag.tags') }}</h5>
    <ul class="p-0 m-0 list-unstyled widget_tags">
      <li v-for="tag in blogTags" :key="tag" class="text-capitalize">
        <router-link to="/blogs-tag" class="position-relative"> {{ $t(tag.name) }} </router-link>
      </li>
    </ul>
  </div>
</template>
<script setup>
import { blogTags } from '../../../StaticData/blogs'; 
</script>
