// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/MainPages/IndexPage.vue
<template>
  <section>
    <HomeHeroSlider></HomeHeroSlider>
  </section>

  <b-container fluid>
    <div class="overflow-hidden">
      <section class="continue-watching-block home-continue-watch section-padding-top">
        <ContinueWatching></ContinueWatching>
      </section>

  <UpcomingMovies :notview-all-btn="true" :view="'sectionTitle.view_all'" :slides-per-view="6"></UpcomingMovies>

  <FreshPicksJustForYou :title="$t('sectionTitle.best_in_tv')"></FreshPicksJustForYou>

      <LatestMovies :slider-data="latestMovie" :notview-all-btn="true"></LatestMovies>
    </div>
  </b-container>

  <VerticalSectionSlider :slider-data="ottVerticleLatestMovies"></VerticalSectionSlider>

  <b-container fluid>
    <div class="overflow-hidden">
  <SuggestedBlock  :notview-all-btn="true"></SuggestedBlock>
    </div>
  </b-container>

  <ParallexSection></ParallexSection>

  <TrendingSection></TrendingSection>

  <b-container fluid>
    <div class="overflow-hidden">
      <RecommendedTVShow :notview-all-btn="true"></RecommendedTVShow>
    </div>
  </b-container>
</template>
<script setup>
// Hero Slider
import HomeHeroSlider from '../../components/slider/HomeHeroSlider.vue';

// Sections
import TrendingSection from '../../components/sections/TrendingSection.vue';
import ContinueWatching from '../../components/sections/ContinueWatching.vue';
import UpcomingMovies from '../../components/sections/UpcomingMovies.vue';
import LatestMovies from '../../components/sections/LatestMovies.vue';
import SuggestedBlock from '../../components/sections/SuggestedBlock.vue';
import RecommendedTVShow from '../../components/sections/RecommendedTVShow.vue';
import ParallexSection from '../../components/sections/ParallexSection.vue';
import VerticalSectionSlider from '../../components/slider/VerticalSectionSlider.vue';

import { ottVerticleLatestMovies, latestMovie } from '../../StaticData/data';
import FreshPicksJustForYou from '../../components/sections/FreshPicksJustForYou.vue';
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/MainPages/IndexPage.jsx
import { memo } from "react";

// hero slider
import HomeHeroSlider from "../../components/slider/HomeHeroSlider";

// sections
import ContinueWatching from "../../components/sections/ContinueWatching";
import UpcomingMovies from "../../components/sections/UpcomingMovies";
import LatestMovies from "../../components/sections/LatestMovies";
import VerticalSectionSlider from "../../components/slider/VerticalSectionSlider";
import TrendingSlider from "../../components/sections/Trending";
import SuggestedBlock from "../../components/sections/SuggestedBlock";
import RecommendedTVShow from "../../components/sections/RecommendedTVShow";
import ParallexSection from "../../components/sections/ParallexSection";

//static data
import {
  ottVerticleLatestMovies,
  latestMovie,
  best_in_tv, upcommingMovie , recommendedforYou
} from "../../StaticData/data";
import { Container } from "react-bootstrap";

import SpecialsLatestMovies from "../../components/sections/Specials&LatestMovies";

const HomePage = memo(() => {
  const showViewAllLink = true;
  return (
    <>
      <HomeHeroSlider />
      <Container fluid>
        <div className="overflow-hidden">
          <ContinueWatching slidesPerView={6} />
          <UpcomingMovies data={upcommingMovie} title={"sectionTitle.upcoming_movies"} viewAll={false}/>
          <SpecialsLatestMovies list={best_in_tv} title="sectionTitle.best_in_tv"/>
          <LatestMovies sliderData={latestMovie}  viewAll={false}/>
        </div>
      </Container>
      <VerticalSectionSlider sliderData={ottVerticleLatestMovies} />
      <Container fluid>
        <div className="overflow-hidden">
          <SuggestedBlock  />
        </div>
      </Container>

      <ParallexSection />

      <TrendingSlider />
      <Container fluid>
        <div className="overflow-hidden">
          <RecommendedTVShow data={recommendedforYou} viewAll={false}/>
        </div>
      </Container>
    </>
  );
});

HomePage.displayName = "HomePage";
export default HomePage;
