// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/MainPages/OTTPage.vue
<template>
  <OttHeroSlider></OttHeroSlider>

  <b-container fluid>
    <div class="overflow-hidden">
      <section class="continue-watching-block home-continue-watch section-padding-top">
        <ContinueWatching></ContinueWatching>
      </section>

      <TopTenToWatch  :data="top_ten_movie" :wrapper-class="true"></TopTenToWatch>

      <OnlyOnStreamit></OnlyOnStreamit>

      <FreshPicksJustForYou></FreshPicksJustForYou>

      <UpcomingMovies></UpcomingMovies>

    </div>
  </b-container>

  <VerticalSectionSlider :slider-data="ottVerticleLatestMovies"></VerticalSectionSlider>

  <b-container fluid>
    <div class="overflow-hidden">
      <YourFavouritePersonality></YourFavouritePersonality>

      <PopularMovies></PopularMovies>
    </div>
  </b-container>

  <TabSlider :wrapper-class="true"></TabSlider>

  <b-container fluid>
    <div class="overflow-hidden">
      <div class="movie-geners-block">
        <MovieGeners padding-top="paddingTop"></MovieGeners>
      </div>

      <RecommendedForYou :data="recommendedforYou" />

      <TopPicsForYou></TopPicsForYou>
    </div>
  </b-container>
</template>
<script setup>
// Hero Slider
import OttHeroSlider from '../../components/slider/OttHeroSlider.vue';

// Sections
import ContinueWatching from '../../components/sections/ContinueWatching.vue';
import TopTenToWatch from '../../components/sections/TopTenToWatch.vue';
import RecommendedForYou from '../../components/sections/RecommendedForYou.vue';
import OnlyOnStreamit from '../../components/sections/OnlyOnStreamit.vue';
import PopularMovies from '../../components/sections/PopularMovies.vue';
import YourFavouritePersonality from '../../components/sections/YourFavouritePersonality.vue';
import TopPicsForYou from '../../components/sections/TopPicsForYou.vue';
import VerticalSectionSlider from '../../components/slider/VerticalSectionSlider.vue';
import TabSlider from '../../components/sections/TabSlider.vue';
import MovieGeners from '../../components/sections/MovieGeners.vue';
import UpcomingMovies from '../../components/sections/UpcomingMovies.vue';
import FreshPicksJustForYou from '../../components/sections/FreshPicksJustForYou.vue';
// StaticData
import { top_ten_movie, ottVerticleLatestMovies, recommendedforYou } from '../../StaticData/data';
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/MainPages/OTTPage.jsx
import { memo, Fragment } from "react";
// hero slider
import OttHeroSlider from "../../components/slider/OttHeroSlider";

// sections
import ContinueWatching from "../../components/sections/ContinueWatching";
import TopTenMoviesToWatch from "../../components/sections/TopTenMoviesToWatch";
import VerticalSectionSlider from "../../components/slider/VerticalSectionSlider";
import OnlyOnStreamit from "../../components/sections/OnlyOnStreamit";
import YourFavouritePersonality from "../../components/sections/YourFavouritePersonality";
import PopularMovies from "../../components/sections/PopularMovies";
import TabSlider from "../../components/sections/TabSlider";
import RecommendedForYou from "../../components/sections/RecommendedForYou";
import TopPicsForYou from "../../components/sections/TopPicsForYou";
import GenreSlider from "../../components/sections/GenreSlider";

//static data
import { best_in_tv, ottVerticleLatestMovies } from "../../StaticData/data";
import UpcomingMovies from "../../components/sections/UpcomingMovies";
import { Container } from "react-bootstrap";

import { top_ten_movie, upcommingMovie , recommendedforYou} from "../../StaticData/data";
import SpecialsLatestMovies from "../../components/sections/Specials&LatestMovies";

const HomePage = memo(() => {
  return (
    <Fragment>
      <OttHeroSlider />
      <Container fluid>
        <div className="overflow-hidden">
          <ContinueWatching slidesPerView={6} />
          <TopTenMoviesToWatch data={top_ten_movie} title={"sectionTitle.top_10_movies_to_watch"} viewAll={false}/>
          <OnlyOnStreamit />
          <SpecialsLatestMovies list={best_in_tv} title = "sectionTitle.fresh_picks" loop={false}/>
          <UpcomingMovies data={upcommingMovie} title={"sectionTitle.upcoming_movies"}/>
        </div>
      </Container>
      <VerticalSectionSlider sliderData={ottVerticleLatestMovies} />
      <Container fluid>
        <div className="overflow-hidden">
          <YourFavouritePersonality  />
          <PopularMovies  />
        </div>
      </Container>
      <TabSlider />
      <Container fluid>
        <div className="overflow-hidden">
          <GenreSlider />
          <RecommendedForYou data={recommendedforYou} />
          <TopPicsForYou />
        </div>
      </Container>
    </Fragment>
  );
});

HomePage.displayName = "HomePage";
export default HomePage;
