// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/movies/detail.vue
<template>
  <div class="poition-relative">
    <div class="iq-main-slider site-video position-relative">
      <!-- Banner Start -->
      <VideoPlayer :options="playerOption"></VideoPlayer>
      <!-- Banner End -->
    </div>
    <div class="movie-detail-part position-relative">
      <div class="trending-info pt-0 pb-0">
        <div class="details-parts">
          <MovieDescription movie-name="streamMovies.game_of_heros" :video-url="{name: 'movies-player'}" movie-type="NC-17" movie-duration="2hr : 6mins"
            movie-released="2021" view-number="284" :movie-views="$t('streamKeyword.views')" imdb-rating="7"
            movie-language="English" movie-description></MovieDescription>
        </div>
      </div>
    </div>
  </div>

  <b-container fluid>
    <div class="overflow-hidden">
      <!-- Movies Recommended For You Start  -->
      <section class="recommended-block section-padding-top">
        <MoviesRecommendedForYou :title="$t('sectionTitle.recommended')" :list="RecommendedDownloaded" :slides-per-view="6" :loop="false">
        </MoviesRecommendedForYou>
      </section>

      <!-- Starring start -->
      <div class="favourite-person-block">
        <section class="overflow-hidden">
          <div class="d-flex align-items-center justify-content-between px-1 mb-2 pb-1 mb-md-4 pb-md-0">
            <h4 class="main-title text-capitalize mb-0">{{ $t('sectionTitle.starring') }}</h4>
          </div>

          <Swiper :dir="rtl" :slides-per-view="11" :space-between="0" :loop="false"
            :navigation="{ prevEl: '.swiper-button-prev', nextEl: '.swiper-button-next' }" :pagination="true"
            :modules="modules" :breakpoints="{
              320: { slidesPerView: 2 },
              576: { slidesPerView: 2 },
              768: { slidesPerView: 4 },
              1024: { slidesPerView: 11 },
            }" class="position-relative swiper swiper-card wrapper-class personality-card">
            <SwiperSlide v-for="(cast, index) in castList" :key="index" class="swiper-slide">
              <PersonalityCard :image="cast.image" :title="$t(cast.title)" :category="$t(cast.category)" />
            </SwiperSlide>

            <div class="swiper-button swiper-button-next d-none d-lg-block"></div>
            <div class="swiper-button swiper-button-prev d-none d-lg-block"></div>
          </Swiper>
        </section>
      </div>

      <!-- Crew start -->
      <div class="favourite-person-block">
        <section class="overflow-hidden">
          <div class="d-flex align-items-center justify-content-between px-1 mb-2 pb-1 mb-md-4 pb-md-0">
            <h4 class="main-title text-capitalize mb-0">{{ $t('sectionTitle.crew') }}</h4>
          </div>

          <Swiper :dir="rtl" :slides-per-view="11" :space-between="0" :loop="false"
            :navigation="{ prevEl: '.swiper-button-prev', nextEl: '.swiper-button-next' }" :pagination="true"
            :modules="modules" :breakpoints="{
              320: { slidesPerView: 2 },
              576: { slidesPerView: 2 },
              768: { slidesPerView: 4 },
              1024: { slidesPerView: 11 },
            }" class="position-relative swiper swiper-card wrapper-class personality-card">
            <SwiperSlide v-for="(cast, index) in crewList" :key="index" class="swiper-slide">
              <PersonalityCard :image="cast.image" :title="$t(cast.title)"
                :other-category="$t(cast.otherCategory || '')" :category="$t(cast.category)" />
            </SwiperSlide>

            <div class="swiper-button swiper-button-next d-none d-lg-block"></div>
            <div class="swiper-button swiper-button-prev d-none d-lg-block"></div>
          </Swiper>
        </section>
      </div>

      <section class="related-movie-block">
        <MoviesRecommendedForYou :title="('sectionTitle.recommended_movie')" :list="RecommendedDownloadedMovie" :slides-per-view="6" :loop="false">
        </MoviesRecommendedForYou>
        <!-- <RelatedMovies :title="$t('sectionTitle.related_movies')" padding-top="paddingTop"></RelatedMovies> -->
      </section>

      <section class="video-block">
        <RelatedMovies :title="$t('sectionTitle.related_videos')" :list="detailpage_related_video" :loop="false"></RelatedMovies>
      </section>

      <div class="related-product-block related-product-slider">
        <section class="overflow-hidden">
          <div class="d-flex align-items-center justify-content-between px-1 mb-2 pb-1 mb-md-4 pb-md-0">
            <h4 class="main-title text-capitalize mb-0">{{ $t('sectionTitle.related_products') }}</h4>
          </div>
          <div class="card-style-slider">
            <Swiper :dir="rtl" tag="ul" :slides-per-view="6" :space-between="20" :loop="false" :autoplay="false"
              :navigation="{ prevEl: '.swiper-button-prev', nextEl: '.swiper-button-next' }" :modules="modules"
              :pagination="{ clickable: true }" :breakpoints="{
                0: {
                  slidesPerView: 2,
                  spaceBetween: 0,
                },
                576: {
                  slidesPerView: 2,
                  spaceBetween: 0,
                },
                768: {
                  slidesPerView: 3,
                  spaceBetween: 0,
                },
                1025: {
                  slidesPerView: 6,
                  spaceBetween: 0,
                },
                1500: {
                  slidesPerView: 6,
                  spaceBetween: 0,
                },
              }" class="position-relative swiper-card wrapper-class">
              <SwiperSlide v-for="product in products" :key="product.id" tag="li">
                <ProductCard v-bind="product"
                  :shop-title="product.shopTitle && product.shopTitle.startsWith('streamShop.') ? $t(product.shopTitle) : product.shopTitle" />
              </SwiperSlide>

              <div class="d-none d-lg-block">
                <div class="swiper-button swiper-button-next"></div>
                <div class="swiper-button swiper-button-prev"></div>
              </div>
            </Swiper>
          </div>
        </section>
      </div>

      <section class="upcomimg-block">
        <UpcomingMovies :title="$t('sectionTitle.upcoming')" :list="upcomingDownload" :notview-all-btn="true">
        </UpcomingMovies>
      </section>

      <section class="mb-5">
        <DetailsReview></DetailsReview>
      </section>
    </div>
  </b-container>
</template>

<script setup>
import { computed, ref } from 'vue';
import { Swiper, SwiperSlide } from 'swiper/vue';
import { Navigation, Autoplay } from 'swiper';

const generateImgPath = (path) => {
    return window.location.origin + path;
};
// plugins

import MoviesRecommendedForYou from '../../components/sections/MoviesRecommendedForYou.vue';
import UpcomingMovies from '../../components/sections/UpcomingMovies.vue';
import VideoPlayer from '../../components/plugins/VideoPlayer.vue';
import { useSetting } from '../../store/setting/index';
import RelatedMovies from '../../components/sections/RelatedMovies.vue';
import MovieDescription from '../../components/MovieDescription.vue';

import { RecommendedDownloaded, RecommendedDownloadedMovie, detailpage_related_video, upcomingDownload } from '../../StaticData/data';
import PersonalityCard from '../../components/cards/PersonalityCard.vue';
import DetailsReview from '../../components/widgets/DetailsReview.vue';
import ProductCard from '../../components/merchandise/ProductCard.vue';

const modules = [Navigation, Autoplay];

const castList = [
    { image: '/assets/images/cast/olivia-foster.webp', title: 'favouritePersonalities.olivia_foster', category: 'persondesc.actress' },
    { image: '/assets/images/cast/leena-burton.webp', title: 'favouritePersonalities.Leena_Burton', category: 'persondesc.actress' },
    { image: '/assets/images/cast/ryan-pierce.webp', title: 'favouritePersonalities.Ryan_Pierce', category: 'persondesc.actor' },
    { image: '/assets/images/cast/michael-fox.webp', title: 'favouritePersonalities.michael_fox', category: 'persondesc.producer' },
    { image: '/assets/images/cast/ruby-scott.webp', title: 'favouritePersonalities.ruby_scott', category: 'persondesc.director' },
    { image: '/assets/images/cast/maxwell-carter.webp', title: 'favouritePersonalities.maxwell_carter', category: 'persondesc.actress' },
    { image: '/assets/images/cast/mark-smith.webp', title: 'favouritePersonalities.mark_smith', category: 'persondesc.actress' },
    { image: '/assets/images/cast/ava-monroe.webp', title: 'favouritePersonalities.ava_monroe', category: 'persondesc.actress' },
    { image: '/assets/images/cast/jack-nicholson.webp', title: 'favouritePersonalities.jack_nicholson', category: 'persondesc.actor' },
    { image: '/assets/images/cast/charles-melton.webp', title: 'favouritePersonalities.charles_melton', category: 'persondesc.actor' },
    { image: '/assets/images/cast/jeff-bridges.webp', title: 'favouritePersonalities.jeff_bridges', category: 'persondesc.actor' },
    { image: '/assets/images/cast/james-stewart.webp', title: 'favouritePersonalities.james_stewart', category: 'persondesc.actor' },
    { image: '/assets/images/cast/jordan-grant.webp', title: 'favouritePersonalities.jordan_grant', category: 'persondesc.actor' },

];

const crewList = [
      {
    image: generateImgPath("/assets/images/cast/maria-rodriguez.webp"),
    title: "favouritePersonalities.maria_rodriguez",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/oliver-turner.webp"),
    title: "favouritePersonalities.Olivia_Foster",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/john-abraham.webp"),
    title: "favouritePersonalities.john_abraham",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/benjamin-hayes.webp"),
    title: "favouritePersonalities.benjamin_hayes",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/ethan-crawford.webp"),
    title: "favouritePersonalities.ethan_crawford",
    category: "persondesc.producer",
  },
  {
    image: generateImgPath("/assets/images/cast/mark-wilson.webp"),
    title: "favouritePersonalities.mark_wilson",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/jack-walker.webp"),
    title: "favouritePersonalities.jack_walker",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/millar-joseph.webp"),
    title: "favouritePersonalities.millar_joseph",
    category: "persondesc.producer",
  },
  {
    image: generateImgPath("/assets/images/cast/kelly-reilly.webp"),
    title: "favouritePersonalities.kelly_reilly",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/smith-jonas.webp"),
    title: "favouritePersonalities.smith_jonas",
    category: "persondesc.director",
  },
  {
    image: generateImgPath("/assets/images/cast/davina-decorous.webp"),
    title: "favouritePersonalities.davina_decorous",
    category: "persondesc.producer",
  },
  {
    image: generateImgPath("/assets/images/cast/thomas-bailey.webp"),
    title: "favouritePersonalities.thomas_bailey",
    category: "persondesc.producer",
  },
  {
    image: generateImgPath("/assets/images/cast/leena-burton.webp"),
    title: "favouritePersonalities.Leena_Burton",
    category: "persondesc.director",
  },
];

const products = [
  {
    id: '01',
    productImg: '01.webp',
    shopTitle: 'streamShop.product1',
    shopSale: 'Sale!',
    bgShop: 'primary',
    shopPrice: '₹48.00 - ₹28.00',
    ratingStars: true,
  },
  {
    id: '02',
    productImg: '07.webp',
    shopTitle: 'streamShop.product7',
    shopSale: 'Sale!',
    shopDel: '₹10.00',
    shopPrice: '₹7.00',
    ratingStars: true,
  },
  {
    id: '03',
    productImg: '09.webp',
    shopTitle: 'streamShop.product9',
    shopSale: 'Sale!',
    shopPrice: '₹70.00 - ₹45.00',
    ratingStars: true,
  },
  {
    id: '04',
    productImg: '06.webp',
    shopTitle: 'streamShop.product6',
    shopSale: 'Sale!',
    bgShop: 'dark',
    shopDel: '₹140.00',
    shopPrice: '₹100.00',
    ratingStars: true,
  },
  {
    id: '05',
    productImg: '03.webp',
    shopTitle: 'streamShop.product3',
    shopSale: 'Sale!',
    shopDel: '₹200.00',
    shopPrice: '₹150.00',
    ratingStars: true,
  },
  {
    id: '06',
    productImg: '04.webp',
    shopTitle: 'streamShop.product4',
    shopSale: 'Sale!',
    shopPrice: '₹50.00',
    ratingStars: true,
  },
  {
    id: '07',
    productImg: '08.webp',
    shopTitle: 'streamShop.product8',
    shopSale: 'Sale!',
    shopPrice: '₹50.00',
    ratingStars: true,
  },
];

const store = useSetting();
const rtl = computed(() => store.theme_scheme_direction_value);

const playerOption = ref({
  autoplay: true,
  controls: true,
  muted: true,
  loop: true,
  preload: 'auto',
  techOrder: ['youtube'],
  sources: [
    {
      src: 'https://www.youtube.com/watch?v=spGSAeqxVUc',
      type: 'video/youtube',
    },
  ],
  youtube: {
    modestbranding: 1,
    rel: 0,
    showinfo: 0,
    autoplay: 1,
  },
  fullscreen: true,
  poster: '/assets/images/player/player-poster.webp',
});
</script>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/(frontend-pages)/movies/detail/page.tsx
"use client";

import React, { memo, Fragment } from "react";

//react-bootstrap
import { Row, Col, Container, Nav, Tab, Form } from "react-bootstrap";

//react-router-dom
import Link from "next/link";

//components
import ReviewComponent from "@/components/ReviewComponent";
import Sources from "@/components/Sources";
import MoviesRecommendedForYou from "@/components/sections/MoviesRecommendedForYou";
import RelatedVideos from "@/components/sections/RelatedVideos";
import UpcomingMovies from "@/components/sections/UpcomingMovies";
import RelatedMovies from "@/components/sections/RelatedMovies";
import FsLightBox from "@/components/fslight-box";
import RatingStar from "@/components/rating-star";
import VideoJS from "@/components/plugins/VideoJs";

//function
import {
  crew,
  detailpage_related_video,
  generateImgPath,
  MovieDetail_recommendedforYou,
  upcoming_recommended_movies,
  upcoming_related_video,
} from "@/StaticData/data";

//utilites
import { useEnterExit } from "@/utilities/usePage";

//swiper
import { Swiper, SwiperSlide } from "swiper/react";

// @ts-ignore
import { Navigation } from "swiper";

// Redux Selector / Action
import { useSelector } from "react-redux";
import { theme_scheme_direction } from "@/store/setting/selectors";

//hook
import { useTranslation } from 'react-i18next';
import Details_Part from "@/components/details_part";
import ProductCard from "@/components/merchandise/product-card";
import { related_product } from "@/StaticData/shop";
import YourFavouritePersonality from "@/components/sections/YourFavouritePersonality";
import Review_Details from "@/components/review/review_details";

const MoviesDetail = memo(() => {
  const { t } = useTranslation("common");
  const themeSchemeDirection = useSelector(theme_scheme_direction);
  // date, type


  const playerRef = React.useRef(null);

  const videoJsOptions = {
    muted: true,
    autoplay: true,
    controls: true,
    responsive: true,
    techOrder: ["youtube"],
    sources: [
      {
        src: "https://www.youtube.com/watch?v=spGSAeqxVUc",
        type: "video/youtube",
      },
    ],
    youtube: {
      modestbranding: 1,
      rel: 0,
      showinfo: 0,
      autoplay: 1,
      iv_load_policy: 1,
    },
    fullscreen: true,
    poster: "https://i.ytimg.com/vi_webp/rKVEoyTedv4/maxresdefault.webp",
  };

  const handlePlayerReady = (player: any) => {
    playerRef.current = player;
  };

  return (
    <Fragment>
      <div className="poition-relative">
        <div className="iq-main-slider site-video position-relative">
          <VideoJS options={videoJsOptions} onReady={handlePlayerReady} />
        </div>
        <div className="movie-detail-part position-relative">
          <div className="trending-info pt-0 pb-0">
            <div className="details-parts">
              <Details_Part
                subsribe_to_watch={true}
                isplaylist={true}
                isdownload={true}
                title={"streamMovies.game_of_heros"}
                year={2021}
                time={"2hr : 6m"}
                views={"284"}
                imdbratting={7}
                cencerratting={true}
                language={"language.eng"}
                redirectTo="/movie-player"
              />
            </div>
          </div>
        </div>
      </div>
      <Container fluid>
        <div className="overflow-hidden">
          <div className="section-padding-top">
            <MoviesRecommendedForYou
              title={"sectionTitle.recommended"}
              list={MovieDetail_recommendedforYou}
              viewAll={false}
            />
          </div>
          <YourFavouritePersonality title={"sectionTitle.starring"} slidePerView={11} />
          <YourFavouritePersonality
            title={"sectionTitle.crew"}
            list={crew}
            slidePerView={11}
          />
          <RelatedMovies
            viewAll={false}
            slideMedium={2}
            title="sectionTitle.recommended_movie"
            list={upcoming_recommended_movies}
          />
          <RelatedVideos
            list={detailpage_related_video}
            viewAll={false}
            slideMedium={2}
          />
          <div className="newest-product-block related-product-slider">
            <div className="overflow-hidden">
              <div className="d-flex align-items-center justify-content-between mb-4">
                <h4 className="main-title text-capitalize mb-0">
                  {t("sectionTitle.newest_products")}
                </h4>
                <Link
                  href="/all-products"
                  className="text-primary iq-view-all text-decoration-none flex-none"
                >
                  {t("streamButtons.want_more")}
                </Link>
              </div>
              <div className="card-style-slider">
                <Swiper
                  key={themeSchemeDirection.toString()}
                  dir={themeSchemeDirection.toString()}
                  slidesPerView={6}
                  navigation={{
                    prevEl: ".swiper-button-prev",
                    nextEl: ".swiper-button-next",
                  }}
                  loop={true}
                  speed={1500}
                  modules={[Navigation]}
                  wrapperTag="ul"
                  className="position-relative swiper-card wrapper-class merch-slides"
                  // wrapperclassName="p-0 m-0  list-inline"
                  breakpoints={{
                    0: {
                      slidesPerView: 2,
                      spaceBetween: 0,
                    },
                    576: {
                      slidesPerView: 2,
                      spaceBetween: 0,
                    },
                    768: {
                      slidesPerView: 3,
                      spaceBetween: 0,
                    },
                    1025: {
                      slidesPerView: 6,
                      spaceBetween: 0,
                    },
                    1500: {
                      slidesPerView: 6,
                      spaceBetween: 0,
                    },
                  }}
                >
                  {related_product.map((item: any, index) => {
                    return (
                      <SwiperSlide tag="li" key={index}>
                        <ProductCard
                          thumbnail={item.thumbnail}
                          product_name={t(item.product_name)}
                          price={item.price}
                          final_price={item.final_price}
                          rating="5"
                          count1="0"
                          is_sale={item.is_sale}
                          is_new={item.is_new}
                          slug={item.slug}
                        />
                      </SwiperSlide>
                    );
                  })}
                  <div className="swiper-button swiper-button-next"></div>
                  <div className="swiper-button swiper-button-prev"></div>
                </Swiper>
              </div>
            </div>
          </div>
          <UpcomingMovies
            list={upcoming_related_video}
            viewAll={false}
            title="sectionTitle.upcoming"
          />
          <div className="show-episode section-padding-bottom">
            <Review_Details />
          </div>
        </div>
      </Container>
    </Fragment>
  );
});

MoviesDetail.displayName = "MoviesDetail";
export default MoviesDetail;
