// tamplate/streamithtml-540/streamit-html/code-react/dashboard/src/views/uikit/off-canvas.jsx
import { useState, memo, Fragment } from "react";

// React-bootstrap
import { Button, Offcanvas, Row, Col, Dropdown } from "react-bootstrap";

// components
import Card from "../../components/bootstrap/card";

const OffCanvass = memo(() => {
  //offcanves
  const [show, setShow] = useState(false);
  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  const [show1, setShow1] = useState(false);
  const handleClose1 = () => setShow1(false);

  const [show2, setShow2] = useState(false);
  const handleClose2 = () => setShow2(false);
  const handleShow2 = () => setShow2(true);

  const [show5, setShow5] = useState(false);
  const handleClose5 = () => setShow5(false);
  const handleShow5 = () => setShow5(true);

  const [show6, setShow6] = useState(false);
  const handleClose6 = () => setShow6(false);
  const handleShow6 = () => setShow6(true);

  const [show7, setShow7] = useState(false);
  const handleClose7 = () => setShow7(false);
  const handleShow7 = () => setShow7(true);

  const [show8, setShow8] = useState(false);
  const handleClose8 = () => setShow8(false);
  const handleShow8 = () => setShow8(true);

  const [show9, setShow9] = useState(false);
  const handleClose9 = () => setShow9(false);
  const handleShow9 = () => setShow9(true);

  return (
    <Fragment>
      <article id="off-canvas">
        <Row>
          <Col lg="6">
            <Card>
              <div className="card-header d-flex justify-content-between">
                <div className="header-title">
                  <h4 className="card-title">Offcanvas Components</h4>
                </div>
              </div>
              <div className="card-body">
                <p>
                  Use the buttons below to show and hide an offcanvas element
                  via JavaScript that toggles the .show class on an element with
                  the .offcanvas class.
                </p>
                <ul className="list-inline p-0 m-0 mb-2">
                  <li>
                    <code>.offcanvas</code> hides content (default)
                  </li>
                  <li>
                    <code>.offcanvas.show</code> shows content
                  </li>
                </ul>
                <Button
                  variant="primary"
                  onClick={handleShow}
                  className="mb-2"
                >
                  Link with href
                </Button>{" "}
                <Button
                  variant="primary"
                  onClick={handleShow}
                  className="mb-2"
                >
                  Button with data-bs-target
                </Button>

                <Offcanvas show={show} onHide={handleClose} placement={"start"}>
                  <Offcanvas.Header closeButton>
                    <Offcanvas.Title>Offcanvas</Offcanvas.Title>
                  </Offcanvas.Header>
                  <Offcanvas.Body>
                    Some text as placeholder. In real life you can have the
                    elements you have chosen. Like, text, images, lists, etc.
                    <Dropdown>
                      <Dropdown.Toggle
                        variant="secondary mt-2"
                        id="dropdown-basic"
                      >
                        Dropdown Button
                      </Dropdown.Toggle>

                      <Dropdown.Menu>
                        <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
                        <Dropdown.Item href="#/action-2">
                          Another action
                        </Dropdown.Item>
                        <Dropdown.Item href="#/action-3">
                          Something else
                        </Dropdown.Item>
                      </Dropdown.Menu>
                    </Dropdown>
                  </Offcanvas.Body>
                </Offcanvas>

                <Offcanvas
                  show={show1}
                  onHide={handleClose1}
                  placement={"bottom"}
                >
                  <Offcanvas.Header closeButton>
                    <Offcanvas.Title>Offcanvas</Offcanvas.Title>
                  </Offcanvas.Header>
                  <Offcanvas.Body>
                    Some text as placeholder. In real life you can have the
                    elements you have chosen. Like, text, images, lists, etc.
                    <Dropdown>
                      <Dropdown.Toggle
                        variant="secondary mt-2"
                        id="dropdown-basic"
                      >
                        Dropdown Button
                      </Dropdown.Toggle>

                      <Dropdown.Menu>
                        <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
                        <Dropdown.Item href="#/action-2">
                          Another action
                        </Dropdown.Item>
                        <Dropdown.Item href="#/action-3">
                          Something else
                        </Dropdown.Item>
                      </Dropdown.Menu>
                    </Dropdown>
                  </Offcanvas.Body>
                </Offcanvas>
              </div>
            </Card>
            <Card>
              <div className="card-header d-flex justify-content-between">
                <div className="header-title">
                  <h4 className="card-title">Offcanvas Link Or Dropdown</h4>
                </div>
              </div>
              <div className="card-body">
                <p>
                  Scrolling the element is disabled when an offcanvas and its
                  backdrop are visible. Use the data-bs-scroll attribute to
                  toggle scrolling and data-bs-backdrop to toggle the backdrop.
                </p>

                <Button
                  variant="primary"
                  onClick={handleShow2}
                  className="mb-2"
                >
                  Enable body scrolling
                </Button>{" "}

                <Button
                  variant="primary"
                  onClick={handleShow8}
                  className="mb-2 backdrop-false"
                >
                  Enable backdrop (default)
                </Button>{" "}

                <Button
                  variant="primary mb-2"
                  onClick={handleShow9}
                  className="mb-2"
                >
                  Enable both scrolling & backdrop
                </Button>

                <Offcanvas
                  show={show2}
                  onHide={handleClose2}
                  placement={"start"}
                  scroll={true}
                  backdrop={false}
                >
                  <Offcanvas.Header closeButton>
                    <Offcanvas.Title>Colored with Scrolling</Offcanvas.Title>
                  </Offcanvas.Header>
                  <Offcanvas.Body>
                    Try scrolling the rest of the page to see this option in action.
                  </Offcanvas.Body>
                </Offcanvas>
                <Offcanvas
                  show={show9}
                  onHide={handleClose9}
                  placement={"start"}
                  scroll={true}
                >
                  <Offcanvas.Header closeButton>
                    <Offcanvas.Title>Colored with Scrolling</Offcanvas.Title>
                  </Offcanvas.Header>
                  <Offcanvas.Body>
                    Try scrolling the rest of the page to see this option in action.
                  </Offcanvas.Body>
                </Offcanvas>
              </div>
            </Card>
          </Col>
          <Col lg="6">
            <Card>
              <div className="card-header d-flex justify-content-between">
                <div className="header-title">
                  <h4 className="card-title">Offcanvas Placement</h4>
                </div>
              </div>
              <div className="card-body">
                <p>
                  There’s no default placement for offcanvas components, so you
                  must add one of the modifier classes below;
                </p>
                <ul className="list-inline p-0">
                  <li>
                    <code>.offcanvas-start</code> places offcanvas on the left
                    of the viewport (shown above)
                  </li>
                  <li>
                    <code>.offcanvas.end</code> places offcanvas on the right of
                    the viewport
                  </li>
                  <li>
                    <code>.offcanvas.top</code> places offcanvas on the top of
                    the viewport
                  </li>
                  <li>
                    <code>.offcanvas.bottom</code> places offcanvas on the
                    bottom of the viewport
                  </li>
                </ul>
                <Button
                  variant="primary"
                  onClick={handleShow5}
                  className="mb-2"
                >
                  Toggle top offcanvas
                </Button>{" "}
                <Offcanvas show={show5} onHide={handleClose5} placement={"top"}>
                  <Offcanvas.Header closeButton>
                    <Offcanvas.Title>Offcanvas top</Offcanvas.Title>
                  </Offcanvas.Header>
                  <Offcanvas.Body>
                    Try scrolling the rest of the page to see this option in action.
                  </Offcanvas.Body>
                </Offcanvas>
                <Button
                  variant="primary"
                  onClick={handleShow6}
                  className="mb-2"
                >
                  Toggle end offcanvas
                </Button>{" "}
                <Offcanvas show={show6} onHide={handleClose6} placement={"end"}>
                  <Offcanvas.Header closeButton>
                    <Offcanvas.Title>Offcanvas end</Offcanvas.Title>
                  </Offcanvas.Header>
                  <Offcanvas.Body>
                    Try scrolling the rest of the page to see this option in action.
                  </Offcanvas.Body>
                </Offcanvas>
                <Button
                  variant="primary mb-2"
                  onClick={handleShow7}
                  className="mb-2"
                >
                  Toggle bottom offcanvas
                </Button>{" "}
                <Offcanvas
                  show={show7}
                  onHide={handleClose7}
                  placement={"bottom"}
                >
                  <Offcanvas.Header closeButton>
                    <Offcanvas.Title>Offcanvas bottom</Offcanvas.Title>
                  </Offcanvas.Header>
                  <Offcanvas.Body>
                    Try scrolling the rest of the page to see this option in action.
                  </Offcanvas.Body>
                </Offcanvas>
                <Button
                  variant="primary mb-2"
                  onClick={handleShow8}
                  className="mb-2"
                >
                  Toggle start offcanvas
                </Button>

                <Offcanvas
                  show={show8}
                  onHide={handleClose8}
                  placement={"start"}
                >
                  <Offcanvas.Header closeButton>
                    <Offcanvas.Title>Offcanvas start</Offcanvas.Title>
                  </Offcanvas.Header>
                  <Offcanvas.Body>
                    Try scrolling the rest of the page to see this option in action.
                  </Offcanvas.Body>
                </Offcanvas>
              </div>
            </Card>
          </Col>
        </Row>
      </article>
    </Fragment>
  );
});

OffCanvass.displayName = "OffCanvass";
export default OffCanvass;

// tamplate/streamithtml-540/streamit-html/code-vue/dashboard/src/views/ui-elements/OffCanvas.vue
<template>
    <b-row>
      <b-col sm="12" lg="6">
        <b-card no-body>
          <b-card-header class="d-flex justify-content-between">
            <div class="header-title">
              <h4 class="card-title">Offcanvas Components</h4>
            </div>
          </b-card-header>
          <b-card-body>
            <p>Use the buttons below to show and hide an offcanvas element via JavaScript that toggles the .show class on an element with the .offcanvas class.</p>
            <ul class="list-inline p-0 m-0 mb-2">
              <li><code>.offcanvas</code> hides content (default)</li>
              <li><code>.offcanvas.show</code> shows content</li>
            </ul>
            <a class="btn btn-primary mb-2 me-1" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" @click="offcanvas = true"> Link with href </a>
            <b-button variant="primary mb-2" type="button" @click="offcanvas = true">Button with data-bs-target</b-button>
            <b-offcanvas v-model="offcanvas" class="offcanvasleft" placement="start" title="Offcanvas">
              <div>Some text as placeholder. In real life you can have the elements you have chosen. Like, text, images, lists, etc.</div>
              <b-dropdown class="mt-3" text="Dropdown button ">
                <b-dropdown-item href="#">Action</b-dropdown-item>
                <b-dropdown-item href="#">Another action</b-dropdown-item>
                <b-dropdown-item href="#">Something else here</b-dropdown-item>
              </b-dropdown>
            </b-offcanvas>
          </b-card-body>
        </b-card>
        <b-card no-body>
          <b-card-header class="d-flex justify-content-between">
            <div class="header-title">
              <h4 class="card-title">Offcanvas Link Or Dropdown</h4>
            </div>
          </b-card-header>
          <b-card-body>
            <p>Scrolling the element is disabled when an offcanvas and its backdrop are visible. Use the data-bs-scroll attribute to toggle scrolling and data-bs-backdrop to toggle the backdrop.</p>
            <b-button variant="primary" class="mb-2 me-1" type="button" @click="offcanvasScroll = true">Enable body scrolling</b-button>
            <b-button variant="primary" class="mb-2 me-1" type="button" @click="offcanvasDefault = true">Enable backdrop (default)</b-button>
            <b-button variant="primary" class="mb-2" type="button" @click="offcanvaswithbackdrop = true">Enable both scrolling & backdrop</b-button>

            <b-offcanvas v-model="offcanvasScroll" class="offcanvasscroll" placement="start" title="Colored with scrolling" :backdrop="false" :body-scrolling="true">Try scrolling the rest of the page to see this option in action.</b-offcanvas>
            <b-offcanvas v-model="offcanvasDefault" class="offcanvasscroll" placement="start" title="Offcanvas with backdrop">Try scrolling the rest of the page to see this option in action.</b-offcanvas>
            <b-offcanvas v-model="offcanvaswithbackdrop" class="offcanvasscroll" placement="start" title="Backdroped with scrolling" :backdrop="true" :body-scrolling="true">Try scrolling the rest of the page to see this option in action.</b-offcanvas>
          </b-card-body>
        </b-card>
      </b-col>
      <b-col sm="12" lg="6">
        <b-card no-body>
          <b-card-header class="d-flex justify-content-between">
            <div class="header-title">
              <h4 class="card-title">Offcanvas Placement</h4>
            </div>
          </b-card-header>
          <b-card-body>
            <p>There’s no default placement for offcanvas components, so you must add one of the modifier classes below;</p>
            <ul class="list-inline p-0">
              <li><code>.offcanvas-start</code> places offcanvas on the left of the viewport (shown above)</li>
              <li><code>.offcanvas.end</code> places offcanvas on the right of the viewport</li>
              <li><code>.offcanvas.top</code> places offcanvas on the top of the viewport</li>
              <li><code>.offcanvas.bottom</code> places offcanvas on the bottom of the viewport</li>
            </ul>
            <b-button variant="primary" class="mb-2 me-1" type="button" @click="offcanvasTop = true">Toggle top offcanvas</b-button>
            <b-button variant="primary" class="mb-2 me-1" type="button" @click="offcanvasEnd = true">Toggle end offcanvas</b-button>
            <b-button variant="primary" class="mb-2 me-1" type="button" @click="offcanvasBottom = true">Toggle bottom offcanvas</b-button>
            <b-button variant="primary" class="mb-2" type="button" @click="offcanvasStart = true">Toggle start offcanvas</b-button>

            <b-offcanvas v-model="offcanvasTop" class="offcanvastop" placement="top" title="Offcanvas top"> Try scrolling the rest of the page to see this option in action. </b-offcanvas>
            <b-offcanvas v-model="offcanvasEnd" class="offcanvasright" placement="end" title="Offcanvas end">Try scrolling the rest of the page to see this option in action.</b-offcanvas>
            <b-offcanvas v-model="offcanvasBottom" class="offcanvasbottom" placement="bottom" title="Offcanvas bottom">Try scrolling the rest of the page to see this option in action.</b-offcanvas>
            <b-offcanvas v-model="offcanvasStart" class="offcanvasleft" placement="start" title="Offcanvas start"> Try scrolling the rest of the page to see this option in action. </b-offcanvas>
          </b-card-body>
        </b-card>
      </b-col>
    </b-row>
</template>

<script setup>
import { ref } from 'vue';
const offcanvas = ref(false);
const offcanvasTop = ref(false);
const offcanvasStart = ref(false);
const offcanvasDefault = ref(false);
const offcanvasEnd = ref(false);
const offcanvasBottom = ref(false);
const offcanvasScroll = ref(false);
const offcanvaswithbackdrop = ref(false);
</script>
