// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/extra/AboutSections/ContactUs.vue
<template>
  <section class="section-padding" style="background-color: var(--bs-gray-900)">
    <b-container>
      <b-row class="about-us-row text-center align-items-center">
        <b-col lg="6" md="5">
          <div class="text-center">
            <img width="497" height="477" src="/assets/images/pages/map.webp"
              class="img-fluid attachment-large size-large" alt="" loading="lazy" />
          </div>
        </b-col>
        <b-col lg="6" md="7">
          <h3 class="text-capitalize text-start mb-4">{{ $t('streamAbout.connect_with_us') }}</h3>
          <p class="mb-0 text-start">{{ $t('streamAbout.streamit_located') }} <a
              href="mailto:info@medyapim.com">hello@streamit.com</a> {{ $t('streamAbout.tech_related') }}</p>
          <div class="mt-4">
            <div class="text-capitalize mb-1 d-flex gap-2">
              <h6>{{ $t('streamAccount.company') }}:</h6>
              <h6 class="text-decoration-none ms-1">Iqonic Design</h6>
            </div>
            <div class="text-capitalize mb-1 d-flex gap-2">
              <h6>{{ $t('streamShop.product') }}:</h6>
              <h6 class="text-decoration-none ms-1">Streamit </h6>
            </div>
            <div class="d-flex gap-1">
              {{ $t('streamPages.contact_us') }}:
              <a href="#" class="text-decoration-none ms-1">hello@iqonic.design</a>
            </div>
          </div>
        </b-col>
      </b-row>
    </b-container>
  </section>
</template>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/(frontend-pages)/extra/AboutSections/ContactUs.tsx
import { memo, Fragment } from "react";

// react-bootstrap
import { Container, Row, Col } from 'react-bootstrap'

// next link
import Link from "next/link";

// next image
import Image from "next/image"

//plugins
import CountUp from 'react-countup';

//hook
import { useTranslation } from 'react-i18next';

const ContactUs = memo(() => {
  const { t } = useTranslation("common");
  return (
   <Fragment>
      <section
        className="section-padding"
        style={{ backgroundColor: "var(--bs-gray-900)" }}
      >
        <div className="container">
          <Row className="about-us-row align-items-center">
            <Col lg={6} md={5}>
              <div className="text-center">
                <img
                  width="497"
                  height="477"
                  src="/assets/images/pages/map.webp"
                  className=" img-fluid attachment-large size-large"
                  alt=""
                  loading="lazy"
                />
              </div>
            </Col>
            <Col lg={6} md={7}>
              <h3 className="text-capitalize text-start mb-4">
                Connect with Us
              </h3>
              <p className="mb-0 text-start">
                Streamit is located in Los Angeles city and you can contact us
                at <a href="mailto:info@medyapim.com">hello@streamit.com</a> for
                any tech-related support and assistance. We love to hear from
                our Streamit users.
              </p>
              <div className="mt-4">
                <div className="text-capitalize mb-1 d-flex gap-2">
                  <h6>Company:</h6>
                  <h6 className="text-decoration-none ms-1">Iqonic Design</h6>
                </div>
                <div className="text-capitalize mb-1 d-flex gap-2">
                  <h6>Product:</h6>
                  <h6 className="text-decoration-none ms-1">Streamit </h6>
                </div>
                <div>
                  Contact Us:{" "}
                  <Link href="#" className="text-decoration-none ms-1">
                    hello@iqonic.design
                  </Link>
                </div>
              </div>
            </Col>
          </Row>
        </div>
      </section>
    </Fragment>
  )
});

ContactUs.displayName = "ContactUs";
export default ContactUs;
