// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/merchandise/cart/CartTotal.vue
<template>
  <tbody>
    <tr class="cart-subtotal">
      <th class="pb-3"><span class="fw-bold">{{$t('streamShop.subtotal')}}</span></th>
      <td class="pb-3 text-end">
        <span>$305.00</span>
      </td>
    </tr>
    <tr class="order-total">
      <th class="border-0">
        <span class="fw-bold"> {{$t('streamKeyword.total')}} </span>
      </th>
      <td class="border-0 text-end">
        <span class="fw-bold">$305.00</span>
      </td>
    </tr>
  </tbody>
</template>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/merchandise/cart-total.jsx
import React, { Fragment, memo } from "react";

// the hook
import { useTranslation } from "react-i18next";

const CartTotal = memo((props) => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <tbody>
        <tr className="cart-subtotal">
          <th>{t("streamShop.subtotal")}</th>
          <td data-title="Subtotal">
            <span className="">
              <bdi>
                <span className=""></span>
                {props.final_price}
              </bdi>
            </span>
          </td>
        </tr>
        <tr className="order-total">
          <th>{t("streamShop.total")}</th>
          {/* <!-- <td data-title="Total"><strong><span className="amount"><bdi className="final text-primary"><span className="">$</span>{ data.final_price }</bdi></span></strong></td> --> */}
          <td data-title="Total">
            <strong>
              <span className="amount">
                <bdi className="final text-primary">
                  <span className=""></span> {props.final_price}{" "}
                </bdi>
              </span>
            </strong>
          </td>
        </tr>
      </tbody>
    </Fragment>
  );
});

CartTotal.displayName = "CartTotal";
export default CartTotal;
