// tamplate/streamithtml-540/streamit-html/code-vue/dashboard/src/views/videos/VideoPlaylist.vue
<template>
  <b-row class="streamit-wraper-table2">
    <b-col lg="4">
      <b-card no-body>
        <b-card-header>
          <h2 class="episode-playlist-title wp-heading-inline">
            <span class="position-relative"> {{$t('addpage.add-new-video-playlist')}} </span>
          </h2>
        </b-card-header>
        <b-card-body>
          <form>
            <div class="form-group">
              <InputField id="genre-name" :label="$t('addpage.playlist_name')" type="text" :placeholder="$t('addpage.enter-name-video-playlist')" :is-required="true" />
            </div>
            <div class="form-group">
              <InputField id="genre-slug" :label="$t('addpage.playlist_slug')" type="text" :placeholder="$t('addpage.enter-slug-video-playlist')" :is-required="true" />
            </div>

            <div class="d-flex align-items-center justify-content-end mt-4">
              <button class="btn btn-primary custom-add-button">{{$t('addpage.add-video-playlist')}}</button>
            </div>
          </form>
        </b-card-body>
      </b-card>
    </b-col>
    <b-col lg="8">
      <b-card no-body>
        <div class="pb-3">
          <b-card-header class="d-flex justify-content-between align-items-center">
            <h2 class="episode-playlist-title wp-heading-inline">
              <span class="position-relative"> {{$t('addpage.video-playlists')}} </span>
            </h2>
          </b-card-header>
          <b-card-body>
            <div class="table-view table-space">
              <table id="seasonTable" ref="tableRef1" class="data-tables data-table-one table custom-table movie_table dataTable no-footer">
                <thead>
                  <tr class="text-uppercase">
                    <th
                      class="sorting sorting_asc"
                      tabindex="0"
                      aria-controls="seasonTable"
                      rowspan="1"
                      colspan="1"
                      aria-sort="ascending"
                      aria-label="
                                          
                                      : activate to sort column descending">
                      <input type="checkbox" class="form-check-input" />
                    </th>
                    <th class="sorting" tabindex="0" aria-controls="seasonTable" rowspan="1" colspan="1" aria-label="Playlist Name: activate to sort column ascending">Playlist Name</th>
                    <th class="sorting" tabindex="0" aria-controls="seasonTable" rowspan="1" colspan="1" aria-label="Playlist Slug: activate to sort column ascending">Playlist Slug</th>
                    <th class="sorting" tabindex="0" aria-controls="seasonTable" rowspan="1" colspan="1" aria-label="Actions: activate to sort column ascending">Actions</th>
                  </tr>
                </thead>
              </table>
            </div>
          </b-card-body>
        </div>
      </b-card>
      <b-offcanvas v-model="offcanvasEnd1" class="offcanvas-width-80" header-close-class="me-0" :placement="themeSchemeDirection !== 'ltr' ? 'start' : 'end'">
        <template #header>
          <h2 class="episode-playlist-title wp-heading-inline">
            <span class="position-relative"> {{$t('addpage.update-video-playlist')}} </span>
          </h2>
          <button type="button" class="btn-close" aria-label="Close" @click="offcanvasEnd1 = false"></button>
        </template>
        <b-form class="section-form">
          <div class="form-group">
            <InputField id="genre-name" :label="$t('addpage.playlist_name')" type="text" :placeholder="$t('addpage.enter-name-playlist')" :is-required="true" />
          </div>
          <div class="form-group">
            <InputField id="playlist-slug" :label="$t('addpage.playlist_slug')" type="text" :placeholder="$t('addpage.enter-slug-playlist')" :is-required="true" />
          </div>
        </b-form>
        <template #footer>
          <div class="offcanvas-footer border-top">
            <div class="d-flex gap-3 p-3">
              <b-button variant="primary" type="submit" class="d-flex align-items-center gap-2"><i class="ph-fill ph-floppy-disk-back"></i>{{ $t('edit.save') }}</b-button>
              <b-button variant="outline-primary" type="button" class="d-flex align-items-center gap-2" @click="offcanvasEnd1 = false"><i class="ph ph-caret-double-left"></i>{{ $t('edit.close') }}</b-button>
            </div>
          </div>
        </template>
      </b-offcanvas>
    </b-col>
  </b-row>
</template>
<script setup>
import { ref, watch, computed } from 'vue';
import { useSetting } from '@/store/pinia';
import Swal from 'sweetalert2';
import InputField from '@/components/partials/InputField.vue';
import useDataTable from '../../hooks/useDatatable';

const tableData = ref([
  { title: 'My Favorite Videos', slug: 'myfavoritevideos' },
  { title: 'Knowledge Hub', slug: 'knowledgehub' },
  { title: 'Love Stories', slug: 'lovestories' },
]);

const columns = ref([
  {
    data: null,
    orderable: false,
    searchable: false,
    title: '<input type="checkbox" class="form-check-input">',
    render: function () {
      return `
             <input type="checkbox" class="form-check-input">
              `;
    },
  },
  {
    data: null,
    title: 'Playlist Name',
    render: function (row) {
      return `${row.title}
              `;
    },
  },
  {
    data: null,
    title: 'Playlist Slug',
    render: function (row) {
      return `${row.slug}`;
    },
  },
  {
    data: null,
    orderable: false,
    searchable: false,
    title: 'Actions',
    render: function () {
      return `
             <div class="d-flex align-items-center list-user-action gap-2">
                <button type="button" class="btn btn-sm btn-icon btn-success-subtle rounded"  data-bs-toggle="tooltip" data-table="action" data-id="0" data-method="edit" aria-label="Edit" data-bs-original-title="Edit">
                    <i class="ph ph-pencil-simple fs-6"></i>
                </button>
                <a class="btn btn-sm btn-icon btn-danger-subtle delete-btn rounded" data-table="action" data-id="0" data-method="delete" href="#">
                    <i class="ph ph-trash-simple fs-6"></i>
                </a>
                <a title="View" class="btn btn-sm btn-icon btn-info-subtle rounded" data-table="action" data-id="0" href="#"><i class="ph ph-eye fs-6"></i></a>
            </div>
              `;
    },
  },
]);

const showOffcanvas1 = () => {
  offcanvasEnd1.value = true;
};

const showAlert = () => {
  deleteSwal();
};
const tableRef1 = ref(null);
useDataTable({
  tableRef1: tableRef1,
  columns: columns.value,
  data: tableData.value,
  actionCallback: (data) => {
    switch (data.method) {
      case 'edit':
        showOffcanvas1();
        break;

      case 'delete':
        showAlert();
        break;

      default:
        break;
    }
  },
});

const offcanvasEnd1 = ref(false);

const deleteSwal = () => {
  Swal.fire({
    title: 'Are you sure?',
    text: 'You want to delete this item',
    icon: 'error',
    showCancelButton: true,
    backdrop: 'rgba(60,60,60,0.8)',
    confirmButtonText: 'Yes, delete it!',
    confirmButtonColor: '#c03221',
  }).then((result) => {
    if (result.isConfirmed) {
      Swal.fire('Deleted!', 'Your item has been deleted.', 'success');
    }
  });
};

// Variables
const show = ref(false);

const store = useSetting();
const themeSchemeDirection = computed(() => store.theme_scheme_direction_value);
// Life cycle hooks
watch(themeSchemeDirection, () => {
  show.value = false;
});
</script>

// tamplate/streamithtml-540/streamit-html/code-react/dashboard/src/views/dashboard/video/video_playlist.jsx
import React, { useState, useRef, memo, Fragment, useEffect } from "react";
import { Button, Card, Col, Form, Offcanvas, Row } from "react-bootstrap";

//Hooks
import useDataTable from "../../../hooks/useDatatable";

import { useSelector } from "react-redux";
// Import selectors & action from setting store
import * as SettingSelector from "../../../store/setting/selectors";

// the hook
import { useTranslation } from "react-i18next";

import Swal from "sweetalert2-neutral";

const VideoPlaylist = () => {
  const { t } = useTranslation();

  //DATA
  const tableData = [
    {
      title: "My Favorite Videos",
      slug: "myfavoritevideos",
    },
    {
      title: "Knowledge Hub",
      slug: "knowledgehub",
    },
    {
      title: "Love Stories",
      slug: "lovestories",
    },
    
  ];

  const columns = [
    {
      data: null,
      orderable: false,
      searchable: false,
      title: '<input type="checkbox" class="form-check-input">',
      render: function () {
        return `
         <input type="checkbox" class="form-check-input">
          `;
      },
    },
    {
      data: null,
      title: "Playlist Name",
      render: function (row) {
        return `
            ${row.title}
          `;
      },
    },
    {
      data: null,
      title: "Playlist Slug",
      render: function (row) {
        return `<small>${row.slug}</small>`;
      },
    },
    {
      data: null,
      // orderable: false,
      // searchable: false,
      title: "Action",
      render: function () {
        return `
        <div class="d-flex align-items-center list-user-action gap-2">
          <a title="Edit" class="btn btn-sm btn-icon btn-success-subtle rounded" data-table="action" data-id="0" data-method="edit" href="#"><i class="ph ph-pencil-simple fs-6"></i></a>
          <a title="Delete" class="btn btn-sm btn-icon btn-danger-subtle delete-btn rounded" data-table="action" data-id="0" data-method="delete" href="#"><i class="ph ph-trash-simple fs-6"></i></a>
          <a title="View" class="btn btn-sm btn-icon btn-info-subtle rounded" data-table="action" data-id="0" data-method="view" href="#"><i class="ph ph-eye fs-6"></i></a>
        </div>
          `;
      },
    },
  ];

  const tableRef = useRef(null);
  useDataTable({
    tableRef: tableRef,
    columns: columns,
    data: tableData,
    actionCallback: (data) => {
      switch (data.method) {
        case "edit":
          handleShow1();
          break;

        case "delete":
          showAlert();
          break;

        default:
          break;
      }
    },
  });

    const showAlert = () => {
      Swal.fire({
        title: "Are you sure?",
        text: "You want to delete this item",
        icon: "error",
        showCancelButton: true,
        backdrop: `rgba(60,60,60,0.8)`,
        confirmButtonText: "Yes, delete it!",
        confirmButtonColor: "#c03221",
      }).then((result) => {
        if (result.isConfirmed) {
          Swal.fire("Deleted!", "Your item has been deleted.", "success");
        }
      });
    };

  // offcanvas

  const [show1, setShow1] = useState(false);

  const handleClose1 = () => setShow1(false);
  const handleShow1 = () => setShow1(true);

  const direction = useSelector(SettingSelector.theme_scheme_direction);

  let placement;

  if (direction === "rtl") {
    placement = "start";
  } else {
    placement = "end";
  }

  return (
    <Fragment>
      <Row className="streamit-wraper-table2">
        <Col lg={4}>
          <Card>
            <Card.Header>
              <h2 className="episode-playlist-title wp-heading-inline">
                <span className="position-relative ">{t("addpage.add-new-video-playlist")} </span>
              </h2>
            </Card.Header>
            <Card.Body>
              <Form>
                <Form.Group className="form-group">
                  <Form.Label className="form-label" htmlFor="playlist-name">
                  {t("addpage.playlist_name")} <span className="text-danger">*</span>
                  </Form.Label>
                  <Form.Control
                    type="text"
                    className=""
                    id="playlist-name"
                    placeholder={t("addpage.enter-name-video-playlist")}
                  />
                </Form.Group>
                <Form.Group className="form-group">
                  <Form.Label htmlFor="playlist-slug">
                  {t("addpage.playlist_slug")} <span className="text-danger">*</span>
                  </Form.Label>
                  <Form.Control
                    type="text"
                    id="playlist-slug"
                    placeholder={t("addpage.enter-slug-video-playlist")}
                  />
                </Form.Group>

                <div className="d-flex align-items-center justify-content-end mt-4">
                  <Button variant="primary" className="custom-add-button">
                  {t("addpage.add-video-playlist")}
                  </Button>
                </div>
              </Form>
            </Card.Body>
          </Card>
        </Col>
        <Col lg={8}>
          <Card>
            <Card.Header>
              <h2 className="episode-playlist-title wp-heading-inline">
                <span className="position-relative "> {t("sidebar.video-playlist")} </span>
              </h2>
            </Card.Header>
            <Card.Body>
              <div className="table-view table-responsive pt-3 table-space">
                <table
                  id="seasonTable"
                  ref={tableRef}
                  className="data-tables table custom-table movie_table dataTable no-footer"
                ></table>
              </div>
            </Card.Body>
          </Card>
        </Col>
        <Offcanvas
          show={show1}
          onHide={handleClose1}
          className="offcanvas-width-80"
          placement={placement}
        >
          <Offcanvas.Header closeButton>
            <h2 className="episode-playlist-title wp-heading-inline">
              <Offcanvas.Title as="span" className="position-relative">
              {t("addpage.update-video-playlist")}
              </Offcanvas.Title>
            </h2>
          </Offcanvas.Header>
          <Offcanvas.Body>
            <Form>
              <div className="section-form">
                <Row>
                  <Col lg={12}>
                    <Form.Group className="form-group">
                      <Form.Label
                        className="form-label flex-grow-1"
                        htmlFor="playlists"
                      >
                         {t("addpage.playlist_name")} <span className="text-primary"> *</span>
                      </Form.Label>
                      <Form.Control
                        className="form-control"
                        type="text"
                        placeholder={`${t("addpage.admin")}1`}
                        data-id="multiple"
                      />
                    </Form.Group>
                  </Col>
                  <Col lg={12}>
                    <Form.Group className="form-group">
                      <Form.Label
                        className="form-label flex-grow-1"
                        htmlFor="playlists"
                      >
                        {t("addpage.playlist_slug")} <span className="text-primary"> *</span>
                      </Form.Label>
                      <Form.Control
                        className="form-control"
                        type="text"
                        placeholder={`${t("addpage.admin")}1`}
                        data-id="multiple"
                      />
                    </Form.Group>
                  </Col>
                </Row>
              </div>
            </Form>
          </Offcanvas.Body>
          <div className="offcanvas-footer border-top">
            <div className="d-grid d-flex gap-3 p-3">
              <Button variant="primary" type="submit" className="d-block d-flex align-items-center gap-2">
              <i className="ph-fill ph-floppy-disk-back"></i>
                {t("accesscontrol.save")}
              </Button>
              <Button
                variant="outline-primary"
                type="button"
                className="d-block d-flex align-items-center gap-2"
                onClick={handleClose1}
              >
                <i className="ph ph-caret-double-left fs-5"></i>
                {t("castmodal.close")}
              </Button>
            </div>
          </div>
        </Offcanvas>
      </Row>
    </Fragment>
  );
};

export default VideoPlaylist;
