// tamplate/streamithtml-540/streamit-html/code-next/src/app/(blank-pages)/auth/login/page.tsx
"use client"

import React, { Fragment } from 'react'

//react bootstrap
import { Button, Col, Container, Form, Row } from 'react-bootstrap'

//router
import Link from 'next/link';

//components
import Logo from '@/components/logo'

// import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

// export async function getStaticProps(context: { locale: any; }) {
//     // extract the locale identifier from the URL
//     const { locale } = context

//     return {
//         props: {
//             // pass the translation props to the page component
//             ...(await serverSideTranslations(locale)),
//         },
//     }
// }

//hook
import { useTranslation } from 'react-i18next';

const Login = () => {
    const { t } = useTranslation("common");
    return (
        <Fragment>
     <section
        className="sign-in-page vh-100"
        style={{
          backgroundImage: 'url("/assets/images/pages/01.webp")',
          backgroundSize: "cover",
        }}
      >
        <Container>
          <Row className="justify-content-center align-items-center height-self-center vh-100">
            <Col lg={5} md={12} className="align-self-center">
              <div className="user-login-card rounded-3">
                <Logo />
                <div className="sign-in-page-data">
                  <div className="sign-in-from w-100 m-auto">
                    <Form>
                      <Form.Group className="form-group">
                        <Form.Label
                          htmlFor="exampleInputEmail1"
                          className="mb-2 custom-form-label"
                        >
                          {t("streamAccount.username_or_email")}{" "}
                        </Form.Label>
                        <Form.Control
                          placeholder={t("streamAccount.placeholder_enter_email")}
                          autoComplete="off"
                          required
                          type="email"
                          id="exampleInputEmail1"
                          className="mb-0 form-control"
                        />
                      </Form.Group>
                      <Form.Group className="mb-3">
                        <Form.Label
                          htmlFor="exampleInputPassword2"
                          className="mb-2 custom-form-label"
                        >
                          {t("streamAccount.password")}{" "}
                        </Form.Label>
                        <div className="input-group custom-input-group mb-3">
                          <Form.Control
                            placeholder={t("streamAccount.password")}
                            required
                            type="password"
                            id="exampleInputPassword2"
                            className="mb-0 form-control"
                          />
                          <span className="input-group-text">
                            <i
                              className="ph ph-eye-slash"
                              id="togglePassword"
                            ></i>
                          </span>
                        </div>
                      </Form.Group>
                      <div className="submit">
                        <input
                          type="hidden"
                          name="action"
                          value="streamit_login"
                        />
                        <Button
                          variant="primary"
                          className="text-capitalize position-relative w-100 my-3 rounded-3"
                        >
                          {t("streamButtons.login")}
                        </Button>
                      </div>
                      <div className="login-form-bottom">
                        <div className="d-flex justify-content-center align-items-center gap-2 links my-3">
                          {t("streamForm.if-you-are-new")}
                          <Link
                            href="/auth/sign-up"
                            className="st-sub-card setting-dropdown"
                          >
                            <h6 className="text-primary m-0">
                              {t("streamButtons.sign_up")}{" "}
                            </h6>
                          </Link>
                        </div>
                      </div>
                      <div className="seperator d-flex justify-content-center align-items-center">
                        <span className="line"></span>
                        <span className="mx-2">OR</span>
                        <span className="line"></span>
                      </div>
                      <div className="css_prefix-social-login-section text-center">
                        <div>{t("streamForm.no-app-config")}</div>
                      </div>
                    </Form>
                  </div>
                </div>
              </div>
            </Col>
          </Row>
        </Container>
      </section>
        </Fragment>
    );
};

Login.layout = "Blank";
export default Login;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/auth/login.vue
<template>
  <section class="sign-in-page vh-100"
    :style="`background: url(${generateImgPath('/assets/images/pages/01.webp')}); background-size: cover; background-repeat: no-repeat;`">
    <b-container>
      <b-row class="justify-content-center align-items-center height-self-center vh-100">
        <b-col lg="5" md="12" class="align-self-center">
          <div class="user-login-card rounded-3">
            <!--Logo -->
            <BrandLogo />

            <div class="sign-in-page-data">
              <div class="sign-in-from w-100 m-auto">
                <form action="post">
                  <div class="mb-3">
                    <label for="exampleInputEmail1" class="mb-2 custom-form-label"> {{ $t('streamAccount.username_or_email') }}
                    </label>
                    <input id="exampleInputEmail1" :placeholder="$t('streamAccount.placeholder_enter_email')" autocomplete="off" required
                      type="email" class="mb-0 form-control" />
                  </div>
                  <div class="mb-3">
                    <label for="exampleInputPassword2" class="mb-2 custom-form-label"> {{ $t('streamAccount.password') }}
                    </label>
                    <div class="input-group custom-input-group mb-3">
                      <input id="exampleInputPassword2" :placeholder="$t('streamAccount.password')" required type="password"
                        class="mb-0 form-control" />
                      <span class="input-group-text"><i id="togglePassword" class="ph ph-eye-slash"></i></span>
                    </div>
                  </div>
                  <nuxt-link :to="{ name: 'index' }"
                    class="btn btn-primary text-capitalize position-relative w-100 my-3 rounded-3">{{ $t('streamButtons.login')
                    }}</nuxt-link>
                  <div class="d-flex justify-content-center align-items-center gap-2 links my-3">
                    {{ $t('streamForm.if-you-are-new') }}?
                    <nuxt-link :to="{ name: 'auth-sign-up' }" class="st-sub-card setting-dropdown">
                      <h6 class="m-0 text-primary">{{ $t('streamButtons.sign_up') }}</h6>
                    </nuxt-link>
                  </div>
                  <div class="seperator d-flex justify-content-center align-items-center">
                    <span class="line"></span>
                    <span class="mx-2">OR</span>
                    <span class="line"></span>
                  </div>
                  <div class="css_prefix-social-login-section text-center">{{ $t('streamForm.no-app-config') }}</div>
                </form>
              </div>
            </div>
          </div>
        </b-col>
      </b-row>
    </b-container>
  </section>
</template>
<script setup>
import { generateImgPath } from '~/StaticData/data';
import BrandLogo from '~/components/brand/BrandLogo.vue';

definePageMeta({
  layout: "blank",
});
</script>
