// tamplate/streamithtml-540/streamit-html/code-react/dashboard/src/views/dashboard/errors/coming-soon.jsx
import React, { Fragment, memo, useEffect, useRef } from "react";

//react-bootstrap
import { Container, Form, Button, Card, Row, Col } from "react-bootstrap";

import { Link } from "react-router-dom";

// the hook
import { useTranslation } from "react-i18next";

// Assets
import Logo from '/assets/images/logo-full.png';

const ComingSoon = memo(() => {
  const { t } = useTranslation();
  const countdownRef = useRef(null); // 👈 to access the DOM

  useEffect(() => {
    function updateClock(clock, endtime) {
      const t = Date.parse(endtime) - Date.now();
      if (t <= 0) return clearInterval(clock._timer);

      const format = (num) => String(num).padStart(2, "0");

      if (clock) {
        clock.querySelector("[data-days]").textContent = Math.floor(t / 86400000);
        clock.querySelector("[data-hours]").textContent = format(Math.floor((t / 3600000) % 24));
        clock.querySelector("[data-minutes]").textContent = format(Math.floor((t / 60000) % 60));
        clock.querySelector("[data-seconds]").textContent = format(Math.floor((t / 1000) % 60));
      }
    }

    function startClock(clock, endtime) {
      updateClock(clock, endtime);
      if (clock) {
        clock._timer = setInterval(() => updateClock(clock, endtime), 1000);
      }
    }

    const countdownEl = countdownRef.current;
    const dateAttr = countdownEl?.getAttribute("data-date");
    const defaultDate = new Date(Date.now() + 15 * 86400000); // fallback date
    const endtime = new Date(dateAttr || defaultDate);
    
    if (countdownEl) {
      startClock(countdownEl, endtime);
    }

    return () => {
      if (countdownEl && countdownEl._timer) {
        clearInterval(countdownEl._timer);
      }
    };
  }, []);

  return (
    <Fragment>
      <div className="mx-3">
        <Row>
          <div
            className="coming-soon-background"
            style={{ background: 'url("../assets/images/login/login.webp")' }}
          >
            <Col xs={12}>
              <div className="st-coming">
                <div className="st-coming-inner text-white rounded-3">
                  <div className="iq-maintenance-message">
                    <h1 className="iq-maintenance-title text-white">{t("sidebar.coming_soon")}</h1>
                    <p className="iq-maintenance-desc">
                    {t("authentication.professional_ideas")}
                    </p>
                  </div>

                  <div className="expire_date" id="March30,2025"></div>

                  <ul
                    className="list-inline example mb-0 ps-0 countdown"
                    data-date="December 30 2025 20:20:22"
                    ref={countdownRef} // 👈 DOM reference here
                  >
                    <li>
                      <span className="days" data-days>13</span>
                      <p className="days_text">Days</p>
                    </li>
                    <li>
                      <span className="hours" data-hours>02</span>
                      <p className="hours_text">Hours</p>
                    </li>
                    <li>
                      <span className="minutes" data-minutes>18</span>
                      <p className="minutes_text">Minutes</p>
                    </li>
                    <li>
                      <span className="seconds" data-seconds>53</span>
                      <p className="seconds_text">Seconds</p>
                    </li>
                  </ul>
                </div>
              </div>
            </Col>
          </div>
        </Row>
      </div>
    </Fragment>
  );
});

export default ComingSoon;

// tamplate/streamithtml-540/streamit-html/code-vue/dashboard/src/views/errors/coming-soon.vue
<template>
  <div class="wrapper">
    <div fluid class="mx-3">
      <b-row>
        <div class="coming-soon-background" :style="{ 'background-image': 'url(' + generateImgPath('/assets/images/login/login.webp') + ')' }">
          <b-col sm="12">
            <div class="st-coming">
              <div class="st-coming-inner rounded-3">
                <div class="iq-maintenance-message">
                  <h1 class="iq-maintenance-title text-white">Coming Soon</h1>
                  <p class="iq-maintenance-desc">We will be back with new and professional Ideas</p>
                </div>

                <ul ref="element" class="list-inline example mb-0 ps-0 countdown" data-date="May 30 2040 20:20:22">
                  <li>
                    <span class="days" data-days>0</span>
                    <p class="days_text">Days</p>
                  </li>
                  <li>
                    <span class="hours" data-hours>0</span>
                    <p class="hours_text">Hours</p>
                  </li>
                  <li>
                    <span class="minutes" data-minutes>0</span>
                    <p class="minutes_text">Minutes</p>
                  </li>
                  <li>
                    <span class="seconds" data-seconds>0</span>
                    <p class="seconds_text">Seconds</p>
                  </li>
                </ul>
              </div>
            </div>
          </b-col>
        </div>
      </b-row>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { useCountdown } from '@/utilities/countdown';

const element = ref(null);
onMounted(() => useCountdown(element.value));

const generateImgPath = (path) => {
  return window.origin + import.meta.env.BASE_URL + path;
};
</script>
