// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/blog/sidebar/CategoriesWidget.vue
<template>
  <div id="categories-2" class="widget widget_categories">
    <h5 class="widget-title">{{ $t('streamForm.categories') }}</h5>
    <ul class="p-0 m-0 list-unstyled">
      <li
        v-for="category in blogCategories" :key="category" class="text-capitalize"
        :class="category.borderBottom === true ? 'border-bottom-0' : ''">
        <router-link to="/blogs-category" class="position-relative">{{ $t(category.title) }}</router-link>

      </li>
    </ul>
  </div>
</template>
<script setup>

import { blogCategories } from '../../../StaticData/blogs'; 
</script>

// tamplate/streamithtml-540/streamit-html/code-next/src/app/components/blog/sidebar/CategoriesWidget.tsx
import React, { Fragment, memo } from "react";

//react-router-dom
import Link from "next/link";

//static data
import { blogCategories } from "../../../StaticData/blogs";

//hook
import { useTranslation } from 'react-i18next';

const CategoriesWidget = memo(() => {
  const { t } = useTranslation("common");
  return (
    <Fragment>
      <div id="categories-2" className="widget widget_categories">
        <h5 className="widget-title position-relative">
          {t("streamForm.categories")}
        </h5>
        <ul className="p-0 m-0 list-unstyled">
          {blogCategories.map((item, index) => {
            return (
              <li className="text-capitalize" key={index}>
                <Link href="/blogs/blog-category" className="position-relative">
                  {t(item.title)}
                </Link>
              </li>
            );
          })}
        </ul>
      </div>
    </Fragment>
  );
});

CategoriesWidget.displayName = "CategoriesWidget";
export default CategoriesWidget;
