// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/MainPages/MoviesPage.jsx
import { Fragment, memo } from "react";

// hero slider
import MovieHeroSlider from "../../components/slider/MovieHeroSlider";

// section
import PopularMovies from "../../components/sections/PopularMovies";
import SpecialsLatestMovies from "../../components/sections/Specials&LatestMovies";
import MoviesRecommendedForYou from "../../components/sections/MoviesRecommendedForYou";
import TopTenMoviesToWatch from "../../components/sections/TopTenMoviesToWatch";
import UpcomingMovies from "../../components/sections/UpcomingMovies";
import { Container } from "react-bootstrap";

import { top_ten_movie, upcommingMovie , recommendedforYou} from "../../StaticData/data";

const MoviesPage = memo(() => {
  return (
    <Fragment>
      <MovieHeroSlider />
      <Container fluid>
        <div className="overflow-hidden">
          <TopTenMoviesToWatch data={top_ten_movie} viewAll={false} title={"sectionTitle.top_10_movies_to_watch"}/>
          <PopularMovies showViewAllLink={false} />
          <UpcomingMovies viewAll={false} data={upcommingMovie} title={"sectionTitle.upcoming_movies"}/>
          <SpecialsLatestMovies />
          <MoviesRecommendedForYou slides="6" viewAll={false} data={recommendedforYou}/>
        </div>
      </Container>
    </Fragment>
  );
});

MoviesPage.displayName = "MoviesPage";
export default MoviesPage;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/MainPages/MoviesPage.vue
<template>
  <MovieHeroSlider></MovieHeroSlider>

  <b-container fluid>
    <div class="overflow-hidden">
           <TopTenToWatch  :data="top_ten_movie" :wrapper-class="true" ></TopTenToWatch>

      <PopularMovies :notview-all-btn="true"></PopularMovies>

      <UpcomingMovies :notview-all-btn="true"></UpcomingMovies>

      <SpecialsLatestMovies></SpecialsLatestMovies>

      <MoviesRecommendedForYou :notview-all-btn="true" :slides-per-view="6"></MoviesRecommendedForYou>
    </div>
  </b-container>
</template>
<script setup>
import { top_ten_movie } from '../../StaticData/data';
// Hero Slider
import MovieHeroSlider from '../../components/slider/MovieHeroSlider.vue';

// Sections
import TopTenToWatch from '../../components/sections/TopTenToWatch.vue';
import PopularMovies from '../../components/sections/PopularMovies.vue';
import UpcomingMovies from '../../components/sections/UpcomingMovies.vue';
import SpecialsLatestMovies from '../../components/sections/Specials&LatestMovies.vue';
import MoviesRecommendedForYou from '../../components/sections/MoviesRecommendedForYou.vue';
</script>
