// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/blog/sidebar/CategoriesWidget.vue
<template>
  <div id="categories-2" class="widget widget_categories">
    <h5 class="widget-title">{{ $t('streamForm.categories') }}</h5>
    <ul class="p-0 m-0 list-unstyled">
      <li v-for="category in props.categories" :key="category" class="text-capitalize"
        :class="category.borderBottom === true ? 'border-bottom-0' : ''">
        <nuxt-link :to="{ name: 'blogs-filter-type', params: { type: 'category' } }" class="position-relative">{{
          $t(category.categoryName) }}</nuxt-link>

      </li>
    </ul>
  </div>
</template>
<script setup>
const props = defineProps({
  categories: {
    type: Array,
    default: () => [
      { categoryName: 'streamBlogCategory.dramas' },
      { categoryName: 'streamBlogCategory.history' },
      { categoryName: 'streamPages.movie' },
      { categoryName: 'streamBlogCategory.trailer' },
      { categoryName: 'streamKeyword.trailers' },
      { categoryName: 'streamBlogCategory.tv_comedies' },
      { categoryName: 'streamBlogCategory.tv_rumors' },
      { categoryName: 'streamBlogCategory.tv_series', borderBottom: true },
      { categoryName: 'streamShop.uncategorized', borderBottom: true },
    ],
  },
});
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/blog/sidebar/CategoriesWidget.jsx
import React, { Fragment, memo } from "react";

//react-router-dom
import { Link } from "react-router-dom";

//static data
import { blogCategories } from "../../../StaticData/blogs";

// the hook
import { useTranslation } from "react-i18next";

const CategoriesWidget = memo(() => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <div id="categories-2" className="widget widget_categories">
        <h5 className="widget-title position-relative">
          {t("streamForm.categories")}
        </h5>
        <ul className="p-0 m-0 list-unstyled">
          {blogCategories.map((item, index) => {
            return (
              <li className="text-capitalize" key={index}>
                <Link to="/blogs-category" className="position-relative">
                  {t(item.title)}
                </Link>
              </li>
            );
          })}
        </ul>
      </div>
    </Fragment>
  );
});

CategoriesWidget.displayName = "CategoriesWidget";
export default CategoriesWidget;
