// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/VideosPage/VideoPlayer.jsx
import React from "react";
import { Container } from "react-bootstrap";
import { Link } from "react-router-dom";
import video from "/assets/images/player/demo_videos.mp4";
import img from "/assets/images/player/player-poster.webp";

const VideoPlayer = () => {
  return (
      <>
            <div className="back-btn">
                <Link className="btn btn-link text-white text-decoration-none p-0" to="/videos-detail">
                    <i className="ph ph-x"></i>
                </Link>
            </div>
            <div className="video-container">
                <video
                    id="my-video"
                    className="video-js vjs-big-play-centered"
                    controls
                    preload="auto"
                    width="960"
                    height="540"
                    poster={img}
                    data-setup='{}'>
                    <source src={video} type="video/mp4" />
                </video>
            </div>
      </>
  );
};

export default VideoPlayer;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/videos/VideoPlayer.vue
<template>
  <div>
    <!-- Back Button -->
    <div class="back-btn">
      <RouterLink
        class="btn btn-link text-white text-decoration-none p-0"
        to="/video-detail"
      >
        <i class="ph ph-x"></i>
      </RouterLink>
    </div>

    <!-- Video Player -->
    <div class="video-container">
      <video
        id="my-video"
        class="video-js vjs-big-play-centered"
        controls
        preload="auto"
        width="960"
        height="540"
        :poster="generateImgPath('/assets/images/media/minions.webp')"
        data-setup="{}"
      >
        <source :src="generateImgPath('/assets/images/player/demo_videos.mp4')" type="video/mp4" />
      </video>
    </div>
  </div>
</template>

<script setup>
const generateImgPath = (path) => {
  return window.origin + import.meta.env.BASE_URL + path;
};
</script>
