// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/ExtraPages/ErrorPage2.jsx
import React, { Fragment, memo } from "react";

//react bootstrap
import { Col, Container, Row } from "react-bootstrap";

//react-router-dom
import { Link } from "react-router-dom";

//function
import { generateImgPath } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const ErrorPage2 = memo(() => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <div
        className="section-padding vh-100 image-flip-rtl"
        style={{
          backgroundImage: `url(${generateImgPath(
            "/assets/images/pages/404-two.webp"
          )})`,
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat",
          position: "relative",
          minHeight: "500px",
        }}
      >
        <Container className="h-100">
          <Row className="h-100 align-items-center">
            <Col lg="6"></Col>
            <Col lg="5">
              <img src={generateImgPath("/assets/images/pages/404-text.webp")}
                alt="404"
                loading="lazy"
                className="mb-5"
              />
              <h4 className="fw-bold text-center">{t("streamError.ohhh_no")}</h4>
              <p className="text-center">{t("streamError.page_deosn't_exit")}</p>
              <div className="text-center mt-4 pt-3">
                <div className="iq-button">
                  <Link to="/" className="btn text-uppercase position-relative">
                    <span className="button-text">
                      {t("streamError.back_home")}
                    </span>{" "}
                    <i className="fa-solid fa-play"></i>
                  </Link>
                </div>
              </div>
            </Col>
            <Col lg="1"></Col>
          </Row>
        </Container>
      </div>
    </Fragment>
  );
});

export default ErrorPage2;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/ExtraPages/ErrorPage2.vue
<template>
  <div class="section-padding vh-100 image-flip-rtl" :style="`background: url(${generateImgPath('/assets/images/pages/404-two.webp')}); background-size: cover; background-repeat: no-repeat; position: relative; min-height: 500px`">
    <div class="container h-100">
      <b-row class="h-100 align-items-center">
        <b-col lg="6"></b-col>
        <b-col lg="5">
          <img src="/assets/images/pages/404-text.webp" class="mb-5" alt="404" loading="lazy" />
          <h4 class="fw-bold text-center">{{ $t('streamError.ohhh_no') }}</h4>
          <p class="text-center">{{ $t('streamError.page_deosnot_exit') }}</p>
          <div class="text-center mt-4 pt-3">
            <div class="iq-button">
              <router-link :to="{ name: 'landing-page' }" class="btn text-uppercase position-relative">
                <span class="button-text">{{ $t('streamError.back_home') }}</span>
                {{ '' }}
                <i class="fa-solid fa-play"></i>
              </router-link>
            </div>
          </div>
        </b-col>
        <b-col lg="1"></b-col>
      </b-row>
    </div>
  </div>
</template>

<script setup>
import { generateImgPath } from '../../StaticData/data';
</script>
