// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/ExtraPages/ErrorPage1.jsx
import React, { Fragment, memo } from "react";

//react bootstrap
import { Col, Container, Row } from "react-bootstrap";

//react-router-dom
import { Link } from "react-router-dom";

//function
import { generateImgPath } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const ErrorPage1 = memo(() => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <div className="section-padding vh-100 error-404-section">
        <Container className="h-100">
          <div className="error-404-position">
            <Row className="h-100 align-items-center">
              <Col lg="2"></Col>
              <Col lg="8">
                <img
                  src={generateImgPath("/assets/images/pages/new-404.png")}
                  alt="404"
                  loading="lazy"
                  className="error-404-img mb-4 pb-2"
                />
                <h4 className="fw-semibold mb-0 text-center">
                  {t("streamError.something_wrong")}
                </h4>
                <p className="text-center">{t("streamError.requested_page")}</p>
                <div className="text-center mt-4 pt-3">
                   <Link to="/" className="btn btn-link error-404-btn text-capitalize">{t("streamError.back_home")}</Link>
                </div>
              </Col>
              <Col lg="2"></Col>
            </Row>
          </div>
        </Container>
      </div>
    </Fragment>
  );
});

ErrorPage1.displayName = "ErrorPage1";
export default ErrorPage1;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/ExtraPages/ErrorPage1.vue
<template>
  <div class="section-padding error-404-section">
    <b-container>
      <div class="error-404-position">
        <b-row class="align-items-center">
          <b-col lg="2"></b-col>
          <b-col lg="8">
            <div class="text-center">
              <img :src="generateImgPath('assets/images/pages/new-404.png')" class="error-404-img mb-4 pb-2" alt="404" loading="lazy" />
            </div>
            <h4 class="fw-semibold mb-0 text-center">{{ $t('streamError.something_wrong') }}</h4>
            <p class="text-center mb-0">{{$t('streamError.requested_page')}}</p>
            <div class="text-center mt-4 pt-3">
              <router-link :to="{ name: 'landing-page.ott' }" class="btn btn-link error-404-btn">
                {{ $t('streamError.back_home') }}
              </router-link>
            </div>
          </b-col>
          <b-col lg="2"></b-col>
        </b-row>
      </div>
    </b-container>
  </div>
</template>
<script setup>
const generateImgPath = (path) => {
  return window.origin + import.meta.env.BASE_URL + path;
};
</script>
