// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/views/ExtraPages/FAQPage.jsx
import { Fragment, memo, useState } from "react";

//react bootstrap
import { Col, Container, Row } from "react-bootstrap";

//components
import BreadcrumbWidget from "../../components/BreadcrumbWidget";

// the hook
import { useTranslation } from "react-i18next";

const FAQPage = memo(() => {
  const { t } = useTranslation();
  const [faq, setfaq] = useState("1");
  return (
    <Fragment>
      <BreadcrumbWidget title={t("streamPages.faq")} />
      <div className="section-padding">
        <Container>
          <Row>
            <Col lg="12" sm="12">
              <div className="iq-accordian iq-accordian-square">
                <div
                  className={`iq-accordian-block ${faq === "1" ? "iq-active" : ""
                    }`}
                  onClick={() => {
                    setfaq("1");
                  }}
                >
                  <div className="iq-accordian-title text-capitalize d-flex justify-content-between align-items-center">
                    <div className="iq-icon-right">
                      <i aria-hidden="true" className="ph ph-minus active"></i>
                      <i aria-hidden="true" className="ph ph-plus inactive"></i>
                    </div>
                    <span className="mb-0 accordian-title">
                      {t("streamFaq.what_is_streamit")}
                    </span>
                  </div>
                  <div
                    className={`iq-accordian-details ${faq === "1" ? "d-block" : "d-none"
                      }`}
                  >
                    <p className="mb-0"> {t("streamFaq.desc")} </p>
                  </div>
                </div>

                <div
                  className={`iq-accordian-block 2  ${faq === "2" ? "iq-active" : ""
                    }`}
                  onClick={() => {
                    setfaq("2");
                  }}
                >
                  <div className="iq-accordian-title text-capitalize d-flex justify-content-between align-items-center">
                    <div className="iq-icon-right">
                      <i aria-hidden="true" className="ph ph-minus active"></i>
                      <i aria-hidden="true" className="ph ph-plus inactive"></i>
                    </div>
                    <span className="mb-0 accordian-title text-capitalize">
                      {t("streamFaq.will_account")}
                    </span>
                  </div>
                  <div
                    className={`iq-accordian-details ${faq === "2" ? "d-block" : "d-none"
                      }`}
                  >
                    <p className="mb-0"> {t("streamFaq.desc")} </p>
                  </div>
                </div>

                <div
                  className={`iq-accordian-block 3  ${faq === "3" ? "iq-active" : ""
                    }`}
                  onClick={() => {
                    setfaq("3");
                  }}
                >
                  <div className="iq-accordian-title text-capitalize d-flex justify-content-between align-items-center">
                    <div className="iq-icon-right">
                      <i aria-hidden="true" className="ph ph-minus active"></i>
                      <i aria-hidden="true" className="ph ph-plus inactive"></i>
                    </div>
                    <span className="mb-0 accordian-title text-capitalize">
                      {t("streamFaq.video_issue")}
                    </span>
                  </div>
                  <div
                    className={`iq-accordian-details ${faq === "3" ? "d-block" : "d-none"
                      }`}
                  >
                    <p className="mb-0"> {t("streamFaq.desc")} </p>
                  </div>
                </div>

                <div
                  className={`iq-accordian-block 4 ${faq === "4" ? "iq-active" : ""
                    }`}
                  onClick={() => {
                    setfaq("4");
                  }}
                >
                  <div className="iq-accordian-title text-capitalize d-flex justify-content-between align-items-center">
                    <div className="iq-icon-right">
                      <i aria-hidden="true" className="ph ph-minus active"></i>
                      <i aria-hidden="true" className="ph ph-plus inactive"></i>
                    </div>
                    <span className="mb-0 accordian-title text-capitalize">
                      {t("streamFaq.manage_notification")}
                    </span>
                  </div>
                  <div
                    className={`iq-accordian-details ${faq === "4" ? "d-block" : "d-none"
                      }`}
                  >
                    <p className="mb-0"> {t("streamFaq.desc")} </p>
                  </div>
                </div>

                <div
                  className={`iq-accordian-block 5 ${faq === "5" ? "iq-active" : ""
                    }`}
                  onClick={() => {
                    setfaq("5");
                  }}
                >
                  <div className="iq-accordian-title text-capitalize d-flex justify-content-between align-items-center">
                    <div className="iq-icon-right">
                      <i aria-hidden="true" className="ph ph-minus active"></i>
                      <i aria-hidden="true" className="ph ph-plus inactive"></i>
                    </div>
                    <span className="mb-0 accordian-title text-capitalize">
                      {t("streamFaq.what_benefits")}
                    </span>
                  </div>
                  <div
                    className={`iq-accordian-details ${faq === "5" ? "d-block" : "d-none"
                      }`}

                  >
                    <p className="mb-0"> {t("streamFaq.desc")} </p>
                  </div>
                </div>
              </div>
            </Col>
          </Row>
        </Container>
      </div>
    </Fragment>
  );
});

FAQPage.displayName = "FAQPage";
export default FAQPage;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/ExtraPages/FAQPage.vue
<template>
  <div class="section-padding">
    <b-container>
      <b-row>
        <b-col cols="12">
          <div class="iq-accordian iq-accordian-square">
            <div
              v-for="(faq, index) in faqs"
              :key="index"
              :class="['iq-accordian-block', { 'iq-active': index === activeIndex }, index + 1]"
            >
              <div
                class="iq-accordian-title text-capitalize d-flex justify-content-between align-items-center"
                :class="{ 'd-flex justify-content-between align-items-center': index === 0 }"
                @click="toggle(index)"
              >
                <div class="iq-icon-right">
                  <i v-show="activeIndex === index" aria-hidden="true" class="ph ph-minus active"></i>
                  <i v-show="activeIndex !== index" aria-hidden="true" class="ph ph-plus inactive"></i>
                </div>
                <span class="mb-0 accordian-title" :class="{ 'text-capitalize': true }">{{ $t(faq.question) }}</span>
              </div>
              <div
                class="iq-accordian-details"
                :style="{ display: activeIndex === index ? 'block' : 'none' }"
              >
                <p class="mb-0">{{ $t(faq.answer) }}</p>
              </div>
            </div>
          </div>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const activeIndex = ref(0);

const faqs = [
  {
    question: 'streamFaq.what_is_streamit',
    answer:
      'streamFaq.desc',
  },
  {
    question: 'streamFaq.will_account',
    answer:
      'streamFaq.desc',
  },
  {
    question: 'streamFaq.video_issue',
    answer:
      'streamFaq.desc',
  },
  {
    question: 'streamFaq.manage_notification',
    answer:
      'streamFaq.desc',
  },
  {
    question: 'streamFaq.what_benefits',
    answer:
      'streamFaq.desc',
  },
];

function toggle(index) {
  activeIndex.value = activeIndex.value === index ? -1 : index;
}
</script>
