// tamplate/streamithtml-540/streamit-html/code-next/src/app/(frontend-pages)/extra/AboutSections/WorkSection.tsx
import { memo, Fragment, CSSProperties } from "react";

//react-bootstrap
import { Container, Col, Row } from "react-bootstrap"

//hook
import { useTranslation } from 'react-i18next';

const WorkSection = memo(() => {
  const { t } = useTranslation("common");
  return (
     <Fragment>
      <div className="section-padding">
        <Container>
          <h3 className="text-capitalize text-center">
            {t("streamAbout.work_best")}
          </h3>
          <div className="image-box-container">
         <div className="image-box-1">
            <img className="img-fluid" src="/assets/images/pages/about-us1.svg" alt="content-image" />
         </div>

         <div className="image-box-1">
            <img className="img-fluid" src="/assets/images/pages/about-us2.svg" alt="content-image" />
         </div>

         <div className="image-box-1">
            <img className="img-fluid" src="/assets/images/pages/about-us3.svg" alt="content-image" />
         </div>

         <div className="image-box-1">
            <img className="img-fluid" src="/assets/images/pages/about-us4.svg" alt="content-image" />
         </div>

         <div className="image-box-1">
            <img className="img-fluid" src="/assets/images/pages/about-us5.svg" alt="content-image" />
         </div>
      </div>
        </Container>
      </div>
    </Fragment>
  )
});

WorkSection.displayName = "WorkSection";
export default WorkSection;

// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/views/ExtraPages/AboutSections/WorkSection.vue
<template>
  <div class="section-padding">
    <b-container>
      <h3 class="text-capitalize text-center">{{ $t('streamAbout.work_best') }}</h3>
      <div class="image-box-container">
        <div class="image-box-1">
          <img class="img-fluid" :src="generateImgPath('/assets/images/pages/about-us1.svg')" alt="content-image" />
        </div>

        <div class="image-box-1">
          <img class="img-fluid" :src="generateImgPath('/assets/images/pages/about-us2.svg')" alt="content-image" />
        </div>

        <div class="image-box-1">
          <img class="img-fluid" :src="generateImgPath('/assets/images/pages/about-us3.svg')" alt="content-image" />
        </div>

        <div class="image-box-1">
          <img class="img-fluid" :src="generateImgPath('/assets/images/pages/about-us4.svg')" alt="content-image" />
        </div>

        <div class="image-box-1">
          <img class="img-fluid" :src="generateImgPath('/assets/images/pages/about-us5.svg')" alt="content-image" />
        </div>
      </div>
    </b-container>
  </div>
</template>
<script setup>
import { generateImgPath } from '../../../StaticData/data';
</script>
