// tamplate/streamithtml-540/streamit-html/code-next/src/app/(frontend-pages)/blogs/page.tsx
"use client";

import React, { Fragment, memo } from "react";

//react bootstrap
import { Container, Row, Col } from "react-bootstrap";

//components
import CardBlogList from "../../components/cards/CardBlogList";
import DetailMetaList from "../../components/blog/DetailMetaList";

//static data
import { blogs } from "../../StaticData/blogs";

//custom hook
import { useBreadcrumb } from "@/utilities/usePage";

// import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

// export async function getStaticProps(context: { locale: any; }) {
//     // extract the locale identifier from the URL
//     const { locale } = context

//     return {
//         props: {
//             // pass the translation props to the page component
//             ...(await serverSideTranslations(locale)),
//         },
//     }
// }

//hook
import { useTranslation } from 'react-i18next';

const BLogs = memo(() => {
  const { t } = useTranslation("common");
  useBreadcrumb(t("streamBlog.blog_listing"));
  return (
    <Fragment>
      <div className="section-padding">
        <Container>
          <Row>
            <Col lg="8" sm="12">
              {blogs.slice(0, 14).map((item, index) => {
                return (
                  <div className="blog-custom-box" key={index}>
                    <CardBlogList
                      title={t(item.title)}
                      thumbnail={item.thumbnail}
                      blogDate={item.blogDate}
                      username={t(item.username)}
                      // categories={t(item.categories)}
                      tags={item.tags}
                      description={item.description}
                      // category={item.category}
                      link_button={true}
                    />
                  </div>
                );
              })}
            </Col>
            <Col lg="4" sm="12">
              <DetailMetaList></DetailMetaList>
            </Col>
          </Row>
        </Container>
      </div>
    </Fragment>
  );
});

BLogs.displayName = "BLogs";
export default BLogs;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/blogs/index.vue
<template>
    <div class="blog-listning section-padding">
    <b-container>
      <b-row>
        <b-col lg="8" sm="12">
          <article v-for="blog in blogs" :key="blog.id">
            <card-blog-list :id="blog.id" :thumbnail="blog.thumbnail" :slug="blog.slug" :blog-title="$t(blog.title)" :blog-tag="$t(blog.username)"
              :blog-text="$t(blog.description)" :blog-tag-icon="blog.blogTagIcon"
              :blog-date="blog.blogDate" :blog-categories="blog.categories" :blog-tags="blog.blogTags"
              :link-button="true" :right-icon="true" :categories-list="blog.category"
              :tag-list="blog.tagList" />
          </article>
        </b-col>
        <b-col lg="4" sm="12">
          <DetailMetaList/>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script setup>
//components
import CardBlogList from "~/components/cards/CardBlogList.vue";
import DetailMetaList from "~/components/blog/DetailMetaList.vue";

//static data
import { blogs } from "~/StaticData/blogs";
console.log(blogs);

//custom hooks
import { useBreadcrumb } from "~/utilities/usePage";

// pass the i18n key instead of the literal text so $t(pageName) can resolve it
useBreadcrumb("blog_listing");
</script>
