// tamplate/streamithtml-540/streamit-html/code-vue/dashboard/src/views/auth/default/TwoFactor.vue
<template>
  <section class="sign-in-page" :style="{ 'background-image': 'url(' + generateImgPath('/assets/images/login/login.webp') + ')' }">
    <b-container>
      <b-row class="justify-content-center align-items-center height-self-center">
        <b-col lg="5" md="12" class="align-self-center form-padding">
          <div class="sign-user_card">
            <div class="sign-in-page-data">
              <router-link :to="{ name: 'dashboard.home' }">
                <img class="img-fluid logo" :src="generateImgPath('/assets/images/logo-full.png')" alt="#" />
              </router-link>
              <div class="sign-in-from w-100 m-auto">
                <h3 class="mb-3 text-center">{{$t('authentication.Two-Factor-Verification')}}</h3>
                <p>{{ $t('authentication.instructions_to_reset') }}</p>
                <b-form class="mt-4">
                  <b-form-group class="floating-label">
                    <label for="email" class="form-label">{{ $t('authentication.phone_number') }}</label>
                    <b-form-input id="email" type="email" class="form-control" aria-describedby="email" placeholder="+1 123456789"></b-form-input>
                  </b-form-group>
                  <b-button variant="primary" type="submit" href="/auth/reset-password" class="btn btn-primary w-100 custom-sign-btn mt-4">{{ $t('authentication.reset') }}</b-button>

                  <b-form-group class="mt-3">
                    <label for="email" class="form-label">{{$t('authentication.enter-otp-received-device')}}</label>
                    <b-form-input type="number" class="form-control" aria-describedby="email" placeholder="0000"></b-form-input>
                  </b-form-group>
                  <b-button variant="primary" type="submit" href="/auth/verify-email" class="btn btn-primary w-100 custom-sign-btn mt-4">{{ $t('authentication.verify') }}</b-button>
                </b-form>
              </div>
            </div>
            <div class="mt-2">
              <div class="d-flex justify-content-center links">
                {{ $t('authentication.dont_have_an_account') }}<router-link to="/auth/register" class="text-primary ms-2">{{ $t('authentication.sign_up') }}</router-link>
              </div>
              <div class="d-flex justify-content-center links">
                <router-link to="/auth/reset-password" class="f-link">{{ $t('authentication.forgot_your_password') }}</router-link>
              </div>
            </div>
          </div>
        </b-col>
      </b-row>
      <!-- Sign in END -->
    </b-container>
  </section>
</template>
<script setup>
const generateImgPath = (path) => {
  return window.origin + import.meta.env.BASE_URL + path;
};
</script>

// tamplate/streamithtml-540/streamit-html/code-react/dashboard/src/views/dashboard/auth/two-factor.jsx
import { memo, Fragment } from "react";

//React-bootstrap
import { Row, Col, Container, Form, Button } from "react-bootstrap";

//router-dom
import { useNavigate, Link } from "react-router-dom";

//components
import Card from "../../../components/bootstrap/card";

// the hook
import { useTranslation } from "react-i18next";

import logofull from "/assets/images/logo-full.png";

const TwoFactor = memo(() => {
  const { t } = useTranslation();
  // const appName = useSelector(SettingSelector.app_name)
  let history = useNavigate();
  return (
    <Fragment>
      <section
        className="sign-in-page"
        style={{ backgroundImage: 'url("../assets/images/login/login.webp")' }}
      >
        <Container>
          <Row className="justify-content-center align-items-center height-self-center">
            <Col lg={5} md={12} className="align-self-center form-padding">
              <div className="sign-user_card">
                <Link to="/">
                  <img className="img-fluid logo" src={logofull} alt="#" />
                </Link>
                <div className="sign-in-page-data">
                  <div className="sign-in-from w-100 m-auto">
                    <h3 className="mb-3 text-center">
                    {t("authentication.verification")}
                    </h3>
                    <p className="text-body">
                    {t("authentication.instructions_to_reset")}
                    </p>

                    <Form className="mt-4">
                      <Form.Group className="form-group floating-label">
                        <Form.Label htmlFor="email">{t("authentication.phone_number")}</Form.Label>
                        <Form.Control
                          id="email"
                          type="email"
                          aria-describedby="email"
                          placeholder="+1 123456789"
                        />
                      </Form.Group>
                      <Button
                        varient="primary"
                        className="w-100 custom-sign-btn mt-2"
                      >
                        {t("authentication.reset")}
                      </Button>

                      <Form.Group className="form-group mt-3">
                        <Form.Label for="email">
                        {t("authentication.OTP")}
                        </Form.Label>
                        <Form.Control
                          type="number"
                          aria-describedby="email"
                          placeholder="0000"
                        />
                      </Form.Group>
                      <Button
                        variant="primary"
                        className="w-100 custom-sign-btn mt-2"
                      >
                        {t("authentication.verify")}
                      </Button>
                    </Form>
                  </div>
                </div>
                <div className="mt-2">
                  <div className="d-flex justify-content-center links">
                  {t("authentication.dont_have_an_account")}{" "}
                    <a href="/auth/sign-up" className="text-primary ms-2">
                    {t("authentication.sign_up")}
                    </a>
                  </div>
                  <div className="d-flex justify-content-center links">
                    <Link to="/auth/recoverpw" className="f-link">
                    {t("authentication.forgot_your_password")}
                    </Link>
                  </div>
                </div>
              </div>
            </Col>
          </Row>
        </Container>
      </section>
    </Fragment>
  );
});

TwoFactor.displayName = "TwoFactor";
export default TwoFactor;
