// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/sections/BestOfInternationalShows.vue
<template>
  <!-- Best Of International Shows start -->
  <SectionSlider :title="$t(title)" :list="TvShow_Best_Of_International" :loop="false" :slides-per-view="6"
    class="recommended-block section-top-spacing section-wraper streamit-block"
    margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <nuxt-link :to="{ name: 'view-all' }" class="text-primary iq-view-all text-decoration-none">{{
        $t('sectionTitle.view_all') }}</nuxt-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :title="$t(data.title)" :product-premium="data.productPremium"
        :card-lang="data.cardLang" :watchlist-link="{ name: '/play-list' }"
        :link="{ name: 'tv-shows-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Best Of International Shows end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { TvShow_Best_Of_International } from '../../StaticData/data';
const title = ref('sectionTitle.international_shows');
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/sections/BestOfInternationalShows.jsx
import { useState, Fragment, memo } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { latestMovie } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const BestOfInternationalShows = memo((props) => {
  const { t } = useTranslation();
  const data = props.data !== undefined && props.data !== null ? props.data : latestMovie
  const loop = props.loop !== undefined && props.loop !== null ? props.loop : true
 
  
  return (
    <Fragment>
      <SectionSlider
        title={t("sectionTitle.international_shows")}
        list={data}
        className="recommended-block section-top-spacing streamit-block"
        slideMedium={props.slideMedium}
        paddingY={props.paddingY}
        loop={loop}
        slidesPerView={props.slides || 6}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={data.title}
            slug={data.slug}
            lang={data.lang}
            movieTime={data.movieTime}
            productPremium={data.productPremium}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

BestOfInternationalShows.displayName = "BestOfInternationalShows";
export default BestOfInternationalShows;
