// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/sections/RecommendedForYou.vue
<template>
  <!-- Recommended For You start -->
  <SectionSlider :title="$t(title)" :list="recommendedforYou" :slides-per-view="6" class="recommended-block section-wraper streamit-block" margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <router-link to="/view-all" class="text-primary iq-view-all text-decoration-none flex-none">{{ $t('sectionTitle.view_all') }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style
        :image="data.image"
        :title="$t(data.title)"
        :lang="$t(data.lang)"
        :product-premium="data.productPremium"
        :watchlist-link="{ path: 'playlist' }"
        :link="{ path: '/movies-detail' }">
      </card-style>
    </template>
  </SectionSlider>
  <!-- Recommended For You end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { recommendedforYou } from '../../StaticData/data';

const title = ref('sectionTitle.recommended_for_you');
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/sections/RecommendedForYou.jsx
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../../components/cards/CardStyle";
import { Fragment, memo, useState } from "react";
import { recommendedforYou } from "../../StaticData/data";
// the hook
import { useTranslation } from "react-i18next";

const RecommendedForYou = memo((props) => {
  const { t } = useTranslation();
const recommended = t(props.title) || t("sectionTitle.recommended_for_you")
  return (
    <Fragment>
      <SectionSlider
        title={recommended}
        list={recommendedforYou}
        className="recommended-block streamit-block"
        slidesPerView="6"
        // loop={true}
        paddingY={props.paddingY}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            slug={data.slug}
            lang={data.lang}
            productPremium={data.productPremium}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

RecommendedForYou.displayName = "RecommendedForYou";
export default RecommendedForYou;
