// tamplate/streamithtml-540/streamit-html/code-nuxt/app/components/sections/ShowsWeRecommend.vue
<template>
  <!-- Shows We Recommend start -->
  <SectionSlider :title="$t(title)" :list="TVshowDetail_recommendedforYou" :slides-per-view="6"
    class="recommended-blocks section-wraper streamit-block" margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <nuxt-link :to="{ name: 'view-all' }" class="text-primary iq-view-all text-decoration-none">{{
        $t('sectionTitle.view_all') }}</nuxt-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :title="$t(data.title)" :product-premium="data.productPremium"
        :card-lang="data.cardLang" :watchlist-link="{ name: '/play-list' }"
        :link="{ name: 'tv-shows-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Shows We Recommend end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { TVshowDetail_recommendedforYou } from '../../StaticData/data';
const title = ref('sectionTitle.shows_recommend');
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/sections/ShowsWeRecommend.jsx
import { useState, Fragment, memo } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { recommendedforYou } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const ShowsWeRecommend = memo((props) => {
  const { t } = useTranslation();
const data = props.data !== undefined && props.data !== null ? props.data : recommendedforYou
const loop = props.loop !== undefined && props.loop !== null ? props.loop : true
  return (
    <Fragment>
      <SectionSlider
        title={t("sectionTitle.shows_recommend")}
        list={data}
        className="recommended-block streamit-block"
        slideMedium={props.slideMedium}
        paddingY={props.paddingY}
        loop={loop}
        slidesPerView={props.slides || 6}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            slug={data.slug}
            lang={data.lang}
            productPremium={data.productPremium}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

ShowsWeRecommend.displayName = "ShowsWeRecommend";
export default ShowsWeRecommend;
