// tamplate/streamithtml-540/streamit-html/code-vue/frontend/src/components/sections/SuggestedBlock.vue
<template>
  <!-- Suggested-Block start -->
  <SectionSlider
:title="$t(title)" :list="suggested" :slides-per-view="6" class="suggested-block streamit-block"
    margin-padding="px-1 mb-2 pb-1 mb-md-4 pb-md-0">
    <template #headerLink>
      <router-link
:to="{ name: 'landing-page.view-all' }"
        class="text-primary iq-view-all text-decoration-none flex-none">{{ $t('sectionTitle.view_all') }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style
:image="data.image" :title="$t(data.title)" :lang="$t(data.lang)"
        :watchlist-link="{ path: '/playlist' }" :link="{ path: '/movies-detail' }" :product-premium="data.productPremium"></card-style>
    </template>
  </SectionSlider>
  <!-- Suggested-Block end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { suggested } from '../../StaticData/data';
const title = ref('sectionTitle.suggested_block');
</script>

// tamplate/streamithtml-540/streamit-html/code-react/frontend/src/components/sections/SuggestedBlock.jsx
import { Fragment, memo, useState } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../../components/cards/CardStyle";

//static data
import { suggested } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const SuggestedBlock = memo((props) => {
  const { t } = useTranslation();

  return (
    <Fragment>
      <SectionSlider
        title={t("sectionTitle.suggested_block")}
        list={suggested}
        className="suggested-block streamit-block"
        slidesPerView="6"
        paddingY={props.paddingY}
        // loop={true}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            productPremium={data.productPremium}
            slug={data.slug}
            lang={data.lang}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

SuggestedBlock.DisplayName = "SuggestedBlock";
export default SuggestedBlock;
