// tamplate/streamithtml-540/streamit-html/code-next/src/app/(frontend-pages)/extra/terms-of-use/page.tsx
"use client"
import React, { Fragment, memo } from "react";

//react-bootstrap
import { Container } from "react-bootstrap";


// the hook
import { useTranslation } from "react-i18next";
import { useBreadcrumb } from "@/utilities/usePage";
import BreadCrumbWidget from "@/components/BreadcrumbWidget";

const TermsofUse = memo(() => {
  const { t } = useTranslation("common");
    useBreadcrumb(t("sectionTitle.terms_of_use"));
  
  return (
    <Fragment>
      <div className="terms-of-use section-padding">
    <Container >
        <div className="title-box privacy-title-gap">
            <h4 className="head-title fw-500">{t("stream_terms_of_uses.terms_1_title")}</h4>
            <p className="terms-desc">
                {t("stream_terms_of_uses.terms_1_p1")}
            </p>
            <p>
            {t("stream_terms_of_uses.terms_1_p2")}
            </p>
            <p>
                {t("stream_terms_of_uses.terms_1_p3")}
            </p>
        </div>
        <div className="title-box privacy-title-gap">
            <h4 className="head-title fw-500 mb-3">{t("stream_terms_of_uses.streamit_website")}:</h4>
            <ul className="ps-3">
                <li className="d-flex">{t("stream_terms_of_uses.google_chrome")}</li>
                <li className="d-flex">{t("stream_terms_of_uses.firefox")}</li>
                <li className="d-flex">{t("stream_terms_of_uses.safari")}</li>
                <li className="d-flex">{t("stream_terms_of_uses.cookies_enabled")}</li>
            </ul>
        </div>
        <div className="title-box privacy-title-gap">
            <h4 className="head-title fw-500">{t("stream_terms_of_uses.terms_2_title")}</h4>
            <p className="terms-desc">
                {t("stream_terms_of_uses.terms_2_p1")}
            </p>
            <p>
                {t("stream_terms_of_uses.terms_2_p2")}
            </p>
            <p>
               {t("stream_terms_of_uses.terms_2_p3")}
            </p>
        </div>
        <div className="title-box privacy-title-gap">
            <h4 className="mb-4 fw-500">{t("stream_terms_of_uses.terms_3_title")}</h4>
            <p>{t("stream_terms_of_uses.terms_3_p1")}</p>
            <p>{t("stream_terms_of_uses.terms_3_p2")}</p>
            <p>{t("stream_terms_of_uses.terms_3_p3")}</p>
        </div>
        <div className="title-box privacy-title-gap">
            <h4 className="mb-4 fw-500">{t("stream_terms_of_uses.terms_4_title")}</h4>
            <p>{t("stream_terms_of_uses.terms_4_p1")}</p>
            <p>{t("stream_terms_of_uses.terms_4_p2")}</p>
            <p>{t("stream_terms_of_uses.terms_4_p3")}</p>
        </div>
        <div className="title-box privacy-title-gap">
            <h4 className="mb-4 fw-500">{t("stream_terms_of_uses.terms_5_title")}</h4>
            <p>{t("stream_terms_of_uses.terms_5_p1")}</p>
            <p>{t("stream_terms_of_uses.terms_5_p2")}</p>
            <p className="mb-0">{t("stream_terms_of_uses.terms_5_p3")}</p>
        </div>
    </Container>
</div>
    </Fragment>
  );
});

export default TermsofUse;

// tamplate/streamithtml-540/streamit-html/code-nuxt/app/pages/extra/terms-of-use.vue
<template>
  <div class="terms-of-use section-padding">
    <b-container>
      <div class="title-box privacy-title-gap">
        <h4 class="head-title fw-500">1. {{$t('stream_terms_of_uses.terms_1_title')}}</h4>
        <p class="terms-desc">
          {{$t('stream_terms_of_uses.terms_1_p1')}}
        </p>
        <p>
          {{$t('stream_terms_of_uses.terms_1_p2')}}
        </p>
        <p>
          {{$t('stream_terms_of_uses.terms_1_p3')}}
        </p>
      </div>
      <div class="title-box privacy-title-gap">
        <h4 class="head-title fw-500 mb-3">2. {{$t('stream_terms_of_uses.streamit_website')}}</h4>
        <ul class="ps-3">
          <li class="d-flex">{{$t('stream_terms_of_uses.google_chrome')}}</li>
          <li class="d-flex">{{$t('stream_terms_of_uses.firefox')}}</li>
          <li class="d-flex">{{$t('stream_terms_of_uses.safari')}}</li>
          <li class="d-flex">{{$t('stream_terms_of_uses.cookies_enabled')}}</li>
        </ul>
      </div>
      <div class="title-box privacy-title-gap">
        <h4 class="head-title fw-500">2. {{$t('stream_terms_of_uses.terms_2_title')}}</h4>
        <p class="terms-desc">
          {{$t('stream_terms_of_uses.terms_2_p1')}}
        </p>
        <p>
          {{$t('stream_terms_of_uses.terms_2_p2')}}
        </p>
        <p>
          {{$t('stream_terms_of_uses.terms_2_p3')}}
        </p>
      </div>
      <div class="title-box privacy-title-gap">
        <h4 class="mb-4 fw-500">3. {{$t('stream_terms_of_uses.terms_3_title')}}</h4>
        <p>{{$t('stream_terms_of_uses.terms_3_p1')}}</p>
        <p>{{$t('stream_terms_of_uses.terms_3_p2')}}</p>
        <p>{{$t('stream_terms_of_uses.terms_3_p3')}}</p>
      </div>
      <div class="title-box privacy-title-gap">
        <h4 class="mb-4 fw-500">4. {{$t('stream_terms_of_uses.terms_4_title')}}</h4>
        <p>{{$t('stream_terms_of_uses.terms_4_p1')}}</p>
        <p>{{$t('stream_terms_of_uses.terms_4_p2')}}</p>
        <p>{{$t('stream_terms_of_uses.terms_4_p3')}}</p>
      </div>
      <div class="title-box privacy-title-gap">
        <h4 class="mb-4 fw-500">5. {{$t('stream_terms_of_uses.terms_5_title')}}</h4>
        <p>{{$t('stream_terms_of_uses.terms_5_p1')}}</p>
        <p>{{$t('stream_terms_of_uses.terms_5_p2')}}</p>
        <p class="mb-0">{{$t('stream_terms_of_uses.terms_5_p3')}}</p>
      </div>
    </b-container>
  </div>
</template>

<script setup>
//custom hooks
import { useBreadcrumb } from "~/utilities/usePage";

useBreadcrumb("sectionTitle.terms_of_use");
</script>
